### ISSUE TITLE
Create Eclipse Intro/Welcome links

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1009]
We should add some pointers to CT4E docs to the _Help > Welcome_:

  - [x] Overview
  - [x] Tutorial
  - [x] Migrate (from GPE)
  - [ ] What's New

**Comment by elharo** [comment]
docs are being tracked elsewhere.

**Comment by briandealwis** [comment]
This issue is referring to content hosted *within* Eclipse.  This content is shipped as a bundle (see [_extending the universal intro_](http://help.eclipse.org/mars/topic/org.eclipse.platform.doc.isv/guide/ua_intro_universal_extending.htm?cp=2_0_19_0_2_2).  For example:

<img width="851" alt="screen shot 2016-11-23 at 11 20 47 pm" src="https://cloud.githubusercontent.com/assets/202851/20586608/925eef7a-b1d3-11e6-81e3-0aa50c3ca533.PNG">

Our content can just be a link elsewhere.  This is a handy place to put those links.

**Comment by elharo** [comment]
Sorry. I misunderstood. Yes, that does sound useful.

**Comment by chanseokoh** [comment]
I'm looking into this. If I understand correctly from [here](https://dzone.com/articles/short-tutorial-introwelcome), our target application is the Eclipse IDE, which has a single "Welcome" intro page for the IDE.

For non-JavaEE Mars, the welcome page is this:
![resource - eclipse platform _003](https://cloud.githubusercontent.com/assets/10523105/20846369/5e0e1c26-b897-11e6-9a3d-eb4bf44c7d72.png)

My understanding is that we will basically add a few links somewhere. I believe it doesn't make much sense to add another top-level section (at the same level as "Overview" or "Tutorial"). Instead, I believe we will want to add a sub-section (basically a link) inside, say, "Overview".

**Comment by branflake2267** [comment]
With Neon, it appears each section as with one link.  I'm not sure how folks use the welcome page. But the only time I've seen the welcome page is installing new plugins, and I use it more as a confirmation as it's installed and has some content I probably won't read, so it's more of a confirmation I'm installed. Then forever hidden until the next plugin is installed.  

Example of my Neon Install: 
![screen shot 2016-12-02 at 12 29 58 pm](https://cloud.githubusercontent.com/assets/1326504/20849537/08deb176-b88c-11e6-8bd2-883615a2194b.png)

I think a specific section might be more handy for end users if used at all. :)

**Comment by briandealwis** [comment]
@branflake2267: those left-hand side links are controlled by the product (i.e., the _IDE for Jave EE_ product in your screenshot above).  We (as plugins) can't contribute to that front-page.  It's really geared more to new users.
