### ISSUE TITLE
Don't verify cloud SDK location in new project wizards

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1028]
Since this is no longer needed to create a project because we load the jars from maven. 

@nbashirbello What do you think? Does this make sense?

**Comment by chanseokoh** [comment]
I vaguely remember @nbashirbello said this Cloud SDK dependency has something to do with installing our App Engine facet, which depends on the Cloud SDK. She will be able to confirm this.

**Comment by elharo** [comment]
When we install the facet we create an app engine standard runtime.
Currently a runtime requires a cloud SDK.
