### ISSUE TITLE
fred and george have same app engine service ID: default

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1030]
Suppose we have two projects, fred and george. Both use the default service ID.

Select "fred" and then "Run As > Run on Server"

You'll get the error message above, even though you only wanted to run "fred" and didn't care about "george".

This check probably shouldn't happen until we get to the next page and actually try to put the two services on the same server:

![image](https://cloud.githubusercontent.com/assets/1005544/20649095/3de174a4-b485-11e6-9453-4eb53e7e9fb7.png)

**Comment by briandealwis** [comment]
This check is done automatically by WTP.  This only happens if you have an existing server defined with one of the other modules.

We can improve the message:
`Cannot add "foo"as "bar" already has App Engine Service ID "default"`

**Comment by elharo** [comment]
Improving the message is a start. Could/should we change the default option so that this comes up with "Manually define a new server" selected instead if the existing server has the service ID default?

**Comment by briandealwis** [comment]
This is less of an issue with our new _Run/Debug on App Engine_.
- We can't change the default option when using _Run/Debug on Server_ as that's provided by WTP.
- Unfortunately the _Add or Remove_ page doesn't validate the modules until the user clicks _Finish_!
