### ISSUE TITLE
Configure service ID in new application wizard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1031]
Include a service element in appengine-web.xml, possibly initialized to the project name, modulo the restrictions on service IDs "Each service and each version must have a name. A name can contain numbers, letters, and hyphens. It cannot be longer than 63 characters and cannot start or end with a hyphen. Choose a unique name for each service and each version. Don't reuse names between services and versions."

Provide UI in the wizard for setting this.

**Comment by patflynn** [comment]
I'm not sure that including a service by default makes sense since the spec
doesn't require it.  It should definitely not be initialized to the project
name.
