### ISSUE TITLE
autoinstall app-engine-java components

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1036]
In new project wizard, if app-engine-java components aren't installed, just install them. Don't bother the user with this.

**Comment by elharo** [comment]
Possibly we just need to stop checking, and gcloud will install them as necessary on run or deploy; but verify that.

**Comment by chanseokoh** [comment]
I think gcloud auto-installs the app-engine-java component only when doing local run but not on deploy.

**Comment by elharo** [comment]
Yes, still not auto-installed on deploy. 

![image](https://user-images.githubusercontent.com/1005544/57640375-673faa00-7580-11e9-8275-78650c09aaaa.png)

**Comment by diego92sigma6** [comment]
Closing as not planned. Please reopen if needed.
