### ISSUE TITLE
doesn't realize we've installed the components

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1037]
after installing the app engine java components and going back in the new project  wizard, then next again, it still doesn't recognize that the app engine java components are installed. the user has to start over.

**Comment by elharo** [comment]
The problem is that in StandardProjectWizard and maven equivalent we pick which pages we show in the wizard once:

  @Override
  public void addPages() {
    if (!cloudSdkExists()) {
      addPage(new CloudSdkMissingPage(AnalyticsEvents.APP_ENGINE_NEW_PROJECT_WIZARD_TYPE_NATIVE));
    } else if (!appEngineJavaComponentExists()) {
      addPage(new AppEngineJavaComponentMissingPage(
          AnalyticsEvents.APP_ENGINE_NEW_PROJECT_WIZARD_TYPE_NATIVE));
    } else { // all is good
      page = new AppEngineStandardWizardPage();
      addPage(page);
    }
  }

we may need to add all possible pages and then check each click on next which page we got to.

**Comment by elharo** [comment]
see Vogella about overriding getNextPage():

http://www.vogella.com/tutorials/EclipseWizards/article.html#changing-the-page-order

**Comment by diegomarquezp** [comment]
Closing as not planned since we don't support GAE + Java 8.
