### ISSUE TITLE
LocalAppEngineConsole should reflect server stopped/terminated status

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1055]
As per our `DeployConsole`, our `LocalAppEngineConsole` should provide an indication when the process / server is stopped: the name should be prefixed with `<terminated>`, and the terminate button should be disabled.

<img width="437" alt="screen shot 2016-12-05 at 11 36 07 pm" src="https://cloud.githubusercontent.com/assets/202851/20913202/d4ccec62-bb43-11e6-8b40-075ec70d1fda.PNG">

**Comment by elharo** [comment]
sounds good, but I'm not sure this a high priority item right now

**Comment by briandealwis** [comment]
It's confusing if you use _Launch on App Engine_ (#225) from the Java perspective as clicking the terminate button appears to do nothing. Fortunately just appears to be a zombie, not a zombie apocalypse.
