### ISSUE TITLE
How do I sign in on deploy?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1074]
When no account is signed in, it is not obvious how one does sign in:

![image](https://cloud.githubusercontent.com/assets/1005544/20987058/22a55e46-bc99-11e6-98a3-f320fcf79b61.png)

I.e. what, if anything, in this dialog needs to be clicked/interacted with?

In this example, we should probably automatically show the "Add a new account" message in the popup menu, or maybe turn it into a button, or something. But ATM it doesn't seem discoverable.

**Comment by chanseokoh** [comment]
Agreed. I think the error message itself is confusing. Even before asking how one does sign in, it's not obvious why one has to sign in for what. Changing it to "Add a new account", "Account not selected" or "Select an account" will make a user click on the account combo. This will naturally lead the user to log in.
