### ISSUE TITLE
App Engine Project in File > New menu

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1080]
Can we/should we put "App Engine Project" and "Maven App Engine Project" in the File > New submenu?

![image](https://cloud.githubusercontent.com/assets/1005544/21014924/d5e8fec4-bd2d-11e6-952c-79bd31eaa81c.png)

**Comment by branflake2267** [comment]
I like the idea. That menu also shows up on right click of project too. 

![screen shot 2016-12-08 at 12 59 57 pm](https://cloud.githubusercontent.com/assets/1326504/21027592/4ebf89a4-bd46-11e6-8c7a-5884cbef530a.png)

**Comment by briandealwis** [comment]
`org.eclipse.ui.perspectiveExtensions` for the win.
