### ISSUE TITLE
wrap the license agreement appropriately on install

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1088]

**Comment by elharo** [comment]
![image](https://cloud.githubusercontent.com/assets/1005544/21074397/fbc4a6cc-bec5-11e6-8bcd-054d1f450ad2.png)

**Comment by chanseokoh** [comment]
I guess you're talking about wrapping the licence text. I think the best users could do is to resize the dialog or the right pane. That said, license texts are pre-formatted with line-breaks, so I guess there's little we can do.

**Comment by diegomarquezp** [comment]
Closing as not planned.
