### ISSUE TITLE
Disable server stop button

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1095]
The red stop button stops a running server, but it isn't disabled after a server stops:

![image](https://cloud.githubusercontent.com/assets/1005544/21067139/61216e7c-be37-11e6-9585-a7152c13cbb8.png)

**Comment by chanseokoh** [comment]
Looks like it's the Console view, right? In that case, it's a duplicate of #1055.

**Comment by elharo** [comment]
you'e right; rediscovering the same bugs
