### ISSUE TITLE
Import from App Engine Prod

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1096]
I'm not sure this is even possible, but if we can make it happen it would be extremely cool to load GCP project source into Eclipse directly from the production App Engine environment.

This might require integration with cloud source repositories.
It might work for some projects but not all.
It might be useful if we can pull down static resources (e.g. HTML) and compiled jars so you can quickly edit the static resources even if you don't change the servlets.

**Comment by patflynn** [comment]
Do you mean using source context of a specific app engine version to
checkout a project?

**Comment by elharo** [comment]
More or less. The idea is that I open a new computer, and pull down the code for the live app straight into Eclipse using my project ID and auth credentials.

**Comment by patflynn** [comment]
We don't have the code to give most of the time.  But for users that have
source context configured, and are using CSR it's conceivable.  Although at
that point pure CSR integration like we have in IntelliJ may make more
sense.
