### ISSUE TITLE
Alternate locations for webapp

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1100]
The standard facet assumes a certain layout of

src/main/webapp

for non-java resources.

This is not the layout used by all projects, and it's not the layout used  by GPE by default. 

We need some way to 

1. Configure different directories as our webapp folder.
2. Ideally recognize these alternate locations when importing/converting an existing project.

**Comment by elharo** [comment]
FYI this is the code from AppEngineStandardFacet  that unconditionally sets "src/main/webapp" as the CONFIG_FOLDER:

  private static void installWebFacet(IFacetedProject facetedProject, IProgressMonitor monitor)
      throws CoreException {
    if (facetedProject.hasProjectFacet(WebFacetUtils.WEB_25)) {
      return;
    }

    IDataModel webModel = DataModelFactory.createDataModel(new WebFacetInstallDataModelProvider());
    webModel.setBooleanProperty(IJ2EEModuleFacetInstallDataModelProperties.ADD_TO_EAR, false);
    webModel.setBooleanProperty(IJ2EEFacetInstallDataModelProperties.GENERATE_DD, false);
    webModel.setBooleanProperty(IWebFacetInstallDataModelProperties.INSTALL_WEB_LIBRARY, false);
    webModel.setStringProperty(IWebFacetInstallDataModelProperties.CONFIG_FOLDER, "src/main/webapp");
    facetedProject.installProjectFacet(WebFacetUtils.WEB_25, webModel, monitor);
  }

**Comment by elharo** [comment]
FYI, I do not see anyway to configure this from the Eclipse UI to change it after initial creation.

**Comment by elharo** [comment]
When the facet is added the code enters StandardFacetInstallDelegate.execute so this is where we can hook in.

public class StandardFacetInstallDelegate extends AppEngineFacetInstallDelegate {
  private final static String APPENGINE_WEB_XML = "appengine-web.xml";

  @Override
  public void execute(IProject project,
                      IProjectFacetVersion version,
                      Object config,
                      IProgressMonitor monitor) throws CoreException {
    super.execute(project, version, config, monitor);
    createConfigFiles(project, monitor);
  }

The config object here seems to be null.

**Comment by chanseokoh** [comment]
Even for Java, I think the src/main/... structure is ostensibly Maven.

**Comment by elharo** [comment]
The UI for the Web facet does allow the selection of the content folder, though I still can't figure out how to change that after the web facet is applied through "Further configuration available...":

![image](https://cloud.githubusercontent.com/assets/1005544/21077156/5ee638c6-bf0f-11e6-92ac-33904bb6bb8a.png)


![image](https://cloud.githubusercontent.com/assets/1005544/21077155/557abc44-bf0f-11e6-8a5c-47d902a4a82e.png)

**Comment by elharo** [comment]
Yes, but I know how to change that source path from within Eclipse so I'm not as worried about that.

**Comment by elharo** [comment]
Per http://stackoverflow.com/questions/1581683/how-do-i-change-in-an-eclipse-web-project-the-webcontent-folder-to-something-dif
the webapp folder/folders can be manually adjusted in the Deployment Assembly property panel.

**Comment by chanseokoh** [comment]
#879 may be related.

**Comment by chanseokoh** [comment]
So, per #879, we first [search for `WEB-INF` when installing the App Engine facet](
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetInstallDelegate.java#L52) and [use `src/main/webapp` as a last resort](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/WebProjectUtil.java#L41). We should (and could simply) do the same thing when installing the Dynamic Web Module 2.5 facet.

This will take care of the two bullet points of this issue below, *assuming that 1) a project has only one webapp folder; and 2) it has `WEB-INF` (i.e., dynamic web app)*.

> We need some way to
> - Configure different directories as our webapp folder.
> - Ideally recognize these alternate locations when importing/converting an existing project.

**Comment by chanseokoh** [comment]
Ah, okay, I was a bit sloppy. the Dynamic Web Module is about creating the `WEB-INF` directory, so here we need a different logic than finding `WEB-INF` when install the App Engine Facet.

**Comment by briandealwis** [comment]
Perhaps this should be another setting in the wizard.

**Comment by briandealwis** [comment]
This value are encoded in `.settings/org.eclipse.wst.common.component`, specifically the `defaultRootSource` tag.  There's a long-open bug for [UI to change the setting](https://bugs.eclipse.org/bugs/show_bug.cgi?id=156417).

**Comment by chanseokoh** [comment]
> specifically the defaultRootSource tag.

Nice. We were discussing what we should do if there are multiple webapp folders defined through Deployment Assembly property pane, which could make things complex. Now we know we can decisively determine which folder is the default root webapp.

**Comment by elharo** [comment]
I'm not sure the value of a hidden config deep inside the project's XML files matches user expectations.

**Comment by chanseokoh** [comment]
FYI, it's the settings file that the _Web Deployment Assembly_ property pane saves and updates the webapp folders, so it's not completely hidden. However, unfortunately, the UI of that pane is sort of incomplete in that it can't set the `defaultRootSource` tag.

**Comment by chanseokoh** [comment]
I found a way to retrieve the web app folder (a path tagged with the name `defaultRootSource`), although I'm not sure if this is the right or best way.

```java
      IVirtualComponent component = ComponentCore.createComponent(project /* of IProject */);
      IVirtualFolder rootFolder = component.getRootFolder();
      if (rootFolder instanceof ITaggedVirtualResource) {
        ITaggedVirtualResource resource = (ITaggedVirtualResource) rootFolder;
        IPath defaultRootSource = resource.getFirstTaggedResource(
            WorkbenchComponent.DEFAULT_ROOT_SOURCE_TAG /* "defaultRootSource" String literal */);
        System.out.println(defaultRootSource);
      }
```

**Comment by chanseokoh** [comment]
> Perhaps this should be another setting in the wizard.

FYI, I'm working on adding a new field to get this web content root in the native new project wizard:

![new app engine standard project _001](https://cloud.githubusercontent.com/assets/10523105/21204129/c42ddf4c-c223-11e6-8bcf-6bd5dee931c8.png)

**Comment by elharo** [comment]
On Wed, Dec 14, 2016 at 5:37 PM, Chanseok Oh <notifications@github.com>
wrote:

> Perhaps this should be another setting in the wizard.
>
> FYI, I'm working on adding a new field to get this web content root in the
> native new project wizard:
>
>
No, please don't do this. We don't need that. The issue is existing
projects, not new projects.


-- 
Elliotte Rusty Harold
elharo@macfaq.com

**Comment by chanseokoh** [comment]
Okay, so I'm guessing you are talking about the scenario where you add the Dynamic Web facet (along with the App Engine facet) to an existing project that does not have the Dynamic Web facet. If users add the Web facet through the Project Facet preference page UI by themselves, then I think it is very tricky to make it right, because the UI installation process will always set the webapp folder to "/WebContent" by default (unless you change the default through the hidden UI). I don't think we can change the installation behavior done through the UI. On the other hand, adding the facet programmatically by our plugin on behalf of users (not through the UI) can be a different story. In that case, we can add the Web facet with the right webapp folder after inspecting the project. Considering we could later implemet adding the Web facet programmatically for convenient import, maybe the best solution could be to lazily detect if the webapp folder set to a wrong folder, show a notification, ask for fixing, and set to the right folder?

**Comment by elharo** [comment]
We should probably brainstorm this a bit in person. I'm not sure exactly what the UI should look like, but we do need a stronger story, for import of existing projects.

**Comment by briandealwis** [comment]
I think it's a matter of modifying [`AppEngineStandardFacet#installWebFacet()`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1100#issuecomment-266251386) to search through the project for a `WEB-INF/web.xml` (and/or `appengine-web.xml`?) and defaulting to `src/main/webapp` if nothing is found.

**Comment by chanseokoh** [comment]
The Project Facet preference UI doesn't call our method to install the Web facet, so that's what I am talking about. As I said, if we install the facet programmatically by ourselves, we could do this right, as you have shown.

**Comment by briandealwis** [comment]
I'm sorry @chanseokoh I skimmed and misread the last part of your comment.  Rather than a notification, we could trigger this as part of a quick-fix.

An alternative might be to provide an GPE importer for the new importer framework (Neon and later only though).

(Another approach might be to fix the WTP `DynamicWebFacetPage` and friends to search for a `WEB-INF` for the installation.)

**Comment by chanseokoh** [comment]
> (Another approach might be to fix the WTP DynamicWebFacetPage and friends to search for a WEB-INF for the installation.)

Had a discussion with @elharo. We agreed that it would be ideal to fix WTP so that it detects WEB-INF when installing the Dynamic Web facet. It may take years, so for now, I think we'd do a workaround, which may prove to be simple:

We will try to fix the webapp folder when the App Engine facet is being installed (in `AppEngineFacetInstallDelegate.execute()`), as long as the user has not explicitly designated the folder when installing the Dynamic Web facet. I like the idea to fix the folder here. The way we detect the right webapp folder could be by looking for `WEB-INF` (as is being done to place `appengine-web.xml` now).

**Comment by chanseokoh** [comment]
> We will try to fix the webapp folder when the App Engine facet is being installed (in AppEngineFacetInstallDelegate.execute())

Well... I noticed a problem with this approach. As soon as the Dynamic Web facet is installed, it will have generated the whole `${project}/WebContent/{WEB-INF|META-INF}` the structure with `web.xml`. etc. You could reproduce this by creating our App Engine project, uninstall Dynamic Web facet and installing it again:

![selection_003](https://cloud.githubusercontent.com/assets/10523105/21232542/0075a278-c2ba-11e6-8585-1ccf03bd0b47.png)

Then the question is, should we delete `WebContent/*`? What could be a safe condition?

**Comment by briandealwis** [comment]
TBH: I think the best approach is avoidance: provide tools and menus to avoid the necessity for our developers from having to open the Project Facets page.

**Comment by elharo** [comment]
That may be the best option. We need a clear story for conversion of existing projects. I'm surprised we can't do that with the facet though. We should do as much as we can with the facet without causing other problems to pop elsewhere, even if that isn't everything we need.

**Comment by chanseokoh** [comment]
Yeah, maybe it's best to add a new context menu item, say, "Convert to Google App Engine project..." which programmatically installs the App Engine facet (along with the Dynamic Web facet if necessary). I like the idea; this will clear all the complications.
