### ISSUE TITLE
No border around Advanced in deployment dialog

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1119]
![image](https://cloud.githubusercontent.com/assets/1005544/21183650/e1773f96-c1d6-11e6-8cff-ffee252eaf60.png)

**Comment by briandealwis** [comment]
That's an accessibility feature to indicate focus.  It can be disabled with the `NO_TITLE_FOCUS_BOX` style bit.

**Comment by diegomarquezp** [comment]
Closing as not planned.
