### ISSUE TITLE
Invalid Bucket Name

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1120]
When no bucket name is entered, this message should say "Enter a bucket name" not "Invalid bucket name" and it should not be an error, though it should prevent the info from being applied.

![image](https://cloud.githubusercontent.com/assets/1005544/21184047/a912fdbe-c1d8-11e6-903b-5199772918ed.png)

**Comment by chanseokoh** [comment]
> When no bucket name is entered, this message should say "Enter a bucket name" not "Invalid bucket name" and it should not be an error, though it should prevent the info from being applied.

Let me double-check: from [this comment of yours](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1252#issuecomment-275487937), now our decision is to show no message and allow the form to be submitted when the bucket string is empty?

**Comment by elharo** [comment]
Yes, and I think we can get rid of the checkbox too.
