### ISSUE TITLE
Update site does not provide license agreement

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1158]
This is found by clicking the More link when installing the plugin

![image](https://cloud.githubusercontent.com/assets/1005544/21350226/33e13e92-c684-11e6-9174-8d649e45d636.png)

**Comment by briandealwis** [comment]
We're going to have difficulties with this since we recreate the p2 repository as part of the current signing process.  Also applies to #1159.
