### ISSUE TITLE
Update site does not provide copyright notice

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1159]
This dialog is found by clicking the More link when installing the plugin:

![image](https://cloud.githubusercontent.com/assets/1005544/21350250/5a6cc392-c684-11e6-86a6-b13257fe3b0e.png)

**Comment by briandealwis** [comment]
I think you're selecting the _Cloud Tools for Eclipse_ category, correct (identifier: `file:/usr/local/google/home/chanseok/category.xml.GCP`, version `1.0.0.01-cKYBg47735E575K5I57`)?  The Eclipse categories have no copyright information either.

I'm not sure if the publishers support associating copyright information to categories.

**Comment by elharo** [comment]
Another question: why is this exposing the path where it was built? file:/usr/local/google/home/chanseok/category.xml.GCP in this case?
