### ISSUE TITLE
Test if necessary resources are exported into final binary (i.e., included in build.properties)

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1161]
For example, `.welcome/plugin.xml`, `.appengine.newproject/helpContexts.xml`, `.welcome/intro/cloud-tools-for-eclipse.xml`, etc should be specified in `build.properties` so that they are included in a final binary. At the minimum, check if some well-known files such as `plugin.xml` are always included.

Adding an integration test that covers all the bundles? Add a new test bundle?

An ideal solution would be to make a debug env reflect the final binary (i.e., a debug run can't find resources if not included very much like in the prod), but not sure if this is possible.

**Comment by elharo** [comment]
You could put this into BasePluginXmlTest (though you might want to rename it) which already has the relevant subclasses in many packages.
