### ISSUE TITLE
New Project Wizard for Maven-based Projects Hangs

### ISSUE THREAD

**Issue by rdayal** [GoogleCloudPlatform/google-cloud-eclipse#1168]
On a fresh install of Eclipse Neon on Mac OS X with Java 8, when I follow our published quickstart and attempt to create a new Maven-based project using our Wizard, Eclipse hangs when on the "Select an Archetype" Page.

I've attached the thread dump to the issue. 

[stack.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/676238/stack.txt)

**Comment by chanseokoh** [comment]
I installed Eclipse Neon JEE on Linux fresh, launched it using Java 8, installed the latest 1.0-beta-7 version, but I can't reproduce it.

**Comment by rdayal** [comment]
Interesting, it started working for me automatically after some time passed.
If i had to suspect what was happening, I think it had to do with the fact that Maven was not installed. 

See if you can re-pro it on a Mac (If there is one there) with no Maven/.m2 metadata around, fresh Eclipse as well. 

Lowering this from high pri.

**Comment by chanseokoh** [comment]
Did it happen after you clicked on Finish? In that case, it might take a long time to download the archetype and libraries from Maven Central for the first time. Not sure if Eclipse also downloads other necessary plugins automatically along the way.

**Comment by rdayal** [comment]
No, before I clicked on Finish. I wanted to click on Finish (or anything, really) but it just had the Mac OS X beachball a couple of seconds after I entered that dialog

**Comment by rdayal** [comment]
Actually, this could be related:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=431370

@briandealwis

**Comment by elharo** [comment]
I can't immediately reproduce this either, though I haven't tried it on a clean system. I don't recall seeing it in the past.

**Comment by rdayal** [comment]
I'll drop the GA blocker. Leaving for Brian to comment on this.

**Comment by briandealwis** [comment]
I'll try to look at this tomorrow.

**Comment by briandealwis** [comment]
So if I understand this correctly, you had a hang as the wizard was transitioning from the _Maven-based App Engine Project Standard Project_ page (for providing the group and artifact IDs) to the _Archetype selection_ page?

I'm unable to reproduce this, though I have experienced this in the past but unrelated to CT4E.  Was there anything in your logs?
