### ISSUE TITLE
New Project Wizard for Maven-based Projects asks for adding APIs before selecting Archetypes

### ISSUE THREAD

**Issue by rdayal** [GoogleCloudPlatform/google-cloud-eclipse#1169]
When going through the New Project Wizard flow for creating a Maven-based App Engine project, we're first asked to select APIs to add (App Engine, Objectify, etc) before selecting an archetype. This is confusing, as the Guestbook archetype probably requires the App Engine API. What is the effect of not selecting the App Engine API but selecting the guestbook archetype?

**Comment by elharo** [comment]
If the archetype requires a particular library, then it's added to the pom.xml unconditionally, regardless of these settings. These radio buttons are to add additional libraries that may not be required by the archetype.
