### ISSUE TITLE
New project wizard for maven guestbook archetype doesn't add endpoints library

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1171]
Even though the endpoints radio button is checked in the new project wizard. 

Might be an issue in the guestbook archetype or version of archetype we're using. 

The endpoints library is added to the hello world archetype.

**Comment by chanseokoh** [comment]
Looking at [`pom.xml` of the guestbook archetype](https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/guestbook-archetype/src/main/resources/archetype-resources/pom.xml), seems like it has never been wired up with our library selection. The objectify library and the App Engine library are always embedded statically. That said, #1169 is related.
