### ISSUE TITLE
Java VM can't start but server stays running

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1172]
I forced the VM to fail when launching a local server by supplying an undefined argument to the VM. The WTP server doesn't notice this and keeps going. 

```
INFO     2016-12-29 12:37:41,007 devappserver2.py:769] Skipping SDK update check.
INFO     2016-12-29 12:37:41,116 api_server.py:205] Starting API server at: http://localhost:52060
INFO     2016-12-29 12:37:41,123 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-12-29 12:37:41,127 admin_server.py:116] Starting admin server at: http://localhost:8000
ERROR    2016-12-29 12:37:42,270 http_runtime.py:396] bad runtime process port ['']
Unrecognized option: -versub2
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
ERROR    2016-12-29 12:37:42,276 http_proxy.py:116] bad runtime process port ['']
INFO     2016-12-29 12:37:42,383 module.py:788] default: "GET /_ah/warmup HTTP/1.1" 500 169
```

**Comment by chanseokoh** [comment]
I think I know why. [We rely on server output to determine if it's running or failed](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerBehaviour.java#L385), which is an incomplete method. We will probably need to add the following output line too:

`Error: A fatal exception has occurred. Program will exit.`

**Comment by elharo** [comment]
OK, sounds right and like an easy fix. Let's do it.

**Comment by chanseokoh** [comment]
For the record, to reproduce, add an invalid JVM arg: `devServerRunConfiguration.setJvmFlags(Arrays.asList("-abc"));`
