### ISSUE TITLE
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1174]
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)

shows up running locally. Do we care? Should we do anything about this?

**Comment by chanseokoh** [comment]
Searching for `"Null value for containerConfigProperties"` and `"devappserver.portMappingProvider"` in our internal codebase will reveal where this is logged. The source file also documents what this `portMappingProvider` is for. (However, I don't understand it.)
