### ISSUE TITLE
Why do we set Java App Engine SDK path in App Engine runtime?

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1185]
[We set Java App Engine SDK Path in the App Engine runtime](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineStandardFacet.java#L204) when we create the runtime for the first time if it doesn't exist. The actual path value is "&lt;Cloud SDK home&gt;/platform/google_appengine/google/appengine/tools/java/lib".

It doesn't seem like we make any use of this path in our code. Local run works fine too without it. ~~We could probably remove it, which also allows removing dependency on appengine-plugins-core in `.appengine.facets` bundle.~~ UPDATED: `AppEngineFacetInstallDelegate` requires appengine-plugins-core for validation.

**Comment by elharo** [comment]
Best guess is it's a legacy of the time before we loaded artifacts from maven. But I'm not certain.

**Comment by nbashirbello** [comment]
I think @elharo is right and its old code.

**Comment by chanseokoh** [comment]
This is so good. I believe this means we can completely get away from the Cloud SDK (such as `CloudSdkMissingPage`, `CloudSdkOutOfDatePage`, `AppEngineJavaComponentMissingPage`, etc) when creating new projects. We will most likely remove the appengine-plugins-core dependency from `MANIFEST.MF`. too.
