### ISSUE TITLE
Run As App Engine should stop  previously running local server

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1186]
for quick edit/run cycles

(rather than requiring user to manually stop the previous local run)

Much like how deploy replaces existing server by default.

**Comment by chanseokoh** [comment]
This doesn't seem to align with the WTP model. (Others don't to do this.) I think users would rather do _Restart_ for that matter.

![selection_001](https://cloud.githubusercontent.com/assets/10523105/21689522/9fd7b538-d33e-11e6-8f4d-df27c608599b.png)

**Comment by elharo** [comment]
Other servers don't have our App Engine shortcut menu item. I encountered this multiple times this morning.

**Comment by briandealwis** [comment]
Note that _Terminate_ is bound to a keystroke (Cmd-F2/Ctrl-F2). But I can see that this would be annoying.  Perhaps if we detect a previous launch, issue a _Terminate?_ dialog with yes/no and a remember-options.

**Comment by briandealwis** [comment]
Interesting: using _Debug_ or _Run_ from the _Servers_ view silently restarts the server.

**Comment by chanseokoh** [comment]
Thinking again, why do we need to restart our server? We made our server to pick up changes to class files and resources, so there is no need to restart for quick edit run cycles.

**Comment by chanseokoh** [comment]
I'm going to close it. This issue seems opened before we improved our server to pick up changes online. There is no need to stop and restart the server.

**Comment by elharo** [comment]
Suppose we have a running server and someone selects a Project and uses our context menu to "Run as App Engine"? This should simply work without an error. Does it?

**Comment by chanseokoh** [comment]
Oh, another case that is relevant is selecting "Debug as App Engine" when the server is running in the non-debug mode. Currently, we show the dialog "Server is already running in debug mode" and stops there, but we could suppress the dialog and silently restart the server in the other mode?

**Comment by briandealwis** [comment]
There is some support in some of the other launchers (JDT launcher?) to prompt to restart in a different mode.

**Comment by elharo** [comment]
There's also the case where server 1 is running and I use Run As App Engine to run Server 2. This should just work.

One thing we could do is pick random unoccupied ports instead of always using 8080.

**Comment by diego92sigma6** [comment]
Closing as not planned. Please reopen if needed
