### ISSUE TITLE
Consistent Cloud SDK and App Engine components validation

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1203]
[`DeployPreferencesDialog`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/DeployPreferencesDialog.java#L150)

[`CloudSdkPreferenceArea`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.sdk.ui/src/com/google/cloud/tools/eclipse/sdk/ui/preferences/CloudSdkPreferenceArea.java#L163)

[`AppEngineFacetInstallDelegate`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/AppEngineFacetInstallDelegate.java#L43)

[`LocalAppEngineServerLaunchConfigurationDelegate`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java#L85)

[`StandardProjectWizard`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java#L64)

[`MavenArchetypeProjectWizard`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenArchetypeProjectWizard.java#L65)

[`CloudSdkContextFunction`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.sdk/src/com/google/cloud/tools/eclipse/sdk/internal/CloudSdkContextFunction.java#L76)

**Comment by chanseokoh** [comment]
I already made some changes before filing this issue, so I'll assign myself.

**Comment by elharo** [comment]
Can you elaborate on this one?

**Comment by chanseokoh** [comment]
- Some of them don't catch `CloudSdkNotFoundException` and/or `CloudSdkOutOfDateException`.
- Some of them catch `AppEngineException` while some others don't.
- One of them doesn't call `validateCloudSdk()` but only `validateAppEngineJavaComponents()`.

I _think_ we don't need to catch `AppEngineException`, but this is worth discussing.

**Comment by elharo** [comment]
I'll have to look but I think not calling validateCloudSdk is deliberate.

--
Elliotte Rusty Harold
on a mobile phone so please excuse weird autocorrects

**Comment by chanseokoh** [comment]
As @briandealwis said, it might make sense to have a small util method in `com.google.cloud.tools.eclipse.sdk` for this.

**Comment by chanseokoh** [comment]
FTR, not calling `validateAppEngineJavaComponents()` for (and only for) local run was intended, as it will auto-install it if it's missing.

**Comment by chanseokoh** [comment]
Fixed by #1205. Closing.
