### ISSUE TITLE
Prevent users from starting multiple devappservers

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1245]
If a user launches more than one devappserver, the first one will start up successfully, but any subsequent instance will fail at the end of the startup process because they all try to use the same local datastore, but the first one will exclusively lock it.

Related issue #937 

We should check if there's any other devappserver running when the user executes the run action of a devappserver, and if there's any active, we should show a message to the user explaining why it wouldn't work and suggest to stop the other instance first.

**Comment by chanseokoh** [comment]
The original problem reported in #942 is also related. If we prevent the database lock, then the specific problem in #942 will not happen.

**Comment by briandealwis** [comment]
The launch framework provides an opportunity via `ILaunchConfigurationDelegate2#preLaunchCheck()` to check if it conflicts with other launches.  We could check if the port definitions conflict, etc.

**Comment by chanseokoh** [comment]
To clarify, we should always return false whenever there is any dev_appserver running.
