### ISSUE TITLE
CT4E installed over GPE on Windows Mars

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1246]
and did not remove GPE:

![image](https://cloud.githubusercontent.com/assets/1005544/22082468/d7837538-dd95-11e6-9376-17b0306eb6b7.png)

**Comment by elharo** [comment]
If you look in the lower right hand corner you can see both GPE and CT4E logins

**Comment by elharo** [comment]
Happened to me on the Mac too with Neon:


![image](https://cloud.githubusercontent.com/assets/1005544/22084000/54eadf9c-dd9c-11e6-89bb-445ee5562657.png)

**Comment by elharo** [comment]
@briandealwis Any ideas on this one? It may be flaky, but it definitely happened to me yesterday with the latest beta on two different platforms/Eclipse versions.

**Comment by briandealwis** [comment]
Hmmm... I'm guessing that the negative requirements aren't being  carried across our signing & re-publishing steps. Which makes sense. Unfortunately p2 doesn't have a standalone IU-publishing tool/app. We could add it to the`invisible.product` like we're doing for the category licence and copyright. The better solution is to create a Maven kokoro-signing plugin that just integrates into our build process.

**Comment by briandealwis** [comment]
Another possible solution is to remove the bundle and feature IUs from our built repo and then re-publish the signed jars back into that bundle.  I don't think that we can re-publish the signed jars directly since the bundle IDs and versions are identical and so p2 will probably skip them since they're already there.

**Comment by briandealwis** [comment]
<blush>  I broke this with #1231 by accidentally removing `com.google.cloud.tools.eclipse.suite.e45.feature`'s `p2.inf` from being included by its `build.properties`.  As a result, Tycho doesn't process the `p2.inf` and so the negative requirements are never added.

**Comment by briandealwis** [comment]
>  I'm guessing that the negative requirements aren't being carried across our signing & re-publishing steps.

On the plus side I verified that the negative requirements *are* recreated when re-publishing the newly-signed features as the `p2.inf` is included in the feature's `.jar`.
