### ISSUE TITLE
Add coloring to deploy console

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1248]
We should color the output from the deploy process according to its source (stdout/stderr).

**Comment by elharo** [comment]
There are Eclipse preferences to control this. I'm not sure why they're not being respected, but they're not.

**Comment by elharo** [comment]
Why does DeployConsole extend MessageConsole? The latter is "@noextend This class is not intended to be subclassed by clients."

**Comment by briandealwis** [comment]
```
MessageConsoleStream stdoutStream = …;
stdoutStream.setColor(DebugUIPlugin.getPreferenceColor(IDebugPreferenceConstants.CONSOLE_SYS_ERR_COLOR));
```

**Comment by chanseokoh** [comment]
Note that the deploy logs we currently see is a mix of stderr from `gcloud` and stdout from `appcfg.sh` (standard staging). `gcloud` stdout outputs a JSON deploy result.
