### ISSUE TITLE
Get freemarker from maven central if possible

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1263]
rather than bundling it

**Comment by elharo** [comment]
If there's some reason we can't just depend on this (possible) here's a trick for pulling it in from maven central anyway:

https://github.com/jbosstools/jbosstools-freemarker/blob/master/plugins/org.jboss.ide.eclipse.freemarker/pom.xml

**Comment by chanseokoh** [comment]
I verified we can pull it in the usual way of ours: #1266 (duplicate of #1270).
