### ISSUE TITLE
New Menu

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1265]
sometimes our new project wizards show up in the File > New menu. Sometimes they don't.

![image](https://cloud.githubusercontent.com/assets/1005544/22175182/fdd46fd8-dfbd-11e6-8a94-9f25fc044afa.png)

Figure out what's going on here, decide when and where we want these items to show up, and make it so.

**Comment by briandealwis** [comment]
It's done on a per-perspective basis: Java, Java EE, and Web. https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1087/commits/ff4218f97a155326656b77dde3df52c6eff5024
