### ISSUE TITLE
Should Convert to App Engine project appear in the configure menu?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1271]
![image](https://cloud.githubusercontent.com/assets/1005544/22183421/f67970e8-e08b-11e6-8904-4904c361f250.png)

**Comment by chanseokoh** [comment]
We plan to do so: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1188#issuecomment-273568715
