### ISSUE TITLE
Test failures do not make Travis build fail

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1276]
https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/194884620#L6687

Possible cause:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=490890

This is how Code Recommenders worked around it: http://git.eclipse.org/c/recommenders/org.eclipse.recommenders.git/commit/?id=5cd08804815230b9e6fb42002de0b6437eef5151

Another possibility is that we're running an older Tycho that is using the older Equinox.
Upgrading Tycho has a problem with our toolchain config.
From @briandealwis :

>  Problem is that Tycho 0.26 (0.25?) requires Java 8. And so our tycho.toolchains won't work on Travis.
> Ah, we can have a .travis.yml rule to copy in a configured ~/.m2/toolchains.xml, and use the docker image to figure out what needs to be done
> I have part of this done as I explored going pomless a while back but hit this issue

Also Travis uses an older Maven version.

**Comment by chanseokoh** [comment]
The problem goes away when we use Maven 3.3.9: https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/builds/194908327

Relevant commit: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/commit/af19f0a2382fd6fdf0720c42f636bfe6f238914c

**Comment by akerekes** [comment]
@chanseokoh would you mind committing the fix?

**Comment by briandealwis** [comment]
I have a slightly different version of the fix in [my pomless branch](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/commit/ffd7778c82a5876cfe041a3297e0e65a88a523da) that uses the maven wrapper approach.  The benefit is that the artifacts should be fetched and thus cached in the `~/.m2/repository` and speed the builds.

**Comment by chanseokoh** [comment]
I guess @briandealwis has a better solution.

BTW and FTR, I was able to reproduce this problem. It isn't a transient problem.

**Comment by briandealwis** [comment]
> I guess @briandealwis has a better solution.

Well let's see.  I forgot to add the [`.extensions` directory](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/pomless/.mvn/extensions.xml) and I'm not sure what will happen.
