### ISSUE TITLE
Cannot test build.properties if bundle doesn't have plugin.xml

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1281]
If a bundle doesn't have `plugin.xml`, it cannot test `build.properties` with [`BasePluginXmlTest.testBuildProperties`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.test.util/src/com/google/cloud/tools/eclipse/test/util/BasePluginXmlTest.java#L101), because `BasePluginXmlTest` will outright fail if `plugin.xml` doesn't exist. We may need to factor out the `build.properties` portion to its own class.

**Comment by elharo** [comment]
Agreed. These should be two separate classes.

**Comment by elharo** [comment]
Per @briandealwis 

The plugin.xml tests may be independent of build.properties tests right now, but as we develop these further they won't be.

The ideal to my mind would be a single class that I create that verifies this is a well-formed bundle, where I have to explicitly toggle off things that I feel don't apply. So it should test that there's a Bundle-Activation: lazy header, that if Bundle-{Name,Vendor,Description} start with an % then there should be a Bundle-Localization header, if there's a Bundle-Localization: XXX header then there's a XXX.properties file and it's in the build.properties.
