### ISSUE TITLE
"Convert to App Engine Standard Project" needs to add missing web.xml

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1291]
I used our new "Convert to App Engine Standard Project" menu item to convert a new empty, plain vanilla Java project. It added WEB-INF and appengine-web.xml but not web.xml. So when I went to the now enabled "Run As > App Engine" menu item:

![image](https://cloud.githubusercontent.com/assets/1005544/22345176/1208202c-e3cd-11e6-8608-8c9b830264ed.png)

**Comment by elharo** [comment]
FYI, I assume it's the missing web.xml that's a problem. Could be something else.

**Comment by chanseokoh** [comment]
I'll look into it now.

**Comment by chanseokoh** [comment]
Turns out that `web.xml` wasn't being generated by the Dynamic Web facet either when we create a new App Engine project. (We happen to supply our own `web.xml`.) Maybe we need more configuration when we programmatically add the facet.

**Comment by elharo** [comment]
Probably. We don't want to create broken projects that can't be run or deployed.
