### ISSUE TITLE
Enter GCS bucket name

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1305]
in release_after_kokoro.sh "-n Enter GCS bucket URL taken from the Kokoro page:"

seems incorrect. It appears this should be a path/bucket name, not a URL. 

```
https://pantheon.corp.google.com/storage/browser/signedjars/staging/prod/google-cloud-eclipse/ubuntu/release/80/20170127-142523?authuser=1
GCS URL extracted: https://pantheon.corp.google.com/storage/browser/signedjars/staging/prod/google-cloud-eclipse/ubuntu/release/80/20170127-142523?authuser=1
-n Check if the URL is correct. 
-n Proceed ([Y]/n)? 
```

e.g. signedjars/staging/prod/google-cloud-eclipse/ubuntu/release/80/20170127-142523

**Comment by chanseokoh** [comment]
The script is supposed to extract the path/bucket name portion from the URL, but my guess is that the the sed regex works differently on Mac?

In any case, I see a bug that if the URL includes parameters (like "?authuser=1"), it won't work.

**Comment by elharo** [comment]
I don't think sed is different but ?authuser=1 may have been the problem.

**Comment by chanseokoh** [comment]
Strange. When I entered the same URL, sed was able to extract the bucket portion (although it still appends `?authuser=1`, which is problematic).

```
#
# Copy files built (signed) by Kokoro
# into '/home/chanseok/CT4E_release_work/signed'.
#
Enter GCS bucket URL taken from the Kokoro page: https://pantheon.corp.google.com/storage/browser/signedjars/staging/prod/google-cloud-eclipse/ubuntu/release/80/20170127-142523?authuser=1
GCS URL extracted: signedjars/staging/prod/google-cloud-eclipse/ubuntu/release/80/20170127-142523?authuser=1
Check if the URL is correct. Proceed ([Y]/n)?
```

**Comment by chanseokoh** [comment]
I'll just use `grep` instead of `sed`. Can't test on Mac, but I hope this will work.

**Comment by elharo** [comment]
I'll have to look but I'm not sure that's the problem. We may want to think about rewriting this script in Python so we can more easily test it.
