### ISSUE TITLE
Verify if constants have been injected...

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1306]
Verify if constants have been injected...

-n Proceed ([Y]/n)? 

This step is not included in the release instructions

**Comment by elharo** [comment]
We should probably just automate this step.

**Comment by elharo** [comment]
Ah looks like it is automated but there's an extra

# Verify if constants have been injected...
#
-n Proceed ([Y]/n)? 

We don't need before the constants are read out of the jar.

**Comment by chanseokoh** [comment]
This step is in the release instructions. I removed the "documentation" label.
