### ISSUE TITLE
Unified New Project Wizard page

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1326]
For discussion. Post 1.0 what do people think of a single wizard like this one?

Flex/standard
Maven/No Maven

One menu item 

![image](https://cloud.githubusercontent.com/assets/1005544/22468003/d0c8b77c-e794-11e6-943f-8f5cdfb0053f.png)

Subsequent pages would change depending on the selections the user made.

**Comment by patflynn** [comment]
I'm not against it, but the libraries would be different between flex and
standard.

random nit: 'use maven' isn't clear. use maven for what?

**Comment by elharo** [comment]
What's different about the libraries between flex and maven?

**Comment by patflynn** [comment]
you mean flex and standard?  The app engine APIs library is for Standard
only.  Flex users are expected to use our VTK libraries. Objectify doesn't
support Flex.

**Comment by chanseokoh** [comment]
Thinking about standard vs. flex and its default selection, I wonder if they warrant more attention from users for decision, given the nature of how vastly different they are. For example, if a widget for such a decision is embedded in a crowded page, I think it's easy for people to think that the default selection (standard, in the above screen case) is the default one that is good for usual cases. That is, most of the time, people wouldn't want or bother to change default selections unless they become interested in advancing into something fancy, right?

That said, I wonder if it's better to make wizard a "true" wizard, i.e., one that walks you through everything in a step-by-step manner. For example, the first page just asks whether they want to create a standard or flex app, with some help texts describing how they are different and for which they are more suitable.

**Comment by elharo** [comment]
@patflynn  Good point. So if we go down this path we should move library selection to a separate screen we only show to standard users. Or perhaps remove it completely if we have a better story for post-project-creation library addition. 

@chanseokoh We do have room to add some additional text to the standard and flex radio buttons.

**Comment by briandealwis** [comment]
I don't think a wizard is the right place to walk through and explain the differences between the different styles of project — witness the pushback from Clippy.

**Comment by hray2003** [comment]
+1 one introducing stepper in the flow as its complexity is growing, i.e. group way fewer closely related actions on one screen so user has a quick overview what's happening. VS team has been exploring [a similar approach](https://folio.googleplex.com/dev-ux/developer_tools/visual_studio/publishing_dialog/flow_02#).

**Comment by elharo** [comment]
@hray2003 The flow you point to seems to be a deploy flow, not a new project flow.

Tangential note: those mocks say "Publish". Most of our docs say "Deploy". Is "Publish the standard term in the VS world? If not you might want to chang those to "Deploy" for consistency.

**Comment by elharo** [comment]
Tentatively, I'm thinking that flex and standard should be separate wizards and menu items. However, maven and non-maven can still be combined into the same wizard with a checkbox.

**Comment by chanseokoh** [comment]
When we unify the two wizards, we could push down the following currently-flex-only Maven code down to the base class:

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/flex/AppEngineFlexProjectWizard.java#L65

There might be more cases where we can push down flex-only Maven code down to the common base.
