### ISSUE TITLE
Add button to refresh the project list

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1352]
~~Query the server periodically for the list of projects and~~ Add a button next to the project list that the user can use to request a refresh of the list's contents. If there's a new project in the result that is not yet in the list, add it. This will ensure that once the user creates the GCP project in the browser, we'll add it to the list eventually.

**Comment by patflynn** [comment]
Don't you refresh every time the user opens the widget?

**Comment by akerekes** [comment]
If the widget is a table then it's not really opened/closed while the dialog is open. When the dialog is displayed, we query the projects, but if the user then creates a new one via the web console, we should be able to notice that and add to the list.

**Comment by patflynn** [comment]
in IJ we have a refresh button on the widget.

**Comment by akerekes** [comment]
I know. It wasn't immediately clear how could I add that to a table that is discoverable by the users (unlike a right click->context menu), so I came up with this. But probably we could just add a refresh button/link next to the table under the corresponding label:

![image](https://cloud.githubusercontent.com/assets/3378942/22707239/260f0078-ed40-11e6-8bfe-f074a7fe964c.png)

**Comment by patflynn** [comment]
Yeah, I think if it's a button it should be OK.

**Comment by akerekes** [comment]
Fixed by #1472
