### ISSUE TITLE
Support shared referenced projects

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#136]
This is a bug from the old plugin we need to check that we don't reproduce in the new plugin:

From:

https://code.google.com/p/googleappengine/issues/detail?id=10652&q=wtp&colspec=ID%20Type%20Component%20Status%20Stars%20Summary%20Language%20Priority%20Owner%20Log

The Eclipse WTP plugin does not support shared referenced projects (shared code) when the projects are referenced from multiple WAR modules.  The referenced project is correctly compiled into a common.jar file, however it's only placed in the WEB-INF/lib directory on the first WAR, and not the others.  You'll get a ClassNotFound exception in other projects.

Steps to reproduce:
1. Create a multi-module EAR project
2. Create a new "common" project (or Utility Project)
3. Reference the "common" project in all modules.
4. Access some classes in the common code project from each module (e.g. some simple method from a Servlet).
5. Run using the WTP server and/or deploy to App Engine.  The common code will work in one module, but not in the others (ClassNotFound).

Expected behaviour:

The "common" code should be accessible in all referenced WAR modules.

What version of the product are you using? On what operating system?
- Eclipse GAE WTP plugin 1.9.0
- Both Mac and Windows

Temporary Workaround:
- Use Eclipse's "Linked Source" directory support to reference shared code between applications.

**Comment by briandealwis** [comment]
Note that _Eclipse WTP Plugin_ in the above is referencing the GPE WTP plugin.

**Comment by briandealwis** [comment]
Our `LocalAppEnginePublishingOperation` isn't handling child modules.  Fortunately it looks relatively straightforward; I'm a bit surprised that WTP doesn't provide a base version out-of-the-box.

**Comment by briandealwis** [comment]
I've pushed up a fix in the branch [i136](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/i136).  I haven't yet figured out how to express the dependencies for a self-contained test.  I'll instead use the GWT `modular-webapp` archetype.
