### ISSUE TITLE
Move commonly used third-party/Google jars to a shared bundle

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1364]
Currently `c.g.c.t.e.login` project contains jars used to communicate with Google APIs, some of them are common jars, that are required also by the `c.g.c.t.e.projectselector` bundle to access other Google APIs.
As a quick workaround classloader issues, the `login` bundle exports these packages as uses the `x-friends` attribute to restrict their visibility, but ultimately these jars should be moved to a bundle that can export these packages.

**Comment by elharo** [comment]
Ultimately these jars should be OSGIfied and pushed to maven central. We shouldn't be carrying around separate lib directories.

Until that gets fixed, do whatever works.

**Comment by chanseokoh** [comment]
I think #1438 was a dup of this. (All jars we embed are now in the `.googleapis` bundle.) Closing.
