### ISSUE TITLE
Class file is Java 8 but max supported is Java 7

### ISSUE THREAD

**Issue by grembek** [GoogleCloudPlatform/google-cloud-eclipse#1365]
Hi,

I am struggling for two days to deploy my code to Google App Engine and I am unable to do so because of the error "Class file is Java 8 but max supported is Java 7". I tried everything I could find on the web and it is very frustrating that I cannot do so. The App can run locally, but fails I deploy it to the remote server. Can you please advise.

"Beginning interaction for module default...
0% Scanning for jsp files.
0% Compiling jsp files.
Unable to stage app: Class file is Java 8 but max supported is Java 7: org/eclipse/jetty/apache/jsp/JettyJasperInitializer$1.class in /Users/grembek/Documents/DevelopmentApps/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/apache-jsp/org.eclipse.jetty.apache-jsp-9.3.14.v20161028-nolog.jar
Please see the logs [/var/folders/24/1d9xwv3536xf_z483zhs_n300000gn/T/appcfg110329673286093132.log] for further information."

<img width="396" alt="screen shot 2017-02-09 at 10 26 59" src="https://cloud.githubusercontent.com/assets/1566285/22775052/955e02bc-eeb2-11e6-9366-b1f055f3a7a1.png">
<img width="797" alt="screen shot 2017-02-09 at 10 28 01" src="https://cloud.githubusercontent.com/assets/1566285/22775053/955f126a-eeb2-11e6-978b-d980f99b3732.png">
<img width="657" alt="screen shot 2017-02-09 at 10 28 25" src="https://cloud.githubusercontent.com/assets/1566285/22775051/955cde5a-eeb2-11e6-9acb-0e1b04654883.png">
<img width="588" alt="screen shot 2017-02-09 at 10 29 36" src="https://cloud.githubusercontent.com/assets/1566285/22775107/ce044626-eeb2-11e6-95d6-a9858e54aec3.png">
<img width="684" alt="screen shot 2017-02-09 at 10 30 17" src="https://cloud.githubusercontent.com/assets/1566285/22775106/ce03f428-eeb2-11e6-8dcb-ad8f7d851020.png">

**Comment by akerekes** [comment]
Hi @grembek ,

can you please check what's schema version set in your web.xml?

Also can you share the web.xml used for staging? You can found it under _&lt;Eclipse workspace&gt;_/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/_&lt;timestamp&gt;_/staging/WEB-INF.

**Comment by grembek** [comment]
Sure. This is the web.xml within the project:
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1">
</web-app>


There are two files in the metadata/plugin folder (different timestamps):
<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1">
</web-app>




<?xml version="1.0" encoding="UTF-8"?>
<web-app xmlns="http://xmlns.jcp.org/xml/ns/javaee"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/web-app_3_1.xsd"
         version="3.1">
</web-app>

**Comment by akerekes** [comment]
So the problem is that the web.xml uses version 3.1, while App Engine Standard only supports 2.5 which causes the staging to fail with this error message. Please change the version and try deploying again.

**Comment by grembek** [comment]
Thanks 
I'll try, anyway, I would suggest to specify a more clear message if that is the case

**Comment by elharo** [comment]
I wonder if this is something we could mark with a warning/error in Eclipse? @abbiefarr What do you think?

Also, there's a second issue here though it's not the cause of the problem you're seeing. You're using the old appengine SDK based maven plugin in your pom.xml whereas the IDES are using gcloud. The equivalent maven plugin is https://cloud.google.com/appengine/docs/java/tools/using-maven
Is that something we should warn about?

**Comment by chanseokoh** [comment]
Cross-ref: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1230

**Comment by sunysudan** [comment]
Unable to update app: Class file is Java 8 but max supported is Java 7 
[The solution is here](http://sunysudan.blogspot.in/2017/06/unable-to-update-app-class-file-is-java.html)
