### ISSUE TITLE
Enhance JDO classes with Datanucleus

### ISSUE THREAD

**Issue by TheCloudGate** [GoogleCloudPlatform/google-cloud-eclipse#1366]
Using in App Engine Standard Envirotment (no Maven):

How is implemented, configured in plugin this step: https://cloud.google.com/appengine/docs/java/datastore/jdo/overview-dn2#Enhancing_Data_Classes

In previous Google Plugin Eclipse, this step was configured in GUI and done automatically.

**Comment by elharo** [comment]
Not a bad idea, but we're working on Objectify and direct DataStore API access first. As that page says,

"We think most developers will have a better experience using the low-level Datastore API, or one of the open-source APIs developed specifically for Datastore, such as Objectify. JDO was designed for use with traditional relational databases, and so has no way to explicitly represent some of the aspects of Datastore that make it different from relational databases, such as entity groups and ancestor queries. This can lead to subtle issues that are difficult to understand and fix"

**Comment by TheCloudGate** [comment]
When we started our project (end 201) Objectify was at the beginning, and those times JDO was a clear choice.

If we would start now a new project, probably we will use Objectify, if I don't value to have a JDO standard in case in need to move my project, but it' not the case. We have legacy, history, not like most developers from your point fo view. It would be interesting if there are more developers like us. 

And also we'll investigate an alternative to launch Datanucleus enhacer in Eclipse.

I encourage to add this functionality sooner or later (once Eclipse Oxygen is launched)

**Comment by akerekes** [comment]
This might be of help: http://www.datanucleus.org/products/datanucleus/jdo/guides/eclipse.html

**Comment by TheCloudGate** [comment]
It seems that Maven could do the job, There is a goal to make Datanucleus...https://cloud.google.com/appengine/docs/java/tools/maven#application_management_goals

What do you think? It could be a solution to this issue if Google-Cloud-Eclipse works fine with Maven.

**Comment by elharo** [comment]
Cloud Tools for Eclipse should not get in the way of any existing Maven goals or workflows. However the page you cite is pointing to an old and not well supported version of the maven plugin. I'd suggest looking at pure DataNucleus plugins that aren't specifically targeted to App Engine.

**Comment by patflynn** [comment]
We have maven instructions for doing that here:
https://cloud.google.com/appengine/docs/java/datastore/jdo/overview-dn2

**Comment by elharo** [comment]
DataNucleus no longer recommended for App Engine.
