### ISSUE TITLE
index.html in install URL not being served

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1372]
IIUC, this file should be served when users access the install URL directly from a browser, e.g., https://dl.google.com/eclipse/google-cloud-eclipse/beta/, right? Unfortunately, this works only if you explicitly append index.html at the end of the URL. This is because the backend is not a generic web server. Could the backend be configured somehow?

**Comment by chanseokoh** [comment]
This may be relevant: https://cloud.google.com/storage/docs/hosting-static-website

However, looks like they recommend HTTP over HTTPS for a static website.

**Comment by elharo** [comment]
The https/http issues are, I think, only when using a custom domain. We should be fine with using the URLs we're using.

**Comment by briandealwis** [comment]
Fetching https://dl.google.com/eclipse/google-cloud-eclipse/beta/index.html (and https://dl.google.com/eclipse/google-cloud-eclipse/stable/index.html) works.

**Comment by diegomarquezp** [comment]
Closing as not planned.
