### ISSUE TITLE
Set application name when making API calls

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1381]
We are starting to add new API calls (getting GCP projects, user names, profile pictures, etc), and we need to ensure that we always set an application name identifying our tool CT4E. I believe APIs will then put (perhaps append) the given application name in the User-Agent HTTP header.

**Comment by elharo** [comment]
@chanseokoh We can close this one now, right?

**Comment by chanseokoh** [comment]
For now, we are done.
