### ISSUE TITLE
Create a new Maven-based App Engine standard environment project in the workspace even when we're not

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1396]
Even when creating a project outside the workspace the info message still says, "Create a new Maven-based App Engine standard environment project in the workspace"

![image](https://cloud.githubusercontent.com/assets/1005544/22898724/55243b5c-f1f6-11e6-976f-bd36a4cb3f0b.png)

**Comment by chanseokoh** [comment]
The wording of the info message seems right, since a project ends up being created in some workspace after all. I think it's the wording of the checkbox "create project in workspace" is incorrect. For example, the label in the standard Java project wizard says "use default location".
