### ISSUE TITLE
Push login icon to right

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1414]
The little multicolored G icon we use to login sometimes shows up on the lower left of the IDE window. It usually eventually moves to the right. We should figure out how to make it appear consistently on the lower right.

![image](https://cloud.githubusercontent.com/assets/1005544/23022029/d2908e2e-f41c-11e6-80d1-4d1bfca7f549.png)

**Comment by chanseokoh** [comment]
Yeah, one place this can happen: if the first screen you see when you start Eclipse is the Welcome page.

**Comment by lak-proddev** [comment]
It's also another eclipse bug. See these bug details.

https://bugs.eclipse.org/bugs/show_bug.cgi?id=253232
https://bugs.eclipse.org/bugs/show_bug.cgi?id=371821
https://bugs.eclipse.org/bugs/show_bug.cgi?id=494789

Bug description from https://bug.cloverdx.com/browse/CLO-4185?focusedCommentId=52724&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-52724

> Short story: positioning contributions in trim area simply does not work.
> Long story: under 3.x one can add query to contribution URI like toolbar:org.eclipse.ui.trim.status?after=org.eclipse.jface.action.StatusLineManager and that placement is honoured during contribution processing (trim contribution is added between status line manager and progress region), however, in the end the contribution is rendered in the left corner even before FastViewBar, let alone StatusLine. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=253232 - perhaps the bug re-appeared in the meantime.
> Under Eclipse 4 the situation is even worse, when using URI with placement query, the contribution is not displayed at all. There is bug about this funcionality (https://bugs.eclipse.org/bugs/show_bug.cgi?id=371821), but developers did not understand the issue and turned it into duplicate of different bug. As the functionality is broken un 3.x, it is unlikely it will be ever fixed in 4.x's compatibiity layer - luckily manual DnD of contribution items works and user can place the control wherever he wishes.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
