### ISSUE TITLE
Project ID not selected when real issue is no GCP access

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1415]
The issue in this case is that no project IDs are available; in this case because the logged in account does not have GCP access. 

![image](https://cloud.githubusercontent.com/assets/1005544/23022226/b8b3ac10-f41d-11e6-8f6e-a211e0e2e48e.png)

Is there anyway we can improve the warning message in this case?

**Comment by chanseokoh** [comment]
Given that we will not show an error message in the Preferences dialog (because users don't have to select a project in Preferences), one option could be to make Project Selector displays a message like "no GCP project found for this account" inside its tableview.
