### ISSUE TITLE
Weird box in Account selector

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1416]
A few times I've seen a little box show up the left of the account name in the account selector:

![image](https://cloud.githubusercontent.com/assets/1005544/23022287/00889cda-f41e-11e6-885e-3417a0a7ebea.png)

Not sure why or when this happens. This isn't worth spending a lot of time on, but if anyone sees a quick way to fix this, go ahead.

**Comment by briandealwis** [comment]
It's supposed to be a checkmark.  Have you set a different font within your Eclipse?

<img width="88" alt="screen shot 2017-02-27 at 3 45 26 pm" src="https://cloud.githubusercontent.com/assets/202851/23379149/d76f0dea-fd03-11e6-81f6-7804a9721eaa.PNG">

**Comment by elharo** [comment]
I've noticed this behavior outside Eclipse as well so it may be something funky on my Mac.
