### ISSUE TITLE
Info Message for deploy

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1417]
When the user has selected an account and a project we should show a brief info message here. Something like "Deploy fred to the GCP project hellobrowser"

![image](https://cloud.githubusercontent.com/assets/1005544/23022385/81674144-f41e-11e6-9150-4ae354f232dc.png)

**Comment by lak-proddev** [comment]
The above fix will show  like this 
![image](https://user-images.githubusercontent.com/39690425/57538223-90d0b980-7365-11e9-9941-d6b5e24f4cb0.png)
