### ISSUE TITLE
Analytics dashboard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#142]
To monitor all the analytics data we're collecting

**Comment by chanseokoh** [comment]
**Server-side metrics**
  - Set CLOUDSDK_METRICS_ENVIRONMENT to a unique string.
    - IntelliJ plugin uses `gcloud-intellij`.
  - Make sure `gcloud` can read the env variable when executed.

**Client-side metrics**
  - Opt-in.
    - Privacy review necessary.
    - The Concord team recommends including hashed project numbers. We haven't decided yet about this.
  - Sending metrics to a Concord GA property.
    - We need some way to hide this Analytics ID from the codebase and magically include it when actually deploying our plugin.
    - We will use this library: [https://github.com/google/cloud-reporting](https://github.com/google/cloud-reporting) (not actively maintained though)

**Comment by chanseokoh** [comment]
Done.
