### ISSUE TITLE
Run As > App Engine with build failures

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1423]
We block deployment when the project doesn't build, but not when we only run locally.

![image](https://cloud.githubusercontent.com/assets/1005544/23023580/5114594a-f424-11e6-82be-1acab815969e.png)

Should we block local run too? I'm not sure. For regular Java apps, Eclipse does let you run with build errors, but it asks you first:

![image](https://cloud.githubusercontent.com/assets/1005544/23023699/c0566276-f424-11e6-94a7-164bf6f8d944.png)

We should probably do something similar.

**Comment by briandealwis** [comment]
This is a similar issue to #1427: we need to implement `getProjectsForProblemSearch()`.
