### ISSUE TITLE
'Run as App Engine' action should wait for user to save changes

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1427]
Steps to reproduce:
1. user modifies the source, but does not save the changes
1. Right click on project/Run as App Engine
1. the local run will start while Eclipse displays a dialog to offer the user to save the changes

Expected: the local run should wait until the user closes the dialog about saving the changes.

**Comment by elharo** [comment]
What happens if, for example, you do the same thing with a regularJava app?

**Comment by briandealwis** [comment]
There's definitely support in the launch delegate for handling this; we must be preventing it.

**Comment by elharo** [comment]
Verified that a regular Run As Junit Test doesn't run until the user has closed the dialog.

**Comment by briandealwis** [comment]
Normally this is handled by the _LaunchConfigurationDelegate_ class by the _preLaunch()_ method.  We're not getting this as we're not implementing `AbstractLaunchConfigurationDelegate#getBuildOrder()` so that `saveBeforeLaunch()` never examines the relevant projects to prompt.


The WTP _Servers_ view does a save-before-launch by directly calling `IWorkbench.saveAllEditors()` from its Run/Debug button.  I guess it does this as it each server may have a separate _LaunchConfigurationDelegate_ class, like we do, and they may not implement `getBuildOrder()`, like we don't (yet):
```
Thread [main] (Suspended)	
	OS.objc_msgSend_bool(long, long, long, long) line: not available [native method]	
	NSRunLoop.runMode(NSString, NSDate) line: 42	
	Display.sleep() line: 4829	
	SaveablesList$2(Window).runEventLoop(Shell) line: 819	
	SaveablesList$2(Window).open() line: 794	
	SaveablesList$2(MessageDialog).open() line: 396	
	SaveablesList.promptForSaving(List<Saveable>, IShellProvider, IRunnableContext, boolean, boolean) line: 546	
	SaveablesList.promptForSavingIfNecessary(IShellProvider, IWorkbenchWindow, Set<Saveable>, Map<Saveable,Integer>, boolean) line: 448	
	SaveablesList.preCloseParts(List<IWorkbenchPart>, boolean, boolean, IShellProvider, IWorkbenchWindow) line: 404	
	WorkbenchPage.saveAll(List<IWorkbenchPart>, boolean, boolean, boolean, IRunnableContext, IWorkbenchWindow) line: 3688	
	Workbench.saveAllEditors(boolean, boolean) line: 1395	
	Workbench.saveAllEditors(boolean) line: 1374	
	ServerUIPlugin.saveEditors() line: 464	
	StartAction.start(IServer, String, Shell) line: 157	
	StartAction.perform(IServer) line: 152	
	StartAction(AbstractServerAction).run() line: 64	
	StartAction(Action).runWithEvent(Event) line: 473	
	ActionContributionItem.handleWidgetSelection(Event, boolean) line: 565	
```

**Comment by briandealwis** [comment]
What's odd is that WTP's `SaveEditorPrompter#saveAllEditors()` uses an _asyncExec()_, so the launch continues even while the user is prompted.
```
 	@Override
	public void saveAllEditors() {
		IWorkbench w = PlatformUI.getWorkbench();
		String saveBeforeLaunch = DebugUITools.getPreferenceStore().getString(org.eclipse.debug.internal.ui.IInternalDebugUIConstants.PREF_SAVE_DIRTY_EDITORS_BEFORE_LAUNCH);
		if (saveBeforeLaunch.equalsIgnoreCase(org.eclipse.jface.dialogs.MessageDialogWithToggle.ALWAYS)){
			Display d =PlatformUI.getWorkbench().getDisplay();
			d.asyncExec(new SaveAllEditorsRunnable(w,false));
		}
		else if (saveBeforeLaunch.equalsIgnoreCase(org.eclipse.jface.dialogs.MessageDialogWithToggle.PROMPT)){
			Display d =PlatformUI.getWorkbench().getDisplay();
			d.asyncExec(new SaveAllEditorsRunnable(w,true));
		}
	}
```

**Comment by briandealwis** [comment]
The WTP _Servers_ view's Run/Debug actions explicitly call `ServerUIPlugin#saveEditors()` which in turn calls `IWorkbench#saveAllEditors()`, which is a synchronous call.

**Comment by briandealwis** [comment]
If I implement `getBuildOrder()` and `getProjectsForProblemSearch()` as [per above](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1427#issuecomment-280449310), then launching a previous launch configuration brings up a select-resources-to-save dialog.

**Comment by briandealwis** [comment]
But WTP's `SaveEditorPrompter#saveAllEditors()` (which is asynchronous) disables the Workbench's _Save required dirty editors before launching_ setting while it pops up its own prompts.  Which I suppose is a good thing as the launch continues during `SaveEditorPrompter`'s prompt, and we'd get two prompts showing.

**Comment by briandealwis** [comment]
So the take-away here is:
  1. We should implement `LaunchConfigurationDelegate`'s `getBuildOrder()` and `getProjectsForProblemSearch()`
  2. We have two options for our launch shortcut and _GCP > {Run|Debug} as App Engine_ implementations (centralized in `LaunchHelper` class):
    - We could call `IWorkbench.saveAllEditors()` explicitly.  But if the user says _No_, then they'll be prompted again.
    - We could avoid using `IServer#start()` and instead use `DebugUIPlugin#launchInBackground()` and provide the LaunchConfiguration instance directly.  The disadvantage is that `IServer#start()`'s implementation also does some publish-before-launch checks.

**Comment by briandealwis** [comment]
Thinking about it a bit more, I've chosen to following the _Servers_ view approach and call to `ServerUIPlugin.saveEditors()` beofre calling `IServer#start()`.  Using `ServerUIPlugin.saveEditors()` respects the user's setting in _Preferences > Server > Launching > Save dirty editors before starting the server_.  Like the _Servers_ view approach, it too leads to a second prompt if the user says _No_ to saving dirty editors as it continue to use the same puzzling `IServer#start()` background-launching code path.
