### ISSUE TITLE
Changes to Java files are not published to local devserver (devappserver2)

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1428]
If the user changes the source code while the local devappserver is running, the changes are noticed by the runtime (i.e. the Servers view indicates that the application should be republished). But running publish from the context menu of the server does not actually refresh the code, although the Servers view indicates that the application is not in sync with the sources.

**Comment by briandealwis** [comment]
IIRC we disabled this as otherwise the server was restarted.  So saving a source file while debugging would trigger a publish and restart the server.

**Comment by akerekes** [comment]
@briandealwis when I observed this issue I was changing the servlet code (in the new project wizard generated hello world example)

**Comment by briandealwis** [comment]
@akerekes were you Debugging or Running the server?  If the former, uh oh.  If the latter, then works as expected. Can you reproduce?

**Comment by chanseokoh** [comment]
> (i.e. the Servers view indicates that the application should be republished). But running publish from the context menu of the server does not actually

![image](https://cloud.githubusercontent.com/assets/10523105/23668764/04085cc6-0330-11e7-93fc-849b1e56e215.png)

A minor point, but I noticed that the status indication "Republish" actually means "Republishing". You don't have to explicitly republish here. If you wait for a _very_ long time (like 10 seconds?), the republishing will be done automatically, and the status will eventually go back to "Started".

**Comment by chanseokoh** [comment]
I did some testing. Summary:

1. Changing `index.html`: server automatically picks up changes in both _Debug_ and _Run_.
1. Changing `HelloAppEngine.java`: server automatically picks up changes in _Debug_ but not in _Run_. Seems like this is intended per https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1428#issuecomment-284742270.

**Comment by briandealwis** [comment]
@chanseokoh did say that there was some latency (5-10s) between making the change and it being picked up by the devappserver.

**Comment by akerekes** [comment]
@briandealwis it was in Run mode

**Comment by briandealwis** [comment]
I made a mistake in updating the title above: @akerekes was referring to changes to `.java` source files not being reflected into the running server.

I can verify that .class files are properly re-published.  But the JVM does not pick up these changes.

**Comment by briandealwis** [comment]
The issue here is: identify code changes and warn the user they likely will not take effect.

**Comment by chanseokoh** [comment]
> But the JVM does not pick up these changes.

To clarify again, only in the _Run_ mode. (_Debug_ picks up changes.)

**Comment by briandealwis** [comment]
`IServer` supports a publish listener mechanism to notify of publish start and stop events.  Server events also track publish state changes, including the module being republished.  We could listen for the module changes, transform that into a resource delta (`IModuleResourceDelta` via `LocalAppEngineServerBehaviour#getPublishedResourceDelta()`), and then look for .class files.  I don't see a way of getting a list of publishing changes.

**Comment by briandealwis** [comment]
Currently we disable _devappserver_'s auto-restart.  Perhaps we should enable it for _Run_, and disable it for _Debug_.

**Comment by briandealwis** [comment]
> Currently we disable devappserver's auto-restart. Perhaps we should enable it for Run, and disable it for Debug.

Note that this behaviour is specific to devappserver2, and devappserver1 (the default as of #1731 / #1739) doesn't seem to support automatic-restart.
