### ISSUE TITLE
check appengine-web.xml for invalid tags

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1432]
Based on https://cloud.google.com/appengine/docs/java/config/appref we could check whether the appengine-web.xml contains an invalid (mistyped?) element and give an error similar to how we give a warning about the `<application>` tag

**Comment by elharo** [comment]
There may be a schema/DTD somewhere we can use. That said, a quickfix in this case may not be possible; but a warning doesn't hurt.

**Comment by akerekes** [comment]
If the invalid tag fails the deployment, we should give an error instead of a warning.

**Comment by briandealwis** [comment]
The Google Cloud SDK includes a copy of the XSD in `platform/google_appengine/google/appengine/tools/java/docs/appengine-web.xsd`.
