### ISSUE TITLE
Inconsistent title of browser tabs

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1433]
The browser tab opened at the end of a deploy (on the left) has a different title than the browser tab opened by clicking on the link highlighted in the deploy console (on the right).

![image](https://cloud.githubusercontent.com/assets/3378942/23032973/566218cc-f444-11e6-8c71-5c04fbba8426.png)

I think these should be the same.

**Comment by elharo** [comment]
What browser/OS? On Firefox/Mac both tabs show "Hello App Engine"

![image](https://cloud.githubusercontent.com/assets/1005544/23121787/c09ff6f8-f72f-11e6-8e13-ad3af7b1ee06.png)

**Comment by akerekes** [comment]
My screenshot is from Linux showing the Eclipse internal browser.

**Comment by elharo** [comment]
In `DeployJob` we set the tab title but this doesn't apply when it's not opened automatically:

```
  private IStatus openAppInBrowser() {
    try {
      String rawDeployOutput = deployStdoutLineListener.toString();
      AppEngineDeployOutput structuredOutput = AppEngineDeployOutput.parse(rawDeployOutput);

      boolean promoted = deployConfiguration.getPromote();
      String appLocation = getDeployedAppUrl(promoted, structuredOutput);
      String project = deployConfiguration.getProject();
      String browserTitle = Messages.getString("browser.launch.title", project);
      WorkbenchUtil.openInBrowserInUiThread(appLocation, null, browserTitle, browserTitle);
      return Status.OK_STATUS;
    } catch (IndexOutOfBoundsException | JsonParseException ex)  {
      return StatusUtil.error(this, Messages.getString("browser.launch.failed"), ex);
    }
  }
```

**Comment by elharo** [comment]
seemsd we can't pass null for the tab title

**Comment by elharo** [comment]
This turns out to be infeasible. WorkbenchUtil.openInBrowserInUiThread requires a tab title, and there's no reasonably straigt-forward way to set it to the title in the page. We'd have to load the poage in a java.net.URL and parse out the title from the HTML instead, or notice what the title is when we're deploying.
