### ISSUE TITLE
Show src/main/webapp and/or appengine-web.xml more prominently in the Project Explorer

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1434]
~~Both for native and Maven projects.~~
Somewhere here:
![image](https://cloud.githubusercontent.com/assets/3378942/23042008/00144348-f465-11e6-958f-91ba0c06596a.png)

**Comment by chanseokoh** [comment]
Seems like it's already there for both native and Maven projects:

![selection_001](https://cloud.githubusercontent.com/assets/10523105/23035206/5dc87fb8-f44c-11e6-9e4c-2818f94e3942.png)

Can you reproduce it?

**Comment by akerekes** [comment]
What you show is that they're included in the deployment assembly. 
![image](https://cloud.githubusercontent.com/assets/3378942/23037362/13c4e818-f454-11e6-95ca-109083e8a0e9.png)

**Comment by chanseokoh** [comment]
That's _Java Build Path_, for `.java` files, isn't it? Do people put .java files under `webapp`? @briandealwis  I'd personally put Java source files under `src/main/java`.

**Comment by briandealwis** [comment]
@chanseokoh's right: you don't want the `/src/main/webapp` directory added there as all any non-Java files will be copied over into the root directory.

I think @akerekes is requesting this so the files under `/src/main/webapp` are more prominently shown.  I think this is why the WTP Dynamic Web facets put the default location under `/WebContent`.

We could provide our own Common Navigator / Project Explorer content contribution, like WTP's _Deployment Descriptor_,  Double-clicking on the _Deployment Descriptor_ opens the web.xml

**Comment by chanseokoh** [comment]
@akerekes Is what you think is what @briandealwis said? If so, can you change the title and the description appropriately?

**Comment by briandealwis** [comment]
Chatting with @akerekes, some ideas:
  - providing a Manifest-style editor that bridges across the web.xml, app.yml/appengine-web.xml,  Dockerfile, and more
  - defining an _App Engine_ node that would offer a set of nodes for common appengine-web.xml/app.yml settings like the serviceID, version, thread-safetyness, environment, scaling, static files (with root, include, and exclude).
    - The static files could be an expandable node to navigate through the files that will actually be visible
    - Double clicking on one of these nodes would allow editing, either by opening the manifest-like editor, or popping up a dialog to edit (which would handle whether it needed to be written out to an app.yaml or appengine-web.xml)

**Comment by briandealwis** [comment]
I was working on something and found being able to double-click on the _Deployment Descriptor_ node to be handy to open up the `web.xml`.  I hacked up a trivial _App Engine Content Provider_ (though double-click doesn't work yet) to show some of the major elements.

![screen shot 2018-04-25 at 11 55 18 pm](https://user-images.githubusercontent.com/202851/39285085-8044b0e6-48e4-11e8-82db-3d2ef79bd6fb.PNG)

There's a bunch of work still required to make this real.

It's easy to add children to some existing object, so we could use this approach for describing `datastore-index.xml`, `dispatch.xml`, `cron.xml`, etc.  Or Kubernetes descriptors,  etc.

**Comment by elharo** [comment]
Sounds nice.

**Comment by briandealwis** [comment]
Latest incarnation, pulling some information as _qualifying_ info onto the projects.  `bookshelf-standard-5` is the Maven example.  `defaultservice` and `secondservice` are different service IDs.

![screen shot 2018-05-10 at 11 00 17 am](https://user-images.githubusercontent.com/202851/39876525-670b4b0e-5441-11e8-81e5-595571f189ef.PNG)

**Comment by briandealwis** [comment]
Removed child elements (project, service, version) since now reflected in the qualifier text of the various items.  Replaced them with file references to other useful files (e.g., cron.xml, dispatch.xml, etc.).  Double-clicking on items will open the corresponding file.

![screen shot 2018-05-12 at 11 35 30 pm](https://user-images.githubusercontent.com/202851/39963585-908a5526-563d-11e8-9ca8-770808745936.PNG)
