### ISSUE TITLE
Error Checking Project Facets

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1435]
![image](https://cloud.githubusercontent.com/assets/3378942/23033232/4b5c4f46-f445-11e6-81ee-0479b7f5cc5f.png)

If the user opens the context menu/Properties/Deployment Assembly page on the Deployment Descriptor element in the Project Explorer, an error is shown. Opening the same page on the top level element (the project itself) loads the page correctly.

**Comment by akerekes** [comment]
It seems it's an Eclipse problem:
http://stackoverflow.com/questions/8399885/eclipse-deployment-assembly-does-not-appear-in-properties

**Comment by akerekes** [comment]
Unfortunately the proposed solution didn't not work for me either, just like http://stackoverflow.com/questions/8399885/eclipse-deployment-assembly-does-not-appear-in-properties#comment25898335_11122253

**Comment by briandealwis** [comment]
Is this on Mars?  I fixed a related problem for Neon.2 and Oxygen (https://bugs.eclipse.org/bugs/show_bug.cgi?id=493164) and as a result I don't see the _Deployment Assembly_ page on normal files on Neon and Oxygen.

**Comment by briandealwis** [comment]
This isn't the same problem as what you're linking to on StackOverflow: you're opening the properties on the _Deployment Descriptor_, not on the project.

**Comment by akerekes** [comment]
@briandealwis Mars.2

**Comment by chanseokoh** [comment]
> it happens with a plain Dynamic Web Project

I also verified that this happens with a plain Dynamic Web Project. I think we can close this.

**Comment by briandealwis** [comment]
Filed with a patch as https://bugs.eclipse.org/bugs/show_bug.cgi?id=512325
