### ISSUE TITLE
Verify if we need to handle proxy settings in com.google.cloud.tools.eclipse.projectselector.GoogleApiFactory

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1439]
We should verify whether the proxy settings (system.workspace/project level) are used when accessing API services

**Comment by briandealwis** [comment]
Oh I forgot about this — Eclipse has its own proxy selection mechanism that we'll need to integrate. There's an example [here](http://git.eclipse.org/c/usssdk/org.eclipse.usssdk.git/tree/org.eclipse.userstorage/src/org/eclipse/userstorage/internal/util/ProxyUtil.java?h=master).

**Comment by chanseokoh** [comment]
Out of curiosity, what is this proxy thing? What could be a problem under when, and what should be done in that case regarding calling APIs?

**Comment by akerekes** [comment]
Let's assume a user is working at a company where all connections need to go through a proxy. In this case if we disregard the proxy settings, the user won't be able to connect to the API services.

**Comment by chanseokoh** [comment]
FTR, the ide-login library might also need support for this.

**Comment by briandealwis** [comment]
The proxy info is configured from the _Preferences > General > Network Connections_ and is used by Help > Install New Software, M2E and much else.  So if we don't consult org.eclipse.core.net then we could get a mismatch where M2E and updates work, but we don't.

**Comment by akerekes** [comment]
The ide-login would also need support for timeout handling.

**Comment by elharo** [comment]
ide-login goes through the user's browser which I think we can assume is correctly configured to work with local proxies. I'd be surprised if the local server it runs to pass the credentials back needs to go through a proxy.

**Comment by chanseokoh** [comment]
It's that the ide-login library additionally makes an API call to fetch user info after login.
