### ISSUE TITLE
Selected project is not selected in deploy dialog

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1457]
Steps to reproduce:
 1. login
 1. select a project and make a deploy
 1. logout
 1. open the deploy dialog and sign in
 1. the project list is shown with the projects the selected account has access to, but **none is selected**, the `Deploy` button is enabled
 1. click the `Deploy` button and a deploy with the previously used project will be executed

**Comment by elharo** [comment]
Maybe in this scenario the deploy button should not be enabled.

**Comment by akerekes** [comment]
Either disable the deploy button or select the project which was selected last time.

**Comment by lak-proddev** [comment]
Is it easily reproducible?. As I can see it always selected the previously deployed project. Otherwise, showing the validation error.
![image](https://user-images.githubusercontent.com/39690425/57526282-9f5da780-734a-11e9-9be3-0d2f287bedb3.png)

**Comment by elharo** [comment]
Thanks for noticing. This one does seem to have been fixed some time in the last couple of years.
