### ISSUE TITLE
BuildPath AddLibraries selector group should extend across dialog

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1465]
![image](https://cloud.githubusercontent.com/assets/1005544/23268627/5295b9b0-f9bc-11e6-8afd-50367176b0d9.png)

**Comment by lak-proddev** [comment]
@elharo  I think this issue is no longer valid. Can you confirm? I can see the different UI.

**Comment by mpeddada1** [comment]
Closing as obsolete
