### ISSUE TITLE
error when web.xml references undefined servlet

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1478]
I.e. the class in servlet-class is not in the project:

    <servlet-class>com.google.example.HelloAppEngine</servlet-class>

**Comment by akerekes** [comment]
Isn't this rather a WTP level check?

**Comment by chanseokoh** [comment]
I'm surprised WTP didn't have this check.

**Comment by elharo** [comment]
Me too, but it doesn't so if we have time we might as well add it.
