### ISSUE TITLE
Remove embedded google-http-client-1.22.jar from .util bundle

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1493]
Now that we have the `.googleapis` bundle which embeds `google-http-client-1.22.jar`, we shouldn't duplicate the same JAR in the `.util` bundle.

Unfortunately, I realized that we can't make `.util` depend on `.googleapis` at the moment, because `.googleapis` is already dependent on `.util` — it will result in a build cycle.

The reason that `.googleapis` depends on `.util` is only because of its use of `CloudToolsInfo.USER_AGENT` to set an application name when calling APIs.

There may be a few options:

- Remove the `.util` dep from `.googleapis` by making `GoogleApiFactory` get a user-agent string from outside, possibly through a constructor.
- Move `CloudToolsInfo` into a new standalone bundle. (Luckily, `CloudToolsInfo` does not depend on `.util`.)
- Move `CloudToolsInfo` into `.googleapis`. (I don't like this).
- ...

**Comment by elharo** [comment]
IMHO .util should not depend on google-http-client-1.22.jar

A utility bundle should be simpler than that. Can we move whatever part of .util depends on google-http-client-1.22.jar into a different bundle?

**Comment by elharo** [comment]
Another possibility, though probably too much work to be justified is to make HttpUtil not depend on google-http-client-1.22.jar. Just use the JDK classes instead. 

Dependencies == pain

**Comment by elharo** [comment]
It seems that this jar is only used by one class, HttpUtil; and in turn HttpUtil is only used by the AnalyticsPingManager in the usage tracker bundle. Let's just move HttpUtil into the usagetracker bundle, and we should be good.

**Comment by chanseokoh** [comment]
I believe there is a transitive dep from other Google API jars. I remember login does not work if  the http jar was not embedded together in the login bundle. Of course, the bundle did not make any direct use of the http jar.

**Comment by elharo** [comment]
Yes, but that should be handled by the API client bundle.

**Comment by chanseokoh** [comment]
Ah, sorry I misunderstood. You are moving a class. Cool.

**Comment by chanseokoh** [comment]
How about moving HttpUtil to a standalone bundle `.util.http`? For now `HttpUtil` is used only by `AnalyticsPingManager`, but it will soon be used by the exception catching framework too.

**Comment by chanseokoh** [comment]
Had an offline chat with @elharo, and the decision is to move `HttpUtil` to the `.usagetracker` bundle.
