### ISSUE TITLE
Having multiple links to install the Cloud SDK is confusing

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#1502]
Regarding adding the Cloud SDK, if it's installed after the plugin, it's confusing having two links to choose from. What's confusing is that the "Google Cloud SDK" link takes you to the generic page and throws you into the where-is-it mode. I recommend removing that link in this sentence and only having a clear path to the install directions. I might add a footer, directly to the documentation of the cloud tools and other links, but put this at the bottom.

![screen shot 2017-02-28 at 3 09 15 pm](https://cloud.githubusercontent.com/assets/1326504/23438741/161c6050-fdc8-11e6-9120-b9d9a6967c63.png)

**Comment by branflake2267** [comment]
Since I'm running through this process, it's a pain still to get booted up. I think it might be even better to have a Google Eclipse Cloud Tools end point where specific start up directions could be had. Even better, but maybe to ideal this early in the game, get the IDE to run the commands. :)

I may be speaking to the choir on this. 

##gcloud bash install
1. https://cloud.google.com/sdk/downloads - install the sdk (Interactive installer recommended) 

##Add the gcloud App Engine Component
2. Install the `gcloud components install app-engine-java` - https://cloud.google.com/sdk/docs/managing-components

Some notes there, still heavy, but some info for future use if needed.

**Comment by diegomarquezp** [comment]
Closing as not planned.
