### ISSUE TITLE
Menu Item for Add Libraries

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1514]
As in GPE, we should have a menu item in the context menu and in the toolbar that brings up the library selection dialog. I.e.

* Add App Engine Library...
* Add Cloud Client Library...

(Once the latter group is defined).

**Comment by elharo** [comment]
perhaps useful for adding to Build Path menu:

![image](https://cloud.githubusercontent.com/assets/1005544/23810851/53f5f18a-05a1-11e7-97b6-392862d49a45.png)

**Comment by briandealwis** [comment]
This menu is generated programmatically and doesn't allow any contributions.

<img width="503" alt="screen shot 2017-03-13 at 12 07 50 pm" src="https://cloud.githubusercontent.com/assets/202851/23863322/d515b048-07e5-11e7-9221-9b067392086a.PNG">

**Comment by elharo** [comment]
Deciding this isn't possible at reasonable cost. We'll just use Build Path > Add Libraries.
