### ISSUE TITLE
Add more screenshots to the Marketplace. 

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#1515]
Suggestion, add some more screenshots to the marketplace. I think it would add more sales pitch for the value adds (visually). I think the more visual add adds context to the value adds from a new user perspective. I don't think the context of changes should worry the screenshots.

Some ideas of screenshots. 
1. Add a screenshot of the App Engine server runtime, Seeing the a running server. 
2. Maybe a screenshot of the a Google facet in the facets config with appengine project.  
3. A acreenshot of an app engine project with some source to show it's app engine.  
4. Maybe a screenshot of the App Engine server time setup.

**Comment by elharo** [comment]
We appear to be limited to 4 total screenshots. I've added two more and updated one.
