### ISSUE TITLE
Should we make google-cloud the fourth core library?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1516]
After App Engine API, Endpoints, and Objectify:

https://github.com/GoogleCloudPlatform/google-cloud-java

<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud</artifactId>
  <version>0.9.3-alpha</version>
</dependency>

1. Not all release quality yet.
2. Pulls in a lot of dependencies. E.g. a developer might want Datastore but not BigQuery.
3. Could we somehow parse this to offer the individual components in their own library group?

**Comment by patflynn** [comment]
Each individual module is released as its own artifact.

Also none of these libraries work in App Engine standard at the moment.

**Comment by elharo** [comment]
I'm not sure that's true. Google Cloud Pub/Sub and Stackdriver Logging don't work in App Engine Standard. The others should.

**Comment by patflynn** [comment]
We'll get there soon. Feel free to talk to me or Les about it.

**Comment by ludoch** [comment]
Just to add some complexity... Some may work in Standard Java8, but not yet
on Java7, so it is not a matter of deciding on Standard versus Flex, but
also Java7 Standard and Java8 Standard...
PubSub should work in Java8 Standard for example, (but we need more formal
testing).
