### ISSUE TITLE
Inconsistent library versions when adding libraries through Build Path > Add Libraries... on Maven project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1522]
I am not certain if this is intended or if we have opened an issue for this.

When I added the App Engine API, Objectify, and Endpoints through _Build Path_ > _Add Libraries..._, Objectify uses a fixed version, but the others use `LATEST`.

```xml
<dependency>
<groupId>com.google.appengine</groupId>
<artifactId>appengine-endpoints</artifactId>
<version>LATEST</version>
</dependency>
<dependency>
<groupId>com.google.appengine</groupId>
<artifactId>appengine-api-1.0-sdk</artifactId>
<version>LATEST</version>
</dependency>
<dependency>
<groupId>com.googlecode.objectify</groupId>
<artifactId>objectify</artifactId>
<version>5.1.14</version>
</dependency>
```

**Comment by elharo** [comment]
This shouldn't even work in Maven 3. Does the result build?

**Comment by chanseokoh** [comment]
The resulting project has no build error. Local run works too.

**Comment by chanseokoh** [comment]
At some point, it looks like guava 20 was also added automatically by the menu. Not sure how to reproduce.

```xml
<groupId>com.googlecode.objectify</groupId>
<artifactId>objectify</artifactId>
<version>5.1.14</version>
</dependency>
<dependency>
<groupId>com.google.guava</groupId>
<artifactId>guava</artifactId>
<version>20.0</version>
</dependency>
<dependency>
<groupId>com.google.appengine</groupId>
<artifactId>appengine-endpoints</artifactId>
<version>LATEST</version>
</dependency>
<dependency>
<groupId>com.google.appengine</groupId>
<artifactId>appengine-api-1.0-sdk</artifactId>
<version>LATEST</version>
</dependency>
</dependencies>
```

At another point, I also saw the following message on the console:

```
!ENTRY org.eclipse.jdt.core 4 1006 2017-03-06 13:05:11.905
!MESSAGE /usr/local/google/home/chanseok/.m2/repository/com/google/guava/guava/19.0/guava-19.0.jar is not on its project's build path
```

**Comment by chanseokoh** [comment]
Ah, by looking at `pluginx.ml` of the `.libraries` bundle, we do fix the version `5.1.14` for Objectify, but for App Engine API and Endpoints, we don't specify any version. In that sense, the `pom.xml` seems correct more or less.

**Comment by chanseokoh** [comment]
Another thing related to Guava: initially, sometimes we add guava-18 and sometimes guava-19.

- guava-18: select all libraries when creating a project.
![selection_033](https://cloud.githubusercontent.com/assets/10523105/23624291/46d434fc-0273-11e7-88c3-fbe1fe41e6ec.png)

- guava-19: select nothing when creating a project.
![selection_035](https://cloud.githubusercontent.com/assets/10523105/23624371/79530494-0273-11e7-8ab8-dff118c42267.png)

**Comment by akerekes** [comment]
Guava is a dependency of Objectify. The `LATEST` is used to have M2E resolve the latest known version instead of a specific one. It was used for the non-Maven projects, I didn't investigate it's effect on Maven projects when introduced it.

**Comment by chanseokoh** [comment]
It's also interesting that we add `5.1.13` for Objectify when guava-18 is added. It should be `5.1.14`.

**Comment by akerekes** [comment]
@chanseokoh not specifying a version in plugin.xml defaults to `LATEST` (or users can explicitly specify `LATEST`)

**Comment by akerekes** [comment]
older Objectify may come from older version of the plugin

**Comment by chanseokoh** [comment]
> older Objectify may come from older version of the plugin

I'm testing this on `HEAD`. I suspect this is an archetype issue.

**Comment by akerekes** [comment]
So that's project creation, not `Build Path > Add Libraries...`

**Comment by chanseokoh** [comment]
> So that's project creation, not Build Path > Add Libraries...

Right, I'll create a new issue.

**Comment by chanseokoh** [comment]
> The LATEST is used to have M2E resolve the latest known version instead of a specific one. It was used for the non-Maven projects, I didn't investigate it's effect on Maven projects when introduced it.

@elharo was saying `LATEST` shouldn't work in Maven 3, and it seems like it could be the case: http://stackoverflow.com/a/1172371/1701388

**Comment by akerekes** [comment]
M2E uses LATEST, and we use M2E to resolve the libraries for a non-maven project. For Maven projects, we shouldn't add it into the pom.xml, I agree.
