### ISSUE TITLE
App Engine API is always added when creating HelloWorld Maven project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1523]
Even if I don't select the App Engine API in the Maven project wizard, I see below in `pom.xml`:

```xml
    <dependency>
      <groupId>com.google.appengine</groupId>
      <artifactId>appengine-api-1.0-sdk</artifactId>
      <version>${appengine.version}</version>
    </dependency>
```

**Comment by elharo** [comment]
That seems likely to be an issue with the archetype, but we can dig into it and find out.

**Comment by elharo** [comment]
Yes, it's an archetype issue. See lines 48-54 here:

https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/appengine-standard-archetype/src/main/resources/archetype-resources/pom.xml

It will need to be fixed there.

**Comment by elharo** [comment]
https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/issues/60
