### ISSUE TITLE
Objectify version in .libraries/plugin.xml not respected when creating a Maven project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1526]
We specify `5.1.14`, but currently `5.1.13` is being added:

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1522#issuecomment-284492335

I suspect this could be an archetype issue. (Needs verification.) I guess we will continue to have this type of problem as long as we depend on archetypes.

**Comment by elharo** [comment]
The archetypes specify 

    <objectify.version>5.1.13</objectify.version>
    <guava.version>18.0</guava.version>

However we should be able to override that when passing parameters to Maven. Maybe we aren't overriding that one and should?

**Comment by elharo** [comment]
And we should probably move Objectify to 5.1.15 from 5.1.14 while we're at it.

**Comment by elharo** [comment]
On further investigation I believe this is a Maven archetype issue. objectify.version is not parameterized as an environment variable.
