### ISSUE TITLE
An unexpected error occured while launching the test runtime (return code 143)

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1527]
This is happening a lot lately on many unrelated PRs.

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.24.0:test (default-test) on project com.google.cloud.tools.eclipse.appengine.validation.test: An unexpected error occured while launching the test runtime (return code 143). See log for details. -> [Help 1]

Rerunning once or more usually fixes it. Anyone have an idea?

**Comment by briandealwis** [comment]
What do the logs show for that test?

**Comment by chanseokoh** [comment]
I found two Travis logs:

- Fails on `.localserver.test`, after spending 2.5 minutes: https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/208321991

- Fails on `.validation.test`, after spending 10 minutes: https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/207149045

Unfortunately, the above two don't provide detailed logs.

**Comment by chanseokoh** [comment]
Correction: the first log above wasn't because of this.

**Comment by chanseokoh** [comment]
I wonder if this has anything to do with https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1484/commits/2ff5762291d6218b5d84daaf2f7568e7ef4c02af. I added `org.eclipse.platform` to make its build work on Travis, which was the first time we introduced this plugin to the surefire.

**Comment by briandealwis** [comment]
Second log:
```
Running com.google.cloud.tools.eclipse.appengine.validation.WebXmlValidatorTest
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80001b (data - Res)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x800018 (PartRender)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x80026a (File Not A)
Window manager warning: meta_window_activate called by a pager with a 0 timestamp; the pager needs to be fixed.
[ERROR] Timeout 600 s exceeded. Process was killed.
```
That shows switching between three different shells:
- `data - Res`: the main workbench window: _data_ is workspace, _Res_ is the _Resource_ perspective
- `PartRender`: hmm don't know what this is
- `File Not A`: looks like an error dialog

**Comment by chanseokoh** [comment]
I saw the timeout many times due to the `File Not A` dialog in the `.validation.test` bundle. It always happened on Travis before I changed `org.eclipse.rcp` to `org.eclipse.platform` for surefire (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1527#issuecomment-284516684). What was interesting was that, the timeout never happened locally with `mvn verify`, even with `org.eclipse.rcp`. Maybe this is due to some timing issue, and locally everything was quick, and hence it was OK?

I wonder if the error dialog might be by `CoreException` from tests. What if we catch all exceptions in `WebXmlValidatorTest`, log them, and throw them again?

**Comment by chanseokoh** [comment]
Another, basically same log: https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/208487453

**Comment by chanseokoh** [comment]
This might be it:

![file not accessible _001](https://cloud.githubusercontent.com/assets/10523105/23646488/07d992e4-02df-11e7-86ed-409bb0a9632e.png)

This happens when you make a change to a file (its edit buffer becomes dirty) and then the file is deleted outside Eclipse.

**Comment by briandealwis** [comment]
Well done!  `SWTWorkbenchBot#closeAllEditors()` is our friend here.

**Comment by briandealwis** [comment]
Unfortunately because the test times out, we can't even hook the `SWTBotJunit4ClassRunner` to take a screenshot as the process is killed rather than the test failing.

**Comment by chanseokoh** [comment]
@abbiefarr told me `XsltSourceQuickFixTest.testApply()` is the only test that makes an edit buffer change to a file open in an editor (i.e., in-memory change) during tests, and it does seem like it's the only case. So my guess is that, when a project gets deleted by `TestProjectCreator.after()`, it will delete the actual file (which hasn't been saved yet), and it naturally brings up the error dialog if timing is right.

**Comment by elharo** [comment]
We need to fix this generally. This is still happening a lot:


[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.24.0:test (default-test) on project com.google.cloud.tools.eclipse.appengine.localserver.test: An unexpected error occured while launching the test runtime (return code 143). See log for details. -> [Help 1]
[ERROR] 


e.g. https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/210048175

**Comment by chanseokoh** [comment]
We need to knock this out case by case, since the 143 error happens whenever a test hangs for any reason.

@elharo The failure logs you linked just above seem to have been cleared (probably the builds have been restarted). Any other logs you can link?

**Comment by chanseokoh** [comment]
Haven't seen this for a good while. Closing.
