### ISSUE TITLE
Align deploy dialog labels

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1533]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1472#issuecomment-284040569

**Comment by elharo** [comment]
I don't see what you're referring to. Can you copy the specific comment into this issue? Thanks.

**Comment by akerekes** [comment]
Align text on the left with same spacing if possible.

**Comment by elharo** [comment]
Can you paste in a complete screenshot? I don't immediately see the problem here.

**Comment by akerekes** [comment]
![image](https://cloud.githubusercontent.com/assets/3378942/23663561/e9c5dc4e-0320-11e7-8f7a-d5c16f7bc353.png)

**Comment by elharo** [comment]
I'm really not sure this is accurate in Eclipse. Compare to other similar dialogs in Eclipse. In any case, it's very low priority so I'm closing it.
