### ISSUE TITLE
Order of new project menu

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1536]
Do we want standard before flex or vice versa? Make a deliberate choice here. Let's make sure it's not random or alphabetical or some such. 

![image](https://cloud.githubusercontent.com/assets/1005544/23655493/2c6c45d8-0303-11e7-9d29-2bbaf161ec87.png)

**Comment by briandealwis** [comment]
The ordering isn't random, but it does depend on the order in which the bundles are loaded.  The bundle load order is consistent between restarts, but may change when new features/bundles are installed, uninstalled, or updated.

We can pre-populate that menu with some placeholder elements (e.g., #aes, #aef).  We can't control the order of what's shown in the actual _New_ wizard though.

I agree that it is confusing to see the Flex first.  I mused privately with @nbashirbello that perhaps we should rename these entries, forgetting that the text actually comes from the _New_ wizard command, and is populated from the new wizard descriptions.

**Comment by elharo** [comment]
Short of changing the labels is there some way we can control the order and override the default ordering if it doesn't work for us? At least within our own contributions if not within all menu items?

**Comment by briandealwis** [comment]
Yes we can.
