### ISSUE TITLE
LATEST not supported in maven 3

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1540]
version="LATEST" is not supported in Maven 3. Can we require a version everywhere? Or allow the version element to be omitted?

**Comment by branflake2267** [comment]
One of the options, might be to use Maven filtering to update the version. Although I tried this it wasn't as flexible as I liked. But this doesn't work to have a ${some.version} when testing, unless a build is fired off for testing.
