### ISSUE TITLE
Maven query for latest version number

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1547]
We would like to be able to query Maven central for the latest version of an artifact, not simply the latest artifact.

**Comment by akerekes** [comment]
What we need is to query the latest version from Maven Central and avoid M2E using the local repo to provide this answer.
Then we can add back `LATEST` to `plugin.xml`

**Comment by elharo** [comment]
The dataflow plugin seems to have some code for this.

**Comment by briandealwis** [comment]
That would avoid fiddling with m2e preferences (#830).

**Comment by elharo** [comment]
FYI Maven itself can do this 
http://www.mojohaus.org/versions-maven-plugin/use-latest-versions-mojo.html

**Comment by elharo** [comment]
We need to decouple DataflowArtifactRetriever from Dataflow and move it to com.google.cloud.tools.eclipse.util.

Also note that this class may have some thread safety issues related to reuse of XPath objects.

**Comment by elharo** [comment]
`MavenUtils.resolveLatestReleasedArtifactVersion` may already exist.

**Comment by elharo** [comment]
This is done in ArtifactRetriever.
