### ISSUE TITLE
set source URIs in libraries/plugin.xml

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1550]

**Comment by akerekes** [comment]
@elharo  Some libraries don't have sources published, and many of them have it in Maven Central which will be tried if no explicit source URI is given. For which library files do you want the source URI to be set?

**Comment by chanseokoh** [comment]
Even if sources are only in Maven Central, we could explicitly set the URIs anyway, no? If we always set source URIs, maybe we could also remove the code that tries to search Maven Central?

**Comment by akerekes** [comment]
I think about trying MC for sources as a convenience that saves manual
updates to the plugin.xml.
