### ISSUE TITLE
Run As > App Engine menu item appears without App Engine facet

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1556]
This was on a Maven Dynamic WTP project (bookshelf).

Probably we shouldn't show that context menu item unless the App Engine Standard factet is present; but if we do show it, it should work. 

![image](https://cloud.githubusercontent.com/assets/1005544/23714749/5b1a18c4-03f8-11e7-9b8e-597c07826021.png)

**Comment by elharo** [comment]
![image](https://cloud.githubusercontent.com/assets/1005544/23714795/8517beba-03f8-11e7-91fb-67b06bb14368.png)

**Comment by chanseokoh** [comment]
Something may have happened to your Bookshelf project. I can't seem to reproduce it. I don't see the _App Engine_ menu under _Run As_, if a project doesn't have the App Engine Standard facet.

**Comment by chanseokoh** [comment]
Said that too early, I see the problem. (However, I'm sure the menu was there only for App Engine projects. Something happened to me too.)

**Comment by briandealwis** [comment]
Oh! The launch shortcut is conditioned on either the selection *or* the active editor being in a faceted project.  In your screenshot, the current editor is an `appengine-web.xml`.

**Comment by chanseokoh** [comment]
It looks like we don't need to check `activeEditorInput` at all. Without it, right-clicking on an open file is properly handled with below (adapting to `IResource`):

```xml
            <enablement>
               <with variable="selection">
                  <iterate>
                     <adapt type="org.eclipse.core.resources.IResource">
                        <test
                              property="org.eclipse.wst.common.project.facet.core.projectFacet"
                              value="com.google.cloud.tools.eclipse.appengine.facets.standard" />
                     </adapt>
                  </iterate>
               </with>
            </enablement>
```
