### ISSUE TITLE
Bookshelf sample app fails to start on local server

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1557]
not immediately clear why:

![image](https://cloud.githubusercontent.com/assets/1005544/23715258/0091aa0a-03fa-11e7-8e12-e740ffd5fecf.png)

**Comment by elharo** [comment]
INFO: submitting command: /Users/elharo/google-cloud-sdk/bin/dev_appserver.py /Users/elharo/workspaces/runtime-gcloud-eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/bookshelf-standard-2 --host=localhost --port=8080 --admin_host=localhost --admin_port=8000 --max_module_instances=1 --automatic_restart=false

**Comment by chanseokoh** [comment]
I was also perplexed by what's going on. After some time, I happened to open the _Console_ view, and I see

```
google.appengine.api.yaml_errors.EventError: Unable to assign value '[YOUR-PROJECT-ID]' to attribute 'application':
Value '[YOUR-PROJECT-ID]' for application does not match expression '^(?:(?:[a-z\d\-]{1,100}\~)?(?:(?!\-)[a-z\d\-\.]{1,100}:)?(?!-)[a-z\d\-]{0,99}[a-z\d])$'
  in "<string>", line 1, column 14:
    application: '[YOUR-PROJECT-ID]'
                 ^
```

Removing the `<application>` element fixes that problem. Running locally works, but the app gives 503. It might be that the app needs further configuration. Not sure.

```
HTTP ERROR 503

Problem accessing /. Reason:

    java.lang.IllegalStateException: Invalid storage type. Check if bookshelf.storageType property is set.
Caused by:

javax.servlet.UnavailableException: java.lang.IllegalStateException: Invalid storage type. Check if bookshelf.storageType property is set.
	at org.mortbay.jetty.servlet.ServletHolder.makeUnavailable(ServletHolder.java:415)
	at org.mortbay.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:458)
	at org.mortbay.jetty.servlet.ServletHolder.doStart(ServletHolder.java:263)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.servlet.ServletHandler.initialize(ServletHandler.java:685)
	at org.mortbay.jetty.servlet.Context.startContext(Context.java:140)
	at org.mortbay.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250)
	at org.mortbay.jetty.handler.ContextHandler.doStart(ContextHandler.java:517)
	at org.mortbay.jetty.webapp.WebAppContext.doStart(WebAppContext.java:467)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at org.mortbay.jetty.handler.HandlerWrapper.doStart(HandlerWrapper.java:130)
	at org.mortbay.jetty.Server.doStart(Server.java:224)
	at org.mortbay.component.AbstractLifeCycle.start(AbstractLifeCycle.java:50)
	at com.google.appengine.tools.development.JettyContainerService.startContainer(JettyContainerService.java:268)
	at com.google.appengine.tools.development.AbstractContainerService.startup(AbstractContainerService.java:284)
	at com.google.appengine.tools.development.AutomaticInstanceHolder.startUp(AutomaticInstanceHolder.java:26)
	at com.google.appengine.tools.development.AbstractModule.startup(AbstractModule.java:87)
	at com.google.appengine.tools.development.Modules.startup(Modules.java:105)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.doStart(DevAppServer2Impl.java:250)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.access$000(DevAppServer2Impl.java:52)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:216)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl$1.run(DevAppServer2Impl.java:214)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.google.appengine.tools.development.devappserver2.DevAppServer2Impl.start(DevAppServer2Impl.java:214)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:131)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance$StartAction.apply(StandaloneInstance.java:83)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:47)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.run(StandaloneInstance.java:67)
	at com.google.appengine.tools.development.devappserver2.StandaloneInstance.main(StandaloneInstance.java:45)
Powered by Jetty://
```

**Comment by chanseokoh** [comment]
However, looking at the [bookshelf doc](https://cloud.google.com/java/getting-started/using-forms), it sounds like it should just work:

> #### Running the app on your local machine
>
> To run the app locally:
>
> 1. In the getting-started-java/bookshelf/2-structured-data directory, enter this command to start a local web server:
> `mvn -Plocal clean jetty:run-exploded -DprojectID=[YOUR-PROJECT-ID]`
> 1. In your web browser, navigate to http://localhost:8080

**Comment by akerekes** [comment]
From the error message we seem to miss this property:

https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/bookshelf-standard/2-structured-data/pom.xml#L34

**Comment by chanseokoh** [comment]
So the issue is like, dev_appserver doesn't import properties defined in `pom.xml`? dev_appserver is independent of build systems and configurations, so basically users may need to provide properties to dev_appserver themselves when necessary? Or, could it be that the app is just broken?

**Comment by briandealwis** [comment]
It looks like some maven plugin uses the pom properties to fill in [`web.xml`](https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/bookshelf-standard/2-structured-data/src/main/webapp/WEB-INF/web.xml#L88) as part of the build.

**Comment by akerekes** [comment]
What are the steps to import this into Eclipse?

**Comment by akerekes** [comment]
Please refer to http://stackoverflow.com/a/42954117/1927782 for steps on how to import the project.

**Comment by briandealwis** [comment]
Importing the `bookshelf-2` has a number of problems.
  1. The example projects (in fact, the `com.google.cloud.samples:shared-configuration` parent) have switched to using the _errorprone_ compiler which leads to configuration errors when importing the projects.  This is arguably something we should fix.
    - We could add m2e lifecycle-metadata to `com.google.cloud.samples:shared-configuration` as I did with https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/354 but this turns into a game of whackamole.
    - We can workaround this by adding a lifecycle-mapping to ignore _errorprone_, similar to what we do for the (`versions-maven-plugin`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/lifecycle-mapping-metadata.xml) (used in the `appengine-standard-archetype`/HelloAppEngine archetype).  But this only helps people who have CT4E installed.
    - I think we may should also turn these into proper m2e configurators that are picked up by the m2e discovery when importing the projects.
  2. We don't auto-discover appengine projects and add our facet, so the user has to manually convert the project to an AES project using our converter.  But we rightly error out as the _Dynamic Web Facet_ is version 3.1.  There are two errors here, but they're in bookshelf-2 (actually all the bookshelf projects):
      - The [web.xml doesn't provide a schema](https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/bookshelf-standard/2-structured-data/src/main/webapp/WEB-INF/web.xml#L15) and so WTP's `web.xml` quick-peek parser (`JavaEEQuickPeek`), used by _m2e-wtp_ during the import to associate various facets, and so [_m2e-wtp_ sets it to Servlet 3.1](http://git.eclipse.org/c/m2e-wtp/org.eclipse.m2e.wtp.git/tree/org.eclipse.m2e.wtp/src/org/eclipse/m2e/wtp/WarPluginConfiguration.java?h=master#n260).
      - The `web.xml` actually says it's _3.0_, which isn't right for AES.
  3. Finally m2e is not applying resource filtering to the `web.xml` and so the `${bookshelf.storageType}` is never propagated.  This is actually a bug in _m2e-wtp_ Here there are two issues: first, _m2e-wtp_ only checks if the _maven-war-plugin_ configuration specifies the `filteringDeploymentDescriptors` property, but it doesn't look for the `maven.war.filteringDeploymentDescriptors` user property which is used in the bookshelf poms.  This user property was removed from the `maven-war-plugin` in 3.0.0 [MWAR-376](https://issues.apache.org/jira/browse/MWAR-376).  But we're pulling in the [default version 2.2](https://github.com/apache/maven/blob/bce33aa2662a51d18cb00347cf2fb174dc195fb1/maven-core/src/main/resources/META-INF/plexus/default-bindings.xml#L221).
    - we can provide a fix for m2e-wtp (filed as [bug 514577](https://bugs.eclipse.org/bugs/show_bug.cgi?id=514577) with a fix)
    - we can explicitly specify the `maven-war-plugin` in the bookshelf parent pom
  4. Finally, I hit an error as the Google Cloud SDK wasn't found (#1709)

Having worked around the above, it works!

**Comment by xmuweili** [comment]
Still have this issue on MacOS with Maven 3.5.0

**Comment by elharo** [comment]
OK, I'll try to take a look at this.

**Comment by elharo** [comment]
see https://cloud.google.com/java/getting-started/tutorial-app

**Comment by xmuweili** [comment]
It terms out commenting out the:
        <configuration>
          <webApp>
            <overrideDescriptor>${project.build.directory}/${project.build.finalName}/WEB-INF/web.xml</overrideDescriptor>
          </webApp>
        </configuration>

in pom.xml fix the issue.

**Comment by jgmatu** [comment]
Good Morning,

I have the same problem @chanseokoh Exception :
 
avax.servlet.UnavailableException: java.lang.IllegalStateException: Invalid storage type. Check if bookshelf.storageType property is set.

My POM bockshelt

...
	<parent> 
		<artifactId>getting-started-java</artifactId>
		<groupId>com.example</groupId>
		<version>1.0.0</version>
		<relativePath>../</relativePath>
	</parent>

	<properties>
		<jetty.maven.plugin>9.4.3.v20170317</jetty.maven.plugin>
		<bookshelf.storageType>datastore</bookshelf.storageType> 
		<sql.dbName>bookshelf</sql.dbName> 	
		<bookshelf.bucket>comfostat-43be5-images</bookshelf.bucket>                    
		<callback.host>SECRET</callback.host>     
		<bookshelf.clientID>SECRET</bookshelf.clientID>                
		<bookshelf.clientSecret>SECRET</bookshelf.clientSecret>        
	</properties>

	<profiles>
...

I am trying 2-data-struct 
...
</parent>
<properties>
		
		<projectID>comfostat-43be5</projectID> 
		<sql.dbName>bookshelf</sql.dbName>                        
		
		
		<sql.instanceName>${projectID}:us-central1:${sql.dbName}</sql.instanceName>
		<sql.userName>root</sql.userName>                         
		<sql.password>myRootPassword1234</sql.password> 
		

		<appengine.maven.plugin>1.3.1</appengine.maven.plugin>
		<jetty.maven.plugin>9.4.3.v20170317</jetty.maven.plugin>

		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>1.8</maven.compiler.source> 
		<maven.compiler.target>1.8</maven.compiler.target> 
		<maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>
		<maven.compiler.showWarnings>true</maven.compiler.showWarnings>
		<maven.compiler.failOnWarning>true</maven.compiler.failOnWarning>
		<maven.war.filteringDeploymentDescriptors>true</maven.war.filteringDeploymentDescriptors>
	</properties>

	<dependencies>
...

**Comment by elharo** [comment]
The initial sample works for me now (which it didn't used to). How deep in the tutorial were you?

**Comment by elharo** [comment]
deployment works though I do get this warning:

```
Nov 07, 2017 10:18:14 AM com.google.cloud.tools.eclipse.appengine.standard.java8.AppEngineWebBuilder build
WARNING: P/bookshelf-standard-2: no build required: missing appengine-web.xml
```

Surprising since this is a Java 7 project.

**Comment by elharo** [comment]
I'm going to close this for now since I can't reproduce. If you can with the latest CT4E, please reopen with more details.

**Comment by jgmatu** [comment]
Sorry I wrong of Google Cloud plataform proyect.

Sorry for the annoy!

**Comment by nlonginow** [comment]
Just downloaded and setup all cloud on MacOS (latest) and see this error as well.  What is the fix?

Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T03:58:13-04:00)
Maven home: /.../apache-maven-3.5.2
Java version: 1.8.0_131, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.1", arch: "x86_64", family: "mac"

**Comment by chanseokoh** [comment]
@nlonginow that is not an error message but what you get when you do `mvn -version`.

**Comment by briandealwis** [comment]
@chanseokoh I think @nlonginow is saying he's encountering this issue (_ Bookshelf sample app fails to start on local server_) and he's reporting his configuration :-)

@nlonginow what version of Eclipse are you running?  There is a [bug in m2e-wtp](https://bugs.eclipse.org/bugs/show_bug.cgi?id=514577) that was fixed for Oxygen.

**Comment by Vicmi13** [comment]
Hi, I figured out how to run correctly **[Bookshelf on the app engine standard Environment](https://cloud.google.com/java/getting-started-appengine-standard/tutorial-app?authuser=1)**

I´m actually running with this

>Maven home: /Applications/apache-maven-3.6.1
>Java version: 1.8.0_211, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home/jre`

First of all.

I updated some repo versions, because when I was runnign locally with
`mvn -Plocal clean appengine:devserver` have some errors with JSTL and doesn´t compile

Original POM.xml
[bookshelf-standard/2-structured-data/pom.xml](https://github.com/GoogleCloudPlatform/getting-started-java/blob/master/bookshelf-standard/2-structured-data/pom.xml)

 


      <dependency>
          <groupId>javax.servlet</groupId>  
          <artifactId>servlet-api</artifactId>
          <version>2.5</version>
          <scope>provided</scope>
      </dependency>
     
     <dependency>
          <groupId>javax.servlet</groupId>
          <artifactId>jsp-api</artifactId>
          <version>2.0</version>
      </dependency>

      <dependency>
         <groupId>jstl</groupId>
         <artifactId>jstl</artifactId>
         <version>1.2</version>
       </dependency>

>my POm.xml **Updated**

     <dependency>
        <groupId>javax.servlet</groupId>
        <artifactId>javax.servlet-api</artifactId>
        <version>4.0.1</version>
        <scope>provided</scope>
    </dependency>


      <dependency>
          <groupId>javax.servlet.jsp</groupId>
          <artifactId>jsp-api</artifactId>
          <version>2.1</version>
          <scope>provided</scope>
      </dependency>

      
      <dependency>
          <groupId>javax.servlet</groupId>
          <artifactId>jstl</artifactId>
          <version>1.2</version>
       </dependency>

I change  `<groupId><artifactID><version>` of these 3 dependencies becasuse the older ones were deprecated (Validated with Maven Repository).

And that`s it, works good

<img width="1157" alt="Captura de pantalla 2019-05-22 a la(s) 14 31 27" src="https://user-images.githubusercontent.com/12403134/58204364-c351af00-7ca1-11e9-8d20-a9e09bc50dd0.png">

For the deploying the app in the App Engine Standard Environment
I updated `appengine-web.xml`, it was running with java 7 and for App Engine was deprecated
[Migrating from Java 7 to Java 8 Runtime](https://cloud.google.com/appengine/docs/standard/java/migrating-to-java8)
Then run the command
>mvn appengine:update -Dappengine.appId=[YOUR-PROJECT-ID] -Dappengine.version=[YOUR-VERSION]

Where YOUR-PROJECT-ID is the name that appears in your console and [YOUR-VERSION] is the number of the version you want to release (Remove [] )

And obtained a BUILD SUCCESS and perfectly running in `https://[YOUR-PROJECT-ID].appspot.com`
<img width="816" alt="Captura de pantalla 2019-05-22 a la(s) 15 02 48" src="https://user-images.githubusercontent.com/12403134/58204798-aec1e680-7ca2-11e9-9a4e-f0b7875f148b.png">
**Check the URL **
