### ISSUE TITLE
Opening and closing Advanced section makes project list table grow wider 

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1561]
Opening and closing the `Advanced` section on the deploy preferences page (right click on project > Properties) makes the table wider in each step.
Maybe https://bugs.eclipse.org/bugs/show_bug.cgi?id=215997

**Comment by elharo** [comment]
No longer seems to be an issue in Oxygen.3 (4.7.3)
