### ISSUE TITLE
Warn if appengine-web.xml contains a version element

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1562]
Very similar to the warning and quickfix for the application element. This is now specified at deploy time.

**Comment by ludoch** [comment]
I am not aware of this change... PRD link please..

**Comment by elharo** [comment]
https://cloud.google.com/sdk/gcloud/reference/app/deploy

**Comment by ludoch** [comment]
My bad, was reading the thread as the 'service' element not the 'version'
