### ISSUE TITLE
When facet config is invalid for the deploy preferences, no validation error message is shown

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1564]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1546#discussion_r105149487

1. open properties of a standard project
1. open the deploy preferences
1. remove standard and add flex facet
1. go back to the deploy preferences page
1. type some illegal version name (e.g.: #)

The Apply and OK buttons become disabled, no error message is shown regarding the version, only that this page is valid for standard projects only. When I try to switch to another page, I get the message that there are invalid values on the page I cannot switch.

**Comment by chanseokoh** [comment]
> 3. remove standard and add flex facet

To make it simpler, removing the standard facet is enough. (No need for the flex facet.)

**Comment by diegomarquezp** [comment]
Closing as GAE does not support the Java 8 runtime and we don't plan to support later versions. cc: @blakeli0
