### ISSUE TITLE
'Restore Defaults' in deploy preferences dialog doesn't restore UI components: account selector and project selector

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1566]
Steps to reproduce:
1. Create a new project.
2. Open the deploy preferences, select an account, select a project, and click _OK_.
3. Re-open the deploy preferences. Verify that the previously selected account and project are loaded.
4. Click _Restore Defaults_. Verify that the account and project remain untouched. Click _OK_.
5. Re-open the deploy preferences. Observe that the account selector and the project selector have been cleared.

Expected: either
1) at step 4, _Restore Defaults_ will clear the account selector and the project selector;
or
2) at step 5, the page should load previously selected values.

I feel 1) is the correct behavior. Technically, I think at step 4, the model is cleared, but the UI components are not synchronized to reflect that.

**Comment by akerekes** [comment]
I agree, it should be 1)

**Comment by elharo** [comment]
What do we do if there's exactly one logged in account? Do we autoselect it?

The more time we spend fixing this dialog, the less convinced I am it's carrying its weight.

**Comment by briandealwis** [comment]
We could call `noDefaultButton()` from the constructor to suppress the _Restore Defaults_ button.
