### ISSUE TITLE
Change text for project selector

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1570]
Since you select both a name and an ID, not just the ID anymore:

![image](https://cloud.githubusercontent.com/assets/1005544/23797733/39db1474-056f-11e7-8efb-ad60e1dbb0de.png)

Or maybe even "No Project Selected"

**Comment by akerekes** [comment]
This is being fixed by #1546. According to UX guidelines it should be more like "Select a project" (i.e. an action instead of an error)

**Comment by elharo** [comment]
Yes, and it probably shouldn't be an error; just an info though I'm waiting for the Eclipse UX guidelines to come back up to confirm that.

Also we should get rid of the label "Select a Google Cloud platform Project" after "Project:" since it's redundant with the new info message and reasonably obvious from the list box.

**Comment by akerekes** [comment]
Also the text for creating a project should say `You can create a new Google Cloud Platform project in the <a>Cloud Console</a>. Then refresh this list.`
