### ISSUE TITLE
Consolidate various "createFolders" methods

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1573]
- v1
`StandardFacetInstallationTest.createFolders()`
`AbstractXmlValidatorTest.createFolders()`
`AppEngineWebXmlValidatorTest.createFolders()`
`PomXmlValidatorTest.createFolders()`
`WebXmlValidatorTest.createFolders()`

- v2
`ResourceUtils.createFolders()`: this one is not flexible in that it can create folders that are relative to a project root only.

- v3
`CodeTemplates.createChildFolder()`: this one is not powerful in that it cannot create multi-depth folders.

I like v1, which is flexible and very concise.

**Comment by chanseokoh** [comment]
`CodeTemplates.createFoldersForPackage()` should also be refactored to utilize `createFolders()`.

**Comment by chanseokoh** [comment]
Code inside `CodeTemplate.materialize()` can be simplified too by using `createFolders()`:

```java
    IFolder src = project.getFolder("src");  //$NON-NLS-1$
    if (!src.exists()) {
      src.create(force, local, subMonitor.newChild(5));
    }
    IFolder main = createChildFolder("main", src, subMonitor.newChild(5)); //$NON-NLS-1$
    IFolder java = createChildFolder("java", main, subMonitor.newChild(5)); //$NON-NLS-1$
    IFolder test = createChildFolder("test", src, subMonitor.newChild(5)); //$NON-NLS-1$
    IFolder testJava = createChildFolder("java", test, subMonitor.newChild(5)); //$NON-NLS-1$
```

**Comment by elharo** [comment]
5 of those are for tests.

Digging into the other three, they're all for creating project files in the user workspace. (Not too surprising in hindsight.) That happens in the new project wizards and the standard facet install delegate.

**Comment by chanseokoh** [comment]
Also `WebXmlScannerTest` once #1571 is merged.

**Comment by nbashirbello** [comment]
Also FacetUtilTest#createPath

**Comment by elharo** [comment]
I think ResourceUtils is the obvious class to contain this functionality, even if the existing method there is the least general.

**Comment by elharo** [comment]
IMHO, our test coverage is not yet sufficient to make this change safely. In particular, comment out line 140 in `StandardFacetInstallDelegate` and all tests still pass:

```
    // ResourceUtils.createFolders(webInfDir, progress.newChild(2));
```

Before we can refactor this, we need a test that fails when this line is not present. There may be other missing test coverage as well.

**Comment by elharo** [comment]
`StandardFacetInstallDelegate` now fails when that line is commented out.

**Comment by elharo** [comment]
At some point `CodeTemplates.createFoldersForPackage()` went away and was replaced by `ResourceUtils`. All other usages are in tests.

**Comment by elharo** [comment]
These all seem to have been fixed one by one.
