### ISSUE TITLE
Update to Tycho 1.0

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1598]
Toolchains aren't doing what we need: although our bundles declare `BREE: JavaSE-1.7`, some of the classes we use, like `org.eclipse.core.databinding.observable.value.ComputedValue`, reference and use Java 8 classes in Neon and Oxygen.  So compilation will fail:
```
$ mvn -Declipse.target=neon -Dmaven.repo.local=/tmp/m2 package
[…]
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project com.google.cloud.tools.eclipse.appengine.deploy.ui: Compilation failure: Compilation failure:
[ERROR] /Users/bsd/Manumitting/Projects/GooglePluginEclipse/ide-target-platform/plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java:[1]
[ERROR] /Users/bsd/Manumitting/Projects/GooglePluginEclipse/ide-target-platform/plugins/com.google.cloud.tools.eclipse.appengine.deploy.ui/src/com/google/cloud/tools/eclipse/appengine/deploy/ui/StandardDeployPreferencesPanel.java:[1]
[ERROR] /*
[ERROR] ^
[ERROR] The type java.util.function.Supplier cannot be resolved. It is indirectly referenced from required .class files
[ERROR] -> [Help 1]
```
Since we ensure Travis builds with 1.7 against Mars, we should just abandon the use of toolchains.

**Comment by elharo** [comment]
What's the implication for local builds? Does this mean we'll need to use JDK 8?

**Comment by briandealwis** [comment]
We already need to use Java 8 to build for Neon or Oxygen.  I've been looking at how EclEmma do their builds and rather than use the BREE to identify a JDK toolchain, they explicitly select a JDK toolchain based on their target (e.g., a Java 7 compiler for their Eclipse 3.8 (!) builds).  Which is kinda what we're doing on Travis.

**Comment by briandealwis** [comment]
But since our default was for Mars, then the default JDK toolchain will be Java 7.

**Comment by briandealwis** [comment]
Tycho 1.0 has been released, but requires running on Java 8.  We should follow [the approach used by EclEmma](https://github.com/eclipse/eclemma/commit/37c744f2773f8914048149f776398a287e068ecb):
- [configure a `toolchains.xml` for Travis](https://github.com/eclipse/eclemma/blob/master/.travis-toolchains.xml)
- allow specifying [a toolchain in the pom.xml](https://github.com/eclipse/eclemma/blob/master/org.eclipse.eclemma.build/pom.xml#L443)
- update the `.travis.yml` to specify the desired platform

**Comment by briandealwis** [comment]
I came across this error in the IDE when using an Oxygen target platform.  Workaround below.

## Cause

Our `AppEngineDeployPreferencesPanel` makes use of `org.eclipse.core.databinding.observable`'s `ComputedValue` class.  On Oxygen, `ComputedValue` makes use of `java.util.function.Supplier`.  As our bundles specify `Bundle-RequiredExecutionEnvironment: JavaSE-1.7`, PDE creates a classpath using the JRE specified as the match in _Preferences > Java > Installed JREs > Execution Environments`.

## Workaround

In my case, I have JREs configured for JavaSE 6, 7, and 8.  My _Installed JREs_ used the proper match.  The workaround is to change the execution environment for `JavaSE-1.7` to use the JRE for JavaSE 8.

<img width="758" alt="screen shot 2017-07-19 at 10 56 39 am" src="https://user-images.githubusercontent.com/202851/28373729-079e9206-6c71-11e7-93ae-8917c819bba1.PNG">
