### ISSUE TITLE
Java package is forced when clearing package input field in Maven new project wizard

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1602]
Even if you clear the Java package input field (i.e., leave the field empty), the project will have the Maven group ID as a package name. This is different from the non-Maven wizard, where it won't create a package.

**Comment by elharo** [comment]
This may be an archetypes issue.

**Comment by elharo** [comment]
Yep, this is how the maven archetype is meant to work. We can do something different when we move off archetypes, but not till then.
