### ISSUE TITLE
LibraryClasspathContainerInitializerTest fails on Mac

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1605]
Failed tests: 
  LibraryClasspathContainerInitializerTest.testInitialize_ifSourcePathIsNullContainerIsNotResolvedAgain:189 
Expected: a value greater than <2>
     but: <2> was equal to <2>
  LibraryClasspathContainerInitializerTest.testInitialize_ifSourcePathIsValidContainerIsNotResolvedAgain:218 
Expected: a value greater than <2>
     but: <2> was equal to <2>

**Comment by briandealwis** [comment]
This test code was replaced with #1591.

**Comment by elharo** [comment]
I'm still seeing this at head. :-(

**Comment by chanseokoh** [comment]
> This test code was replaced with #1591.

Seems like it should have been greater-than-equal.

**Comment by elharo** [comment]
Here are the entries in the IDE:

/test0.15238835409614115/src
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/resources.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/rt.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/jsse.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/jce.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/charsets.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/jfr.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/ext/dnsns.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/ext/localedata.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/ext/sunec.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/ext/sunjce_provider.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/ext/sunpkcs11.jar
/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/ext/zipfs.jar
/System/Library/Java/Extensions/MRJToolkit.jar
/var/folders/3d/cks0l_0n6zs56ztf89nt6nsr0028bc/T/junit7194422467099128845/junit1792653925183757197.tmp

**Comment by elharo** [comment]
resolvedClasspath.length is 15 in the IDE and 2 at the command line. That's a big discrepancy. Absent a reason otherwise, I'd expect them to be equal.

**Comment by elharo** [comment]
Running in the CLI these are the libraries:

/test0.3518241435224271/src
/var/folders/3d/cks0l_0n6zs56ztf89nt6nsr0028bc/T/junit6259266087719033054/junit8885742672780016877.tmp

The difference appears to be that the IE includes system jars and the CLI doesn't.
