### ISSUE TITLE
Support Eclipse Marketplace editor and project-nature discovery

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1607]
The Eclipse Marketplace client offers support to suggest relevant plugins when opening a file.  A new feature to come in Oxygen/4.7 M7 (May 2017) is to support project-nature-based discovery too.

> The Marketplace Client has just integrated support to detect missing natures used by new projects and to propose available marketplace solutions if some are available. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=513306
> 
> Similarly to how discovery of file types support is implemented, it runs a
specific search on marketplace to find appropriate solutions to satisfy a
missing nature. More precisely, it expects the solutions defining a nature
to add a `nature_<fully.qualified.nature.id>` tag.
The only real-life example declaring such tag on their marketplace extension
so far is JDT.

We could publish associations for `appengine-web.xml` and `app.yaml`.  And we could define a general GCP nature and take advantage of that too.

These functions may be available in Neon/4.6 if users update MPC?

**Comment by briandealwis** [comment]
Can be tested with MPC with Oxygen M6 by running with `-Dorg.eclipse.epp.mpc.naturelookup=true`.

**Comment by jtsaur** [comment]
In case there is no connectivity to market place, how can I disable Oxygen 4.7.3 to search market place for project nature support?

**Comment by briandealwis** [comment]
@jtsaur you have to change two preferences.

First, visit _Preferences > General > Project Natures_ and turn off _Automatically detect missing natures and propose IDE extensions from Marketplace_:

<img width="686" alt="screen shot 2018-05-31 at 5 00 17 pm" src="https://user-images.githubusercontent.com/202851/40808107-1d8ae4d0-64f4-11e8-8d48-4a495c07833a.PNG">

Second, visit _Preferences > General > Editors > File Associations_ and change the _Open unassociated files with:_ combo to your desired setting.

<img width="680" alt="screen shot 2018-05-31 at 4 59 14 pm" src="https://user-images.githubusercontent.com/202851/40808054-fbf9ca7a-64f3-11e8-8b1b-862de98f8656.PNG">

**Comment by briandealwis** [comment]
Closing this issue as we seem happy with using the XML and YAML editors.
