### ISSUE TITLE
Details in status

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#162]
The Status error dialog offers to show the user more details but these are not helpful:

![image](https://cloud.githubusercontent.com/assets/1005544/15218774/58b4c972-182f-11e6-916e-e3750d17b1b2.png)

Either figure out how to put something actually useful here, or get rid of the details pane.

**Comment by briandealwis** [comment]
`InvocationTargetExceptions` should always wrap another exception, so it's safe to pass in the `ex.getCause()`.  And our call to `StatusManager` should also include StatusManager.LOG.

**Comment by chanseokoh** [comment]
Looking at the screen shot where it says "Failed to create project", and considering places where `InvocationTargetExcpetion` is being thrown, this error status message comes from [here](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java#L102).

I am guessing this was fixed at some point. [We are currently doing `ex.getCause()` in `StandardProjectWizard`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.newproject/src/com/google/cloud/tools/eclipse/appengine/newproject/StandardProjectWizard.java#L93).

If verified, we may close this. However, I see there are a few things we can clean up, so I'll create a relevant PR.
