### ISSUE TITLE
Flex deployment properties need min width

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1621]
If the Properties dialog is resized (more narrow), the text input fields can be shrunk to a 1px wide field, which makes them unusable. These fields should have a minimum width set, so when the page shrinks horizontally, they maintain that minimum width and the page displays a scrollbar since the contents become wider than the dialog.

**Comment by chanseokoh** [comment]
Obsolete with the new flex deploy properties dialog.
