### ISSUE TITLE
Attach the sources of the downloaded jars (if available) when creating a new flex project

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#1632]

**Comment by chanseokoh** [comment]
This is also the case in standard projects, unless you are talking about other new libraries in flex besides App Engine API, Objectify, and Endpoints. AFAIK, we deliberately don't attach sources for these: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1460#issuecomment-282051675

**Comment by chanseokoh** [comment]
Ah, I guess the jars include servlet, jsp, and jstl.

**Comment by diego92sigma6** [comment]
Closing as not planned
