### ISSUE TITLE
Design Syntax Highlighting

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1636]
@saturnism suggested we look into syntax highlighting for protobufs and other files in CT4E. I haven't done this before but I'm sure it's doable and probably not too hard. We might be able to borrow some protobuf syntax highlighting from Guide, and perhaps make an intern project out of the other files. 

We should start by making a list of formats and files we'd like to syntax highlight that Eclipse does not already handle.

**Comment by elharo** [comment]
Maybe even just declare a dependency on protobuf-dt if protobufs are what we need:

https://marketplace.eclipse.org/content/protobuf-dt

**Comment by diego92sigma6** [comment]
Closing as obsolete.
