### ISSUE TITLE
Test StandardFacetUninstallDelegate

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1637]
Our unit tests don't hit this class at all and it's reasonably complex.

https://codecov.io/gh/GoogleCloudPlatform/google-cloud-eclipse/src/bff1ec470ad2a681a8a3a4b8bc3ba4938c9d459d/plugins/com.google.cloud.tools.eclipse.appengine.facets/src/com/google/cloud/tools/eclipse/appengine/facets/StandardFacetUninstallDelegate.java

**Comment by diegomarquezp** [comment]
Closing as not planned since we don't support GAE + Java 8.
