### ISSUE TITLE
Make integration tests run last

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1641]
Since they take a long time to run and are our flakiest tests, put them last in test order so failures in other tests are found sooner.

**Comment by chanseokoh** [comment]
Seems like we can't manually control the build order: http://stackoverflow.com/a/11131721/1701388

However, I can think of a couple of workarounds:
1. Bind the integration test to, e.g., the `post-integration-test` or `verify` lifecycle phase. ([`tycho-surefire` runs tests in the `integration-test` phase.](https://eclipse.org/tycho/sitedocs/tycho-surefire/tycho-surefire-plugin/test-mojo.html))
1. Define a `<profile>` that runs the integration test. For example,
```xml
    <profile>
      <id>run-integration-test</id>
      <activation>
        <property>
          <name>!skip.integration.test</name>
        </property>
      </activation>
      <modules>
        <module>plugins/com.google.cloud.tools.eclipse.integration.appengine</module>
      </modules>
    </profile>
```

**Comment by elharo** [comment]
Actually that SO entry suggests my PR will work:

```
The following relationships are honoured when sorting projects:

a project dependency on another module in the build
a plugin declaration where the plugin is another modules in the build
a plugin dependency on another module in the build
a build extension declaration on another module in the build
the order declared in the element (if no other rule applies)
```

"the order declared in the element (if no other rule applies)" is what applies here. 

What can't be done is changing the build order without changing the pom.

**Comment by chanseokoh** [comment]
Makes sense!
