### ISSUE TITLE
Set default editor for app.yaml, if not it opens app.yaml as text file outside eclipse

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#1642]

**Comment by elharo** [comment]
consider whether Yedit makes sense here: https://marketplace.eclipse.org/content/yedit

**Comment by elharo** [comment]
This looks like the extension point: http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fruntime_content_contributing.htm

Shouldn't be too hard to map this to the text editor.

**Comment by elharo** [comment]
Make that org.eclipse.core.contenttype.contentTypes
