### ISSUE TITLE
Converted project doesn't have correct srcpath

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1647]
![image](https://cloud.githubusercontent.com/assets/1005544/24259007/bd97c1b2-0fac-11e7-8658-99cbde631a4a.png)

The first project was created by our wizard.
The second project in this screenshot, test, was converted from a basic Java Project. Note how main.webapp is treated as a Java package.

**Comment by elharo** [comment]
To configure the exclusions programmatically I think you need to use `IJavaProject` to remove the src folder from the classpath, then put it back but with an additional exclusion filter as setup b y `JavaCore.newSourceEntry` with the exclusion pattern.

We may want to consider whether this instead belongs in a different hierarchy parallel to src rather than in src.

**Comment by briandealwis** [comment]
> We may want to consider whether this instead belongs in a different hierarchy parallel to src rather than in src.

I think that's the right approach.  I'll check if the Java project has a src/ folder already configured, and use `WebContent/` instead, following WTP's normal lead.

(There's a separate but related problem: what should happen if the project has an incompatible Java version?)

**Comment by chanseokoh** [comment]
> (There's a separate but related problem: what should happen if the project has an incompatible Java version?)

For now, if the java project doesn't have the Java 7 facet, the auto-conversion menu will display our custom message dialog that the App Engine Standard facet requires Java 7.
