### ISSUE TITLE
Google project preferences page disappeared

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1650]
Select a project > _Properties_. There used to be a CT4E preference page, but it's gone.

**Comment by elharo** [comment]
Do you see this at head or in the released version?
 I see it, and I'm only 1 or 2 PRs behind head.

**Comment by chanseokoh** [comment]
Yeah, I guess my local workspace was corrupted. After cleaning, the page is there.

**Comment by chanseokoh** [comment]
I have seen this a lot, and now clearing my workspace doesn't help.

**Comment by chanseokoh** [comment]
This may not always be consistent, but for now, I don't see it when I am on the Java perspective, while it's there when on Resources or J2EE perspective.
