### ISSUE TITLE
Unable to provide custom flags (such as enable_jar_classes) when deploying

### ISSUE THREAD

**Issue by jason-elmore** [GoogleCloudPlatform/google-cloud-eclipse#1658]
This message shows in the log, but there is no option to provide this on deploy:

We detected that you have a large number of .class files in WEB-INF/classes. You may be able to reduce request latency by packaging your .class files into jars. To do this, supply the --enable_jar_classes flag when using appcfg on command line. If you're using the gcloud-maven-plugin, add <enable_jar_classes>true</enable_jar_classes> in the plugin's <configuration> tag. If you are using the appengine-maven-plugin, supply <enableJarClasses>true</enableJarClasses> in the plugin's <configuration> tag. Note that this flag will put the jar in WEB-INF/lib rather than WEB-INF/classes. The classloader first looks in WEB-INF/classes and then WEB-INF/lib when loading a class. As a result, this flag could change classloading order, which may affect the behavior of your app.

**Comment by akerekes** [comment]
@jason-elmore thanks for the report. It is indeed not possible to provide this flag currently when launching the deploy action.

**Comment by elharo** [comment]
This change would need to go into appengine-plugins-core, right?

**Comment by washowasho** [comment]
Hi - I am willing to help test this one when ready. I have a scenario where I need this. This will improve app launch time, correct?

**Comment by chanseokoh** [comment]
@elharo The option is already available in appengine-plugins-core: https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/v0.2.11/src/main/java/com/google/cloud/tools/appengine/cloudsdk/CloudSdkAppEngineStandardStaging.java#L63

So it's a matter of providing a UI for this option on our side. Another checkbox in the _Advanced_ section of the deploy dialog?

**Comment by elharo** [comment]
Is there any reason not to enable this unconditionally? I prefer not to clutter the UI if we can help it.

**Comment by ludoch** [comment]
In general, *all* possible flags should be exposed one way or another
(advanced tab if not a usual workflow), an IDE should not limit the list of
available flags... For example, do you expose the flags that control the
JSP files deletion and JSP jar creation?
Do you know if this is the same in Intellij? @paflynn

**Comment by washowasho** [comment]
Can there just be a field where you can set custom flags if there isn't going to be one built specifically for this one?

**Comment by washowasho** [comment]
Or how about if the "We detected that you have a large number of .class files" message arrives, set it to true, otherwise set it to false.

**Comment by mhopkins-dynactive** [comment]
I have the same problem. I am getting the 10k limit and was hoping to make my classes a .jar. Is there work around for this?

**Comment by jason-elmore** [comment]
And actually this doesn't work even when using Maven. I converted my project to Maven, thinking it would work, but nope.

**Comment by elharo** [comment]
Anyone know where this is documented for Cloud SDK?

**Comment by jason-elmore** [comment]
I could only find these two places mentioning the flag:
https://cloud.google.com/appengine/docs/standard/java/tools/maven-reference
https://cloud.google.com/appengine/docs/standard/java/tools/appcfg-arguments

**Comment by chanseokoh** [comment]
@jason-elmore the Maven plugin should work as a workaround (however, only for App Engine standard). Are you using the new plugin (`com.google.cloud.tools:appengine-maven-plugin`), not the old one (`com.google.appengine:appengine-maven-plugin`)? My configuration looks like

```xml
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>1.3.2</version>
        <configuration>
          <stage.enableJarClasses>true</stage.enableJarClasses>
        </configuration>
      </plugin>
```

If I do `$ mvn clean appengine:deploy` (or `$ mvn clean appengine:stage` just for staging), it places a JAR whose name is like `_ah_webinf_classes-0000.jar`.
```
$ tree target/appengine-staging/WEB-INF/
target/appengine-staging/WEB-INF/
├── appengine-generated
│   └── app.yaml
├── appengine-web.xml
├── classes
├── lib
│   ├── _ah_webinf_classes-0000.jar
│   └── jstl-1.2.jar
├── min-quickstart-web.xml
├── quickstart-web.xml
└── web.xml
```

**Comment by jason-elmore** [comment]
I'm using the new one.

    <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>${appengine.maven.plugin.version}</version>
        <configuration>
        <stage.enableJarClasses>true</stage.enableJarClasses>
        </configuration>
      </plugin>

I deployed via command line and that worked. Does the Eclipse plugin not use the configuration parameters specified in pom.xml?

**Comment by elharo** [comment]
If we want to do this (still TBD) then it's a one liner in

`CloudSdkStagingHelper.stageStandard`

**Comment by chanseokoh** [comment]
@jason-elmore ah, now I get what you meant Maven configs not working. The Eclipse plugin doesn't read configs defined in `pom.xml` for the `appengine-maven-plugin`. The Eclipse flow is pretty independent. Instead of calling `mvn appengine:deploy`, the Eclipse plugin runs its own staging and deploy executions. In fact, the Eclipse plugin doesn't even look into `pom.xml`.

**Comment by jason-elmore** [comment]
@chanseokoh So then there's no way to configure Eclipse to jar classes then, even when it's a Maven project?

**Comment by chanseokoh** [comment]
@jason-elmore correct. For now, flags/options/parameters you can pass down to gcloud or appcfg is very limited in Eclipse. Only implemented/supported currently are the options you see in the deploy dialog.

**Comment by patflynn** [comment]
@loosebazooka @etanshaul OI think this flag should be supported from all our tools.

**Comment by mhopkins-dynactive** [comment]
What I think is weird is that if you have a lot of class files and you deploy using eclipse, it tells you what to do but none of the things that it suggests can be done using the eclipse plugin to deploy. It would be nice to be able to at least put a flag in the config files that will do this for you. 

There are a lot of options that are not in the deploy dialog that are in the appengine-web.xml but the flag to say to jar up the classes isn't there.

My suggestion would be to let us put a flag in an appropriate config file and have eclipse read that flag and jar up everything. I don't think it is necessary to have the option in the deploy dialog. 

Also, like @elharo said, seems like it should be a standard thing to do? Especially if you have detected that there are a lot of classes.

**Comment by chanseokoh** [comment]
@patflynn not just this flag, but it'd be ideal if we support every possible flag as @ludoch said above. We could have a UI to accommodate all such flags, or alternatively, we might have a custom field for simplicity. Another relevant question is whether we should sync with Maven/Gradle plugin settings (which wouldn't work for native projects), but this would mean forcing users to put, e.g., a project to deploy in `pom.xml` rather than they can select a project in GUI.

**Comment by chanseokoh** [comment]
> My suggestion would be to let us put a flag in an appropriate config file and have eclipse read that flag and jar up everything. I don't think it is necessary to have the option in the deploy dialog.

@mhopkins-dynactive I think we need to ponder over the UX and carefully draw the line between which options must be put in relevant config files and which options should be given through GUI. Otherwise, this can greatly confuse users. For example, you can specify which project to deploy in `pom.xml` when using `appengine-maven-plugin`, but we deliberately don't use it because we want to provide an IDE UX where you can conveniently select a project through GUI. Also, `appengine-maven-plugin` could be thought of as one of many other CLI-tools for deploying an App Engine app. Another case is an app configured to use both `appengine-maven-plugin` and `appengine-gradle-plugin`.

> Also, like @elharo said, seems like it should be a standard thing to do? Especially if you have detected that there are a lot of classes.

As the following message suggests, we need to evaluate if it's safe to make this default, because it may change the behavior of an app. (However, I think it will be OK for apps that are built sane.)

> Note that this flag will put the jar in WEB-INF/lib rather than WEB-INF/classes. The classloader first looks in WEB-INF/classes and then WEB-INF/lib when loading a class. As a result, this flag could change classloading order, which may affect the behavior of your app.

**Comment by mhopkins-dynactive** [comment]
@chanseokoh true.

Its funny though because I was dealing with the 10k limit problem so I had a few options. I needed to exclude files from being uploaded and I could jar the classes. So to exclude files I was working in the appengine-web.xml but I couldn't tell the app to jar the classes the same way.

**Comment by chanseokoh** [comment]
There is an internal doc that lists all the flags finalized to be supported going forward. We should expose the flags in UI so that users can specify them.

**Comment by etanshaul** [comment]
@chanseokoh whats that link to the internal doc again?

**Comment by nbashirbello** [comment]
@briandealwis Hey what defaults would you be using for the staging flags?

**Comment by briandealwis** [comment]
@nbashirbello I was planning to follow your lead ;)

**Comment by elharo** [comment]
I still don't feel I have enough grasp of the issues here to move forward on this. There are several questions I don't have answers to yet:

1. Should enable_jar_classes be set unconditionally? If not, under what conditions should it be set?
2. What does this all look like if appcfg goes away in favor of Cloud SDK?

Ideally I'd like to see public documentation on cloud.google.com explaining what's going on here and what users can expect.

**Comment by briandealwis** [comment]
Closing: as noted in https://github.com/GoogleCloudPlatform/google-cloud-intellij/pull/1865#issuecomment-365288402, `appengine-web.xml` will soon support setting these staging instructions.

**Comment by briandealwis** [comment]
Staging instructions now supported in `appengine-web.xml` as of Google Cloud SDK 190.0.0.  Documentation on new options at:

  https://cloud.google.com/appengine/docs/standard/java/config/appref#staging_elements

**Comment by patflynn** [comment]
I think we need to test this out.  I suspect that the transformation of
appengine-web.xml staging properties to stage time parameters only occurs
if 'gcloud app deploy' is called on unstaged exploded apps.  We may need a
round of tooling updates to start using this.

**Comment by chanseokoh** [comment]
@patflynn I've tested this in Eclipse (for the Java 7 and 8 runtimes), and it works.

```
Beginning interaction for module default...
0% Scanning for jsp files.
...
Success.
Temporary staging for module default directory left in <...redacted...>/runtime-gcloud-eclipse/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1519746430624/staging
```

```
$ tree <...redacted...>/runtime-gcloud-eclipse/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1519746430624/staging
   ...
└── WEB-INF
    ├── appengine-generated
    │   └── app.yaml
    ├── appengine-web.xml
    ├── classes
    ├── lib
    │   ├── _ah_webinf_classes-0000.jar
    │   └── jstl-1.2.jar
    ├── min-quickstart-web.xml
    ├── quickstart-web.xml
    └── web.xml
```

**Comment by chanseokoh** [comment]
However, there is a XML validation problem on `appengine-web.xml`. I'll file a new issue.

**Comment by patflynn** [comment]
Just to double-check, when you say you tested it, did you test adding
<staging> elements to appengine-web.xml and verify that they applied?

**Comment by chanseokoh** [comment]
Yes, added them to `appengine-web.xml`. I tested setting `<enable-jar-classes>` to true or false.

**Comment by patflynn** [comment]
cool. thanks.
