### ISSUE TITLE
Marketplace search for plugin doesn't work

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#1668]
I'm finding I can't find the plugin through an Eclipse Market Place search. 

1. goto the marketplace
2. search for something like "Google Cloud Tools for Eclipse"
https://marketplace.eclipse.org/search/site/Google%2520Cloud%2520Tools%2520for%2520Eclipse
3. I'm expecting the plugin to show up in the results for but some reason it's not for me. 

![screen shot 2017-03-27 at 12 57 44 pm](https://cloud.githubusercontent.com/assets/1326504/24375422/0d6a7764-12ed-11e7-9564-46dc4aa700fe.png)

What I'm looking for: 
https://marketplace.eclipse.org/content/google-cloud-tools-eclipse

![screen shot 2017-03-27 at 12 59 08 pm](https://cloud.githubusercontent.com/assets/1326504/24375452/2dfbe558-12ed-11e7-830d-49bb088ada3f.png)

Do you get the same results?

**Comment by akerekes** [comment]
It used to work, I've checked it not long after we published the plugin, but it doesn't work now for me either.

**Comment by briandealwis** [comment]
I've pinged the maintainer and will follow-up.

**Comment by chanseokoh** [comment]
Wasn't working, but now it works. @branflake2267 Can you confirm and close this?

**Comment by branflake2267** [comment]
It's working today. 

![screen shot 2017-03-28 at 8 56 36 am](https://cloud.githubusercontent.com/assets/1326504/24414921/9ce84e32-1394-11e7-9620-c6c12d871a31.png)

**Comment by chanseokoh** [comment]
@branflake2267 Yeah, @briandealwis pinged the maintainer, and it seemed like it had stale data yesterday.

**Comment by briandealwis** [comment]
\o/
