### ISSUE TITLE
Change the servlet api version for the sample Flex projects and fix at version 3.1

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#1674]
javax.servlet:javax.servlet-api

**Comment by elharo** [comment]
According to public facing docs, App Engine Flex supports 3.1. Why do you want to change to 4.0?

**Comment by chanseokoh** [comment]
Definitely not 4.0. As @briandealwis said, it's still under development. https://mvnrepository.com/artifact/javax.servlet/javax.servlet-api

**Comment by elharo** [comment]
Good for flex. Standard is still 2.5 ATM.
