### ISSUE TITLE
queue.xml not included in "Deploy to App engine standard"

### ISSUE THREAD

**Issue by foreverwithmalli** [GoogleCloudPlatform/google-cloud-eclipse#1676]
When we deploy a project from eclipse using "Deploy to app engine standard" only app.yaml gets deployed, queue.xml & cron.xml are not deployed. How can I add them?

**Comment by foreverwithmalli** [comment]
I see that in "google-cloud-eclipse/plugins/com.google.cloud.tools.eclipse.appengine.deploy/src/com/google/cloud/tools/eclipse/appengine/deploy/AppEngineProjectDeployer.java" only app.yaml is included.
We have to include other yaml's as well.

**Comment by chanseokoh** [comment]
A workaround for now is to use Maven on the command line, using the new Maven plugin with a config similar to this: https://github.com/GoogleCloudPlatform/app-maven-plugin/issues/153#issuecomment-287845224

@patflynn I recall we have a plan to add a new goal to the Maven plugin to take care of deploying these config files independently of an app. What could be a good UX in IDE? Having a separate deploy dialog for config files, or a checkbox to deploy config files along with an app?

**Comment by akerekes** [comment]
Or if the project does not use Maven, you can use `gcloud app deploy cron.yaml`, see https://cloud.google.com/appengine/docs/flexible/go/scheduling-jobs-with-cron-yaml
