### ISSUE TITLE
Allow simultaneous com.android.ide installation

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1678]
These should not be antirequisites:

com.android.ide.eclipse.ddms.feature.feature.group
com.android.ide.eclipse.gldebugger.feature.feature.group
com.android.ide.eclipse.hierarchyviewer.feature.feature.group
com.android.ide.eclipse.ndk.feature.feature.group
com.android.ide.eclipse.traceview.feature.feature.group

**Comment by briandealwis** [comment]
GPE's `CloudToolsUpgradeJob` uninstalls the ADT features.
