### ISSUE TITLE
CT4E may not show up in installed components even though it is installed

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1687]
![image](https://cloud.githubusercontent.com/assets/1005544/24467882/47a96460-1484-11e7-8341-ec64b77b93a3.png)

![image](https://cloud.githubusercontent.com/assets/1005544/24467889/5193cc9a-1484-11e7-97a8-5c338bb3a014.png)

**Comment by elharo** [comment]
Just realized this may have happened because I used the upgrade from within GPE notification. Will test that hypothesis now.

**Comment by briandealwis** [comment]
Possibly, though we do set the root property on our additions there.

**Comment by elharo** [comment]
Nope, was not able to reproduce so that wasn't it (or at least not every time)

**Comment by elharo** [comment]
appears fixed
