### ISSUE TITLE
Re-run last deploy

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1693]
It would be convenient to re-run the most recent deploy with a single click. This could be e.g. a button on the deploy console. If the user needs to make a minor change and re-run the deploy, he needs to click on either the project or the toolbar icon, select the deploy action, and click on the `Deploy` button in the dialog.

Possibly we could have separate console pages for each deploy and we could re-run the corresponding deploy, not only the most recent.

**Comment by elharo** [comment]
A single click requires a toolbar button, which feels like more than this feature is worth. Maybe a context menu item though?

**Comment by briandealwis** [comment]
One approach might be to leverage the Run/Debug launchers by defining our own launch mode (`deploy`).  It would enable repeatable deploys.

Though it strikes me as something that's better supported in the build via CI/DI.
