### ISSUE TITLE
Is it expected that version is 0.0.0 when running hosted?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1704]
- Cloud Tools for Eclipse Version: 0.0.0
- OS: Mac OS X 10.12.3
- Java Version: 1.7.0_80

If so, close this issue.

**Comment by chanseokoh** [comment]
Yeah, unfortunately, @briandealwis said the version is available only after actual installation: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1489#pullrequestreview-24156453
