### ISSUE TITLE
Convert to App Engine Standard Project doesn't work with Java 8

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1718]
![image](https://cloud.githubusercontent.com/assets/1005544/24606687/5c671bb6-183c-11e7-9663-e75eca349ef5.png)

**Comment by briandealwis** [comment]
Should be fixed: we now bash the Java and DWP facets to correspond to the AES facet, and we also apply the default AES version (currently JRE7) if there's no `appengine-web.xml`.
