### ISSUE TITLE
Internal web browser caches http://localhost:8080/ and serves previous page, but only initially

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1728]
A very minor nuisance.

1. Create a HelloWorld project.
2. _Run As_ > _App Engine_
3. An internal browser serves `index.html` at `http://localhost:8080/`
4. Stop the server.
5. Modify `src/main/webapp/index.html`.
6. _Run As_ > _App Engine_
7. Observe that the same internal browser still serves the previous `index.html`.

At this point, if you reload the browser, it will correctly server the new `index.html`.

**Comment by diegomarquezp** [comment]
Closing as not planned since Java 8 is not supported in GAE. cc: @blakeli0
