### ISSUE TITLE
Disable Next/Finish for high ports

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1748]
We pop up an error for a too high port on local run but we don't actually prevent the user from running:

![image](https://cloud.githubusercontent.com/assets/1005544/24768560/052b7c7e-1ad1-11e7-8b7c-fce60bd3c1f3.png)

**Comment by elharo** [comment]
Probably a WTP issue.

**Comment by briandealwis** [comment]
We discussed this during #871 and it's a restriction on WTP.  We could move the port into a separate page, or bring back the support that @chanseokoh removed to filter the possible values.
