### ISSUE TITLE
Deploying into App Engine Flexible with Eclipse plugin

### ISSUE THREAD

**Issue by rafaelsf80** [GoogleCloudPlatform/google-cloud-eclipse#1755]
Hi,

Is it possible to deploy an App Engine Flexible project with the Eclipse plugin ?
I'm trying to deploy [this app](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/helloworld-servlet), but **Run As App Engine** fails saying "Server does not support version 3.1 of J2EE".
Any guidance would be appreciated,

Thanks,
Rafa

**Comment by chanseokoh** [comment]
Hi @rafaelsf80,

It is not yet possible to deploy a flexible env project with the Eclipse plugin. Implementing support for flex is under way. For now, you may want to use the App Engine Maven or Gradle plugin as described in the README of the app.

FYI, **Run As App Engine** is to run an App Engine standard env project _locally_ with a dev server. It's not for deployment.
