### ISSUE TITLE
Use "Google" in wizard names or don't

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1766]
Right now we're inconsistent:

![image](https://cloud.githubusercontent.com/assets/1005544/24859141/4d497cce-1dbd-11e7-9f44-a6a5b168a68e.png)

**Comment by arouzrokh** [comment]
Yes please use the word Google in all of them. Here is what it should look like:

Google Dataflow Java Project
Google App Engine Flexible Java Project
Google App Engine Standard Java Project
Maven-based Google App Engine Standard Java Project

This also helps when people search in the bar above, where they use the word google probably as a start when they are thinking about GCP. 

Thanks,
