### ISSUE TITLE
build/verify-feature-installation failed to catch missing dependency

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1777]
Our `build/verify-feature-installation` didn't catch that `org.yaml.snakeyaml`, a new dependency from `com.google.cloud.tools.appengine`/`appengine-plugins-core`, was unavailable and thus installations would fail.  Turns out that our check succeeds as:

  1. the `build/verify-feature-completeness` uses the `ide-target-platform` as its source, to avoid re-downloading artifacts from the net, and
  2. we include `appengine-plugins-core` in our `ide-target-platform`, and 
  3. snakeyaml is pulled in from Orbit, which is specified in our .target files

The root problem is that our `ide-target-platform` is a development target, including SDKs etc, and not a deployment target.

We should do this verification step without using `ide-target-platform`, perhaps as a Travis cron job.

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
