### ISSUE TITLE
after upgrade to new Eclipse plug in, option to deploy my app to App Engine is not enabled

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#1786]
- Cloud Tools for Eclipse Version: 1.0.2.201704031432
- OS: Windows 10 10.0
- Java Version: 1.8.0_92

after upgrade to new Eclipse plug in, the option to Deploy to App Engine Standard is not enabled. How do I deploy my app?

**Comment by chanseokoh** [comment]
Hi @Rob46,

Right click on your project and see if you have  _Configure..._ > _Convert to App Engine Standard Project_. If you see it, execute the menu item to migrate your project. Let me know if you encounter any problems afterwards.

**Comment by Rob46** [comment]
I actually gave up trying and had to reinstall Eclipse Neon from scratch just to get the old plugin to work. This is a production project and I can't afford to be down with issues on the new plugin. Will try again in a couple of months when hopefully it is sorted out better.

**Comment by elharo** [comment]
I wonder if there's some way we could autoconvert? Maybe display the Deploy menu item for projects with the old GPE natures/facets and convert the project before running/deploying it?

**Comment by Rob46** [comment]
That would be helpful. Also, is the conversion one-way? I ask because I didn't want to even run the conversion given the 1.0 status of the new plug in in case I couldn't get it to work properly and then couldn't easily revert to the old plugin. Clarifying that in a popup would help too.

**Comment by elharo** [comment]
There's no "one click" to convert back, though it is possible . y mucking around in Eclipse dialogs. At the end of the day you don't need Eclipse to deploy, and it's all just Java code. 

Also, note GPE will be going away this year, and will not work at all in Eclipse 4.7.

**Comment by Rob46** [comment]
So what is the preferred method going forward?

**Comment by elharo** [comment]
see https://cloud.google.com/eclipse/docs/converting
