### ISSUE TITLE
Dataflow preferences pane has issues

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1805]
On opening dataflow preference pane for first time

![image](https://cloud.githubusercontent.com/assets/1005544/25050088/4bdfc218-2113-11e7-840a-09a5ff6208e7.png)

From the stack trace this may just be another symptom of

```
java.lang.NoClassDefFoundError: com/google/api/client/json/jackson2/JacksonFactory
```

**Comment by chanseokoh** [comment]
Putting a link: #1745.

To be safe, I'd like to make a note: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1745#issuecomment-292926034.
