### ISSUE TITLE
Retrieve App Engine directory from flex deploy preferences (set via flex deploy dialog) when executing flex deploy command

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1823]
When deploying flex projects, we assume the App Engine directory (where `app.yaml` is located) is always `src/main/appengine`, but this should come from the flex deploy preference (`FlexDeployPreferences.getAppEngineDirectory`) which will be set by the deploy dialog. The dialog also needs to be extended to have a path input field for this directory.

**Comment by briandealwis** [comment]
Shouldn't this location be stored via a config object on the App Engine flexible facet, similar to the config folder (_WebContent_) on the `jst.web` facet?

**Comment by briandealwis** [comment]
After some discussion with @chanseokoh, app.yaml mixes configuration with deployment settings, so it can make sense to have multiple app.yamls.
