### ISSUE TITLE
Refactor DeployJob constructor

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1824]
It's taking 6 parameters, which are a lot. (However, they are all required.)

1. Two of them are of type `ProcessOutputLineListener`, for which we will ever pass the same object (unless we want to create a console for staging logs and another console for deploy logs, which won't happen). I suggest to pass just one.
1. `ProcessOutputLineListener` and `DefaultDeployConfiguration` are objects for `CloudSdk` from `appengine-plugins-core`. We could completely hide any CloudSdk-specific dependencies from the clients of `DeployJob`.
1. To take care of the above point, we will pass `DeployPreferences` (which is the user selected values from the deploy dialog) instead of `DefaultDeployConfiguration`. That way, `DeployJob` will be able to retrieve the value of `includeOptionalConfigurationFiles` from the preferences, hence no need to pass this argument.

**Comment by briandealwis** [comment]
I think we want to pass two `ProcessOutputLineListener`s to support #1248

**Comment by chanseokoh** [comment]
> I think we want to pass two `ProcessOutputLineListener`s to support #1248

I'd say two of something (probably `MessageConsoleStream`) other than `ProcessOutputLineListener`.

**Comment by elharo** [comment]
1. I think we can get rid of the `workDirectory` parameter. Just pick a temporary directory and use it.

2. I'm still not convinced `includeOptionalConfigurationFiles` is needed. We could just deploy all files that are present.

3. Pass a MessageConsole or an output stream rather than the two line listeners.

**Comment by chanseokoh** [comment]
As a note, I realized that using a system temp directory does not work for `PublishHelper`. For some unknown reason,  it seems like it cannot write a WAR (or its exploded contents) on a directory outside a project area or the plugin area. That is probably why we are managing (i.e., cleaning) the "temp" directory ourselves with `CleanupDeployJob`.

**Comment by elharo** [comment]
This appears to be obsolete.
