### ISSUE TITLE
Servlet API validation should check namespace-version match

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#1834]
`WebXmlValidator` checks if the `<web-app>` namespace is either _http://xmlns.jcp.org/xml/ns/javaee_ or _http://java.sun.com/xml/ns/javaee_, but does not verify that the `version` attribute matches the namespace.

Should also check for a missing `version`.

**Comment by elharo** [comment]
We do check for a missing version.

We also note mismatched version but ohnly if a schema is present.

**Comment by diegomarquezp** [comment]
Closing as not planned.
