### ISSUE TITLE
stopPreviousVersion is effective only for Flexible environment

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1837]
Instances in standard will just scale down to 0 automatically (learned from @loosebazooka )

**Comment by elharo** [comment]
What's the implication? Is there anything to do here? Should we remove the stopPreviousVersion checkbox?

**Comment by elharo** [comment]
Yes, we should remove the stopPreviousVersion checkbox from standard deployment. It has no effect.

**Comment by briandealwis** [comment]
The [`appengine-web`'s scaling section](https://cloud.google.com/appengine/docs/standard/java/config/appref#scaling_elements) notes that the _automatic-scaling > min-idle-instances_ element only takes effect for the default version, but there is no such note on the _manual-scaling_ element.  The link to the ["How Applications Scale"](https://cloud.google.com/appengine/docs/standard/java/scaling) is broken.

**Comment by patflynn** [comment]
@akerekes interestingly it's possible that the previous version is flex even though you're deploying standard now.  Not quite sure what the right behavior should be.

**Comment by loosebazooka** [comment]
That's a good point. Perhaps we should leave it in.

**Comment by chanseokoh** [comment]
I verified that it is indeed possible to stop a flex app when deploying a standard app. The log from gcloud in this case will show

```
Updating service [default]...
......................Stopping version [<... project ...>/default/20170421t154956].
.Sent request to stop version [<... project ...>/default/20170421t154956]. This operation may take some time to complete. If you would like to verify that it succeeded, run:
  $ gcloud app versions describe -s default 20170421t154956
until it shows that the version has stopped.
done.
```
