### ISSUE TITLE
Convert generated pom.xml files to use new maven appengine plugin instead of old plugin

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#184]

**Comment by briandealwis** [comment]
Is this an issue with the current New Wizard, or is this for upgrading existing projects?

**Comment by elharo** [comment]
Both. Anything that generates a pom.xml

**Comment by elharo** [comment]
Actually, I think I misunderstood you. This is for the new generated wizards, not for autoconverting old projects (though maybe we should do that too?)

**Comment by briandealwis** [comment]
We realized during the call on May 19 (IIRC) that I didn't know there was a successor to the `gcloud-maven-plugin`.

**Comment by rdayal** [comment]
This is a high priority. You can't effectively have a New Web App Project Wizard backed by the proper maven import unless you are using the new maven plugin (app-maven-plugin).

I'd recommend creating a new archetype based on the new plugin.

**Comment by elharo** [comment]
Let me check in with Les V and see what they want to do: new archetype or new version of old archetype.

**Comment by elharo** [comment]
https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/issues/24

**Comment by elharo** [comment]
Assigning to @rdayal to coordinate with other teams

**Comment by elharo** [comment]
The artifact will be appengine-standard-archetype although this is not yet pushed to maven central.

**Comment by elharo** [comment]
blocked by https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/pull/36

**Comment by elharo** [comment]
fixed
