### ISSUE TITLE
DeployPreferencesModel might not be necessary

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1846]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1844#pullrequestreview-34061135

It sits between the data binding (UI stuff in the deploy dialog) and the persisted user preferences, so it may be possible to remove it. However, I'm not so sure if we can do this easily, because my understanding is that, we modify the model values whenever a user changes UI selections for example, so we do need to delay persisting until a user presses _OK_, _Apply_, or _Deploy_. That sounds like we nevertheless need some dirty buffer object anyway.

**Comment by chanseokoh** [comment]
Hmm... #1844 may be about _merging_ the two objects `DeployPreferencesModel` and `DeployPreferences`.

**Comment by briandealwis** [comment]
What I envision:
  - DeployPreferences would load its values from the `IEclipsePreferences` prefstore into local fields (like DeployPreferencesModel)
  - getters and setters would reference the local fields (like DeployPreferencesModel)
  - `save()` would write out local fields to the `IEclipsePreferences` prefstore.

**Comment by chanseokoh** [comment]
That does make sense. I like it.
