### ISSUE TITLE
UX review

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#185]
Once the plugin is a little more complete, see if we can get a UX engineer to run through the basic workflow and note any obvious problems.

**Comment by rdayal** [comment]
I don't think we need to block on UX here. For the alpha, we should run through it (on our team), plus other java devs at Google, plus trusted external devs.

**Comment by elharo** [comment]
See https://wiki.eclipse.org/User_Interface_Guidelines

Also http://www.oracle.com/technetwork/java/jlf-135985.html for a few things Eclipse doesn't cover such as alignment.

**Comment by elharo** [comment]
@hray2003 Would you like to make any final comments on the plugin before 1.0, or are we good to go?
