### ISSUE TITLE
Test failure on Windows - LocalAppEngineServerLaunchConfigurationDelegateTest.testGenerateRunConfiguration_withVMArgs

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#1856]
LocalAppEngineServerLaunchConfigurationDelegateTest.testGenerateRunConfiguration_withVMArgs:276 expected:<[a, b, c d]> but was:<[a, b, 'c, d']>

**Comment by briandealwis** [comment]
`org.eclipse.debug.core.DebugPlugin#parseArguments()` has special Windows parsing which seems to support only double-quotes and not single quotes.  So it interprets `'c d'` as two elements, `'c` and `d'`.
