### ISSUE TITLE
Move appengine-web.xml validation-disabling rules to common plugin

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#186]
We define some rules in `com.google.cloud.tools.eclipse.appengine.newproject.maven` that are more general and should be moved to a more general plugin:
- disable XML validation for `appengine-web.xml` (the rule for `nbaction.xml` may be ok to stay, since it's specific to the generated archetypes?)
- m2eclipse lifecycle mappings for the `versions-maven-plugin`?

**Comment by elharo** [comment]
Specifically you're taking baout this, right?

```
   <extension
         id="appengine"
         point="org.eclipse.wst.validation.exclude">
      <validator
            id="org.eclipse.wst.xml.core.xml">
         <exclude>
            <rules>
               <file
                     name="nbactions.xml"
                     type="full">
               </file>
               <file
                     name="appengine-web.xml"
                     type="file">
               </file>
            </rules>
         </exclude>
      </validator>
   </extension>
```

As is, it applies to everything. The problem is just that there's no real reason this code should be in the maven plugin, is that correct?

**Comment by briandealwis** [comment]
Yeah.  I'm ok with the `nbactions.xml` here, though perhaps we should programmatically associate this with the actual file in our wizard.

**Comment by briandealwis** [comment]
Closing as we no longer use the maven archetype for new project generation.
