### ISSUE TITLE
Installing without maven

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1884]
GPE Upgrade failed for one user who did not have m2e in their Eclipse:

```
Could not undertake update
Cannot complete the install because one or more required items could not be found.Software being installed: Google Cloud Platform for Eclipse 4.5 and later 1.0.3.201704111618 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 1.0.3.201704111618)
Missing requirement: Cloud Tools for Eclipse App Engine Local Server 0.1.0.201704111542 (com.google.cloud.tools.eclipse.appengine.localserver 0.1.0.201704111542) requires 'bundle org.eclipse.m2e.wtp 1.2.1' but it could not be found
Cannot satisfy dependency:
```

**Comment by briandealwis** [comment]
Mars SR0 had org.eclipse.m2e.wtp 1.2.0.20150602-1740.  We could downgrade our minimum version to 1.2.0.

**Comment by elharo** [comment]
Also affects internal Google Eclipse distro

**Comment by briandealwis** [comment]
@elharo Did you have "Contact all update sites during install to find required software" ticked?
Was one of the Eclipse update sites in your available sites? (e.g., http://download.eclipse.org/releases/mars)

Is the solution here to try to decouple or make m2e optional?

**Comment by elharo** [comment]
I'll check with the internal distro when I get into work. Should be easy to reproduce there.

**Comment by elharo** [comment]
It now works for me in Oxygen with and without "Contact all update sites during install to find required software" ticked though there's a slight difference in the flow with that checked. If it's nhot checked, Eclipse gives me the modify installation to make compatible screen. 

Maybe this is an issue only in Mars?
