### ISSUE TITLE
getHeader in MockHttpServletResponse

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1886]
Servlet 3.0 ( or 3.1) added a `getHeader` and several other methods to HttpServletResponse we need to implement in our sample code. 

The type MockHttpServletResponse must implement the inherited abstract method HttpServletResponse.getHeader(String)	MockHttpServletResponse.java	/fred/src/test/java	line 19	Java Problem

This broke the project on conversion to Java 8. 

```

@Override
public void setContentLengthLong(long len) {
	// TODO Auto-generated method stub
	
}

@Override
public int getStatus() {
	// TODO Auto-generated method stub
	return 0;
}

@Override
public String getHeader(String name) {
	// TODO Auto-generated method stub
	return null;
}

@Override
public Collection<String> getHeaders(String name) {
	// TODO Auto-generated method stub
	return null;
}

@Override
public Collection<String> getHeaderNames() {
	// TODO Auto-generated method stub
	return null;
}
```

**Comment by elharo** [comment]
FYI the four getter methods are from Servlet 3.0. setContentLengthLong is from Servlet 3.1.

**Comment by chanseokoh** [comment]
As a note, he flex HelloWorld app, which uses 3.1, currently implement all these.
