### ISSUE TITLE
Detect Java 8 enabled before deployment

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1887]
Not sure whether this is possible without too much effort; but can we detect which runtimes a given App Engine application for a GCP project supports and not show these projects as options in the project selector? 

![image](https://cloud.githubusercontent.com/assets/1005544/25555029/87170560-2caa-11e7-8e7c-b13bac1f6fe0.png)

**Comment by briandealwis** [comment]
@elharo is this moot now that `java8` is in public beta and no longer requires whitelisting?

**Comment by elharo** [comment]
moot
