### ISSUE TITLE
Bad error message on deploying Java 8 app on Java 7 runtime

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1888]
Probably a gcloud bug. This has nothing to do with Java 6. 

![image](https://cloud.githubusercontent.com/assets/1005544/25555059/10a68300-2cab-11e7-8d3b-4feb25108f4d.png)

ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Java 6 applications are prevented from being deployed to Google App Engine from any version of the SDK, including older ones. If you need to continue to deploy Java 6 applications for compatibility reasons, you can request that your application be whitelisted for Java 6 deployment by visiting http://goo.gl/ycffXq.

**Comment by elharo** [comment]
My mistake, should have been <runtime>java8</runtime>

**Comment by iatomic** [comment]
we are having the same issue here:
ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Java 6 applications are prevented from being deployed to Google App Engine

Here is our yaml...:

runtime: java
env: standard
runtime_config:
  jdk: openjdk8
  server: tomcat8

env_variables:
  SPRING_PROFILES_ACTIVE: "cloud-gcp"

handlers:
- url: /.*
  script: this field is required, but ignored
  secure: always
  redirect_http_response_code: 301
manual_scaling: 
  instances: 1

resources:
  cpu: 1
  memory_gb: 3

**Comment by chanseokoh** [comment]
@iatomic App Engine standard doesn't yet support `app.yaml` for Java. You should be using [`appengine-web.xml`](https://cloud.google.com/appengine/docs/standard/java/config/appref). And for standard, there is effectively one runtime you will use for now: [Java 8 runtime which runs Jetty 9](https://cloud.google.com/appengine/docs/standard/java/runtime-java8). (There is the Java 7 runtime, but will be turned down very soon.)

**Comment by iatomic** [comment]
that is interesting because I am actually deploying with app.yaml fine and using flex env and Java. I tried standard env but it has 33MB war file upload limit in deploy. When I tired the above (standard env and yaml) it did complain about java 6 (!!!!).... so how does google recommend to deploy springboot apps (WAR archives are ABOVE 33MB limit in size), standard and Java? with gcloud app deploy and uploading 100s of files one by one from an unpacked WAR dir?

**Comment by chanseokoh** [comment]
Good to hear you figured out, but for the record:

First of all, standard and flexible are quite different. Now for standard, I believe you use Maven, so one of the recommended ways of developing and deploying is to configure the Cloud SDK-based Maven plugin. For example,

```xml
<plugin>
   <groupId>com.google.cloud.tools</groupId>
   <artifactId>appengine-maven-plugin</artifactId>
   <version>1.3.2</version>
</plugin>
```

And to deploy, you run `mvn appengine:deploy`.

For more information, see https://cloud.google.com/appengine/docs/standard/java/tools/using-maven and https://cloud.google.com/appengine/docs/standard/java/tools/uploadinganapp. The latter doc also mentions App Engine SDK-based or another alternative `appcfg` way, but they are different from Cloud SDK-based way. (I know these can sometimes be confusing.)
