### ISSUE TITLE
org.eclipse.m2e.wtp 1.2.1 not found

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1902]
Installing from update site https://dl.google.com/eclipse/google-cloud-eclipse/stable/

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Google Cloud Platform for Eclipse 4.5 and later 1.0.3.201704111618 (com.google.cloud.tools.eclipse.suite.e45.feature.feature.group 1.0.3.201704111618)
  Missing requirement: Cloud Tools for Eclipse App Engine Local Server 0.1.0.201704111542 (com.google.cloud.tools.eclipse.appengine.localserver 0.1.0.201704111542) requires 'bundle org.eclipse.m2e.wtp 1.2.1' but it could not be found
```

This happens with the internal Google Eclipse distro, which perhaps has different packages than the normal distros.

**Comment by chanseokoh** [comment]
Looks like a dup of #1884?

**Comment by elharo** [comment]
yep, though this time i managed to get it to happen to me. :-)

**Comment by briandealwis** [comment]
Did you have _"Contact all update sites during install to find required software"_ ticked?
Was one of the Eclipse update sites in your available sites?  (e.g., http://download.eclipse.org/releases/mars)
