### ISSUE TITLE
Import google app script issues

### ISSUE THREAD

**Issue by Oussama-bch** [GoogleCloudPlatform/google-cloud-eclipse#1909]
- Cloud Tools for Eclipse Version: 1.0.3.201704111618
- OS: Windows 7 6.1
- Java Version: 1.8.0_131

I can't import a google app script from Eclipse and i dont know why ?

**Comment by chanseokoh** [comment]
Hi @Oussama-bch, The Google Apps Script is a non-Cloud product that was supported in the old GPE. The new Cloud Tools for Eclipse covers the scope of Google Cloud, so it does not have support for Google Apps Script. But let me check with other folks what we can do to help the migration story for Apps Script.

**Comment by elharo** [comment]
Apps Script projects can be edited directly in your web browser using the Google Drive script editor.

All of your Apps Script projects are already available in Google Drive. No additional export or conversion is required.
