### ISSUE TITLE
working directory should be application root

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1932]
running in local server we get this warning:

WARNING: Your working directory, (/usr/local/google/home/elharo) is not equal to your 
web application root (/usr/local/google/home/elharo/runtime-gcloud-eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/test)
You will not be able to access files from your working directory on the production server.

We should set the working directory to the application root when launching the devappserver.

**Comment by elharo** [comment]
W'll need to make some adjustments in appengine-plugins-core first since neither `CloudSdk.Builder` nor `CloudSdkAppEngineDevServer1` expose a means of setting the working directory. :-(

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/385
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1864
http://stackoverflow.com/questions/43618900/cannot-access-file-using-relative-path-in-local-test-when-developing-google-app

**Comment by chanseokoh** [comment]
This will be fixed (however only for single-service runs) when we have the next appengine-plugins-core release: https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/411

(Unfortunately, there does not seem a viable way to make all things right for multi-service runs).

**Comment by NicolaSpreafico** [comment]
I'm having the same problem. I created a text file under the WEB-INF folder that I need to read in memory to execute some operations.

With the previous plugin I simply used a new File("...") to read the file, but now the path are starting from a wrong folder.

Any update on fixing this problem?

**Comment by patflynn** [comment]
@NicolaSpreafico any reason you're not loading the file as a classpath resource?  Relying on the File API and working directory is likely to be flaky regardless of whether we fix this bug.

**Comment by NicolaSpreafico** [comment]
@patflynn I know, I agree with you, but there are some projects that are born like this and the stayed like this. For the new projects we are using the src/main/resources folder of Maven, but the old one have been not migrated.

We have migrated some of them, when possible, ma others cannot be modified per the moment.
