### ISSUE TITLE
appengine-web.xml doesn't have line break after XML declaration

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1940]
when creating a new project

```
<?xml version="1.0" encoding="UTF-8"?><appengine-web-app xmlns="http://appengine.google.com/ns/1.0">

  <threadsafe>true</threadsafe>
```

should be 

```
<?xml version="1.0" encoding="UTF-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">

  <threadsafe>true</threadsafe>
```

**Comment by elharo** [comment]
This appears to be a side effect of the Java 8 work. The 
FacetChangeListener runs on new project creation, and applies an XSLT stylesheet. It probably shouldn't do this.

**Comment by chanseokoh** [comment]
This also happens when applying the quick-fix to remove `<application>`.

**Comment by elharo** [comment]
This is really a separate bug, but see 
 https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1944/files for the changes we need here. These just need to be done to the stylesheets that apply the quick fixes:

removeApplication.xsl
removeVersion.xsl
