### ISSUE TITLE
Can't update Java facet to 1.8 in Maven project

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1941]
It immediately reverts to 1.7.

**Comment by elharo** [comment]
Manually adding `<runtime>java8</runtime>` to appengine-web.xml makes this work, but this is not automatic as it is with a non-Maven project.

**Comment by elharo** [comment]
Given that Java 8 support is still in whitelist beta, I'm inclined to declare this a non-release blocker.

**Comment by elharo** [comment]
From the debugger it looks like maybe the runtime is added, but then the Java 1.8 facet add event is immediately followed by another event changing the facet back to 1.7.

**Comment by elharo** [comment]
Hypothesis: when the facet is updated some job checks appengine-web.xml, sees there's no <runtime>java8</runtime> and resets the facet to Java 1.7.

**Comment by elharo** [comment]
The problem is here:

```
  private void checkRuntimeElement(IFacetedProject project, IFile appEngineWebDescriptor,
      IProgressMonitor monitor) {
    try (InputStream input = appEngineWebDescriptor.getContents()) {
      boolean hasJava8Runtime = AppEngineDescriptor.parse(input).isJava8();
      boolean hasJava8Facet = project.hasProjectFacet(JavaFacet.VERSION_1_8);
      // if not the same, then we update the facet to match the appengine-web.xml
      if (hasJava8Facet != hasJava8Runtime) {
        Set<Action> updates = new HashSet<>();
        if (hasJava8Runtime) {
          updates.add(new Action(Action.Type.VERSION_CHANGE, JavaFacet.VERSION_1_8, null));
        } else {
          updates.add(new Action(Action.Type.VERSION_CHANGE, JavaFacet.VERSION_1_7, null));
        }
        logger.fine(getProject() + ": changing facets: " + updates);
        project.modify(updates, monitor);
      }
    } catch (SAXException ex) {
      // Parsing failed due to malformed XML; just don't check the value now.
    } catch (CoreException | IOException ex) {
      logger.log(Level.SEVERE, getProject() + ": error updating facets", ex);
    }
  }
```

comment out the line `updates.add(new Action(Action.Type.VERSION_CHANGE, JavaFacet.VERSION_1_7, null));` and this works. Not clear why this is only a problem for maven.

**Comment by elharo** [comment]
Just noticed that adding the Java 1.8 facet to a maven project does *not* update appengine-web.xml with a `runtime` element. That may be the root cause here.

**Comment by elharo** [comment]
In the debugger I've noticed that for a standard project adding the  Java 8 facet only runs the addJava8Runtime.xsl. However for a maven project, adding the  Java 8 facet first runs the addJava8Runtime.xsl and then runs the removeJava8Runtime.xsl.

**Comment by elharo** [comment]
Just a guess but maybe

```
    if (event.getType() != Type.POST_INSTALL && event.getType() != Type.POST_UNINSTALL
        && event.getType() != Type.POST_VERSION_CHANGE) {
      return;
    }
``` 

should be

```
    if (event.getType() != Type.POST_VERSION_CHANGE) {
      return;
    }
```

it's only changes we care about

**Comment by elharo** [comment]
Nope, that's not it. even with that change I still see

```
<event project="mvn" type="POST_VERSION_CHANGE">
  <facet id="java" version="1.7"/>
</event>
```

that causes the runtime removal stylesheet to run.

**Comment by elharo** [comment]
OTOH making that change does prevent the stylesheets from running on new project creation, which is something we wanted to do.

**Comment by briandealwis** [comment]
I wonder if the Facet -> Maven propagation should be handled by m2e-wtp.

**Comment by elharo** [comment]
I'm going to close this for now since it's now possible to update the Java facet to 1.8 in a Maven project. We can open new issues for the details of autoupdating `runtime` elements, pom.xml, and other things we may want to change but let's take those one at a time.
