### ISSUE TITLE
User icons have weird colors

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1942]
Possibly negatives?

![image](https://cloud.githubusercontent.com/assets/1005544/26017768/4ca834e6-3739-11e7-89cb-2f85a9f32bde.png)

**Comment by chanseokoh** [comment]
This is funny. I thought this happens only on my Linux desktop. (Doesn't happen on my Linux laptop.) On my desktop, simply accessing the following URL (my profile picture) in a Chrome browser shows a color-reverted image:

https://lh5.googleusercontent.com/-EyzM-4rNtK4/AAAAAAAAAAI/AAAAAAAAACY/GGFx5G7R94M/photo.jpg

![photo jpg 96x96 - google chrome_006](https://cloud.githubusercontent.com/assets/10523105/26018141/21ad351e-373b-11e7-8f5a-9cf5e706f71d.png)

**Comment by chanseokoh** [comment]
Search internally with, e.g., "seeing color-inverted / negative images?", and it explains what's happening. Working on fixing this.

**Comment by elharo** [comment]
Wow. That was...interesting.
