### ISSUE TITLE
Leaving Java package field empty does not work in new Maven App Engine project wizard

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1950]
Enter a group ID, and delete the auto-filled text in the _Java package_ field. It should use the default (i.e., empty) package (which is the case with the non-Maven wizard), but the Java files will be generated with the group ID in the case.

This poses another problem because some group ID is not a valid package name. For example, if you enter `com.` as a group ID (ending with a dot) and leave the package field blank, the generated project will have compilation errors.

**Comment by elharo** [comment]
The inability to support the empty package may be a function of the archetype.

**Comment by elharo** [comment]
Yes, it is. see here:

https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/blob/master/appengine-standard-archetype/src/main/resources/archetype-resources/src/main/java/HelloAppEngine.java

Notice that the package statement is always included.
