### ISSUE TITLE
Adding <runtime>java8</runtime> auto-updates Dynamic Web Module facet to 3.1, but web.xml remains 2.5

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#1951]
For native Java7 App Engine projects, adding `<runtime>java8</runtime>` in `appengine-web.xml` will auto-magically update the Dynamic Web Module facet and the `server-api` JAR to 3.1 (and the Java facet too), which is nice.

However, `web.xml` still retains 2.5:

```xml
<web-app ...
         xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_2_5.xsd"
         version="2.5">
```

**Comment by chanseokoh** [comment]
This is also the case with Maven-base projects.

**Comment by chanseokoh** [comment]
Another project with the Maven-base projects is that the `servlet-api` in `pom.xml` remains `2.5` as well.

BTW, not immediately clear if `jstl` can remain `1.2` for both native and Maven-based projects.

**Comment by chanseokoh** [comment]
Maybe the following properties need to be updated too.

```
<maven.compiler.source>1.7</maven.compiler.source>
<maven.compiler.target>1.7</maven.compiler.target>
```

**Comment by elharo** [comment]
We might want to try just not updating to 3.1 for the moment.

```
        if (hasJava8Runtime) {
          updates.add(new Action(Action.Type.VERSION_CHANGE, JavaFacet.VERSION_1_8, null));
          updates.add(new Action(Action.Type.VERSION_CHANGE, WebFacetUtils.WEB_31, null));
        } 
```

**Comment by elharo** [comment]
On further thought we probably should just let upgrading to 3.1 be a completely separate action.
