### ISSUE TITLE
SWTBot flakiness

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1958]
This code is failing a *lot* (more than half the time) on my local box which means releases take hours longer than they should. 

```
  public static IProject createNativeWebAppProject(SWTWorkbenchBot bot, String projectName,
      String location, String javaPackage) {
    bot.menu("File").menu("New").menu("Project...").click();

```

Similar problem when creating as maven project. 

The specific problem is a `WidgetNotFoundException` in the first line that clicks.

What if we caught that `WidgetNotFoundException` here, waited a few seconds, and tried again? E.g.

```
for (int i = 0; i < MAX_RETRIES; i++) {
  try {
    bot.menu("File").menu("New").menu("Project...").click();
    break;
  } catch (WidgetNotFoundException ex) {
    Thread.sleep(2000);
  }
}
```

**Comment by chanseokoh** [comment]
In any chance you are running the test inside Eclipse? In that case, you should change your Debug run configuration not to use a UI thread.

BTW, on my Linux (desktop and laptop), the integration test is pretty stable (although something could go slightly awry to make it run very slower).

**Comment by elharo** [comment]
This is pure command line, nothing else running.

**Comment by briandealwis** [comment]
Is this still happening?

**Comment by diego92sigma6** [comment]
Closing due to cleanup. Please reopen if needed.
