### ISSUE TITLE
App Engine Standard Runtime does not use an Eclipse configured JRE

### ISSUE THREAD

**Issue by Rhobal** [GoogleCloudPlatform/google-cloud-eclipse#1970]
The "App Engine Standard Runtime" has no obvious way to configure the JRE it should use to run. It doesn't use the JRE configured in Eclipse (Java > Installed JREs) nor does it seem to depend on the JAVA_HOME environment variable.

It now uses a Java 8 JRE. I have no idea where this was found, except that the java.exe is in the same path as the javaw.exe that's configured in eclipse.ini

**Comment by elharo** [comment]
We try to pick the JRE that most closely matches the server environment you'll be running in. If it's running in Java 8, most likely one or both of these is the case:

1. The Java facet on the project is set to 1.8
2. There's a `<runtime>java8</runtime>` element in appengine-web.xml.

If neither of those is true, let me know and we'll look into it further.

**Comment by patflynn** [comment]
@elharo but presumably the JRE has to be one of the Installed Eclipse JREs doesn't it?

**Comment by Rhobal** [comment]
@elharo Thanks for the quick response! Neither is the case: The Java facet is set to 1.7 and no `<runtime>` is set in app-engine.xml. I am trying this with the guestbook example app as well as with my own.

Like @patflynn, I would much prefer to set the JRE explicitly or use the eclipse default JRE instead of guessing; just like this description for Tomcat: http://www.codejava.net/ides/eclipse/how-to-change-java-runtime-environment-for-tomcat-in-eclipse

**Comment by chanseokoh** [comment]
@Rohbal What is your CT4J plugin version? If it is at or below 1.0.3 (FYI, the next 1.1.0 was just released very recently), it won't guess the best JRE. Also, is the "java.exe" it picks up i your %PATH%?

**Comment by Rhobal** [comment]
@chanseokoh CT4J = "Google Cloud Platform for Eclipse 4.5 and later"? (Why CT4J?)
Just upgraded to 1.1 and it now runs with a Java 7 JRE, thanks for the tip!

Yet I would like to change this in a feature request, that an Eclipse runtime can be chosen instead of guessing and looking for some java.exe.

**Comment by chanseokoh** [comment]
@Rhobal sorry, I meant CT4E, not CT4J. FYI, 1.1 will use the JRE configured for your project.

**Comment by Rhobal** [comment]
Thanks so much; with your help I just got another part of my app running on CT4E :-)
If it's using the JRE for my project, then I'm fine

**Comment by elharo** [comment]
The underlying issue is the JRE and classpath supplied by the App Engine deployment environment. In App Engine standard environment, this isn't very configurable by the end user. The local server is doing its best to reproduce the environment your app will run in once deployed.

With Flex, you can choose different runtimes with particular VMs. When/if we add support for flex local run, we'll have to consider this feature.
