### ISSUE TITLE
I can´t deploy projects from the last version of Eclipse Neon

### ISSUE THREAD

**Issue by ecra98** [GoogleCloudPlatform/google-cloud-eclipse#1973]
Since i update eclipse Neon, i can´t deploy the projects of the last version, and i tried to deploy in Eclipse kepler but i couldn´t sign in my google account... 

What can i do?

- Cloud Tools for Eclipse Version: 1.1.0.201705161607
- OS: Windows 10 10.0
- Java Version: 1.8.0_111

**Comment by elharo** [comment]
We need more context here. How do you know you can't deploy? What happens? What do you see? Please include any console output and screenshots.

**Comment by ecra98** [comment]
Here is the problem, so this project was created in the last version of Eclipse (Neon.2) (Image 1), but i update it to Neon.3, and the project "EjemploAPI" can´t be deployed in this version, so i created another project to show that this can be deployed (Image 2).
  
- ![captura](https://cloud.githubusercontent.com/assets/28832533/26317074/e4261460-3edb-11e7-9893-db4aef51cb47.PNG)

- ![2](https://cloud.githubusercontent.com/assets/28832533/26317274/8d1fa7d4-3edc-11e7-9084-11e4c4c2419d.PNG)

The other issue that i had, is that, when i create a Quote i can´t directly create a Google Endpoint of it (Image 2), in the last version i could create it when i clicked right button and select Google option of it (Image 1). 

- ![18679060_10213271193442641_307949620_n](https://cloud.githubusercontent.com/assets/28832533/26317791/4b699d20-3ede-11e7-937a-7aba58f4363c.jpg)

-  ![image](https://cloud.githubusercontent.com/assets/28832533/26317473/2c33c968-3edd-11e7-92f6-fc0621744b34.png)

**Comment by chanseokoh** [comment]
> Here is the problem, so this project was created in the last version of Eclipse (Neon.2) (Image 1), but i update it to Neon.3, and the project "EjemploAPI" can´t be deployed in this version, so i created another project to show that this can be deployed (Image 2).

I tried to reproduce this issue, but I couldn't. Here's what I did:
1. Installed a fresh Neon 2.
1. Installed the latest CT4E 1.1.0 from the Eclipse Marketplace. Restarted Eclipse as requested.
1. Created a new native App Engine Standard HelloWorld project.
1. Upgraded to Neon 3 by _Help_ > _Check for Updates_. Upgraded everything suggested and restarted Eclipse as required.
1. The menu for deploying on the project previously created is still enabled. I couldn't reproduce it.

@ecra98, looking at your Image1 where the App Engine Standard menu items are disabled, I think the facet settings of your project `EjemploAPI` have changed or got corrupted somehow and do not have a App Engine Standard Environment facet. Can you check your project facet settings? Select your project, right-click on it, and _Properties_ > _Project Facets_. For working projects, it should have "App Engine Java Standard Environment", "Dynamic Web Module 2.5", and "Java 1.7" like this:

![selection_014](https://cloud.githubusercontent.com/assets/10523105/26318807/67dcf202-3eea-11e7-9bd7-e9ed4f929cbc.png)

If the "App Engine Standard Environment" facet doesn't exist, you can try adding it back: right-click on your project, and _Configure_ > _Convert to App Engine Standard Project_. (Or, you can also try adding it yourself on that _Project Facets_ property page if that fails.) I recommend to do it after making a copy, if that's important.

**Comment by elharo** [comment]
GPE is a different (and deprecated) product with different functionality, not a previous version. Cloud Tools for Eclipse does not generate Cloud Endpoints client libraries.

**Comment by ecra98** [comment]
Thanks for all!! 

I follow your steps and it works, but i uploaded google App Engine to the last version, and since then i can´t import javax.jdo.annotations.*

![image](https://cloud.githubusercontent.com/assets/28832533/26385535/004baac6-4006-11e7-8078-c05fb1828b41.png)

And it doesn´t appear to import it...

**Comment by ecra98** [comment]
@elharo  ohhh hmmm well, the thing is that in the last project i create public APIs to relate with Android, but now with this new update some libraries can´t be imported, like the image i showed in the last post, and by this way i make public APIs, so do you know another form to make it with this new version?

**Comment by elharo** [comment]
The obvious answer is that you don't have the JDO jars in your classpath. I can't see everything but it looks like maybe the endpoint-libs folder needs to be added to the classpath?
