### ISSUE TITLE
Classpath entry /Users/elharo/workspaces/registrar/jetty_flex_test/lib/javax.servlet-api-3.1.0.jar will not be exported or published. Runtime ClassNotFoundExceptions may result.  

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1989]
Create a demo flex project and this warning is immediate:

Classpath entry /Users/elharo/workspaces/registrar/jetty_flex_test/lib/javax.servlet-api-3.1.0.jar will not be exported or published. Runtime ClassNotFoundExceptions may result.  

Either fix this or verify it isn't important and suppress the warning.

**Comment by chanseokoh** [comment]
Figured out how to git rid of this. We can explicitly state that the library is not to be exported/published using `org.eclipse.jst.j2ee.classpathdep.UpdateClasspathAttributeUtil.addNonDependencyAttribute()`. I have a working implementation now, but without tests. I'll come back later after I finish another issue.
