### ISSUE TITLE
Enable configuring local run GCS settings

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#1999]
In the doc, it says use dev_appserver.py with additional parameters. 

https://cloud.google.com/appengine/docs/standard/java/googlecloudstorageclient/setting-up-cloud-storage

I.e. how to set default_gcs_bucket_name from the UI

see #601 for a similar issue

**Comment by rdayal** [comment]
Status on this?

**Comment by briandealwis** [comment]
I've pushed up a branch to wire up the _Program Arguments_ section of the `JavaArgumentsTab` to the [`appengine-plugin-tools`'s `RunConfiguration`](https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/432):

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/i1999

Builds will fail until we get a snapshot up of `appengine-plugin-tools`.

**Comment by briandealwis** [comment]
I'm looking into configuring some _editor sections_ on the server definition editor (double-click on the server definition in the _Servers_ view).  We can wire up the server port, and we could wire up the choice of using devappserver 1 or 2 too.

**Comment by briandealwis** [comment]
Closing this as we've wired up the VM and Program arguments tabs.  Nice UI should be done as #1404 or other issues.
