### ISSUE TITLE
A project that cannot run a dataflow pipeline should be checked before attempting execution

### ISSUE THREAD

**Issue by tgroh** [GoogleCloudPlatform/google-cloud-eclipse#2001]
Doing so gives a more immediate error and reaction, and can make it obvious why the Pipeline cannot be run.

**Comment by tgroh** [comment]
Specifically, if the project is insufficiently configured to execute a Dataflow Pipeline, missing components of the configuration can be signaled within the eclipse environment rather than via the console.

This can include not having billing enabled, and not having the Dataflow API enabled.

For reference, a list of required APIs are located [here](https://cloud.google.com/dataflow/docs/quickstarts/quickstart-java-eclipse) (currently
Google Dataflow, Compute Engine, Stackdriver Logging, Google Cloud Storage, Google Cloud Storage JSON, BigQuery, Google Cloud Pub/Sub, and Google Cloud Datastore APIs). I believe we should be able to use the service management APIs for at least some of these checks.

**Comment by chanseokoh** [comment]
Another launch config validation we can consider: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2141#issuecomment-316529402

For Dataflow v2.x (not v1.x), the staging location cannot be a bucket on the root (i.e., should be at least 2 levels of depth such as `gs://level-1/level-2`).
