### ISSUE TITLE
just upgraded a project to Cloud Tools from Plugin lots of bad imports

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2008]
- Cloud Tools for Eclipse Version: 1.1.0.201705161607
- OS: Windows 10 10.0
- Java Version: 1.8.0_121

After converting my project I have tons and tons of errors. For example, imports like this are broken:
import com.google.appengine.api.datastore.DatastoreService;

What libraries are missing? How do I add them?

**Comment by elharo** [comment]
Is it a maven project or a non-Maven project?

**Comment by Rob46** [comment]
I choose "Convert to App Engine Standard Project" from the menu.
What is the difference?

**Comment by Rob46** [comment]
I assume this is non-Maven, correct?

**Comment by chanseokoh** [comment]
Does your project has `pom.xml`, and if so, do you see the _Maven_ menu item when you right-click on your project? If yes and yes, then your project is configured to use Maven.

Nonetheless, I hope adding App Engine API will take care of the most (if not all) missing import errors. Right-click on you project > _Build Path_ > _Add Libraries_ > _App Engine Libraries_ > check _App Engine API_ > _Finish_. (If you don't see the _Add Libraries_ menu item, switch to _Java Perspective_ first.

**Comment by Rob46** [comment]
I did that and it helped a lot, but still other issues to resolve.

in my web.xml it is highlighting this following as a problem:

	<servlet>
		<servlet-name>SystemServiceServlet</servlet-name>
		<servlet-class>com.google.api.server.spi.SystemServiceServlet</servlet-class>
		<init-param>
			<param-name>services</param-name>
			<param-value />
		</init-param>
	</servlet>
	<servlet-mapping>
		<servlet-name>SystemServiceServlet</servlet-name>
		<url-pattern>/_ah/spi/*</url-pattern>
	</servlet-mapping>

Its the com.google.api.server.spi.SystemServiceServlet reference that is doesn't like.

**Comment by Rob46** [comment]
And it also doesn't like the src/META-INF/jdoconfig.xml 
Is this file needed?
Is there a more correct one to use?

Description	Resource	Path	Location	Type
cvc-elt.1: Cannot find the declaration of element 'jdoconfig'.	jdoconfig.xml	/ParaSQL/src/META-INF	line 4	XML Problem


Description	Resource	Path	Location	Type
Referenced file contains errors (http://java.sun.com/xml/ns/jdo/jdoconfig).  For more information, right click on the message in the Problems View and select "Show Details..."	jdoconfig.xml	/ParaSQL/src/META-INF	line 1	XML Problem

**Comment by elharo** [comment]
`SystemServiceServlet` is from Cloud Endpoints 1.0. Until you migrate to Endpoints Framework, you'll need to manually add the relevant jars to your build path. 

https://cloud.google.com/endpoints/docs/frameworks/legacy/v1/java/migrating

**Comment by elharo** [comment]
The jdoconfig schema issue is Eclipse complaining. IMHO, this is a bug in Eclipse; but either way CT4E is not involved here.

**Comment by Rob46** [comment]
We don't use Cloud Endpoints directly in any of our code. Is it needed by any of the services like cron that does Datastore backups?

**Comment by elharo** [comment]
If you don't use endpoints, just remove those entries from web.xml.
