### ISSUE TITLE
Maven-based project wizard broken due to recent updates to archetypes

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2011]
Today's release of the updated archetypes (https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/pull/63) completely breaks our Maven-based project wizard.

You may not be able to reproduce this until you delete locally cached archetypes. Delete them first:

`rm -rf ~/.m2/repository/com/google/appengine/archetypes/`

![selection_001](https://cloud.githubusercontent.com/assets/10523105/26810595/9df8502e-4a3a-11e7-805b-2603ac50a47e.png)

**Comment by chanseokoh** [comment]
The reason seems that the new properties `java8`, `CloudSDK_Tooling`, and `service` are required properties: https://github.com/GoogleCloudPlatform/appengine-maven-archetypes-java/pull/63/files#diff-8491f269f1ba3798dd02cd113d5a7d2fR42

Not sure if releasing our plugin with a fix will be faster than releasing fixed archetypes.

**Comment by chanseokoh** [comment]
This will also break any future Kokoro builds, since it doesn't cache archetypes but always downloads them.

**Comment by elharo** [comment]
I wonder if we can specify a version of the archetypes we download? 

Depending on archetypes was a mistake. That said, we can almost certainly push an update of CT4E faster than the archetypes can be changed.

**Comment by chanseokoh** [comment]
Pinning down specific versions sounds a good idea. Propably easy to do so.

**Comment by chanseokoh** [comment]
Will work on this.
