### ISSUE TITLE
Use latest appengine-maven-plugin in generated pom.xml

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2014]
Currently the version is fixed to be "1.3.1" in the template `pom.xml.standard.ftl` and `pom.xml.flex.ftl`. We can check the latest version with something like this:

```java
    String latestVersion = MavenUtils.resolveLatestReleasedArtifactVersion(
        monitor,
        "com.google.cloud.tools", //$NON-NLS-1$
        "appengine-maven-plugin", //$NON-NLS-1$
        "maven-plugin", //$NON-NLS-1$
        DEFAULT_VERSION);
```

**Comment by elharo** [comment]
That code is returning 1.3.0 ATM. I wonder why?

```
org.junit.ComparisonFailure: expected:<1.3.[1]> but was:<1.3.[0]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at 
```

**Comment by elharo** [comment]
I'm surprised it's not returning

com.google.cloud.tools : appengine-maven-plugin : 99.99.99

**Comment by briandealwis** [comment]
Our `MavenUtils` still uses the m2e-configured maven session and so will use the m2e global-update-policy (#830).  You mentioned #1547 that Dataflow had an alternative lookup mechanism, which I assume used Aether directly?

**Comment by elharo** [comment]
Once https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2173 lands we can use that.

**Comment by elharo** [comment]
ArtifactRetriever can now be used for this.
