### ISSUE TITLE
GpeMigrator to remove GPE classpath entries

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2018]
From #2015:

Our `GpeMigrator` does remove GPE classpath entries (see `GpeMigrator.removeGpeClasspathEntries()`), but I think we missed the following container:

Classpath Dependency Validator Message:
Description	Resource	Path	Location	Type
Classpath entry com.google.gdt.eclipse.managedapis.MANAGED_API_CONTAINER/compute-v1r147lv1.21.0 will not be exported or published. Runtime ClassNotFoundExceptions may result. ParaSQL P/ParaSQL	Classpath Dependency Validator Message
Classpath entry com.google.gdt.eclipse.managedapis.MANAGED_API_CONTAINER/sqladmin-v1beta4r39lv1.21.0 will not be exported or published. Runtime ClassNotFoundExceptions may result. ParaSQL	P/ParaSQL	Classpath Dependency Validator Message
Classpath entry com.google.gdt.eclipse.managedapis.MANAGED_API_CONTAINER/storage-v1r105lv1.21.0 will not be exported or published. Runtime ClassNotFoundExceptions may result. ParaSQL P/ParaSQL	Classpath Dependency Validator Message

I'm guessing we want to remove this container, right?

**Comment by elharo** [comment]
sounds right

**Comment by briandealwis** [comment]
And I noticed `demos/helloeservers` includes a `com.google.gwt.eclipse.core.GWT_CONTAINER` container.

**Comment by briandealwis** [comment]
We also need to ensure we have 2 WTP/JST containers to pull in libraries from `WEB-INF/lib` and `WEB-INF/classes`: `org.eclipse.jst.j2ee.internal.web.container` and `org.eclipse.jst.j2ee.internal.module.container`.

A new WTP Dynamic Web Project with the App Engine Standard Runtime has the following `.classpath`:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
        <classpathentry kind="src" path="src"/>
        <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8">
                <attributes>
                        <attribute name="owner.project.facets" value="java"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="con" path="org.eclipse.jst.server.core.container/com.google.cloud.tools.eclipse.appengine.standard.runtimeClasspathProvider/App Engine Standard Runtime">
                <attributes>
                        <attribute name="owner.project.facets" value="jst.web"/>
                </attributes>
        </classpathentry>
        <classpathentry kind="con" path="org.eclipse.jst.j2ee.internal.web.container"/>
        <classpathentry kind="con" path="org.eclipse.jst.j2ee.internal.module.container"/>
        <classpathentry kind="output" path="build/classes"/>
</classpath>
```
