### ISSUE TITLE
warning when deploying to GAE Std

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2022]
- Cloud Tools for Eclipse Version: 1.1.0.201705161607
- OS: Windows 10 10.0
- Java Version: 1.8.0_121

From the console in Eclipse:

WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.

Don't know if it matters... just providing feedback.

**Comment by chanseokoh** [comment]
Interesting. Does this always happen whenever you deploy? Could you provide an entire console log to get some idea at which point this happens by whom?

**Comment by elharo** [comment]
https://groups.google.com/forum/#!topic/google-web-toolkit/LQfsBSwD_ug

**Comment by elharo** [comment]
I suspect this is a known issue in java.util.prefs.WindowsPreferences. It tries to save preferences for the machine rather than the current user.

**Comment by Rob46** [comment]
my log from windows 10 with jre8

----- copied from log below -------------------------------
Jun 08, 2017 11:48:00 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Reading application configuration data...
Jun 08, 2017 11:48:00 AM com.google.apphosting.utils.config.IndexesXmlReader readConfigXml
INFO: Successfully processed C:/Users/rober/Software Development/Eclipse Workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1496936872285/staging-work\WEB-INF/datastore-indexes.xml


Beginning interaction for module default...
0% Scanning for jsp files.
0% Compiling jsp files.
Jun 08, 2017 11:48:06 AM org.apache.jasper.JspC processFile
INFO: Built File: \overview.jsp
Jun 08, 2017 11:48:06 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\about-us.jsp
Jun 08, 2017 11:48:06 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\api.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\best-practices.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\caspio-alternative.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\change-log.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\confirm-accept-invite.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\create-account-form.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\create-account.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\dedicated-server.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\dom-api.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\error.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\examples.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\features.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\integration.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\license.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\ms-access-alternative.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\no-code-application-development.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\no-code-applications.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\no-code-database-apps.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\no-code-database.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\pricing.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\privacy.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\quickbase-alternative.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\rest-api.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\sla.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\support-forum.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\support.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\thank-you.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\videos.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\zoho-alternative.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\core-message.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\core-top-right.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\create-trial-account-box.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\footer.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\header.jsp
Jun 08, 2017 11:48:07 AM org.apache.jasper.JspC processFile
INFO: Built File: \about\include\request-form.jsp
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Success.
Temporary staging for module default directory left in C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1496936872285\staging
You are about to deploy the following services:
 - parasql-app/default/55 (from [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1496936872285\staging\app.yaml])
     Deploying to URL: [https://55-dot-parasql-app.appspot.com]
     (add --promote if you also want to make this service available from
     [https://parasql-app.appspot.com])

You are about to update the following configurations:
 - parasql-app/cron  (from [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1496936872285\staging\WEB-INF\appengine-generated\cron.yaml])
 - parasql-app/index  (from [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1496936872285\staging\WEB-INF\appengine-generated\index.yaml])
 - parasql-app/queue  (from [C:\Users\rober\Software Development\Eclipse Workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1496936872285\staging\WEB-INF\appengine-generated\queue.yaml])
Beginning deployment of service [default]...
Some files were skipped. Pass `--verbosity=info` to see which ones.
You may also view the gcloud log file, found at
[C:\Users\rober\AppData\Roaming\gcloud\logs\2017.06.08\11.48.13.870000.log].
#============================================================#
#= Uploading 28 files to Google Cloud Storage               =#
#============================================================#
File upload done.
Updating service [default]...
..................done.
Deployed service [default] to [https://55-dot-parasql-app.appspot.com]
Updating config [cron]...
.done.
Updating config [index]...
done.
Updating config [queue]...
done.

Cron jobs have been updated.

Task queues have been updated.

Visit the Cloud Platform Console Task Queues page to view your queues and cron jobs.

Indexes are being rebuilt. This may take a moment.

You can stream logs from the command line by running:
  $ gcloud app logs tail -s default

To view your application in the web browser run:
  $ gcloud app browse
