### ISSUE TITLE
Link in deploy dialog to create new GCP project doesn't seem to work

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2023]
Not sure if we had a similar issue here or internally.

![selection_027](https://user-images.githubusercontent.com/10523105/26901131-acb55e68-4ba2-11e7-811e-f1925fe05b5d.png)

No matter which account is selected, I am presented with the following screen on the Developer Console:

![selection_028](https://user-images.githubusercontent.com/10523105/26901241-16405342-4ba3-11e7-9e8c-deb17d853041.png)

**Comment by elharo** [comment]
see b/36122790

**Comment by chanseokoh** [comment]
We need to change the URL to

`https://console.cloud.google.com/projectcreate?authuser=<URL encoded email>`

**Comment by briandealwis** [comment]
The dialog contents have been slightly changed on the Developer Console, though it's still confusing.

![screen shot 2017-08-02 at 2 56 41 pm](https://user-images.githubusercontent.com/202851/28889706-d7cb4d30-7792-11e7-8db6-f51e2a767f25.PNG)

**Comment by chanseokoh** [comment]
The good thing about the current URL is that the "Create" button takes to the App Engine application creation screen after a project is created.

So, the current URL actually works, but it's a bit confusing that the link to create a new project takes users to the App Engine Dashboard page and that the message there is primarily "To view this page, select a project." Users then need to push the "Create" button.

Now I think we may be able to use the link of the "Create" button itself:

https://pantheon.corp.google.com/projectcreate?previousPage=%2Fprojectselector%2Fappengine%2Fcreate%3Flang%3Djava%26authuser%3D...&authuser=...

**Comment by chanseokoh** [comment]
So, basically, you just provide an additional parameter (`previousPage`) to specify where you want to be redirected after project creation:

`https://console.cloud.google.com/projectcreate?authuser=<URL-encoded email>&previousPage=<App Engine application creation screen>`
