### ISSUE TITLE
Invalid runtime 'java8' specified on converted project

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2030]
ERROR: (gcloud.app.deploy) Error Response: [400] Invalid runtime 'java8' specified. Accepted runtimes are: [go, java, java7, php, php55, python, python27]

![image](https://user-images.githubusercontent.com/1005544/26940465-c15a0b24-4c48-11e7-8a49-cf38494251ff.png)

**Comment by elharo** [comment]
Possible cause: Java 8 only in installed JREs and CT4E "helpfully" adds `<runtime>java8</runtime>` to appengine-web.xml

**Comment by elharo** [comment]
Reproduced this. Definitely happens on project conversion.

**Comment by elharo** [comment]
It's not, but that's not the issue. This was supposed to be a Java 7 project. The bug is in our code that is being overly eager to add `<runtime>java8</runtime` to the appengine-web.xml.

**Comment by briandealwis** [comment]
I think this is a user configuration error: I suspect your project had a JavaSE-1.8 execution environment. I verified that converting a JavaSE-1.7 project preserves the Java 1.7 facet and the `appengine-web.xml` is untouched.

<img width="738" alt="java-build-path" src="https://user-images.githubusercontent.com/202851/26976485-f52c11d2-4cf1-11e7-94bc-dc2389e2d119.PNG">

If the user's project is configured with JavaSE-1.8, then they can already use Java 8'isms, and so we should set the `<runtime>`.

Perhaps more to the point, if I have an existing 1.8 servlet project that I'm aiming to port to App Engine, I may get strange results trying to deploy the project.

**Comment by elharo** [comment]
That is indeed what happened but that does not mean this isn't a bug. Java 7 is the expected default for App Engine. Unless the user makes a conscious decision to convert it to Java 8 we should not convert it for them. There is no reason for a user to expect that convertin a project from GPE will aklso make it a Java 8 project.

**Comment by briandealwis** [comment]
We'll have to back this out once Java 8 goes GA.  My preference is to prompt the user to say something along the line of:
> Your project is Java 8, but Java 8 support for App Engine is not yet GA. Switch to Java 7?

**Comment by elharo** [comment]
I'm not sure we will. At some point Java 8 becomes the default regardless of runtime element. 

We should not change the user's project without their explicit request. If they haven't taken a deliberate action to ask for Java 8 we shouldn't force it on them.

**Comment by chanseokoh** [comment]
Both of the views of you guys make sense to me.

When importing a GPE project into Eclipse whose sole configured JRE is Java 8, Eclipse seems to set the JRE of the project to Java 8. So, in some sense, the project in this case is not configured correctly (semantically) in that the project cannot deployed to App Engine. To fix this, a user needs to set up Java 7 in Eclipse and set the project JRE to Java 7. If the user converts the project after that, there won't be any issue.

However, from the perspective of a GPE migration story, it could be viewed as that our conversion may silently modify users' code, which will have a big impact. For example, some users may not be conscious of their Eclipse having only Java 8, and users who just simply follow the migration doc will end up having `<runtime>java8</runtime>` in `appengine-web.xml`. To users who don't know this has happened, it could contribute to bad user experience later.

**Comment by patflynn** [comment]
+1. the project source shouldn't be affected by the migration.   Ideally
the user could have any JRE > Java 7 configured and we would just set the
language level to 7 or 8 depending on the value of runtime in
appengine-web.xml. That's what we do for IJ.

**Comment by briandealwis** [comment]
Fixed by #2079 as `appengine-web.xml` now used as source of truth.
