### ISSUE TITLE
Dataflow Icon should have few pixels of white space on right

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2031]
Icon should have few pixels of white space on right

![image](https://user-images.githubusercontent.com/1005544/26941666-44cb7a98-4c4d-11e7-9c77-48375bd0aac2.png)

compare

![image](https://user-images.githubusercontent.com/1005544/26940314-3c596b22-4c48-11e7-912f-a01e28522c0b.png)

**Comment by diegomarquezp** [comment]
Closing as not planned.
