### ISSUE TITLE
NPE when deploying App Engine flex project not configured with Dynamic Web Module facet

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2034]
Currently, you can add the AE flex facet to a plain Java project without adding the Dynamic Web Module facet. This seems to cause an NPE when trying to deploy such a project.

This is also distantly related to https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2019#issuecomment-306873454.

**Comment by chanseokoh** [comment]
However, it is conceivably and conceptually possible that eventually we may not need the Dynamic Web Module facet for flex, as a custom flex project can just be a container with anything.

**Comment by elharo** [comment]
Does it make sense to have different facets for flex java8 runtime and flx custom runtime?

**Comment by elharo** [comment]
```
java.lang.NullPointerException
	at org.eclipse.wst.web.internal.deployables.FlatComponentDeployable.members(FlatComponentDeployable.java:223)
	at org.eclipse.jst.j2ee.internal.deployables.J2EEFlexProjDeployable.members(J2EEFlexProjDeployable.java:267)
	at com.google.cloud.tools.eclipse.appengine.deploy.WarPublisher.publish(WarPublisher.java:69)
	at com.google.cloud.tools.eclipse.appengine.deploy.WarPublisher.publishWar(WarPublisher.java:47)
	at com.google.cloud.tools.eclipse.appengine.deploy.flex.FlexStagingDelegate.stage(FlexStagingDelegate.java:55)
	at com.google.cloud.tools.eclipse.appengine.deploy.DeployJob.stageProject(DeployJob.java:180)
	at com.google.cloud.tools.eclipse.appengine.deploy.DeployJob.runInWorkspace(DeployJob.java:136)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
```

**Comment by briandealwis** [comment]
> @elharo: Does it make sense to have different facets for flex java8 runtime and flx custom runtime?

I think it does.  The `FlexStagingDelegate` at least needs to check if the project has a `jst.web` facet.  

I'm not sure what we do for, say, SpringBoot, which doesn't use a WAR.  For example, [the HelloWorld-SpringBoot](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/helloworld-springboot) produces a runnable jar.  Perhaps in this case we check if it's a Maven project and do `mvn appengine:deploy` (or `mvn com.google.cloud.tools:appengine-maven-plugin:1.3.1:deploy`)?

**Comment by etanshaul** [comment]
I don't have all the eclipse context here but just pointing out that in intellij, the flex facet gets added independently of the web facet (unlike for standard)

**Comment by chanseokoh** [comment]
Thinking about it, the fact that the Dynamic Web Module facet is currently not a requirement of App Engine Flex facet is correct even at this point where we don't support the custom runtime; users can have `runtime: java` in their `app.yaml` and still deploy a runnable JAR.

That said, I am leaning toward to fix `FlexStagingDelegate` so that it calls `publishWar` only when the project has the Dynamic Web Module facet. Otherwise, it's a runnable JAR, and we just need to locate the path of the JAR in the output directory and pass it to `CloudSdkStagingHelper.stageFlexible()`.

**Comment by chanseokoh** [comment]
I have updated the title to better reflect the discussions above.

**Comment by briandealwis** [comment]
> @chanseokoh: That said, I am leaning toward to fixing FlexStagingDelegate so that it calls publishWar() only when the project has the Dynamic Web Module facet. Otherwise, it's a runnable JAR, and we just need to locate the path of the JAR in the output directory and pass it to CloudSdkStagingHelper.stageFlexible().

:+1:

**Comment by chanseokoh** [comment]
As we discussed, we need to explorer how we would handle non-WTP flex projects, and for now, let's make it a requirement to have WTP.
