### ISSUE TITLE
It is possible to install Dynamic Web Module facet 3.0 with Java 7 and App Engine standard facet

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2044]
Steps to reproduce:

1. Create a plain Java project with JRE 1.7.
2. Go to the _Project Facets_ project properties page. Enable facets.
3. Check App Engine Standard facet with Dynamic Web Module facet 3.0. Click _Apply_.

**Comment by chanseokoh** [comment]
Related: #2034.

**Comment by chanseokoh** [comment]
I will put `@Ignore` to the tests mentioned in #2049. The annotations must be deleted when this is fixed.

**Comment by briandealwis** [comment]
Fixed by #2079.
