### ISSUE TITLE
Project broken after upgrading eclipse

### ISSUE THREAD

**Issue by georges-stephan** [GoogleCloudPlatform/google-cloud-eclipse#2051]
- Cloud Tools for Eclipse Version: 1.1.0.201705161607
- OS: Mac OS X 10.12.5
- Java Version: 1.8.0_121

**Comment by georges-stephan** [comment]
In the app engine-web.xml , the "application" xml now shows the warning "Project ID should be specified at deploy time" and the "version" tag "version should be specified at run time".

**Comment by elharo** [comment]
This is intentional. The current App Engine recommendation is not to put project ID or version in appengine-web.xml but supply it to the tool at deploy time so the code is decoupled from which project you deploy it to. Hence the warnings.
