### ISSUE TITLE
Add instructions to the new issue template to check for new plugin version

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2057]
Consider implementing GPE-like notifications when an update is available.  Such notifications would be useful especially in light of issues like #2055.

**Comment by elharo** [comment]
Doesn't Eclips already do this subject to user preferences?

--
Elliotte Rusty Harold
on a mobile phone so please excuse weird autocorrects

**Comment by chanseokoh** [comment]
True, but users won't see notifications per their preferences. @briandealwis is talking about the GPE-like notifications that will always pop up whenever there is a new release.

**Comment by patflynn** [comment]
Shouldn't we respect the user's notification preferences?

**Comment by briandealwis** [comment]
I'm of mixed opinions on this.  We also waste our users' time by hitting and diagnosing problems that we've already fixed.

But maybe the better solution is to see about convincing the Eclipse communities to enable the update notifications by default.

**Comment by patflynn** [comment]
how about adding instructions to make sure they're up to date to the new
issue template?

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by elharo** [comment]
I really think that if the user has asked not to be notified we shouldn't go around the end and introduce yet another notification mechanism that doesn't respect their preferences. 

https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.user%2Freference%2Fref-p2-autoupdate.htm

**Comment by elharo** [comment]
I like Patrick's suggestion. Let's do that.
