### ISSUE TITLE
Investigate if we need to restrict adding com.google.cloud API libraries

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2067]
Currently, we don't impose any restriction on adding (some or all of?) these libraries (through _Build Path_ > _Add Libraries_ > _Google API Libraries_). Users can add them to a plain Java project, for example. However, [it has been suggested that the language level of these libraries might start at Java 8](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2065#issuecomment-308850752). We may need to restrict adding the libraries if the conditions are not met, or alternatively, show errors that they won't work until the conditions are met.

**Comment by patflynn** [comment]
What's more important is that these libraries do not work on the App Engine
standard Java 7 runtime. We should never suggest to the user to add them.
