### ISSUE TITLE
static files - like compiled.min.js - not showing after deploy

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2068]
- Cloud Tools for Eclipse Version: 1.2.0.201706082053
- OS: Windows 10 10.0
- Java Version: 1.8.0_121

It seems that when deploying static files - like myapp.min.js which is a new complied file with each deployment - they are not seen immediately by the web browser, even after clearing the cache. It seems GAE std has changed is caching policy?

**Comment by briandealwis** [comment]
Could you provide some more detail?  Is this in the development server (devappserver?  Or on the public server?  If the latter, have you seen the following section of the App Engine Java docs:

   https://cloud.google.com/appengine/docs/standard/java/config/appref#static_cache_expiration

There are also [some differences whether the files are being served through the .appspot.com or a custom domain](https://stackoverflow.com/questions/11949367/any-way-to-force-reset-of-all-cached-static-files-on-appengine).

**Comment by Rob46** [comment]
Public server. Strange, I have not run into this before. I think I know why too... if I do a very short test and find a problem and then do a very fast deploy I'm likely within that default 10 min cache expiration. I'm seldom that fast either on testing or fixing :-) so normally not something I hit. 

Sorry to have wasted your time on this.
