### ISSUE TITLE
"--host" option doesn't seem to be working

### ISSUE THREAD

**Issue by itip** [GoogleCloudPlatform/google-cloud-eclipse#2088]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_.)

- Cloud Tools for Eclipse version: 1.2.0.201706082053
- OS: MacOS (10.12.5)
- Java version: 1.7.0_80

**What did you do?**
Used "--host=0.0.0.0" as a "program  argument" in the debug configuration in Eclipse.

**What did you expect to see?**
This should allow the app to be accessed remotely (i.e. not using localhost or 127.0.0.1). However, it seems it is ignored. I've also tried --address but that doesn't seem to work either.

**What did you see instead?**
The app can only be accessed over 127.0.0.1 or localhost, regardless of what is entered. It's possible to change the IP address if you run the app using the Maven command but I'd prefer to use Eclipse as it's much easier to debug the app. 

![screen shot 2017-06-28 at 16 00 34](https://user-images.githubusercontent.com/974575/27644285-0105d29e-5c1b-11e7-9446-105e55ad9043.png)

**Comment by chanseokoh** [comment]
Hi @itip,

We've implemented a different workflow for users who want to use an arbitrary host and a port. Right-click on your project > _Run As_ (or _Debug As_) > _Run on Server_. In the dialog below, select _Manually define a new server_, select "App Engine Standard" as the server type, and use `0.0.0.0` in the _Server's host name:_ field.

![run on server _003](https://user-images.githubusercontent.com/10523105/27645276-ad737e50-5bf3-11e7-8f5c-a9b904d66467.png)

**Comment by itip** [comment]
Hi @chanseokoh,

Ah, yes, that makes sense. I already had a server so I opened that up and set the host there. I can now access using my computer's IP address.

Thanks for your help! I'll go ahead and close this issue.

![screen shot 2017-06-28 at 16 55 52](https://user-images.githubusercontent.com/974575/27647205-b0c7ca96-5c22-11e7-923d-427e5b32c728.png)


 
Ian

**Comment by daffodilistic** [comment]
Been having an issue looking for the appropriate documentation for a few weeks, and finally found it here. Thanks @chanseokoh !

**Comment by elharo** [comment]
I wonder if we should:

A) Add this to the docs
B) Recognize --host= in the arguments tab? or put up an error dialog if it conflicts with the server?

**Comment by briandealwis** [comment]
It would be nice to support the Program arguments to allow specifying new arguments that we don't yet support.  That would require enhancing `appengine-plugins-core` to support adding arbitrary commands though.

Alternatively we could create our own _Arguments_ tab, and remove the _Program arguments_ and the _Working directory_ sections entirely.
