### ISSUE TITLE
Google Cloud library definitions need updating for 0.20.1-alpha (1.2.1)

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2097]
Some of the fundamental classes in the Google Cloud Core libraries (`google-cloud-core-1.0.0.jar`) use classes from `org.threeten.bp` (a backport of the Java 8 Date and Time library from JSR-310).  Specifically, `com.google.cloud.ServiceOptions` uses `org.threeten.bp.Duration`.

**Comment by briandealwis** [comment]
It turns out we're quite a bit behind in our library definitions.  `google-cloud-core` and `-storage` are now at 1.2.1.

**Comment by briandealwis** [comment]
The `google-cloud` libraries inherit a bunch of dependencies; it's really quite painful to work out.  We should either auto-gen these definitions or auto-slurp them from the corresponding `.pom`s.

**Comment by elharo** [comment]
Agreed. Do you happen to know a convenient library for pulling the transitive dependency tree out of Maven?

**Comment by briandealwis** [comment]
I see two possible avenues within m2e.

The `pom.xml` editor has a _Dependency Hierarchy_ page which lists the transitive dependencies of the POM.  This content is loaded in [`DependencyTreePage#loadData()`](http://git.eclipse.org/c/m2e/m2e-core.git/tree/org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/pom/DependencyTreePage.java?h=master#n216), which uses [`MavenPomEditor#readDependencyTree()`](http://git.eclipse.org/c/m2e/m2e-core.git/tree/org.eclipse.m2e.editor/src/org/eclipse/m2e/editor/pom/MavenPomEditor.java?h=master#n681).  It pulls content from m2e and aether.

The other codepath is m2e's [`DefaultMavenDependencyResolver#resolveProjectDependencies()`](http://git.eclipse.org/c/m2e/m2e-core.git/tree/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/project/registry/DefaultMavenDependencyResolver.java?h=master#n53), which is used by the _Maven > Update Projects…_ option.

**Comment by elharo** [comment]
Both of those are based on Aether, which is archived. I wonder what m2e plans to do about that?
