### ISSUE TITLE
Debug mode JSP hot reload is dead slow

### ISSUE THREAD

**Issue by theomails** [GoogleCloudPlatform/google-cloud-eclipse#2100]
Im running my app in the Eclipse environment, running with Google Cloud tools, "Debug on app engine". JSP hot reload is dead slow... it takes several minutes for a one word changes that I do in the JSP to show up in my chrome browser. 

Is there a configuration or property somewhere to fix this? Can you give some way to configure this at least for the dev environment. Maybe something like a system property?
 
I'm not sure where the problem is. I'm editing the file within Eclipse JSP editor.. so Eclipse detects the change. Either the maven package is happening only once in several minutes, or the jettey server is not hot loading frequently.

- Cloud Tools for Eclipse Version: 1.2.0.201706082053
- OS: Mac OS X 10.12.5
- Java Version: 1.8.0_102

**Comment by briandealwis** [comment]
Our server definition follows the WTP default to wait 15 seconds before publishing changed files to the server.  You can force the server to publish any changes manually, or change this publishing interval to a lower value; setting it to 0 will cause all changes to be published immediately.

Open the _Servers_ view and you should see your _App Engine Standard_ entry.  After you make a change, your server entry will show _Republish_ to indicate that there are changes pending to be publishedto the server.  You can right-click on the server and select _Publish_ to publish these pending right away.

![screen shot 2017-07-04 at 2 37 27 pm](https://user-images.githubusercontent.com/202851/27840379-6535f4ce-60c6-11e7-8a4a-e5a114d5287b.PNG)

To change the publishing interval, double-click on server entry to open the server-definition editor.  Expand the _Publishing_ section in the upper right and change the _Publishing interval_ to 0.  Changes should then be immediately pushed to the server.

![screen shot 2017-07-04 at 2 38 27 pm](https://user-images.githubusercontent.com/202851/27840389-7fc20ec2-60c6-11e7-85e7-076d5e182899.PNG)

I'll close this issue as that should solve your problem, but please re-open if it does not.

**Comment by elharo** [comment]
I've created an FAQ label for issues like this we should consider adding to the formal docs.

**Comment by theomails** [comment]
Thanks for the suggestion! It works great now.

Regarding: "To change the publishing interval, double-click on server entry to open the server-definition editor."...

Surprisingly, there is no right-click menu item to do the same action as that double click! That seems like an un-eclipsey way of doing it. Feels almost like a "hidden setting" for advanced users.
