### ISSUE TITLE
Add "App Engine Java Flexible Environment (JAR)" facet

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2104]
With a version "1", which is consistent with the existing WAR facet. The facet should conflict with any other App Engine facets.

Also we need to rename the existing “App Engine Java Flexible Environment” facet to “App Engine Java Flexible Environment (WAR)”.

**Comment by etanshaul** [comment]
I believe "flexible environment" and "standard environment" should not be capitalized. If its just an internal key then its not a big deal.

**Comment by chanseokoh** [comment]
I think we allowed capitalization as facet names. For example, people use "Utility Module" or "Cloud Foundry Standalone Application" for facet names. But I think it's perfectly OK to make them not capitalized.

**Comment by chanseokoh** [comment]
Fixed by #2367.
