### ISSUE TITLE
Changes to Java files are not published to local devserver (devappserver1)

### ISSUE THREAD

**Issue by jonathanlal** [GoogleCloudPlatform/google-cloud-eclipse#2111]
- Cloud Tools for Eclipse Version: 1.2.0.201706082053
- OS: Windows 10 10.0
- Java Version: 1.8.0_73

Last update made it so that publishing locally doesn't update all the changed code. 
Working on a web application and if i make changes to the front end, so the basic JSP files, HTML/CSS, all that updates fine on publish locally.
But when trying to publish edited code in the backend..(Servlets,Models,Database), it doesn't work. Only when i restart the server do the changes register (when editing backend code).. 

Before the update, everything was working smoothly and didn't have this problem. Looked into the settings but didn't see anything that could be causing this to happen. Forgive me if i'm asking a noob question and forgot to flip a switch somewhere but pretty sure this is a bug.

**Comment by briandealwis** [comment]
To be clear, when you mean "publish edited code in the backend", do you mean `.java` files?  If so, this is the same as #1428.

**Comment by chanseokoh** [comment]
That said, if you run the local server in the _Debug_ mode (not in the _Run_ mode), you don't have to restart the server when you edit `.java` files, although it takes quite some for the server to pick up the edits (5~10 seconds).

**Comment by jonathanlal** [comment]
Debug mode solves the problem. Thank you so much! Should i delete this post then if the issue was already raised elsewhere? Can i ask why this feature was turned off for run mode? @briandealwis @chanseokoh

**Comment by briandealwis** [comment]
It was initially an oversight (I personally run everything in debug mode since I use exception breakpoints to trap common errors like `NPE`s, `ClassCastException`, etc.).  But we've since switched to a different variant of the App Engine development server (called devappserver1) which doesn't support automatic restart on file changes.

**Comment by briandealwis** [comment]
@ludoch on #2125 pointed to [gradle-appengine-plugin](https://github.com/GoogleCloudPlatform/gradle-appengine-plugin/issues/97) for some additional system properties supported by devappserver1:
  - `appengine.fullscan.seconds`
  - `datastore.backing_store`: path to the .bin file

**Comment by chanseokoh** [comment]
We should not forget upgrading appengine-plugins-core to really close this.

**Comment by briandealwis** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/435

**Comment by chanseokoh** [comment]
FTR, in order for this work with the _run_ mode, one still needs to change the WTP's publishing interval too: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2100#issuecomment-312934552
