### ISSUE TITLE
Unable to stage app: Failed to compile the generated JSP files.

### ISSUE THREAD

**Issue by tweverett** [GoogleCloudPlatform/google-cloud-eclipse#2128]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_.)

- Cloud Tools for Eclipse version:  1.2.0.201706082053
- OS: Windows 7
- Java version: 1.7.0_71

**What did you do?**
Attempted to Deploy to App Engine Standard using the toolbar dropdown.

**What did you expect to see?**
Successful deployment

**What did you see instead?**
...
C:\Users\Todd\AppData\Local\Temp\1499710922414-0\org\apache\jsp\login_jsp.java:14: error: package com.google.appengine.api.urlfetch does not exist
import com.google.appengine.api.urlfetch.*;
^
C:\Users\Todd\AppData\Local\Temp\1499710922414-0\org\apache\jsp\login_jsp.java:15: error: package com.google.appengine.api.utils does not exist
import com.google.appengine.api.utils.SystemProperty;

6 errors
1 warning
Unable to stage app: Failed to compile the generated JSP java files.
Please see the logs [C:\Users\Todd\AppData\Local\Temp\appcfg7648762342118271795.log] for further information.

**Comment by elharo** [comment]
It looks like you didn't add the App Engine API library to your project; i.e. the appengine-api-1.0-sdk-1.9.51.jar file yet. Try

Build Path > Add LIbraries > App Engine Libraries > App Engine API

**Comment by tweverett** [comment]
I already have the App Engine API on my build path. I just tried removing and adding it again. I get the same deployment error.

**Comment by chanseokoh** [comment]
We've got other users reporting similar problems. We're investigating this. Thanks.

**Comment by chanseokoh** [comment]
@tweverett can you check if your gcloud version is above 158, and if so, can you try after downgrading gcloud to 158? You can do so by

`gcloud components update --version=158.0.0`

**Comment by tweverett** [comment]
I can confirm that the deploy succeeds with no JSP compile errors when downgraded to v158.0.0.

**Comment by chanseokoh** [comment]
We think this happens only on gcloud v161 (159 and 158 should work) and if the install path of gcloud contains spaces. We expect the next gcloud release will fix this. A workaround until then is to downgrade to 159 (avoid 160 as it was rollback), or move gcloud to a path without spaces.
