### ISSUE TITLE
Stacktrace hyperlinks in console output

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/google-cloud-eclipse#2140]
I noticed a different handling of Eclipse dev-server logs (Console view).
Of course the color is not the main theme here, but I'm referring to the stacktrace hyperlinks.

Here is my configuration (the 2 plugins has beend installed separately in order to do the first and the second test)

> **Google Plugin for Eclipse**:
> _Version: 3.9.6.v20170329-1604_
> 
> **Cloud Tools for Eclipse**:
> _Version: 1.2.0.201706082053_
> 
> **Eclipse**:
> _Eclipse Java EE IDE for Web Developers.
> Version: Neon.3 Release (4.6.3)
> Build id: 20170314-1500_
> 
> **OS**:
> _Windows 10 ver 1703 (build SO 15063.413)_
> 
> **Java version**:
> _Java version "1.8.0_111"
> Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
> Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)_

As test project I created a brand new using `appengine-standard-archetype`.
I added a simple code which thrown an exception and print the stacktrace in order to see the difference
```
Logger.getLogger(HelloAppEngine.class.getName()).log(Level.SEVERE, null, new Throwable());
```

This is the dev-server launched with CT4E, all the logs are in black-color, only the urls are hyperlinked and all the stacktrace classes are not enhanced
![image](https://user-images.githubusercontent.com/12278553/28107197-02d6c82c-66e7-11e7-92c2-7834bf276399.png)

This is the dev-server launched with the (deprecated?) Google Plugin for Eclipse, all the logs are in red-color, the urls are NOT hyperlinked (not a big problem) but all the classes are hyperlinked to the source
![image](https://user-images.githubusercontent.com/12278553/28107320-93ec4a1c-66e7-11e7-9753-1d560a7eeb5e.png)

During local debugging having a link directly to the stacktrace can be very handy, is there a way to introduce this kind of behaviour even with the new CT4E?

Thanks

**Comment by briandealwis** [comment]
Coloring the stderr output is #1248.

**Comment by briandealwis** [comment]
`org.eclipse.jdt.debug.ui` provides several console pattern matchers for pulling out hyperlinks to java stack traces and file paths.

```xml
   <extension point="org.eclipse.ui.console.consolePatternMatchListeners">
     […omitted…]
         <consolePatternMatchListener
            class="org.eclipse.jdt.internal.debug.ui.console.JavaExceptionConsoleTracker"
            regex="\w[^\(\s]+Exception[\s|:]"
            qualifier="Exception"
            id="org.eclipse.jdt.debug.ui.JavaExceptionConsoleTracker">
         <enablement>
            <or>
               <test property="org.eclipse.ui.console.consoleTypeTest" value="javaStackTraceConsole"/>
               <test property="org.eclipse.debug.ui.processTypeTest" value="java"/>
               <test property="org.eclipse.debug.ui.processTypeTest" value="org.eclipse.ant.ui.antProcess"/>
            </or>
         </enablement>
      </consolePatternMatchListener>
</extension>
```

The association is governed by one of two types of property testers: either testing 

  1. that the console type is `javaStackTraceConsole` (impl: `org.eclipse.ui.console`'s `ConsoleTypePropertyTester`)
  2. that the console's associated `IProcess` has type `java` or `antProcess` type (impl: `org.eclipse.debug.ui`'s `ProcessTypePropertyTester`).

We currently do not specify a console type, nor do we associate the devappserver/CloudSDK process to the console.  I previously experimented mapping the devappserver process as an `IProcess` to the `ILaunch` instance,  but bailed as it led to the debug framework automatically mapping the process' stdout and stderr to a newly-created console, which interfered with our processing of the output.  This behaviour might be avoided if I associate the process with our console.  

My hesitation is that neither approach allows associating to multiple console types or process types, and would seem to preclude supporting other languages in the future.  For example, if we had multiple services, one in Java and another in Python.  

Alternatively, we could add our own `<consolePatternMatchListener>` definitions that reference these `jdt.debug.ui` classes, though these classes are internal.

**Comment by briandealwis** [comment]
Reopening due to #2220

**Comment by briandealwis** [comment]
As I noted in #2327:

> I think the better longer-term change would be to figure out how to recast our CloudSdk Process as an org.eclipse.debug.core.model.IProcess and leverage the Eclipse Debug's ProcessConsole of type java, which should also let us get hyperlinking for free (#2140).

**Comment by Emperorlou** [comment]
![pysqmwr](https://user-images.githubusercontent.com/315164/42390807-32299984-811b-11e8-884c-0a6f49cf206c.png)

Is there any way we can get this fixed? I'm using Eclipse Oxygen2 and there are no hyperlinks in stacktraces.

**Comment by briandealwis** [comment]
Just an update: I have a [branch in progress](
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/i2140) where I've incorporated stack trace and URL hyperlinking using the [`IProcess`/`ProcessConsole` approach described above](
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2327#issuecomment-326366839).  Still outstanding are:
  - [ ] Handle VM termination error dialogs that popup sometimes during manual testing
  - [ ] Improve labels shown in the _Debug_ view: the _App Engine Development Application Server_ is the process thread 
      <img width="516" alt="screen shot 2018-09-18 at 12 04 44 pm" src="https://user-images.githubusercontent.com/202851/45778189-ecf39b80-bc25-11e8-9be1-c8ebc9a0e5a7.png">
  - [ ] Fix console description to include server execution state (`<started>`, `<stopped>`)
      <img width="647" alt="screen shot 2018-09-18 at 12 03 36 pm" src="https://user-images.githubusercontent.com/202851/45778305-4c51ab80-bc26-11e8-8402-04cb133db6e5.png">
  - [ ] Fix up tests

**Comment by briandealwis** [comment]
> - [ ] Handle VM termination error dialogs that popup sometimes during manual testing

This termination error dialog occur when selecting the "Terminate" button in the console.  It arises as it attempts to terminate all of the _debug targets_ associated with the launch, which includes:
  1. our `CloudSdkDebugTarget` (the _Google Cloud SDK Dev App Server [214.0.0]_ in the above screenshot above)
  2. a `JDIDebugTarget` (the _Java HotSpot(™) 64-bit Server VM<00:00.000>[61690]_ in the above screenshot) — these are the JVMs that connect to the debugger.
  3. and the `DevAppServerRuntimeProcess` (introduced in this PR) that represents the running DevAppServer.

The dialog occurs as the `JDIDebugTarget` is configured to not support termination.  This supportsTerminate flag in our case is determined by the launch configuration attribute `IJavaLaunchConfigurationConstants.ATTR_ALLOW_TERMINATE`.  Setting this to `true` marks the `JDIDebugTarget` as supportsTerminate, but the actual termination silently fails as  it doesn't have an associated process (which works for us).

<details>
<summary>More detail...</summary>
What's odd is that the normal _Debug As Java Application_ launcher's `JDIDebugTarget` is configured to support termination.  That launcher uses a different connector (`org.eclipse.jdi.internal.connect.SocketListeningConnectorImpl`) than our _Debug As App Engine_ launcher (`org.eclipse.jdt.launching.SocketListenerConnector`).  The `.jdi` one configures the resulting `JDIDebugTarget` as being supportsTerminate, whereas the `.jdt` sets the canTerminate flag based on the the launch configuration attribute `IJavaLaunchConfigurationConstants.ATTR_ALLOW_TERMINATE`.

Ah, our launcher explicitly configures an `IVMConnector` as we delegate the devappserver launching to appengine-plugins-core (i.e., it runs `java ...`) whereas the _Debug As Java Application_ uses the JDT `IVMRunner` interface.  I did briefly look into using `IVMRunner` but abandoned it as it won't work for the `devappserver2` case (https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/353). But perhaps we could use the [JDI connector instead](http://git.eclipse.org/c/jdt/eclipse.jdt.debug.git/tree/org.eclipse.jdt.launching/launching/org/eclipse/jdt/internal/launching/StandardVMDebugger.java?h=master#n623)

Stacktrace of our server causing the canTerminate flag to be false.
```
Thread [Worker-13: Waiting for vm to connect at port 49337...] (Suspended (breakpoint at line 335 in org.eclipse.jdt.internal.launching.SocketListenConnectorProcess$WaitForConnectionJob))	
	org.eclipse.jdt.internal.launching.SocketListenConnectorProcess$WaitForConnectionJob.run(org.eclipse.core.runtime.IProgressMonitor) line: 335	
	org.eclipse.core.internal.jobs.Worker.run() line: 60	
```

Stacktrace of the _Debug As Java Application_::
```
Thread [Worker-12: Launching Main] (Suspended (entry into method setSupportsTerminate in org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget))	
	org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget.setSupportsTerminate(boolean) line: 775	
	org.eclipse.jdt.internal.debug.core.model.JDIDebugTarget.<init>(org.eclipse.debug.core.ILaunch, com.sun.jdi.VirtualMachine, java.lang.String, boolean, boolean, org.eclipse.debug.core.model.IProcess, boolean) line: 351	
	org.eclipse.jdt.debug.core.JDIDebugModel$1.run(org.eclipse.core.runtime.IProgressMonitor) line: 201	
	org.eclipse.core.internal.resources.Workspace.run(org.eclipse.core.runtime.ICoreRunnable, org.eclipse.core.runtime.jobs.ISchedulingRule, int, org.eclipse.core.runtime.IProgressMonitor) line: 2289	
	org.eclipse.core.internal.resources.Workspace.run(org.eclipse.core.resources.IWorkspaceRunnable, org.eclipse.core.runtime.jobs.ISchedulingRule, int, org.eclipse.core.runtime.IProgressMonitor) line: 2316	
	org.eclipse.jdt.debug.core.JDIDebugModel.newDebugTarget(org.eclipse.debug.core.ILaunch, com.sun.jdi.VirtualMachine, java.lang.String, org.eclipse.debug.core.model.IProcess, boolean, boolean, boolean) line: 205	
	org.eclipse.jdt.internal.launching.macosx.MacOSXDebugVMRunner(org.eclipse.jdt.internal.launching.StandardVMDebugger).createDebugTarget(org.eclipse.jdt.launching.VMRunnerConfiguration, org.eclipse.debug.core.ILaunch, int, org.eclipse.debug.core.model.IProcess, com.sun.jdi.VirtualMachine) line: 508	
	org.eclipse.jdt.internal.launching.macosx.MacOSXDebugVMRunner(org.eclipse.jdt.internal.launching.StandardVMDebugger).run(org.eclipse.jdt.launching.VMRunnerConfiguration, org.eclipse.debug.core.ILaunch, org.eclipse.core.runtime.IProgressMonitor) line: 378	
	org.eclipse.jdt.launching.sourcelookup.advanced.AdvancedJavaLaunchDelegate(org.eclipse.jdt.launching.JavaLaunchDelegate).launch(org.eclipse.debug.core.ILaunchConfiguration, java.lang.String, org.eclipse.debug.core.ILaunch, org.eclipse.core.runtime.IProgressMonitor) line: 130	
	org.eclipse.debug.internal.core.LaunchConfiguration.launch(java.lang.String, org.eclipse.core.runtime.IProgressMonitor, boolean, boolean) line: 859	
	org.eclipse.debug.internal.core.LaunchConfiguration.launch(java.lang.String, org.eclipse.core.runtime.IProgressMonitor, boolean) line: 717	
	org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(org.eclipse.debug.core.ILaunchConfiguration, java.lang.String, org.eclipse.core.runtime.IProgressMonitor) line: 1039	
	org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(org.eclipse.core.runtime.IProgressMonitor) line: 1256	
	org.eclipse.core.internal.jobs.Worker.run() line: 60	
```
</details>
