### ISSUE TITLE
Cannot run StarterPipeline generated by Dataflow wizard (Dataflow 2.0.0)

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2141]
```
Exception in thread "main" java.lang.RuntimeException: Failed to construct instance from factory method DataflowRunner#fromOptions(interface org.apache.beam.sdk.options.PipelineOptions)
	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:233)
	at org.apache.beam.sdk.util.InstanceBuilder.build(InstanceBuilder.java:162)
	at org.apache.beam.sdk.PipelineRunner.fromOptions(PipelineRunner.java:52)
	at org.apache.beam.sdk.Pipeline.create(Pipeline.java:141)
	at f.StarterPipeline.main(StarterPipeline.java:50)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.beam.sdk.util.InstanceBuilder.buildFromMethod(InstanceBuilder.java:222)
	... 4 more
Caused by: java.lang.IllegalArgumentException: Missing object or bucket in path: 'gs://my-awesome-bucket/', did you mean: 'gs://some-bucket/my-awesome-bucket'?
	at org.apache.beam.sdks.java.extensions.google.cloud.platform.core.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:383)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsPathValidator.verifyPath(GcsPathValidator.java:79)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsPathValidator.validateOutputFilePrefixSupported(GcsPathValidator.java:62)
	at org.apache.beam.runners.dataflow.DataflowRunner.fromOptions(DataflowRunner.java:211)
	... 9 more
```

Arguments given to `main()` are as follows:
```
arg: --runner=DataflowRunner
arg: --project=my-gcp-project-id
arg: --gcpTempLocation=gs://my-awesome-bucket
arg: --stagingLocation=gs://my-awesome-bucket
```

**Comment by elharo** [comment]
This is the relevant bit:

Caused by: java.lang.IllegalArgumentException: Missing object or bucket in path: 'gs://my-awesome-bucket/', did you mean: 'gs://some-bucket/my-awesome-bucket'?

I seem to recall hitting this myself. May be a config issue.

**Comment by chanseokoh** [comment]
> May be a config issue.

You mean users' config error? But then, the same config of mine works with Dataflow v1 (i.e., when the staging location is set to my existing bucket). In fact, I was not able to make a remote Dataflow v2 job work in any way.

**Comment by chanseokoh** [comment]
This seems like an issue inside the Dataflow SDK v2.x, unless the SDK specifically requires the GCS bucket path to be `gs://<some bucket>/<some object>` (which isn't case for the SDK v1.x). Here's where the check is done:

```java
  public String verifyPath(String path) {
    GcsPath gcsPath = getGcsPath(path);
    ...
    checkArgument(!gcsPath.getObject().isEmpty(),
        "Missing object or bucket in path: '%s', did you mean: 'gs://some-bucket/%s'?",
        gcsPath, gcsPath.getBucket());
```

If `path` is like `gs://my-awesome-bucket`, `gcsPath` won't have the bucket object part, so `gcsPath.getObject()` is no doubt empty. This is how `gcsPath` parses a string path:

```java
  public static final Pattern GCS_URI =
      Pattern.compile("(?<SCHEME>[^:]+)://(?<BUCKET>[^/]+)(/(?<OBJECT>.*))?");

  public static GcsPath fromUri(String uri) {
    Matcher m = GCS_URI.matcher(uri);
    ...
    return new GcsPath(null, m.group("BUCKET"), m.group("OBJECT"));
  }
```

If I create a sub-folder under my bucket and set that as the Dataflow staging bucket (e.g., `gs://my-awesome-bucket/sub-folder`), everything works.

@tgroh is this bucket validation required a sub-folder intended for Dataflow SDK v2.x? TBH, this doesn't make sense to me.

**Comment by tgroh** [comment]
My understanding is that it is intended; doing so permits the runner to utilize space within the bucket without interfering with the actual staged files.

**Comment by chanseokoh** [comment]
Okay. Maybe developers would already know this requirement, but we could do our validation on a launch config and warn before running. Seems like we already have an issue for that: #2001. Closing.

**Comment by chanseokoh** [comment]
I see an immediate problem that needs to be fixed. The Dataflow wizard prevents entering sub-folders:

![selection_001](https://user-images.githubusercontent.com/10523105/28395858-2b05b09a-6cc5-11e7-8354-a9c195c8aa4e.png)

**Comment by chanseokoh** [comment]
https://cloud.google.com/storage/docs/naming#requirements

GCS is pretty liberal about object naming (although it strongly recommends avoiding certain naming)

> - Object names can contain any sequence of valid Unicode characters, of length 1-1024 bytes when UTF-8 encoded.
> - Object names must not contain Carriage Return or Line Feed characters

![selection_002](https://user-images.githubusercontent.com/10523105/28471644-cf925e78-6e0b-11e7-8c76-8f12657cb8fc.png)

For now, what we can do is to parse the input string and validate only the bucket name portion.

**Comment by chanseokoh** [comment]
Allowing entering GCS object path involves a bit more work than just validation, as we have the "create-staging-location" button.

**Comment by chanseokoh** [comment]
What a bummer... Dataflow will take care of creating a new GCS object if it doesn't exist, as long as a bucket exist. No need to create an object on our side.

**Comment by sadohert** [comment]
Apologies if this is my noob-ness, but is there a workaround for this?  I'm trying to follow along with the Cloud Dataflow Quickstart Eclipse and I can't get it to work.  I don't see what my workaround is in the comments, and I don't think the referenced fixes are applied.

I'm going to go try CLI now, but would prefer the Eclipse case work if possible.

**Comment by chanseokoh** [comment]
The fix is in. If you are still seeing the error, I bet you are specifying only the bucket. Try enter `gs://your-bucket/any-text-you-want`. `any-text-you-want` doesn't have to exist.

**Comment by sadohert** [comment]
Thanks @chanseokoh ... maybe its my environment?

- Ubuntu Artful 17.10
- Eclipse Oxygen.2 Release (4.7.2) (installed Google Cloud through marketplace as instructions [here described](https://cloud.google.com/dataflow/docs/quickstarts/quickstart-java-eclipse)

In the Debug Configuration I have the following:

![screenshot from 2018-01-12 22-08-24](https://user-images.githubusercontent.com/260544/34902236-5e50bc32-f7e5-11e7-93e7-2297e3d7e555.png)
![screenshot from 2018-01-12 22-08-55](https://user-images.githubusercontent.com/260544/34902235-5e41506c-f7e5-11e7-9631-fe7af99da910.png)

I can't seem to add a path element to the "Google Cloud Staging Location" field... it just doesn't stick.

If I should be handling this issue another way please let me know.

**Comment by chanseokoh** [comment]
You could uncheck the "Use default Dataflow options" to put a custom location for this launch configuration of yours. The location value you are seeing here as read only is the default value you defined elsewhere. So, alternatively you could update the default option values, which you can edit by going to your project preference page or the global Eclipse preference page. You will find a Datafow preference node there.

**Comment by olegkamuz** [comment]
Same here :
 ```       
DataflowPipelineOptions options = PipelineOptionsFactory.as(DataflowPipelineOptions.class);
        options.setStagingLocation("gs://" + bucketName + "/staging");
        options.setTempLocation("gs://" + bucketName + "/tmp");
        options.setProject(projectId);
        options.setRunner(DataflowRunner.class);
        options.setRegion(region);

        Pipeline pipeline = Pipeline.create(options);
```
and 
```
Failed to construct instance from factory method DataflowRunner#fromOptions
```
```"gs://" + bucketName + "/staging") ```  and  ```"gs://" + bucketName + "/tmp"```  does not 
exist

how to fix that? thanks)

**Comment by chanseokoh** [comment]
@olegkamuz sounds like you need to create the buckets `gs://<bucketName>/staging` and `gs://<bucketName>/tmp` first. You can do it on the Cloud Console (https://console.cloud.google.com) and go to the "Storage" page.

**Comment by olegkamuz** [comment]
**@chanseokoh** 
I had had gs://<bucketName> done made already. Creating ```staging``` and ```tmp``` not helped.

**Comment by chanseokoh** [comment]
@olegkamuz how about this? https://stackoverflow.com/q/49227327/1701388

**Comment by olegkamuz** [comment]
@chanseokoh 
Thank you. I have already tried it, not helped.
But I solved the issue. I changed:
```
        <dependency>
            <groupId>org.apache.beam</groupId>
            <artifactId>beam-vendor-guava-20_0</artifactId>
            <version>0.1</version>
        </dependency>
```
to
```
        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>30.0-jre</version>
        </dependency>
```

The root cause was: first dependency don't have needed methods.
