### ISSUE TITLE
Not able to Sign in to Google Account from Eclipse Oxygen

### ISSUE THREAD

**Issue by sanc-enovate** [GoogleCloudPlatform/google-cloud-eclipse#2148]
- Cloud Tools for Eclipse Version: 1.2.0.201706082053
- OS: Mac OS X 10.12.5
- Java Version: 1.8.0_40
Eclipse Oxygen : 4.7

Issue : Sign in to Google is not working. 

I am new to Google Cloud tools and facing problem at very first step where I need to sign in to Google account.
When I hit "Sign in to Google" It opened the login process in external browser(Chrome), After login and giving permission, It redirects to localhost:RANDOM_PORT/Callback?code=xxxxxx

This URL doesn't exist  and showing "This site can’t be reached", standard google chrome page ,

In eclipse, Showing processing dialog window with Cancel option. 

Not sure why callback redirection is to a Random localhost port ?

Additional information:
  I tried with Safari and result is same.

**Comment by chanseokoh** [comment]
Can you clarify if what you see is the literal string "RANDOM_PORT"? If so, that's certainly a bug. (It is, however, correct that it should be some random localhost port.)

**Comment by sanc-enovate** [comment]
It is some random localhost port like 60456, 54329 and so on

**Comment by chanseokoh** [comment]
I see. At least it is correct that it redirects to a random localhost port. When the login browser launches, our CT4E plugin also listens from the port locally to receive the `code` value. Let me check what could go wrong.

**Comment by chanseokoh** [comment]
The fact that you actual random port numbers very likely suggests that the local webserver is up and running (not as a separate process).

I suspect your browser is blocked to access "http://localhost", perhaps due to your proxy settings. Can you update your browser proxy setting so that localhost address bypass the proxy?

**Comment by sanc-enovate** [comment]
I doubt about proxy, my node JS apps run smoothly on different port,  web
server works fine


Any other thought?


On Jul 14, 2017 10:52 PM, "Chanseok Oh" <notifications@github.com> wrote:

The fact that you actual random port numbers very likely suggests that the
local webserver is up and running (not as a separate process).

I suspect your browser is blocked to access "http://localhost", perhaps due
to your proxy settings. Can you update your browser proxy setting so that
localhost address bypass the proxy?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2148#issuecomment-315416516>,
or mute the thread

**Comment by briandealwis** [comment]
Are you behind a firewall or anti-virus?

Could you check your `<workspace>/.metadata/.log`?

**Comment by chanseokoh** [comment]
First, let's check if the local webserver is listening, and try to connect to the local webserver from other clients than browsers, such as `wget()` in the terminal.

Let Eclipse be the only Java process. `netstat -tlnp` will give you listening TCP ports. You'll see only one Java process for Ecilpse. I recommend restarting Eclipse before doing this.
```
$ netstat -tlnp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:30003         0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:9557          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:9558          0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:9559          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:45596           0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:8103            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:999           0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::31337                :::*                    LISTEN      -               
tcp6       0      0 :::44681                :::*                    LISTEN      -               
tcp6       0      0 :::12589                :::*                    LISTEN      -               
tcp6       0      0 :::111                  :::*                    LISTEN      -               
tcp6       0      0 :::9554                 :::*                    LISTEN      -               
tcp6       0      0 :::9555                 :::*                    LISTEN      -               
tcp6       0      0 ::1:9557                :::*                    LISTEN      -               
tcp6       0      0 ::1:9558                :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 ::1:9559                :::*                    LISTEN      -               
tcp6       0      0 ::1:631                 :::*                    LISTEN      -               
tcp6       0      0 :::3900                 :::*                    LISTEN      -               
tcp6       0      0 :::3901                 :::*                    LISTEN      -               
tcp6       0      0 :::8224                 :::*                    LISTEN      -               
tcp6       0      0 :::12513                :::*                    LISTEN      -               
tcp6       0      0 :::32100                :::*                    LISTEN      -               
tcp6       0      0 :::32101                :::*                    LISTEN      -               
tcp6       0      0 :::8103                 :::*                    LISTEN      -               
```

Then, click on the login button in Eclipse. When the "Sign in to Google" dialog pops up, check which port is open. There will be one Java process:

```
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:30003         0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:9557          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:9558          0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:9559          0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:45596           0.0.0.0:*               LISTEN      -               
tcp        0      0 0.0.0.0:8103            0.0.0.0:*               LISTEN      -               
tcp        0      0 127.0.0.1:999           0.0.0.0:*               LISTEN      -               
tcp6       0      0 :::31337                :::*                    LISTEN      -               
tcp6       0      0 :::44681                :::*                    LISTEN      -               
tcp6       0      0 :::12589                :::*                    LISTEN      -               
tcp6       0      0 :::111                  :::*                    LISTEN      -               
tcp6       0      0 :::9554                 :::*                    LISTEN      -               
tcp6       0      0 :::9555                 :::*                    LISTEN      -               
tcp6       0      0 127.0.0.1:41237         :::*                    LISTEN      101879/java     
tcp6       0      0 ::1:9557                :::*                    LISTEN      -               
tcp6       0      0 ::1:9558                :::*                    LISTEN      -               
tcp6       0      0 :::22                   :::*                    LISTEN      -               
tcp6       0      0 ::1:9559                :::*                    LISTEN      -               
tcp6       0      0 ::1:631                 :::*                    LISTEN      -               
tcp6       0      0 :::3900                 :::*                    LISTEN      -               
tcp6       0      0 :::3901                 :::*                    LISTEN      -               
tcp6       0      0 :::8224                 :::*                    LISTEN      -               
tcp6       0      0 :::12513                :::*                    LISTEN      -               
tcp6       0      0 :::32100                :::*                    LISTEN      -               
tcp6       0      0 :::32101                :::*                    LISTEN      -               
tcp6       0      0 :::8103                 :::*                    LISTEN      -               
```

So, you now know there is a Java process listening on port `41237`. Try

`$ wget 127.0.0.1:41237`
`$ wget localhsot:41237`

If it returns 404, then at least we know the server is running and it's the browser problem.
```
HTTP request sent, awaiting response... 404 Not Found
2017-07-14 14:04:37 ERROR 404: Not Found.
```

**Comment by chanseokoh** [comment]
I somethings see Eclipse listens on port on its down, so I recommend you check netstat multiple times by clicking on the login button and cancelling the "Sign in to Google" dialog.

**Comment by chanseokoh** [comment]
Also, hitting `/Callback?error=anything` will return 200, so this is the sure thing to know the server is the right one. When returning 200 with this URL, the "Sign in to Google" dialog in Eclipse will disappear.

```
$ wget 127.0.0.1:60039/Callback?error=killit
--2017-07-14 14:18:16--  http://127.0.0.1:60039/Callback?error=killit
Connecting to 127.0.0.1:60039... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘Callback?error=killit’

    [ <=>                                                                                                                                             ] 159         --.-K/s   in 0s      

2017-07-14 14:18:16 (20.7 MB/s) - ‘Callback?error=killit’ saved [159]
```

**Comment by sanc-enovate** [comment]
Netstat stuff did the trick,

Here are the steps that help to resolve the issue (Steps for Mac):-


   1.  Click on "sign in to google"
   2. Run below command on terminal

   sudo lsof -i -n -P | grep TCP
   3.

   Check the IP and port with program name eclipse
   4.

   When callback url returned on browser, Simply replace localhost  with
   the IP address noted in step 3 and press Enter
   5.

   We are good.

*What is the root cause* :

Google sing in process run webserver on 192.168.*.*:45678 in place of (
127.0.0.1/localhost):45678 .

Thank you for pointing towards right direction





*Best Regards*
Sanjeev Choudhary
http://one.enovate-it.com/ <http://www.enovate-it.com/>

*Disclaimer*: This email and any files transmitted with it are confidential
and intended solely for the use of the individual or entity to whom they
are addressed. If you have received this email in error please notify the
system manager. This message contains confidential information and is
intended only for the individual named. If you are not the named addressee
you should not disseminate, distribute or copy this e-mail. Please notify
the sender immediately by e-mail if you have received this e-mail by
mistake and delete this e-mail from your system.Our company accepts no
liability for the content of this email, or for the consequences of any
actions taken on the basis of the information provided, unless that
information is subsequently confirmed in writing. If you are not the
intended recipient you are notified that disclosing, copying, distributing
or taking any action in reliance on the contents of this information is
strictly prohibited.

**Comment by chanseokoh** [comment]
Seems like this can happen when there are multiple localhost interfaces. We need to let Jetty return the actual host here:

https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java#L129
