### ISSUE TITLE
Google Sheets support?

### ISSUE THREAD

**Issue by p-doyle** [GoogleCloudPlatform/google-cloud-eclipse#2160]
- Cloud Tools for Eclipse Version: 1.2.0.201706082053
- OS: Windows 10 10.0
- Java Version: 1.8.0_101

Hello.

I would like to import a javascript project from Google Sheets into Eclipse but the only options I see are for java.  From what I can tell this was possible with the Google Plugin For Eclipse but that is being deprecated.  Is there going to be similar functionality in Google Cloud Tools for Eclipse or am I missing something?

Thanks

**Comment by elharo** [comment]
Not sure what you mean here. If it's Apps Script, you can edit your Apps Script projects directly in your web browser using the Google Drive script editor.

All of your Apps Script projects are already available in Google Drive, without additional export or conversion.

**Comment by p-doyle** [comment]
I know I can edit them directly in a web browser but the script editor UI is very basic.  I would like to import them into an IDE.  Is that possible with Google Cloud Tools?

**Comment by elharo** [comment]
No, it isn't

**Comment by patflynn** [comment]
hi @p-doyle,  I regret to say that support for Google Apps is currently out of scope of the Cloud Tools plugins and unlikely to be on our roadmap any time soon.   The plugin is intended for Google Cloud Platform users.

**Comment by p-doyle** [comment]
Thank you for the responses.

I realize this may not be the right place to ask but if Cloud Tools isn't going to support the functionality that is being deprecated in the  [Google Plugin for Eclipse ](https://developers.google.com/eclipse/docs/apps_script), is there anything else that will be?

**Comment by patflynn** [comment]
Unfortunately not that we're aware.
