### ISSUE TITLE
Menu Item for Add Google APIs

### ISSUE THREAD

**Issue by TimTheCelticist** [GoogleCloudPlatform/google-cloud-eclipse#2168]
I am looking for the proper place to request an enhancement to "Google Cloud Tools for Eclipse" related to adding APIs to a Google App Engine Standard Java Project. I just upgraded/re-installed my Google SDK to 162.0.1 and my Eclipse to Oxygen 4.7 and I am now unable to easily add the API libraries for BigQuery or Drive to my project. I can find the JAR files and add them as External JARs in the build path, but I assume that this is not the right way to do this.

Here are the components that are installed in my Google SDK:
![image](https://user-images.githubusercontent.com/13539741/28369646-3be5d8b8-6c66-11e7-9e71-5a0dbc770ac9.png)

Adding Google APIs has now changed in Eclipse and it looks like it can now be done by clicking the usual "Add Library" from the project build path:
![image](https://user-images.githubusercontent.com/13539741/28369786-955abb16-6c66-11e7-9560-41b263eae939.png)

The options available when the "Google API Libraries" is selected seems very limited:
![image](https://user-images.githubusercontent.com/13539741/28369838-b9788cc6-6c66-11e7-98f8-754118ad9831.png)

Is that list "hard-coded" or is it dynamically generated off of information that it finds in the installed components in my Google SDK?

**Comment by elharo** [comment]
The list is hard coded ATM. Which specific BigQuery/Drive APIs do you need?

**Comment by TimTheCelticist** [comment]
Thanks for responding so quickly. For the specific use-case that the application addresses, I only needed to get access to the Drive scopes, and I suppose that I could have just used strings for that. For BigQuery, it is very different. I need to connect /login to a dataset, run a query, wait for the query to finish and then iterate through the result set to get an answer.

**Comment by elharo** [comment]
Can you point me to the specific API library you want to use?

Also, are you using Java 7 or Java 8 in App Engine Standard?

The tricky bit here is that not all the API libraries actually work in App Engine Standard, irrespective of the IDE. I need to check if BigQuery is supported there.

**Comment by TimTheCelticist** [comment]
I am using Java 7 and I am referencing google-api-services-bigquery-v2-rev295-1.22.0.jar from my Google SDK repository.

**Comment by Electricks94** [comment]
Does anyone have a solution yet?
I'm trying to receive Data from BigQuery in Eclipse as well but I get the error "Could not get the access token". I have no Idea how to do it although I ran the how to guides from google.

**Comment by elharo** [comment]
It's not a menu item, but this is now done. https://cloud.google.com/eclipse/docs/libraries

![image](https://user-images.githubusercontent.com/1005544/40585932-e1e68e12-6187-11e8-8d3a-8d10e7e9d19b.png)
