### ISSUE TITLE
Server Status is always "Started" even if Debugging

### ISSUE THREAD

**Issue by NicolaSpreafico** [GoogleCloudPlatform/google-cloud-eclipse#2179]
I'm running Eclipse Oxygen
```
Eclipse Java EE IDE for Web Developers.

Version: Oxygen Release (4.7.0)
Build id: 20170620-1800
```

with Cloud Tools 4 Eclipse 

```
Google Cloud Tools for Eclipse
Version: 1.2.0.201706082053
```

and when I launch the server in Debug mode I get a `[Started]` status. Here is the difference compared to the previous Google Plugin for Eclipse

Stopped
![image](https://user-images.githubusercontent.com/12278553/28413149-d7df8a62-6d46-11e7-883d-11d26470345f.png)

Starting
![image](https://user-images.githubusercontent.com/12278553/28413205-08288dfe-6d47-11e7-9c0d-00f201a02402.png)

Started
![image](https://user-images.githubusercontent.com/12278553/28413210-0da1b878-6d47-11e7-86ed-16bd15d577d3.png)

Debugging
![image](https://user-images.githubusercontent.com/12278553/28413224-197c4104-6d47-11e7-9a27-682c7ca169ac.png)

And now the same with CT4E

> 
> Stopped
> ![image](https://user-images.githubusercontent.com/12278553/28413251-2ea8485c-6d47-11e7-9881-7631c384ed30.png)
> 
> Starting
> ![image](https://user-images.githubusercontent.com/12278553/28413260-341c4e14-6d47-11e7-9047-5647e278f1fc.png)
> 
> Started
> ![image](https://user-images.githubusercontent.com/12278553/28413277-3a3af6e2-6d47-11e7-9344-33fa687f2ecb.png)
> 
> Debugging
> ![image](https://user-images.githubusercontent.com/12278553/28413294-4c9fb714-6d47-11e7-81a5-1b521d0a03eb.png)

This is very annoying because I cannot determine the type of launch of the dev-server reading directly the status

I need to open the Debug view of Eclipse and See if the Debugger is attached (so the Dev-server is launched in Debug mode)
![image](https://user-images.githubusercontent.com/12278553/28413360-7658859a-6d47-11e7-9b67-bac800167eaa.png)

Or there isn't any debugger, so the Dev-server is launch in Run mode)
![image](https://user-images.githubusercontent.com/12278553/28413384-889789c2-6d47-11e7-81f1-09d14e47bdd2.png)

May the labels be normalized specifying the tipo of run mode?

**Comment by briandealwis** [comment]
Huh, need to call `ServerBehaviourDelegate#setMode()`.  Thanks for noticing.
