### ISSUE TITLE
Using new Dynamic Web Project appears to produce invalid configuration

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2188]
Noticed as part of fixing #1939.

There's a minor issue in our runtime definition in that we share a single runtime definition for both the AES Java 7 and Java 8.  The problem manifests once we have created an AES project (and thus create an _App Engine Standard Runtime_ `IRuntime`) as subsequent attempts to  use _New > Dynamic Web Project_ show a wizard with a _Dynamic web module version 3.1_ and _Default Configuration for App Engine Standard Runtime_ configuration selected.  Once the user enters a project name, they see an error (below).  I suspect the framework has selected AESv7, Java 1.8, and DWP 3.1 as these are the default versions of the facets associated with the runtime component. The default version of a facet can be explicitly defined (as we do for AES, which is v7), or otherwise the framework selects the highest version (hence Java 1.8 and 3.1).  So we end up with this situation where the versions chosen are in conflict.  Although the user can either change the configuration, or change the _Dynamic web module version_ to 2.5, it's puzzling.  

<img width="581" alt="screen shot 2017-07-21 at 3 12 07 pm" src="https://user-images.githubusercontent.com/202851/28479199-5c3727d8-6e29-11e7-8c46-da5eca133164.PNG">

I suspect the only cure is to have separate versions of the _App Engine Standard Runtime_.  This may complicate life a tiny bit, but I suspect it may be best.

**Comment by diegomarquezp** [comment]
Closing as not planned.
