### ISSUE TITLE
Deploy option not activated although I followed the tutorial and created a maven project just as required and it works on my localhost

### ISSUE THREAD

**Issue by elGreato** [GoogleCloudPlatform/google-cloud-eclipse#2191]
- Cloud Tools for Eclipse Version: 1.2.0.201706082053
- OS: Windows 10 10.0
- Java Version: 1.8.0_131

**Comment by chanseokoh** [comment]
Hi @Hyp-nos, it should be enabled when you select the project in the _Package Explorer_ or the _Project Explorer_. Alternatively, you can right click on the project and select _Deploy to App Engine Standard..._.

**Comment by elharo** [comment]
@Hyp-nos Do you have a screenshot showing the context menu with the project selected?

**Comment by briandealwis** [comment]
Closing as no further feedback and works for us.  Please re-open @elGreato if you have more detail.
