### ISSUE TITLE
Collecting error messages does not work for App Engine staging failure

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2199]
I should have created this as a new issue back then: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1219#discussion_r95827603

The same issue with #527 but for staging failure.

![image](https://user-images.githubusercontent.com/10523105/28630612-b6891502-71f8-11e7-95a1-92a9a8233d9e.png)

The cause: we look for the prefix `ERROR:` in gcloud output and collect such lines as error messages, but staging failure error messages don't have the prefix.

To reproduce staging failure, change `appengine-web.xml` to be a malformed XML. (You may need to turn off auto-build.)

**Comment by briandealwis** [comment]
Should this be raised elsewhere?  Some errors, like an invalid runtime (e.g., `<runtime>FOO</runtime>`) are properly prefixed and picked up.

<img width="769" alt="screen shot 2017-07-26 at 12 49 34 pm" src="https://user-images.githubusercontent.com/202851/28633163-e946629e-7200-11e7-878e-22e01f73d6c8.PNG">

**Comment by briandealwis** [comment]
Ah, XML validation errors are logged differently. But it should be impossible to deploy in such situations as our deploy handler refuses to run if there are any problems markers on the selected project.

**Comment by chanseokoh** [comment]
I think the error in your screenshot is not from the staging phase, but after that. I see "Success." and the last output of the staging saying that the staging result has been left in some directory.

**Comment by briandealwis** [comment]
Oops, good point!

**Comment by chanseokoh** [comment]
Also, currently, the staging output is in black, while the deploy output is in red. That's one way to distinguish the two output.

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
