### ISSUE TITLE
App Engine Deployment Error

### ISSUE THREAD

**Issue by kalegar** [GoogleCloudPlatform/google-cloud-eclipse#2202]
- Cloud Tools for Eclipse version: 1.2.0
- Google Cloud SDK version: 164.0.0
- OS: Windows 7
- Java version: 1.8.0_141

I imported a project that had used google plugin for eclipse previously and converted it to an App Engine Project via Project -> Configure -> Convert To App Engine Project. Afterwards I attempted to deploy the project to App Engine Standard but it failed after attempting to compile my project's .jsp files with the following error:

`Jul 28, 2017 8:40:58 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Reading application configuration data...
Jul 28, 2017 8:40:59 AM com.google.apphosting.utils.config.IndexesXmlReader readConfigXml
INFO: Successfully processed C:\Eclipse\eclipse-oxygen\eclipse-workspace\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1501252855920\staging-work\WEB-INF\appengine-generated\datastore-indexes-auto.xml

Beginning interaction for module default...
0% Scanning for jsp files.
0% Compiling jsp files.
Jul 28, 2017 8:41:02 AM org.apache.jasper.JspC processFile
INFO: Built File: \create-drive-object.jsp
Jul 28, 2017 8:41:02 AM org.apache.jasper.JspC processFile
INFO: Built File: \error.jsp
Jul 28, 2017 8:41:02 AM org.apache.jasper.JspC processFile
INFO: Built File: \index.jsp
Jul 28, 2017 8:41:03 AM org.apache.jasper.JspC processFile
INFO: Built File: \menu.jsp
Jul 28, 2017 8:41:03 AM org.apache.jasper.JspC processFile
INFO: Built File: \tmp.jsp
Jul 28, 2017 8:41:03 AM org.apache.jasper.JspC processFile
INFO: Built File: \upload.jsp
Jul 28, 2017 8:41:03 AM org.apache.jasper.JspC processFile
INFO: Built File: \taxonomy\jsp\admin.jsp
Jul 28, 2017 8:41:03 AM org.apache.jasper.JspC processFile
INFO: Built File: \taxonomy\jsp\error.jsp
warning: [options] bootstrap class path not set in conjunction with -source 1.7
c:\temp\1501252861825-0\org\apache\jsp\menu_jsp.java:6: error: package com.google.appengine.api.users does not exist
import com.google.appengine.api.users.User;
                                     ^
c:\temp\1501252861825-0\org\apache\jsp\menu_jsp.java:7: error: package com.google.appengine.api.users does not exist
import com.google.appengine.api.users.UserService;
                                     ^
c:\temp\1501252861825-0\org\apache\jsp\menu_jsp.java:8: error: package com.google.appengine.api.users does not exist
import com.google.appengine.api.users.UserServiceFactory;
                                     ^
Note: c:\temp\1501252861825-0\org\apache\jsp\menu_jsp.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
1 warning
Unable to stage app: Failed to compile the generated JSP java files.
Please see the logs [c:\temp\appcfg888916121682305476.log] for further information.
`
The thing is I have the appengine api jar in my libraries:
![capture](https://user-images.githubusercontent.com/15331125/28722674-c49e0024-7371-11e7-9440-b3ffc718e4bb.PNG)

I'm probably missing something simple but I can't for the life of me figure out what.
Any help would be greatly appreciated.

**Comment by chanseokoh** [comment]
Sorry for the trouble. This is a known issue, and there exist less-than-ideal workarounds. Please take a look at #2153.

**Comment by chanseokoh** [comment]
For future reference, the workaround until newer gcloud releases fix this is to
- move/copy Cloud SDK to a path without spaces; or
- downgrade gcloud to 159: `gcloud components update --version 159.0.0`

**Comment by kalegar** [comment]
Thanks, the problem was a space in the cloud sdk path.
