### ISSUE TITLE
Better Analytics pinging and opt-in dialog handling

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2203]
I didn't really like how the field `AnalyticsPingManager.optInDialogOpened` of type `AtomicBoolean` works. The field feels a bit hacky, and it has a number of problems:

- Currently, this assumes that once an opt-in dialog is opened, users will never see it again no matter what happens to the dialog. Therefore, we are not able to have a button like "Ask Me Later" (although I am not suggesting we should have). More importantly, the current implementation must assume just dismissing the dialog means commiting an answer (opting out), and if this policy changes, our code will go broken, which is very easy to lose keeping track of.

- Another problem is that, if event pings come in while the opt-in dialog is being displayed (which always happens), those pings will just be dropped and discarded even if the user answers "yes" a bit later.

**Comment by elharo** [comment]
I am a hard no on any kind of "Ask Me Later." Users rightly hate these. There's a preference to set if they really want to change their answer.

I suppose we could queue pings and only send them if we get permission, though it doesn't seem like a major improvement.

**Comment by patflynn** [comment]
I wouldn't go to the trouble of trying to keep those events.

If the user hasn't explicitly opted-out using the dialog it makes sense to
me to show it to them again next time around.

**Comment by chanseokoh** [comment]
We are already queuing pings, so it is just a matter of holding them until the opt-in dialog closes. It just needs a small change.

At first, I also though losing some events is not a big deal. However, one major problem I observed is that, e.g., login success events outnumbers total login usage numbers, and I think this is because of our current model that we show the opt-in dialog at the first time a user uses any of our features. So, when a user logs in for the first time, the login event is discarded immediately, while the login success event is registered later. I also think the fact that users usually login only once (because we maintain logins) aggravates this problem.
