### ISSUE TITLE
Deploy to App Engine Standard Skips spring-web jar file

### ISSUE THREAD

**Issue by freeman-g** [GoogleCloudPlatform/google-cloud-eclipse#2206]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_.)

- Cloud Tools for Eclipse version:  
Cloud Tools for Eclipse 1.2

- Google Cloud SDK version: _(run `gcloud version`)_
gcloud version
Google Cloud SDK 164.0.0
app-engine-go
app-engine-java 1.9.54
app-engine-python 1.9.57
bq 2.0.24
core 2017.07.25
gcloud
gsutil 4.27

- OS:
MacOS sierra 10.12

- Java version:
java -version
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.141-b15, mixed mode)

**What did you do?**
I ran Deploy to App Engine Standard from Eclipse

**What did you expect to see?**
I expected my application to deploy successfully to app engine

**What did you see instead?**
My application does not completely deploy.  The Jar file spring-web-4.3.9.RELEASE.jar does not get deployed even though it is a maven dependency.  Therefore the application fails with a class not found exception.  The application runs fine in the local Eclipse environment.  I am using the Java8 runtime.

These are my Maven dependencies:

![image](https://user-images.githubusercontent.com/495886/28750391-51c4f368-74b7-11e7-95aa-13979e9ba2ed.png)

These are the files in the `workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1501385321020/staging/WEB-INF/lib` directory.  Notice how spring-web is missing:

```
ls -ln
total 18320
-rw-r--r--  1 501  20   106862 Jul 29 23:28 Astrolib-1.jar
-rw-r--r--  1 501  20    61829 Jul 29 23:28 commons-logging-1.2.jar
-rw-r--r--  1 501  20  2256213 Jul 29 23:28 guava-18.0.jar
-rw-r--r--  1 501  20    55784 Jul 29 23:28 jackson-annotations-2.8.0.jar
-rw-r--r--  1 501  20   282438 Jul 29 23:28 jackson-core-2.8.8.jar
-rw-r--r--  1 501  20  1238590 Jul 29 23:28 jackson-databind-2.8.8.jar
-rw-r--r--  1 501  20   414240 Jul 29 23:28 jstl-1.2.jar
-rw-r--r--  1 501  20   348450 Jul 29 23:28 objectify-5.1.13.jar
-rw-r--r--  1 501  20   380572 Jul 29 23:28 spring-aop-4.3.9.RELEASE.jar
-rw-r--r--  1 501  20   763050 Jul 29 23:28 spring-beans-4.3.9.RELEASE.jar
-rw-r--r--  1 501  20  1140303 Jul 29 23:28 spring-context-4.3.9.RELEASE.jar
-rw-r--r--  1 501  20  1121720 Jul 29 23:28 spring-core-4.3.9.RELEASE.jar
-rw-r--r--  1 501  20   263287 Jul 29 23:28 spring-expression-4.3.9.RELEASE.jar
-rw-r--r--  1 501  20   915475 Jul 29 23:28 spring-webmvc-4.3.9.RELEASE.jar
```

Any help would be very appreciated.  I'm stuck and cannot deploy this application.

**Comment by chanseokoh** [comment]
Interesting. I can reproduce this. There must be a reason for this behavior. 

To reproduce, add the following to `pom.xml`, try deploying, and check the staging directory.

```xml
    <dependency>
    	<groupId>org.springframework</groupId>
    	<artifactId>spring-webmvc</artifactId>
    	<version>4.3.6.RELEASE</version>
    </dependency>
    <dependency>
    	<groupId>org.springframework</groupId>
    	<artifactId>spring-web</artifactId>
    	<version>4.3.6.RELEASE</version>
    </dependency>
```

```
└── WEB-INF
    ├── appengine-generated
    │   └── app.yaml
    ├── appengine-web.xml
    ├── classes
    │   └── com
    │       └── example
    │           └── HelloAppEngine.class
    ├── lib
    │   ├── commons-logging-1.2.jar
    │   ├── jstl-1.2.jar
    │   ├── spring-aop-4.3.6.RELEASE.jar
    │   ├── spring-beans-4.3.6.RELEASE.jar
    │   ├── spring-context-4.3.6.RELEASE.jar
    │   ├── spring-core-4.3.6.RELEASE.jar
    │   ├── spring-expression-4.3.6.RELEASE.jar
    │   └── spring-webmvc-4.3.6.RELEASE.jar
    └── web.xml
```

**Comment by chanseokoh** [comment]
I guess it is m2e-wtp that resists or fails to include `spring-web`.

`publishSmart()` from `WarPublisher.publish()` doesn't have the JAR in the list when publishing `WEB-INF/lib`.

![selection_029](https://user-images.githubusercontent.com/10523105/28786728-0ff05bb2-75e8-11e7-90ac-f0b90722257c.png)

**Comment by chanseokoh** [comment]
The `web-fragment.xml` in `spring-web-4.3.9.RELEASE.jar` specifies Servlet 3.0 specification:

```xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<web-fragment xmlns="http://java.sun.com/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-fragment_3_0.xsd"
	version="3.0" metadata-complete="true">

	<name>spring_web</name>
	<distributable/>

</web-fragment>
```

App Engine standard environment Java **7** runtime doesn't support 3.0, so my guess is that WTP strips out it, as the spec doesn't match.

Some references:
https://jira.spring.io/browse/SPR-10494
https://stackoverflow.com/questions/15174774/spring-web-maven-dependency-not-being-published-with-eclipse
https://www.ibm.com/developerworks/community/forums/html/topic?id=8fde79d3-8ede-4a19-b503-de6c5b75c320

**Comment by chanseokoh** [comment]
> App Engine standard environment Java 7 runtime doesn't support 3.0, so my guess is that WTP strips out it, as the spec doesn't match.

Maybe this isn't the reason. I tried App Engine standard Java 8 runtime with Servlet 3.0, but the same thing happens.

**Comment by chanseokoh** [comment]
I think the reason that `PublishHelper.publishSmart()` in `WarPublisher.publish()` has something to do with the fact that `spring-web` is a web fragment type and as a result it is not in the resources list but in the child module list: https://bugs.eclipse.org/bugs/show_bug.cgi?id=439685

I don't really get the resources list and the child module part, but I am guessing that `spring-web` cannot be found in `deployable.members()` but rather in `deployable.getChildModuels()` below (not confirmed).

```java
    PublishHelper publishHelper = new PublishHelper(null);
    J2EEFlexProjDeployable deployable =
        new J2EEFlexProjDeployable(project, ComponentCore.createComponent(project));
    ...
      publishHelper.publishSmart(deployable.members(), destination, progress.newChild(100));
```

I'm not an expert on the JEE spec/WTP, so it's not clear if this is a bug or working as intended, who's at fault, or who may possibly make this work.

Another ref: https://developer.ibm.com/answers/questions/249285/spring-webjar-not-being-deployed.html

**Comment by freeman-g** [comment]
Thanks a lot for looking into this.

**Comment by chanseokoh** [comment]
@freeman-g no problem. I think the best workaround is to deploy on the command line using the App Engine Maven plugin, as this isn't likely that it can be resolved soon. It's as easy as following these steps:

1. Add the plugin to your `pom.xml` (if your app was generated from our wizard, it's already there):
```xml
  <build>
    <plugins>
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>appengine-maven-plugin</artifactId>
        <version>1.3.1</version>
      </plugin>
      ...
```
2. Do `gcloud init` to set the target GCP project ID and the login credential.
3. `mvn appengine:deploy`

More detailed docs:
- https://cloud.google.com/appengine/docs/standard/java/tools/using-maven
- https://cloud.google.com/appengine/docs/standard/java/tools/maven-reference

**Comment by chanseokoh** [comment]
@freeman-g However, one concern is that `spring-web` specifies Servlet >= 3.0. App Engine standard Java 7 doesn't support it, unless you switch to the Java 8 runtime which is in Beta.

**Comment by chanseokoh** [comment]
> I don't really get the resources and the child modules part, but I don't really get the resources list and the child module part, but I am guessing that `spring-web` cannot be found in `deployable.members()` but rather in `deployable.getChildModules()` below (not confirmed).

Confirmed. `deployable.members()` lists resources for a (root) module. The resources are of type `IModuleResource`. (BTW, the root module is a web module (`IWebModule`), which can also be thought of as a web fragment module (`IWebFragmentModule`).) Since `spring-web` is a web fragment (it has `META-INF/web-fragment.xml`), Eclipse WTP doesn't treat it as a module resource, but rather than a web fragment module, and puts it as a child module of the root module. This child module is listed by `deployable.getChildModules()`, and the following code on the module will print `spring-web-4.3.6.RELEASE.jar | ModuleType[jst.webfragment, 3.0]`.
```java
System.out.println(module.getName() + " | " + module.getModuleType())
```

This can be visualized when running such an app locally. An app will have `spring-web` as a child web fragment module:
![selection_030](https://user-images.githubusercontent.com/10523105/28835811-ad164024-76b4-11e7-8870-5c21b12639d0.png)

> I'm not an expert on the JEE spec/WTP, so it's not clear if this is a bug or working as intended, who's at fault, or who may possibly make this work.

Still true.

**Comment by elharo** [comment]
If  a maven deploy works here, I suspect the bug is in WTP and we should report it there.

If a maven deploy doesn't work, then it's likely a spring bug and we should report it to spring.

**Comment by briandealwis** [comment]
I believe this is our fault: `WarPublisher` needs to handle child modules somewhat like we do during the normal server publishing operations in `BasePublishOperation#execute()`.

**Comment by elharo** [comment]
OK, under that assumption marking it a high priority bug. Supporting spring is important.

**Comment by chanseokoh** [comment]
Managed to make this work, though not sure if it will be the way to go. I'll put up a PR soon.
