### ISSUE TITLE
Set error response code on deployment

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2235]
```
      IStatus deployStatus = deployProject(credentialFile, stagingDirectory, progress.newChild(70));
```

This  can result in

!MESSAGE ERROR: (gcloud.app.deploy) Error Response: [13] Deployment Manager operation failed, name: operation-1501854717878-555edccf69ef0-fbc59417-e33baca7, error: [{"code":"RESOURCE_ERROR","location":"/deployments/aef-default-20170804t095117/resources/aef-default-20170804t095117-hcfw","message":"{\"ResourceType\":\"compute.v1.firewall\",\"ResourceErrorCode\":\"404\",\"ResourceErrorMessage\":{\"code\":404,\"errors\":[{\"domain\":\"global\",\"message\":\"The resource 'projects/hellobrowser/global/networks/default' was not found\",\"reason\":\"notFound\"}],\"message\":\"The resource 
...

The IStatus should have its code field set to the error response code, 13 in this case.

**Comment by diego92sigma6** [comment]
Closing issue as not planned. Please reopen if needed
