### ISSUE TITLE
CT4E toolbar definition should be refactored

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2239]
The original CT4E toolbar definition (`com.google.cloud.tools.eclipse.appengine.actions`) needs refactoring:

  1. It's in the wrong bundle (`.appengine.ui`), 
  2. Its ID is misnamed since it's really for CT4E, and not just App Engine.
  3. It has the App Engine projects embedded within it too, whereas they should be contributed from `.newprojects`.

**Comment by elharo** [comment]
Agreed. I noticed some of this when I added the dataflow menu item, but figured we should get that in first.
