### ISSUE TITLE
Source attachment

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#224]
![image](https://cloud.githubusercontent.com/assets/1005544/15938206/3abace04-2e40-11e6-9577-ecf3ac104d2f.png)

It would be nice if we included sources for the jars we attach, e.g. servlet.jar, for easier debugging.

We might need to fix this in cloud SDK since that's where these jars come from.

**Comment by patflynn** [comment]
isn't this the generic servlet api?  Shouldn't it be pulled in from maven
central?

The fact that the servlet-api is in the java/lib is for the benefit of the
dev app server.

**Comment by elharo** [comment]
I noticed this in the non-Maven project, which does not pull from maven central.

**Comment by patflynn** [comment]
I thought there was a means of pulling maven central deps for Eclipse
native projects.

the appengine sdk tools/java/lib directory is an implementation detail of
the dev app server that probably should not be depended on.

**Comment by briandealwis** [comment]
There is this plugin that I've seen referenced elsewhere: https://github.com/ifedorenko/com.ifedorenko.m2e.sourcelookup
