### ISSUE TITLE
Cloud SDK v166 compatible on Windows?

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2257]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.3.0.201708031339
- Google Cloud SDK version: 159.0.0
- OS: Windows 10 10.0
- Java version: 1.8.0_121

does Cloud SDK v166 still have the issue with spaces in directory names causing deployment to fail on Windows 10?

**Comment by elharo** [comment]
Yes, it does. :-(
