### ISSUE TITLE
Name template default value

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2276]
In the dataflow new project wizard, the name template defaults to artifact ID. This should be shown in the dropdown menu when the wizard opens.

![image](https://user-images.githubusercontent.com/1005544/29312928-940ea752-8185-11e7-940e-ac45ebd31019.png)

Of course, we may prefer to simply remove this field and ask the user to type a project name instead. Blocking until we decide that.

**Comment by diegomarquezp** [comment]
Closing as not planned since dataflow is not supported.
