### ISSUE TITLE
Maven test dependencies are staged and cause deploy failure

### ISSUE THREAD

**Issue by Rhobal** [GoogleCloudPlatform/google-cloud-eclipse#2286]
- Cloud Tools for Eclipse version: 1.3.0.201708031339
- Google Cloud SDK version: 167.0.0
- OS: Windows 7 6.1
- Java version: 1.8.0_144

When I try to deploy my app, the staging directory contains maven _test_ dependencies are also written to the staging directory. This causes the deploy to fail because one of the test dependencies (jetty-server) requires Java 8.

I would expect that test dependencies are not deployed.

The same problem exists when publishing to the local WTP server; test dependencies are also written to the WEB-INF/lib directory. I have to manually delete three jars to remove a conflict before I can run the server.

**Comment by Rhobal** [comment]
After commenting out all test dependencies in the POM, I finally was able to deploy.

Of course, I had to open the problem view and delete ~1000 compile errors in the test classes caused by the missing dependencies, because otherwise I couldn't deploy due to #2253

**Comment by chanseokoh** [comment]
Did you properly put `<scope>test</scope>` in your pom.xml? It works well for me. For example, if I don't put the test scope, I see junit in `WEB-INF/lib`:

```
└── WEB-INF
   ...
    ├── lib
    │   ├── hamcrest-core-1.3.jar
    │   ├── jstl-1.2.jar
    │   └── junit-4.12.jar
```

If I put the scope, then I don't see it:

```
    ├── lib
    │   └── jstl-1.2.jar
```

**Comment by Rhobal** [comment]
`<scope>test</scope>` is present at every test dependency in the pim.xml. Is there an additional way to specify test scope?

Here are some lines out of my pom.xml:
```xml
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>5.2.4.Final</version>
		</dependency>
		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>javax.el</artifactId>
			<version>3.0.0</version>
		</dependency>
		<!-- Test Dependencies -->
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.hamcrest</groupId>
			<artifactId>hamcrest-all</artifactId>
			<version>1.3</version>
			<scope>test</scope>
		</dependency>
```

the junit-4.12.jar is also present in `WEB-INF/lib`

**Comment by chanseokoh** [comment]
It's hard to figure out what's going on without a reproducible sample. Could you provide us with a sample project? Get rid of all source/test files and unnecessary dependencies in pom.xml, and it may not be that difficult to get a small sample.

**Comment by chanseokoh** [comment]
Be careful not to include any sensitive information.

**Comment by chanseokoh** [comment]
Also check if there seems anything wrong with the WTP's deploy assembly settings. (project _Properties_ > _Deployment Assembly_).

![selection_049](https://user-images.githubusercontent.com/10523105/29387335-99414e7c-82ad-11e7-9038-b2cd6b1c7db4.png)

**Comment by Rhobal** [comment]
Is there a way to configure the Maven dependencies im Deployment Assembly 
to not include test dependencies? Otherwise it looks fine to me.

Mit AquaMail Android
http://www.aqua-mail.com gesendet


Am 17. August 2017 12:07:11 vorm. schrieb Chanseok Oh 
<notifications@github.com>:

**Comment by chanseokoh** [comment]
I think it should just work fine. I wonder if it's a problem of WTP or M2E.

Can you try with a very small app? Our App Engine Standard wizard can create a hello-world app with JUnit. (Check `Create as Maven Project` in the wizard.) If that app still has the problem, please try that in another machine. For me, it works well.

**Comment by briandealwis** [comment]
Might try from the project _Properties > Maven > Update Project…_.  It may be that m2e-wtp didn't pick up on the test sources properly.

**Comment by Rhobal** [comment]
When I run _Maven > Update Project_ with the _Update project configuration from pom.xml_ option, I lose the _Maven Dependencies_ in _Deployment Assembly_. When fix the Deployment Assembly manually and publish, the test dependencies are again all in the lib directory.

It seems similar to [Missing maven dependencies from deployment assembly on Stackoverflow](https://stackoverflow.com/questions/31148282/missing-maven-dependencies-from-deployment-assembly) with the additional issues of the test dependencies that are included.

**Comment by chanseokoh** [comment]
> When I run _Maven > Update Project_ with the _Update project configuration from pom.xml_ option, I lose the _Maven Dependencies_ in _Deployment Assembly_. When fix the Deployment Assembly manually and publish, the test dependencies are again all in the lib directory.

There may be a reason. A rough guess, your pom.xml has some explicit dependency copying or something like that?

Have you tested with a simple HelloWorld app? I am really curious if that works or not in you env or in other machines.

**Comment by Rhobal** [comment]
It works with the hello world app, test dependencies are not copied and updated. So its some issue with that project's configuration.

I'm closing this issue and try my luck with stackoverflow.
Thanks for all the help!

**Comment by briandealwis** [comment]
> @Rhobal: When I run Maven > Update Project with the Update project configuration from pom.xml option, I lose the Maven Dependencies in Deployment Assembly. 

Hmm, can you check that you have _m2e-wtp_ installed?  Keeping the _Deployment Assembly_ is one of its responsibilities.

**Comment by Rhobal** [comment]
@briandealwis thanks; I do have m2e-wtp.

In my case, it was a `pluginExecutionFilter` in the `pluginManagement` section (for m2e) in the pom.xml.
