### ISSUE TITLE
Concurrency flaw in Dataflow PipelineArgumentsTab UI class

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2289]
While I was working on #2232, I noticed that there is a concurrency flaw, which cannot easily be fixed unless we make a fundamental change to the overall workings of `PipelineArgumentsTab`.

The class can launch two types of async jobs: [hierarchy-update job from `updateHierarchy()`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.3.0B/plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java#L345) and [UI-update job from `updatePipelineOptions()`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.3.0B/plugins/com.google.cloud.tools.eclipse.dataflow.ui/src/com/google/cloud/tools/eclipse/dataflow/ui/launcher/PipelineArgumentsTab.java#L395).

- The hierarchy-update job calls `getPipelineOptionsHierarchy(majorVersion, progress)` asynchronously to get a new hierarchy, probably because it may take a long time.
   ```java
    Job job = new Job("Update Hierarchy") {
      @Override
      public IStatus run(IProgressMonitor progress) {
        hierarchy = getPipelineOptionsHierarchy(majorVersion, progress);
        return Status.OK_STATUS;
      }
    };
   ```
   So, `getPipelineOptionsHierarchy()` will run in a non-UI thread. However, the fundamental flaw is that the outcome of the method depends on the states of `PipelineArgumentsTab` (e.g., the `launchConfiguration` field); the states can be modified concurrently in another thread (in fact, the UI thread). It is not safe to call `getPipelineOptionsHierarchy()` asynchronously.

- The same kind of problem happens with the UI-update job too. It calls `launchConfiguration.getOptionsHierarchy(hierarchy)` in a non-UI thread, probably because it may take a long time.
   ```java
    Job job = new Job("Update Pipeline Options Form") {
      @Override
      protected IStatus run(IProgressMonitor monitor) {
        optionsHierarchyFuture.set(launchConfiguration.getOptionsHierarchy(hierarchy));
        return Status.OK_STATUS;
      }
    };
   ```
   However, `launchConfiguration` is a stateful object, whose states can be modified concurrently in the UI thread. It is not safe to access `launchConfiguration` asynchronously.

**Comment by chanseokoh** [comment]
@briandealwis don't forget that the root problem here is that access to `launchConfiguration` or calling `getPipelineOptionsHierarchy()` (a non-static method) should be synchronized (which effectively means everything in the both jobs becomes synchronized — basically there is no opportunity for parallelization at the current settings.) I think identifying and isolating which tasks can be safely parallelized is the first step, unless we decide to do everything synchronously with a blocking progress UI.

**Comment by briandealwis** [comment]
I did some instrumentation and `getPipelineOptionsHierarchy()` is fast  (about 100ms), and `PipelineLaunchConfiguration.getOptionsHierarchy()` was about 500ms to 1s.  The bulk of the time was in `PipelineOptionsFormComponent.updateForm()` which took between 1-2 seconds.
