### ISSUE TITLE
google cloud sdk not being recognised by google cloud platform tools

### ISSUE THREAD

**Issue by yorkshireandrew** [GoogleCloudPlatform/google-cloud-eclipse#2294]
17/8/2017 Installed eclipse oxygen and google cloud platform tools - when I try to build a google app project it indicates it needs google cloud sdk installing... I install this from https://cloud.google.com/sdk/ .. then gcloud components install app-engine-java add app-engine-java ...that adds the component .... in preferences tell Oxygen https://cloud.google.com/sdk/ the location... appData\local\google\cloud sdk (note the space) but oxygen refuses to recognise this as a valid cloud SDK

(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.3.0.201708031339
- Google Cloud SDK version: com.google.cloud.tools.appengine.cloudsdk.CloudSdkVersionFileNotFoundException: Cloud SDK version file not found at C:\Users\andrew\AppData\Local\Google\VERSION
- OS: Windows 10 10.0
- Java version: 1.8.0_112

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

(screenshots are helpful)

**Comment by yorkshireandrew** [comment]
I found an install.bat which I ran again in here, and set this as the path in oxygen... funny it now works...
C:\Users\andrew\AppData\Local\Google\Cloud SDK\google-cloud-sdk

**Comment by patflynn** [comment]
@elharo is this an documentation issue on the gcloud install side?

**Comment by patflynn** [comment]
@yorkshireandrew thanks for reporting this!  Did you notice that you'd missed a step for the windows Cloud SDK install? Or does this error happen after running the installer?
