### ISSUE TITLE
Servlet annotations in 3.1

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2297]
Should Java 8 App Engine sample code use servlet 3.x annotations such as `@WebServlet`? or continue to use web.xml for configuration?

**Comment by briandealwis** [comment]
I'll cast my vote for the annotation.  It could otherwise lead people to think that 3.1 support is incomplete.

**Comment by patflynn** [comment]
@lesv @ludoch for comment

**Comment by lesv** [comment]
Annotations - which one are you looking at?

**Comment by ludoch** [comment]
Yes, encourage annotations.

**Comment by elharo** [comment]
Sounds like everyone's on board for annotations.
