### ISSUE TITLE
Run verify-feature-completeness tests on nightly basis

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2298]
We have Travis configured to run the `verify-completeness-checks` on every push; this test verifies that the `com.google.cloud.tools.eclipse.e45.feature` feature can be installed from our packaged up repository (i.e., there are no missing dependencies).  It also installs alongside ADT, as we hit an issue earlier (#1678).  But ADT is downloaded for the test (that's 6 times per push, which is a bit expensive; we could try to cache it in `~/.m2`) and, as we discovered yesterday, can sometimes fail.

Rather than do it on every push, we could probably do this as a nightly job and pick up any dependency errors later.  Or, only do the ADT part of the test as a nightly.

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
