### ISSUE TITLE
Can't Create App Engine Project with Endpoints v2

### ISSUE THREAD

**Issue by supungscse** [GoogleCloudPlatform/google-cloud-eclipse#2308]
- Cloud Tools for Eclipse version: 1.3.0.201708031339
- Google Cloud SDK version: 166.0.0
- OS: Windows 7 6.1
- Java version: 1.8.0_144

I created a App Engine Standard Java Project with CTE plugin. I want to use endpoints v2, so I added the servlet node in web.xml with com.google.api.server.spi.EndpointsServlet. But, build fails with error " com.google.api.server.spi.EndpointsServlet could not be resolved". I checked the Build Paths in Eclipse, it is using appengine-endpoints-1.9.51.jar. Plugin and SDK is up to date, so why I doesn't it create projects with latest endpoints version?

![unnamed](https://user-images.githubusercontent.com/23624472/29492319-bb2dff4a-8595-11e7-981d-d4536905282b.png)

**Comment by elharo** [comment]
You're trying to use Endpoints v2 but you've added Endpoints v1 to the classpath. Try adding  com.google.endpoints:endpoints-framework:2.0.7 instead.  

We should make this clearer in the UI, and we do need to figure out what to do about v2.
