### ISSUE TITLE
Endpoints v2 support

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2310]
@lesv @patflynn "Cloud Endpoints Frameworks v1 has been deprecated and will be shut down on August 2, 2018. We recommend that you use the latest version of this feature, which is renamed to Cloud Endpoints Frameworks for App Engine. This new version supports App Engine standard environment..."

What should we do about Endpoints v2? Should we add it to the list of available libraries or replace the current endpoints v1?

It appears to run on App Engine Standard Java 7.

![image](https://user-images.githubusercontent.com/1005544/29494258-3e6f45e8-8574-11e7-9a07-142849433a30.png)

**Comment by patflynn** [comment]
@elharo l we should be including the v2 libraries by default.

@etanshaul FYI

**Comment by lesv** [comment]
Push people to v2, v1 is the exception.  (if you already have v1 code, you can keep it, but you shouldn't be creating new v1 code (except possibly to talk to other v1 code)

**Comment by patflynn** [comment]
+1

**Comment by elharo** [comment]
OK, updating to 2.0 now
