### ISSUE TITLE
Report staging-location creation errors

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2313]
In testing #2265, I specified a bucket named `blah.blah.blah`.  No validation error is reported in the UI, but the actual bucket creation fails (but the actual reason is never surfaced).

Before attempt to create bucket:
<img width="661" alt="screen shot 2017-08-21 at 10 11 42 pm" src="https://user-images.githubusercontent.com/202851/29545822-869fc3ba-86be-11e7-83e0-829c313ed0ef.PNG">

After attempt to create bucket:
<img width="666" alt="screen shot 2017-08-21 at 10 16 44 pm" src="https://user-images.githubusercontent.com/202851/29545834-9af5b93c-86be-11e7-89f2-0335ddbb6fec.PNG">

Looking with the debugger, the create-bucket fails with:
```
400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Bucket name contains \".\", but is not under a currently recognized top-level domain.",
    "reason" : "invalid"
  } ],
  "message" : "Bucket name contains \".\", but is not under a currently recognized top-level domain."
}
```

**Comment by elharo** [comment]
Guess what? We don't check this on deployment with a staging bucket either:

ERROR: gcloud crashed (UploadError): Error uploading files: HttpError accessing <https://www.googleapis.com/storage/v1/b/blah.blah.blah/o?alt=json&maxResults=1000>: response: <{'status': '404', 'content-length': '165', 'expires': 'Tue, 22 Aug 2017 10:27:29 GMT', 'vary': 'Origin, X-Origin', 'server': 'UploadServer', 'x-guploader-uploadid': 'AEnB2Up8JSW7ZS68r_txU25NeVreiMZdNI080at27nmetDGp9TeppPBqDbb1bnLuH4V5aLtAdm305VMomZ-i_MOqlm7btsn4jw', 'cache-control': 'private, max-age=0', 'date': 'Tue, 22 Aug 2017 10:27:29 GMT', 'alt-svc': 'quic=":443"; ma=2592000; v="39,38,37,35"', 'content-type': 'application/json; charset=UTF-8'}>, content <{


We should use the same corrected BucketNameValidator in both locations

**Comment by elharo** [comment]
Guidelines are here:

https://cloud.google.com/storage/docs/naming

**Comment by elharo** [comment]
We can put a com.google.cloud.tools.storage.BucketNameValidator in appengine-plugins-core similar to https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/master/src/main/java/com/google/cloud/tools/project/ServiceNameValidator.java

**Comment by briandealwis** [comment]
I realize this isn't an issue: I was confused on my part between the uses of _buckets_ and _staging locations_ in the code.  We do have a central `com.google.cloud.tools.eclipse.ui.util.databinding.BucketNameValidator` class, but we don't sufficient information available to us to determine that the dot-delimited bucket-name _is not under a currently recognized top-level domain_.  (Maybe `.blah` will become a new TLD.)

But we should report the validation error message to the user.  I'll repurpose this issue.

**Comment by elharo** [comment]
Guava has libraries for checking top-level domains: https://github.com/google/guava/wiki/InternetDomainNameExplained
https://google.github.io/guava/releases/22.0/api/docs/com/google/common/net/InternetDomainName.html
