### ISSUE TITLE
Development localhost server not considering port number

### ISSUE THREAD

**Issue by SetV** [GoogleCloudPlatform/google-cloud-eclipse#2332]
When 'Run on App Engine' option was selected from Google Cloud Platform menu. The localhost server was launched on default 8080 port.

Where as a different port of 8088 was specified in pom.xml 'com.google.cloud.tools' plugin's configuration.

'Run on App Engine' option need to consider port specified in pom.xml file.

**Comment by elharo** [comment]
The menu item for 'Run on App Engine' is not a maven task. It gets the port elsewhere. 

@parkjam4 Where are we on getting ports documented for then local server?
