### ISSUE TITLE
Using modules and a EAR project, can't upgrade to google-cloud-eclipse and SDK

### ISSUE THREAD

**Issue by mhopkins-dynactive** [GoogleCloudPlatform/google-cloud-eclipse#2340]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.3.0.201708031339
- Google Cloud SDK version: 168.0.0
- OS: Mac OS X 10.12.6
- Java version: 1.8.0_144

**What did you do?**
Tried to upgrade to gcloud eclipse with an EAR project. 

I have a project with the following as its application.xml file. 

`<?xml version="1.0" encoding="UTF-8"?>`

`<application xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://java.sun.com/xml/ns/javaee" xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/application_5.xsd" version="5">`

  ```
<display-name>Gaerdvark-EAR</display-name>

  <module>

    <web>

      <web-uri>GaerdvarkMain.war</web-uri>

      <context-root>gaerdvark-main</context-root>
    </web>

  </module>

  <module>

    <web>

      <web-uri>offline-course-generator.war</web-uri>

      <context-root>offline-course-generator</context-root>

    </web>

  </module>

  <module>

    <web>

      <web-uri>transcoder-notification-handler.war</web-uri>

      <context-root>transcoder-notification-handler</context-root>

    </web>

  </module>

</application>
````

I could not convert this project to a standard app engine project because it says 

> Failed to convert project "Container Project". One or more constraints have not been satisfied.
> EAR 5.0 and Java 1.7 cannot both be selected.

I did convert the other projects but now it seems like they have their own facets where they probably should not have facets. 

The reason why we have this configurations is because of this we converted legacy backends to services (modules). 

https://cloud.google.com/appengine/docs/standard/java/modules/converting

**What did you expect to see?**

I expected that when I right clicked the overall EAR project and chose configure and convert to standard app engine project that it would convert it and I would be ready to go. 

**What did you see instead?**

> Failed to convert project "Container Project". One or more constraints have not been satisfied.
> EAR 5.0 and Java 1.7 cannot both be selected.

I also get random 500 errors while running servlets such as 

> com.google.appengine.repackaged.com.google.common.collect.HashMultimap cannot access its superclass com.google.appengine.repackaged.com.google.common.collect.AbstractSetMultimap

I am also getting 403 errors which is weird also. :(

**Comment by elharo** [comment]
The EAR format is not supported by the Cloud SDK or Cloud Tools for Eclipse. You need to deploy each service individually.
