### ISSUE TITLE
has the issue with spaces in file paths been fixed in the lastest Goolge Cloud SDK

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2348]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.3.0.201708031339
- Google Cloud SDK version: 159.0.0
- OS: Windows 10 10.0
- Java version: 1.8.0_121

has the issue with spaces in file paths been fixed in the lastest Goolge Cloud SDK?
it seems like v159 is getting kind of old

**Comment by chanseokoh** [comment]
Unfortunately, no. The Cloud SDK v169 is still stuck with app-engine-java 1.9.54. This is expected to be fixed with 1.9.55+.

```
$ gcloud version
Google Cloud SDK 169.0.0
app-engine-java 1.9.54
app-engine-python 1.9.57
beta 2017.03.24
bq 2.0.25
cloud-datastore-emulator 1.2.1
core 2017.08.28
gcloud 
gsutil 4.27
```

FTR, this is about #2153.
