### ISSUE TITLE
Error dialog too tall

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2349]
Oxygen
CT4E 1.3.0

![image](https://user-images.githubusercontent.com/1005544/30068640-5f0fd85c-922c-11e7-969f-c49fb9e3b308.png)

**Comment by elharo** [comment]
This was in the new project wizard. Maybe it's height doesn't get sized right in this case?

**Comment by briandealwis** [comment]
The wizard dialog remembers its height from the last invocation.  My guess is that you previously resized it to be tall?  When I run from a fresh workspace, I see a regular-sized dialog.

<img width="1108" alt="screen shot 2017-09-05 at 4 46 44 pm" src="https://user-images.githubusercontent.com/202851/30082725-d554e520-9259-11e7-8048-3abc337a51b0.PNG">

**Comment by elharo** [comment]
Yes, also just verified that if I show the dialog at the correct size, move the cloud SDK,a nd reshow, it's the wrong size the second time only.

**Comment by elharo** [comment]
Perhaps `CloudSdkMissingPage` needs its height set explicitly somehow.

**Comment by chanseokoh** [comment]
It's tall in on my machine too.
