### ISSUE TITLE
Simple GCS bucket creation throws an exception

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2368]
Sample code: https://github.com/GoogleCloudPlatform/java-docs-samples/blob/master/storage/cloud-client/src/main/java/com/example/storage/QuickstartSample.java

```
java.lang.NoSuchMethodError: com.google.api.services.storage.model.Bucket.getBilling()Lcom/google/api/services/storage/model/Bucket$Billing;
	at com.google.cloud.storage.BucketInfo.fromPb(BucketInfo.java:944)
	at com.google.cloud.storage.Bucket.fromPb(Bucket.java:1130)
	at com.google.cloud.storage.StorageImpl.create(StorageImpl.java:107)
```

I tried the code in a plain Java 8 project after adding the GCS library through our _Build Path_ > _Add Libraries..._ feature. The exact same error also happens in App Engine Standard Java 7 and Java 8 projects when deployed.

The bucket is created despite the error, BTW.

**Comment by elharo** [comment]
I've seen this sporadically too. It may be an error in google-cloud-java or in our dependency tree.

**Comment by elharo** [comment]
I get 

Exception in thread "main" com.google.cloud.storage.StorageException: 401 Unauthorized

when I run that. Must be missing an auth somewhere.

**Comment by elharo** [comment]
We do pull in com/google/api/services/storage/model/Bucket but it doesn't appear to have a Billing inner class.
