### ISSUE TITLE
Build errors when adding GCS library and Translate library on App Engine project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2369]
1. Create a App Engine Standard Java 8 native project.
1. _Build Path_ > _Add Libraries_ > Add the GCS library and the Translate library.

Wait for a bit, and you'll see 6 build errors of a same kind. One of them is

`Invalid classpath publish/export dependency /.../.m2/repository/com/google/api-client/google-api-client/1.22.0/google-api-client-1.22.0.jar. The project contains another dependency with the same archive name.`

The errors go away when deleting the Translate library (through _Properties_ > _Java Build Path_). Interestingly, this doesn't happen on a plain Java project.

**Comment by chanseokoh** [comment]
Reproducible when add all the available libraries all at once. Also happens with a flex project.

**Comment by elharo** [comment]
We may have to drop translate until we fix this. It's not a trivial fix.
