### ISSUE TITLE
Library export conflict build error when adding Objectify and Cloud Core Client Library together

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2381]
The same error as in #2369, but with Objectify and Cloud Core Client Library on App Engine. This must have been like this (not a regression).

`Invalid classpath publish/export dependency /home/chanseok/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar. The project contains another dependency with the same archive name.`

**Comment by chanseokoh** [comment]
It seems like this error happens only between our library containers. If I place any duplicate JAR in `src/main/webapp/WEB-INF/lib` (JARs in this directory is handled by the Web App Libraries container as in the screenshot below) to a project that has only Objectify (without the Core Client library, i.e., no build error), it won't cause any conflict problem. All JARs in `WEB-INF/lib` are properly packaged, of course.

![selection_001](https://user-images.githubusercontent.com/10523105/30382732-f1c3f466-986d-11e7-9e4e-c04803cfdb26.png)

Maybe there is a simple way to avoid conflicts like the Web App Libraries container does?

**Comment by chanseokoh** [comment]
Ah, but then, from the above screenshot, the Web App Libraries container doesn't have the "Publish/export dependency: /WEB-INF/lib" entry. Maybe that's the difference that avoids conflicts.

**Comment by briandealwis** [comment]
It looks like #2347 caused Objectify and Guava libraries to be exported.  Objectify makes sense, but perhaps Guava can be kept _internal_.

Alternatively, we could package up Guava as a separate library so that it's included once?

**Comment by chanseokoh** [comment]
Not sure I follow what you mean keeping internal... When the Core library is added only (happens transitively when adding the GCS library), it also needs to export Guava to make it work.

Anyway, this time it is Guava, but I fear this may happen for any shared library and happen frequently as we add more libraries? Perhaps we should have a good solution for this and #2369? We talked about having a single large container yesterday in our meeting, but this time Objectify is out of the Cloud library boundary, so not sure if that means the single container should incorporate Objectify, Endpoints, etc, too?

**Comment by briandealwis** [comment]
[We weren't marking the Guava libraryFile as being exported previously](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2347/files#diff-87176adf0d08762ac94949ffe6278007R61).  So one possible fix is to revert exporting the other associated `libraryFiles`.

**Comment by elharo** [comment]
Was Objectify not working previously? I understand why this broke here, but not why the fix is so tricky. We should be able to revert this to the previous behavior, unless of course that behavior was also broken.

**Comment by chanseokoh** [comment]
Objectify by itself works fine. This happens only when adding Objectify and Cloud Core together. @briandealwis confirmed it was a problem in 1.3.0 too.

**Comment by elharo** [comment]
FYI this is how we can update a classpath container:

https://github.com/eclipse/m2e-core/blob/11922879173b8516103e935c574be289bc1cbe9c/org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/BuildPathManager.java

```

  public void updateClasspath(IProject project, IProgressMonitor monitor) {
    IJavaProject javaProject = JavaCore.create(project);
    if(javaProject != null) {
      try {
        IClasspathEntry containerEntry = getMavenContainerEntry(javaProject);
        IPath path = containerEntry != null ? containerEntry.getPath() : new Path(CONTAINER_ID);
        IClasspathEntry[] classpath = getClasspath(project, monitor);
        IClasspathContainer container = new MavenClasspathContainer(path, classpath);
        JavaCore.setClasspathContainer(container.getPath(), new IJavaProject[] {javaProject},
            new IClasspathContainer[] {container}, monitor);
        saveContainerState(project, container);
      } catch(CoreException ex) {
        log.error(ex.getMessage(), ex);
      }
    }
  }
```
