### ISSUE TITLE
Properties for Classpath container don't make sense

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2400]
1. Create new project and include some libraries such as Objectify.
2. Select Objectify in Project Explorer
3. Context Menu > Properties

![image](https://user-images.githubusercontent.com/1005544/30540748-7c2a76b2-9c46-11e7-80a9-e83221f76ff7.png)

**Comment by elharo** [comment]
For comparison here are the properties for the JUnit container:

![image](https://user-images.githubusercontent.com/1005544/30540945-2c2d15f6-9c47-11e7-9d3e-92ac99a80cca.png)

**Comment by elharo** [comment]
can hit this in other places too:

![image](https://user-images.githubusercontent.com/1005544/30548004-f348e748-9c5e-11e7-80e1-0d5dee7dfda1.png)

**Comment by elharo** [comment]
This may make a little more sense when we switch to a single container. We will need to check what is currently selected and set the checkboxes accordingly.

**Comment by elharo** [comment]
To check what is currently selected and set the checkboxes accordingly we need to save the list of libraries. I think we can do this as extra classpath attributes on our master container. 

In `CloudLibrariesPage` this is passed to the `initialize` method as `currentEntries`:

```
  @Override
  public void initialize(IJavaProject project, IClasspathEntry[] currentEntries) {
    this.project = project;
  }
```

More specifically it is the current entry with the path `com.google.cloud.tools.eclipse.appengine.libraries/master-container`.

When we add/remove a library to this path we should add/remove an `IClasspathAttribute` that notes the library ID. 

A classpath attribute defines a name/value pair that can be persisted with a classpath entry. Such an attribute can be created using the factory method `JavaCore.newClasspathAttribute(String name, String value)`.

**Comment by briandealwis** [comment]
The list of libraries is now persisted by #2436: see `LibraryClasspathContainerSerializer#loadLibraryIds()`. That list would make sense to be added as a classpath attribute.

**Comment by chanseokoh** [comment]
This makes sense now, as we now have a single master container.
