### ISSUE TITLE
Provide a link to open Cloud SDK preferences

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2403]
Some Eclipse users [are confused by our instructions](https://stackoverflow.com/questions/44877338/cloud-sdk-missing-error-on-eclipse-in-linux?rq=1) to configure the Cloud SDK location.  We should provide a link to open the appropriate preference page.

**Comment by briandealwis** [comment]
[Using underline-style links in `StyledText`](http://git.eclipse.org/c/platform/eclipse.platform.swt.git/tree/examples/org.eclipse.swt.snippets/src/org/eclipse/swt/snippets/Snippet356.java)

**Comment by elharo** [comment]
This should be obsolete with the managed SDK and I can no longer find this message in our code.
