### ISSUE TITLE
Project MiniSelector height is initially small

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2424]
I thought it could be a problem only on my Ubuntu, but today, I noticed that it also happens on Fedora. The combo restores it's proper size when I resize the dialog.

![screenshot from 2017-09-26 14 37 42](https://user-images.githubusercontent.com/10523105/30877655-5bbcf804-a2c8-11e7-96f5-b41aaa4237af.png)

**Comment by briandealwis** [comment]
It looks like AccountSelector's `Combo` has layout with vertical=`SWT.FILL`, whereas the MiniSelector's `Combo` uses `SWT.CENTER`.

**Comment by chanseokoh** [comment]
It's much better on Ubuntu, but characters like `j`, `p`, `q`, and `y` get clipped.

![selection_001](https://user-images.githubusercontent.com/10523105/30986083-51f5ae4e-a460-11e7-84f3-af33207fe814.png)

**Comment by briandealwis** [comment]
Odd as I just checked on Ubuntu 16.04 and the combos and letters (see the 'p' below) look fine.  I'm thinking this is a GTK3 bug…

<img width="655" alt="screen shot 2017-09-28 at 11 53 44 pm" src="https://user-images.githubusercontent.com/202851/31000311-af3afe0e-a4a8-11e7-9c4f-1d1db6532c25.PNG">

**Comment by chanseokoh** [comment]
Yeah, maybe a GTK3 bug. Doesn't happen when disabling it (SWT_GTK3=0). Let's close this.
