### ISSUE TITLE
Mini project selector and GCS bucket field enabled when using defaults in Dataflow launch config

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2430]
This is after fixing #2410.

If the _Use default Dataflow options_ is checked, all the controls are supposed to be disabled. However, the mini project combo selector is enabled, and this is fairly confusing. The GCS bucket field is (mostly?) disabled initially, but it can be made enabled when ticking/unticking the checkbox.

![selection_014](https://user-images.githubusercontent.com/10523105/30932515-b37bdcfe-a395-11e7-8acb-4070d9181471.png)

**Comment by briandealwis** [comment]
/me bangs head on wall

This situation arises as loading the default from the preferences into the `RunOptionsDefaultsComponent` which sets the project, which triggers a verification job. When the verification job completes, it triggers a validation of the `RunOptionsDefaultsComponent`, which seeing a valid account and project, re-enables the staging location.

That will account for the periodic test failures in #2378.

**Comment by briandealwis** [comment]
I realize that with #2375 the toggle-to-use-defaults doesn't actually make sense as the defaults may be incomplete.  The check button should really be a push button to _Load Defaults_.

**Comment by chanseokoh** [comment]
The enablement of `RunOptionsDefaultsComponent` is currently broken, and I see it will be more so after #3044. It's really time to fix this.

**Comment by chanseokoh** [comment]
The [i2430-correct-enablement branch](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/i2430-correct-enablement) is a fix, but I need to devise a test.
