### ISSUE TITLE
access compute engine via internal IP?

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2443]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.3.1.201709121426
- Google Cloud SDK version: 173.0.0
- OS: Windows 10 10.0
- Java version: 1.8.0_121

I noticed that v1.9.56 adds subnetwork_name but couldn't find any mention in the documentation here
https://cloud.google.com/appengine/docs/standard/java/config/appref

I was wondering if this new setting has anything to do with being able to access a Compute Engine VM via its internal IP address (assuming I can config GAE std to be on the same network).

An unrelated question: is there any chance I will be able to have GAE std deployed to multiple regions within the same project? We want a GAE std in US accessing databases in the US, with a European GAE std accessing databases in the EU. We want them on the same project so all of the security keys, and especially datastore tables and storage bucket permissions can be accessed by either. So 
eu.parasql.com hits app engine eurpoe (which has its databases in EU) while us.parasql.com hits app engine US central which is where the US databases are located. I appologize in advance if this is the wrong place to ask this question...

**Comment by patflynn** [comment]
@lesv can you comment on the questions from @Rob46 ?

Perhaps https://groups.google.com/forum/#!forum/google-appengine is a better forum?
