### ISSUE TITLE
doesn't create dataflow project

### ISSUE THREAD

**Issue by magicomajid** [GoogleCloudPlatform/google-cloud-eclipse#2447]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.3.1.201709121426
- Google Cloud SDK version: 162.0.1
- OS: Windows 10 10.0
- Java version: 1.8.0_121

**What did you do?**
create a project dataflow using the plugin

**What did you expect to see?**
when i click finish it should create the project

**What did you see instead?**
no process, no project is created

(screenshots are helpful)

**Comment by elharo** [comment]
Any error messages in the log by any chance?
