### ISSUE TITLE
Add JSTL when creating App Engine flex native project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2455]
For the _native_ flex project, we add only the servlet JAR. However, we add JSTL to Maven flex projects and all standard projects.

Fixing it seems simple; just add JSTL to the `CreateAppEngineFlexWtpProject.PROJECT_DEPENDENCIES` list.
```java
  private static final List<MavenCoordinates> PROJECT_DEPENDENCIES;

  static {
    MavenCoordinates.Builder servletApi = new MavenCoordinates.Builder()
        .setGroupId("javax.servlet") //$NON-NLS-1$
        .setArtifactId("javax.servlet-api") //$NON-NLS-1$
        .setVersion("3.1.0"); //$NON-NLS-1$
    PROJECT_DEPENDENCIES = Collections.singletonList(servletApi.build());
  }
```

**Comment by chanseokoh** [comment]
Turns out JSTL should have a different scope than `provided` (for which the current `servlet-api` is applicable), if we want to provide it on behalf of users: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2465#issuecomment-335545290

**Comment by elharo** [comment]
fixed
