### ISSUE TITLE
Clean up App Engine standard runtime ID and runtime type ID string literals

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2457]
- AppEngineStandardFacet:
```java
  static final String DEFAULT_RUNTIME_ID =
      "com.google.cloud.tools.eclipse.appengine.standard.runtime";
```
- LocalAppEngineServerDelegate
```java
  public static final String RUNTIME_TYPE_ID =
      "com.google.cloud.tools.eclipse.appengine.standard.runtime"; //$NON-NLS-1$
```
- AppToolsRuntime
```java
  static final String RUNTIME_TYPE_ID = "com.google.cloud.tools.eclipse.appengine.standard.runtime";
```

**Comment by elharo** [comment]
Please make sure we don't add any inter-bundle dependencies just to share strings.

**Comment by briandealwis** [comment]
There is a difference between a runtime type and a runtime, even if we used the same identifier.  They're in separate spaces at least.

**Comment by chanseokoh** [comment]
That's what I guessed. So I think we can get rid of one of `LocalAppEngineServerDelegate` or `AppToolsRuntime`? (They are in the same bundle and package.)

**Comment by briandealwis** [comment]
Makes sense.
