### ISSUE TITLE
Correct Icon for Cloud Libraries

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2459]
This functionality and dialog isn't App Engine specific. Figure out what icon we should use here. Maybe a general GCP icon? 

![image](https://user-images.githubusercontent.com/1005544/31222818-878819d0-a996-11e7-8869-fe9fb33bc993.png)

**Comment by patflynn** [comment]
why is the library branding inconsistent? For instance why isn't it 'Google
Cloud DNS'?

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
