### ISSUE TITLE
Unable to run AppEngine Java project in Eclipse Oxygen on Ubuntu

### ISSUE THREAD

**Issue by dloghin** [GoogleCloudPlatform/google-cloud-eclipse#2464]
- Cloud Tools for Eclipse version: 1.3.1.201709121426
- Google Cloud SDK version: 174.0.0
[
Google Cloud SDK 174.0.0
app-engine-java 1.9.57
app-engine-python 1.9.61
bq 2.0.27
cloud-datastore-emulator 1.2.1
core 2017.10.02
gsutil 4.27
]
- OS: Ubuntu 16.10, Linux 4.8.0-59-generic, x86_64
- Java version: 1.8.0_144 (Oracle)

**What did you do?**

When I want to Run or Debug my App Engine Java project, the server does not start. I just get a "<stopping...> GAE" in Eclipse console and the following mesage in /var/log/syslog:

: Oct 06, 2017 9:28:16 AM com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour stop
: WARNING: Error terminating server: Error connecting to http://localhost:8080/_ah/admin/quit
: com.google.cloud.tools.appengine.api.AppEngineException: Error connecting to http://localhost:8080/_ah/admin/quit
: #011at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.stop(CloudSdkAppEngineDevServer1.java:175)
: #011at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour.stop(LocalAppEngineServerBehaviour.java:140)
: #011at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerBehaviour.startDevServer(LocalAppEngineServerBehaviour.java:347)
: #011at com.google.cloud.tools.eclipse.appengine.localserver.server.LocalAppEngineServerLaunchConfigurationDelegate.launch(LocalAppEngineServerLaunchConfigurationDelegate.java:476)
: #011at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:885)
: #011at org.eclipse.debug.internal.core.LaunchConfiguration.launch(LaunchConfiguration.java:739)
: #011at org.eclipse.debug.internal.ui.DebugUIPlugin.buildAndLaunch(DebugUIPlugin.java:1039)
: #011at org.eclipse.debug.internal.ui.DebugUIPlugin$8.run(DebugUIPlugin.java:1256)
: #011at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
: Caused by: java.net.ConnectException: Connection refused (Connection refused)
: #011at java.net.PlainSocketImpl.socketConnect(Native Method)
: #011at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
: #011at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
: #011at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
: #011at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
: #011at java.net.Socket.connect(Socket.java:589)
: #011at java.net.Socket.connect(Socket.java:538)
: #011at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
: #011at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
: #011at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
: #011at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
: #011at sun.net.www.http.HttpClient.New(HttpClient.java:339)
: #011at sun.net.www.http.HttpClient.New(HttpClient.java:357)
: #011at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
: #011at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
: #011at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
: #011at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
: #011at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
: #011at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
: #011at com.google.cloud.tools.appengine.cloudsdk.CloudSdkAppEngineDevServer1.stop(CloudSdkAppEngineDevServer1.java:167)
: #011... 8 more

I'm using Eclipse Oxygen.1 Release (4.7.1). 

Any help is really appreciated. Thanks!

**Comment by chanseokoh** [comment]
- Don't you see any message in the "\<stopped\> App Engine Standard ..." console? Is it completely empty? Given that you saw the log in `/var/log/syslog`, the console must have shown some logs there too.
- You probably have other earlier logs about attempting to start a server in `/var/log/syslog`, because the log you copied above is about terminating the server. Can you search through it a bit more? The log may have been rotated, so check `syslog.1` (or `syslog.1.gz`) too.
- Do you see any relevant log when you go _Windows_ > _Show View_ > _Error Log_?
- I'd like to check if the server doesn't start either with the helloworld sample app generated by our CT4E plugin. Could you try the following steps and see if it works?
   1. Click the CT4E toolbar button > _Create New Project_ > _Google App Engine Standard Java Project..._
   1. Enter a project name. Click _Finish_.
   1. Right-click on the project > _Run As_ > _App Engine_

**Comment by chanseokoh** [comment]
OK, looking at the stack trace, it is indeed possible that you see nothing in the console and nothing else in `/var/log/syslog`. However, I am pretty confident that you will see a log entry "Google Cloud SDK: Error starting server: <reason for the failure>" in the _Error Log_ view.

**Comment by dloghin** [comment]
Indeed, I see nothing else in the console or in `syslog`. But I got this error from _Error Log_ view: 

Google Cloud SDK: Error starting server: java.nio.file.NoSuchFileException: /home/<user>/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/<project>/WEB-INF/appengine-web.xml

There is nothing in `/home/<user>/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/` folder.

As a side note (maybe I should add a new issue), when the server is not successfully started or if it encounters an exception and I want to run or debug again, I get the error `Launching <Config> has encountered a problem. Conflicts with running server "App Engine Standard at localhost" server port: 8080`

**Comment by chanseokoh** [comment]
Thanks for the update. You have `WEB-INF/appengine-web.xml` in your project, right?

If you do have it, I'd still like to confirm if the helloworld sample works well. If it is the case, your app or your project settings may have something particular that's causing the issue.

**Comment by dloghin** [comment]
I have solved it. Because I created the project on Windows, I had a linked folder with Windows style path (e.g. C:) in Eclipse `.project` file.

Indeed, HelloWorld is working and that is how I saw the difference in `.project` file. Thank you!
