### ISSUE TITLE
Change default admin port (8000)

### ISSUE THREAD

**Issue by deepfriedbrain** [GoogleCloudPlatform/google-cloud-eclipse#2466]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_.)

- Cloud Tools for Eclipse version: 1.3.1.201709121426
- Google Cloud SDK version: _(run `gcloud version`)_ 
Google Cloud SDK 174.0.0
app-engine-java 1.9.57
app-engine-python 1.9.61
bq 2.0.27
core 2017.10.02
gsutil 4.27

- OS: MacOS 10.12.6
- Java version: jdk1.7.0_80

**What did you do?**

Right click on the project > Run As > App Engine

**What did you expect to see?**

Run the project on the local webserver.

**What did you see instead?**

Error - Port 8000 is in use.

![image](https://user-images.githubusercontent.com/1531669/31327550-a4cac4f6-ad02-11e7-8668-199421c42f45.png)

I followed the instructions on this page (https://cloud.google.com/eclipse/docs/faq-set-host) but no matter what server port number I set, I got the error "Port 8000 is in use". Refer to the screenshot where I've changed the port to 8888, but it still gave me the same error about port 8000.

![image](https://user-images.githubusercontent.com/1531669/31327654-4120b6ee-ad03-11e7-9557-b52b4b24470e.png)

After going through other issues on this repo, I understand that port 8000 is the admin port, but I have no idea how to change it. I tried setting it in the Run Configuration, but whatever I add in the Run Configuration is simply ignored. I manually killed the process on my system that was using port 8000 and then I was able to run the application. I can change the Server port using the FAQ instructions, but I don't see any way to change the admin port.

So, how do I change the default admin port? 

I'm using a fresh installation of Eclipse Neon. I imported my project, which was based on Google App Engine plugin for Eclipse. My objective is to migrate to Google Cloud Tools for Eclipse. 

Thanks.

**Comment by elharo** [comment]
Can you figure out what's using port 8000 and shut that down? 

```
sudo lsof -i
sudo netstat -lptu
sudo netstat -tulpn
```

**Comment by chanseokoh** [comment]
Seems like a bug. The dev appserver1 doesn't use a separate admin port but shares the service port, AFAIK.

**Comment by elharo** [comment]
I don't know that the admin port is involved here.

**Comment by deepfriedbrain** [comment]
As I said in the original post, I killed the process (something called irdma) running on port 8000 (identified it using netstat and lsof commands) and then I could start the server. But when I shutdown the server, the original process automatically started again on the same port 8000. So I have to kill it every time before running the app engine server.

**Comment by chanseokoh** [comment]
Easy to reproduce. Occupy 8000 (e.g., `nc -l 8000`) and run.

dev_appsever1 doesn't use 8000. No problem occupying 8000 when it is running. The error message is wrong and should be gone.

dev_appserver1 console logs that it uses `/_ah/admin/ is the admin page on 8080 by default:
```
Oct 09, 2017 4:27:16 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:8080/
Oct 09, 2017 4:27:17 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:8080/_ah/admin
Oct 09, 2017 12:27:17 PM com.google.appengine.tools.development.DevAppServerImpl doStart
INFO: Dev App Server is now running
```

It is dev_appserver2 that by default takes 8000 for the admin page:
```
Running dev_appserver.py.
INFO 2016-09-22 16:43:14,981 devappserver2.py:769] Skipping SDK update check.
INFO 2016-09-22 16:43:15,068 api_server.py:205] Starting API server at: http://localhost:64781
INFO 2016-09-22 16:43:15,072 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO 2016-09-22 16:43:15,074 admin_server.py:116] Starting admin server at: http://localhost:8000
```

**Comment by deepfriedbrain** [comment]
You are right. I confirmed that I can access the admin console from my updated port (8888) at http://localhost:8888/_ah/admin and the main app from http://localhost:8888/. So, the validation and the related error for port 8000 seems to be a bug.
