### ISSUE TITLE
Error in dataflow project pom.xml

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2479]
Description	Resource	Path	Location	Type
org.apache.maven.archiver.MavenArchiver.getManifest(org.apache.maven.project.MavenProject, org.apache.maven.archiver.MavenArchiveConfiguration)	pom.xml	/gf	line 1	Maven Configuration Problem

seems to build at command line. Not sure what the error really is here. Message isn't very helpful.

![image](https://user-images.githubusercontent.com/1005544/31496334-f6bcc188-af28-11e7-9bd6-56eee8e1e8ae.png)

**Comment by chanseokoh** [comment]
I remember this. Probably a bug of M2E: https://stackoverflow.com/a/38098828/1701388. The workaround is to upgrade M2E, or downgrade `maven-jar-plugin`.

**Comment by chanseokoh** [comment]
Indeed, if we change the `maven-jar-plugin` version to 2.6, the error goes away.

**Comment by elharo** [comment]
OK, may not be our bug then. Closing.
