### ISSUE TITLE
JSTL in both WEB-INF/lib and runtime

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2483]
Two copies of the same jstl-1.2.jar at different paths in the file system. New AES 8 standard project.

![image](https://user-images.githubusercontent.com/1005544/31508869-72320f16-af4d-11e7-8985-d1c11f5779ad.png)

**Comment by briandealwis** [comment]
Fixed by clearing configuration area prior to launch.
