### ISSUE TITLE
new subnetwork_name setting in appengine-web.xml

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2495]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.3.1.201709121426
- Google Cloud SDK version: 173.0.0
- OS: Windows 10 10.0
- Java version: 1.8.0_121

I saw in Updated Java SDK to version 1.9.56 "For flexible runtimes compatible with the App Engine standard environment APIs (compat runtimes), this SDK version includes updates to the appengine-web.xml file configuration to add support for subnetwork_name, session_affinity, and updated liveness and readiness health checks."

Where is the documentation for this... especially the subnetwork_name ... I'm wondering if this allows me to specify that my GAE Std is in the same network space as my Compute Engine instances... or is this something else?

**Comment by elharo** [comment]
You can file  a bug on the relevant cloud.google.com docs page if you're logged in.

**Comment by briandealwis** [comment]
@Rob46 the text notes that it's for _flexible_, not standard, and more specifically for the compat runtimes which are deprecated.
