### ISSUE TITLE
Library versions are updated only when adding libraries to native projects (i.e., no chance for Maven users)

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2499]
(From https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2481#issuecomment-336262415. Forgot to create an issue then.)

We lazily update library versions to the most recent releases. However, the only point we update them is when adding libraries to native projects. That is, if users always work on Maven projects, they will be bound to use the pre-defined versions in `libraries.json`, as they won't have a chance to update versions.

**Comment by elharo** [comment]
Good catch. We should fix this, but it's not a release blocker IMHO.

**Comment by elharo** [comment]
I think we can reasonably do this in `BuildPath.addMavenLibraries` and/or the methods it calls.

**Comment by chanseokoh** [comment]
I also think this is not a release blocker. How about holding off fixing this until the next release?
