### ISSUE TITLE
Problem when removing Google APIs container and adding new libraries later

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2523]
1. Create a Java project.
1. Add Endpoints.
1. Right-click on the _Google APIs_ container > _Build Path_ > _Remove from Build Path_. The container will be gone.
1. Add Objectify.

Open the container, and note that the Endpoints revived.

The problem is that the `_libraries.container` and `master-container.container` JSONs are not purged when removing the container. If there is a way to hook into the event of a container being removed by any means, we could potentially remove the files together. Not sure if there is such an event we can use.

But I can think of another easy way: when adding the container to a project that does not already have it, just purge those JSONs. I am trying this way, and I think I can make it work soon.

**Comment by chanseokoh** [comment]
Hmm... seems like we can detect classpath changes: https://stackoverflow.com/questions/10173053/how-to-detect-changes-to-eclipse-classpath-container-contents

**Comment by elharo** [comment]
This should be resolved by @briandealwis's work on a more reasonable way to remove libraries.

**Comment by elharo** [comment]
#2523 helped, but didn't completely fix this. If you follow the steps above, the endpoints library comes up selected in the Add Library dialog and must be manually deselected.

Still a low priority fix though.

**Comment by chanseokoh** [comment]
Yeah, I think this is a low priority, given that at least the library is pre-checked.

**Comment by briandealwis** [comment]
I had to [back out that commit](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2553#issuecomment-344054071).
