### ISSUE TITLE
Should we export appengine-api-1.0-sdk JAR? Or place it under `WEB-INF/lib`?

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2531]
Stemmed from #2530.

AFAIK, appengine-api-1.0-sdk doesn't have to exported, much like the servlet JAR; it is provided in prod. However, the dev appserver doesn't provide it — I verified NoClassDefFoundErrors when trying to use it. So, the JAR should be exported locally, or somehow the dev appserver should be able to load it at the same level where apps are loaded.

Before 1.4.0, I believe the JAR was being exported (whether or not we intended) for native projects. We had separate containers for libraries, and I believe some base containers (like the Cloud Core Libraries) must have had the appengine-api-1.0-sdk JAR in them. All of the JARs in library containers must have been exported.

After 1.4.0, we pushed the JAR into the App Engine Standard Runtime container and made it not exported. Users will start to hit #2530. This happens for both native and Maven projects.

The easiest (and maybe a common) solution is to mark the JAR to be exported. The deploy staging scrubs off the JAR by the deploy staging, so this won't cause any trouble. It's just that exporting the JAR is conceptually not correct.

**Comment by elharo** [comment]
Is this is really an issue for everyone on every local run that refers to these classes, then it's worth a 1.4.1 release.

How sure are we it's that bad? Will a new project created in 1.4.0 work or is this only for converted projects? (It wasn't clear to me the initial reporter had converted their project.)

**Comment by chanseokoh** [comment]
I think it affects everyone on every local run. New projects won't work, as we no longer export it (`export="false"` in `plugin.xml`). Converted projects don't seem to work either, which is not surpeising, as we saw in the user report.

I vaguely remember we briefly agreed that the dev appserver really should provide the JAR, but I guess that's not going to happen soon.

**Comment by elharo** [comment]
OK, let's work around this then.

**Comment by elharo** [comment]
b/68205805

**Comment by elharo** [comment]
Definitely happens in Maven too. Here's a simple class that can demo the problem:

```
package com.google;

import java.io.IOException;

import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.google.appengine.repackaged.org.joda.time.DateTime;


@WebServlet(
    name = "HelloAppEngine",
    urlPatterns = {"/hello"}
)
public class HelloAppEngine extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
      
	  DateTime dt = new DateTime();
 
    response.setContentType("text/plain");
    response.setCharacterEncoding("UTF-8");

    response.getWriter().print("Hello App Engine on " + dt + "\r\n");

  }
}
```

**Comment by chanseokoh** [comment]
Per the discussion in https://issuetracker.google.com/76144204, we may need to revert #2533.
