### ISSUE TITLE
Attach source for appengine-api-1.0-sdk.jar

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2540]
![image](https://user-images.githubusercontent.com/1005544/32082847-5f3e328c-ba8c-11e7-8232-cd78edc6c6af.png)

**Comment by chanseokoh** [comment]
They don't publish source JARs on Maven Central: https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.appengine%22%20AND%20a%3A%22appengine-api-1.0-sdk%22

The App Engine SDK zip (~200 MB) does contain a source JAR though.

**Comment by elharo** [comment]
b/68379022

**Comment by ludoch** [comment]
Today, we are making https://github.com/GoogleCloudPlatform/appengine-java-standard public and push artifacts from there to maven, including javadocs and sources

**Comment by ddixit14** [comment]
This issue is now unblocked.
