### ISSUE TITLE
Google App Engine Standard Project Generated by Google Cloud Tools for Eclipse missing logging.properties from old plugin

### ISSUE THREAD

**Issue by jamesmortensen** [GoogleCloudPlatform/google-cloud-eclipse#2541]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.3.1.201709121426
- Google Cloud SDK version: 173.0.0
- OS: Mac OS X 10.12.6
- Java version: 1.8.0_101

**What did you do?**
Generated a new Google App Engine Standard Project

**What did you expect to see?**
Expected to see a logging.properties file in the WEB-INF folder, just like with the old Eclipse plugin.

**What did you see instead?**
No logging.properties file and no clear way to quickly and easily adjust the logging level of what I see in Eclipse.

<img width="351" alt="screen shot 2017-10-27 at 11 10 32 am" src="https://user-images.githubusercontent.com/1315816/32089644-d3d33008-bb08-11e7-906a-20822b7940fc.png">

(screenshots are helpful)

**Comment by jamesmortensen** [comment]
For context, we used to increase the logging level to "ALL" so that we could see the scratch dir.  The scratch dir contained all of the JSP files compiled to Java.  It was a nice way to be able to explain to new engineers what was happening with JSP by showing them the JSP compiled to Java.

It was also helpful for other reasons, not just this.  But this was the specific use case that prompted me creating this issue.  Hope the context helps!

**Comment by elharo** [comment]
see https://cloud.google.com/appengine/docs/standard/java/logs/

**Comment by jamesmortensen** [comment]
Thanks @elharo we'll just do that for now. 

 I think the request would still be helpful to just have that work out of the box like it did in the last plugin.  Cheers!

**Comment by elharo** [comment]
FYI WARNING and INFO level messages re shown in the console by default. You only need this if you want to see lower priority messages.
