### ISSUE TITLE
Drop support for Mars

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2557]
This issue is, for now, for tracking thoughts. If this is going to cause major problems for anyone, please do comment below.

When Mars usage drops low enough, eliminate support for it.

Disadvantages:

  * Lose anyone still using Java 7
  * Lose anyone still committed to Mars

Advantages:

  * Can move appengine-plugins-core and rest of build to Java 8
  * Moving to Java 8 lets us move to Tycho 1.0
  * cut 1/3 of our Travis CI and flakes
  * Can use Submonitor.split() instead of newChild
  * LDP Dockertools requires Neon: https://marketplace.eclipse.org/content/eclipse-docker-tooling#group-details
  * Bring Guava to 21 or later
  * `private final WritableList/* <GcpProject> */ input; // Generics supported only in Neon+`

[LSP support](https://developers.redhat.com/blog/2016/11/24/deliver-support-for-new-languages-in-eclipse-ide-faster-with-generic-editor-and-language-servers/) is also interesting but would require us to drop Neon too.

Maybe when Photon is released in 2018?

**Comment by briandealwis** [comment]
> cut 1/3 of our Travis CI and flakes

We'd probably add Photon instead.

**Comment by elharo** [comment]
I suppose then we'd cut a quarter of the flakes we'd get if we kept all four. :-)
