### ISSUE TITLE
WebProjectUtil.getWebInfDirectory() doesn't always work as expected

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2564]
I've got curious about https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1557#issuecomment-342517225; I can reproduce it whenever importing the [bookshelf-standard sample](https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/bookshelf-standard/2-structured-data) into Eclipse.

It turns out `WebProjectUtil.getWebInfDirectory()` sometimes doesn't work, and in this case it was returning `/target/m2e-wtp/web-resources/WEB-INF` instead of the correct `/src/main/webapp/WEB-INF`.

Surprisingly, the result depends on the order of XML elements in `.settings/org.eclipse.wst.common.component`. For example, if we have `<wb-resource deploy-path="/" source-path="/src/main/webapp" tag="defaultRootSource"/>` before `<wb-resource deploy-path="/" source-path="/target/m2e-wtp/web-resources"/>` like below

```xml
<?xml version="1.0" encoding="UTF-8"?>
        ...
        <wb-resource deploy-path="/" source-path="/src/main/webapp" tag="defaultRootSource"/>
        <wb-resource deploy-path="/" source-path="/target/m2e-wtp/web-resources"/>
        <wb-resource deploy-path="/WEB-INF/classes" source-path="/src/main/java"/>
        ...
    </wb-module>
</project-modules>
```

then it returns "/src/main/webapp", which is what we want. But if the two `wb-resource` elements are switched, then "/target/m2e-wtp/web-resources" is returned.

Our code makes use of `getRootFolder()`, and it may be just returning the first root (`deploy-path="/"`).

```java
    if (component != null && component.exists()) {
      IVirtualFolder root = component.getRootFolder();
      ...
        return (IFolder) root.getFolder(WEB_INF).getUnderlyingFolder();
```

There should be a way to get the path tagged with `defaultRootSource`. Not sure if that's possible.

**Comment by chanseokoh** [comment]
`DeployAssemblyEntryRemoveJob.run()` and `WebXmlValidator.validateJsp()` also use the same logic to get the root, so they probably suffer from the same issue.

**Comment by chanseokoh** [comment]
`J2EEModuleVirtualComponent.getDefaultDeploymentDescriptorFolder(component.getRootFolder())` is to the rescue.

Other misc facts:
- The `IVirtualComponent` we get through `ComponentCore.createComponent(project)` is actually `J2EEModuleVirtualComponent`. We can directly cast its type or use `getAdapter()`. We don't need it thought.
- `component.getRootFolder().getUnderlyingFolders()` indeed lists all folders, while `getUnderlyingFolder()` just gets the first folder in the list.

**Comment by elharo** [comment]
Good detective work.

**Comment by briandealwis** [comment]
So basically the situation is as follows:
  - Retrieving files should follow the order of the `<wb-resource>` elements in `org.eclipse.wst.common.component` ([1](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448544), [2](https://bugs.eclipse.org/bugs/show_bug.cgi?id=437441)).  The means that 
  - Creating files should be placed in the `defaultSourceRoot` ([1](https://bugs.eclipse.org/bugs/show_bug.cgi?id=121460#c12))

So I'll change `WebProjectUtil` to provide operations to find and create files within `WEB-INF`.

That said, the configuration in @chanseokoh's motivating example:
```
    <wb-resource deploy-path="/" source-path="/src/main/webapp" tag="defaultRootSource"/>
    <wb-resource deploy-path="/" source-path="/target/m2e-wtp/web-resources"/>
```
runs counter to what should be the [expected case with _m2e-wtp_](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448544), behaviour that was [fixed for m2e-wtp 1.2.0 / Mars](https://bugs.eclipse.org/bugs/show_bug.cgi?id=437441).

**Comment by briandealwis** [comment]
I wonder if our appengine facet installation is interfering and changing the order here…

**Comment by chanseokoh** [comment]
I think our `WebProjectUtil.getWebInfDirectory()` should always returns the path with the `defaultRootSource` tag, regardless of what the WTP implementation does with publishing or what the order of `web-resource` is. I expect it to be the contract of `getWebInfDirectory()` (which actually means `getWebInfDirectoryInSourceRepo()`).

**Comment by briandealwis** [comment]
Changing the behaviour of `getWebInfDirectory()` as you described is contrary to the expectations documented in [bug 448544](https://bugs.eclipse.org/bugs/show_bug.cgi?id=448544) and would break m2e-wtp's popular resource filtering.  This filtering allows replacing strings like `${maven.properties}` within files like `web.xml` with properties resolved from the project's `pom.xml`.  m2e-wtp is careful to ensure that its filtered directory is put ahead of the project's WEB-INF directory.

**Comment by chanseokoh** [comment]
It is our method that we wholly own, which is called only by us for our convenience. The contract can be whatever we want to be for our purposes. I think almost all of our usage of `getWebInfDirectory()` has an assumption that it always returns `WEB-INF` in user's project, not `target/m2e-wtp/web-resources/WEB-INF`, which is happening right now.

- `StandardFacetInstallDelegate.createConfigFiles()`: we want to create `appengine-web.xml` under `src/main/webapp/WEB-INF`, not `target/m2e-wtp/web-resources`.
- `CreateAppEngineWtpProject.addJstl12ToClasspath()`: we want to put the JSTL JAR under ``src/main/webapp/lib`, not `target/m2e-wtp/web-resources/lib`.

If you think you need a behavior of what you described, then I think you should just create a new method with a different name than `getWebInfDirectory()`. Otherwise, what should be fixed first I think is to have a method `getWebInfSourceDirectory()` that always returns `src/main/webapp/WEB-INF`, and fix a lot of code (such as `StandardFacetInstallDelegate.createConfigFiles()`) to switch from `getWebInfDirectory()` to `getWebInfSourceDirectory()`.

**Comment by briandealwis** [comment]
> If you think you need a behavior of what you described, then I think you should just create a new method with a different name than getWebInfDirectory().

Yup: there is no one right directory for `WEB-INF`.  Maven may filter multiple files, and may not filter others.  Fundamentally we're trying to resolve files, so we should just let the virtual component model resolve them and respect its rules when creating them.
