### ISSUE TITLE
Support editing and removing libraries for Maven projects

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2567]
Following on #2553, the Google APIs container page allows adding new libraries to a Maven project, but doesn't support editing or removing libraries.  

We could slurp up the libraries from the `pom.xml` to set the current selection.  Removal should be relatively easy.  But what should happen if they use a different version of the libraries?  Do we preserve the versions of the existing libraries?  Or write out everything with the new versions?

We could punt on supporting Maven projects entirely and instead shown an error message directing the users to the POM editor, and `setPageComplete(false)`.

**Comment by elharo** [comment]
I'm not sure why version is an issue. If they have one in place, leave it. If they don't add the most current.

**Comment by briandealwis** [comment]
I'll admit that this is a theoretical risk, but mixing versions may introduce dependency conflicts as we're essentially mixing BOMs.  For example, `com.google.cloud:google-cloud-pom` [0.20.0-alpha](https://repo1.maven.org/maven2/com/google/cloud/google-cloud-pom/0.20.0-alpha/google-cloud-pom-0.20.0-alpha.pom) (released June 15) relies on Guava 19.0, whereas [0.28.0-alpha](http://search.maven.org/remotecontent?filepath=com/google/cloud/google-cloud-pom/0.28.0-alpha/google-cloud-pom-0.28.0-alpha.pom) relies on Guava 20.0.

At least conflicting dependencies is an understood problem and there are ways to manage it with `<dependencyManagement>`.

The alternative is to update all `com.google.cloud` artifact versions.  But that risks API changes and possibly behaviour changes.

**Comment by chanseokoh** [comment]
We are already mixing versions for native projects (you added 0.20.0-alpha the other day, and a month later, when you add another library, its version could be 0.28.0-alpha), so doing so in Maven is not a new risk. IMO, the version conflict problems are real, and we haven't implemented a good solution but taken the most simplest approach to always add most recent versions.

**Comment by elharo** [comment]
This is a FIXME at line 186 of `CloudLibrariesPage`.
