### ISSUE TITLE
Adding Cloud libraries to Maven projects results in errors

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2583]
Not sure if it's the problem only on my machine.

It doesn't matter if you add it to a plain Java Maven project or an App Engine Maven project.

![selection_002](https://user-images.githubusercontent.com/10523105/32810039-435607c2-c967-11e7-8709-f13cea959d9f.png)

Interestingly, for an App Engine project, the problem goes away after ALT+F5 (_Maven_ > _Update Project..._). Doesn't work on a plain Java project.

**Comment by chanseokoh** [comment]
- Not every Cloud library has the problem, but many (e.g., Cloud Speech) will trigger this.
- ALT+F5 seems to work only on App Engine standard projects. Doesn't work on App Engine flex or plain Java projects.

**Comment by chanseokoh** [comment]
I can't reproduce it either on my desktop, so maybe this is some cache issue on my laptop.

**Comment by briandealwis** [comment]
`BuildPath.addMavenLibraries()` writes content using the Resources `IFile#setContents()` via `Pom.writeDocument()`.  You might be able to simulate this by editing the `pom.xml`, adding the deps, and then saving.

Are there any errors on the log?

**Comment by chanseokoh** [comment]
The errors didn't make sense. All the JARs are already in my .m2 cache.

Problem gone after updating my target platform. Glad I made it work on my laptop again. I'll close this.
