### ISSUE TITLE
ErrorProne checks on each PR

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2608]
Is there a Github hook for this?

**Comment by patflynn** [comment]
almost certainly not since it uses javac. You'll have to hook this into your CI, which is easy for Maven.

**Comment by briandealwis** [comment]
I'm not sure how easy this will be for us since Tycho uses Eclipse's JDT compiler, and is responsible for computing a classpath based on the OSGi manifests.  It might work if we explicitly configure the maven-compiler-plugin and associate it to a later goal.

**Comment by briandealwis** [comment]
Here's the configuration block used in [appengine-plugins-core](https://github.com/GoogleCloudPlatform/appengine-plugins-core/blob/57bf4efb101e8e93cd23b0a3e8ac56b15af13625/pom.xml#L119).
