### ISSUE TITLE
Do we have a diamond dependency problem?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2609]
Not sure. May just need a target platform rebuild, but I noticed my workspace has picked up multiple versions of several jars in googleapis:

![image](https://user-images.githubusercontent.com/1005544/33399908-3e8fc4e6-d522-11e7-8229-abf9daff083b.png)

**Comment by chanseokoh** [comment]
For the jars in this `lib` directory, delete all the 1.22.0 jars. They are left uncleaned in your local machine after upgrading to 1.23.0.

**Comment by elharo** [comment]
OK. Done.
