### ISSUE TITLE
Project selector doesn't fill space

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2612]
I noticed too much vertical space between the project selector and the service account key field. I added a border to verify that it's the project selector that's too short:

![image](https://user-images.githubusercontent.com/1005544/33429785-3ead4186-d59c-11e7-9946-c091d642d004.png)

What seems to be happening is that the empty table view doesn't occupy its full available space. When projects are added, it grows a bit and occupies the full space:

![image](https://user-images.githubusercontent.com/1005544/33430076-37ef275a-d59d-11e7-8158-6c8d1bcf4ade.png)

We should figure out how to make sure the empty table view is initially sized the same as the full table view.

**Comment by lak-proddev** [comment]
The additional space in the empty table is for a status link. Which should be hidden by default. 

![image](https://user-images.githubusercontent.com/39690425/57772968-84b57500-7734-11e9-8f2b-62f9a0d7de2c.png)
