### ISSUE TITLE
slf4j warnings

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#263]
These warnings litter our build and are annoying and confusing and pointless:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

Figure out a way to get rid of them without introducing any new dependencies.

**Comment by briandealwis** [comment]
Should be able to include `org.eclipse.m2e.maven.runtime.slf4j.simple` in the ide-target-platform

**Comment by briandealwis** [comment]
Sadly including `org.eclipse.m2e.maven.runtime.slf4j.simple ` was not the easy fix I had hoped — it is a hack to pull in a logger.  As Logback was already in Orbit, I just pulled it in instead.

**Comment by chanseokoh** [comment]
Reopening. I have a bad feeling that we will keep reopening this as we continue to add bundles.

**Comment by briandealwis** [comment]
I can think of a few approaches to handling this.  One is to create our own internal minimal testing feature that includes these minimal bundles.  Another is to gather different types of tests into different directories (e.g., `/tests/workbench-based`, `/tests/simple`?) and then use the module inheritance to configure the dependencies.
