### ISSUE TITLE
Add Libraries dialog window should scroll

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-eclipse#2641]
When I adjust the size of the dialog, I see that the window does not scroll.

<img width="614" alt="scroll" src="https://user-images.githubusercontent.com/11820506/33684240-9c6f92c0-da9b-11e7-8e29-43b0ef396a15.png">

**Comment by elharo** [comment]
Yes, we probably should add a scroll pane.

**Comment by elharo** [comment]
We need a mock for how this will work.

**Comment by chanseokoh** [comment]
Fixed by #2643.
