### ISSUE TITLE
No project in Dataflow run configuration bad message

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2645]
Notice project isn't set:

![image](https://user-images.githubusercontent.com/1005544/33713748-788194b0-db1a-11e7-9d8a-0f604a4cb9d8.png)

Here's the error on run:

![image](https://user-images.githubusercontent.com/1005544/33713766-86a2dd06-db1a-11e7-8c37-c48883a47b07.png)

Ideally we should disable the run until the project is set, but if not we should at least give a better error message in this case.

**Comment by briandealwis** [comment]
This is fixed as part of the fix for #2232.

**Comment by chanseokoh** [comment]
Seems fixed by #2232.
