### ISSUE TITLE
Refactor PipelineArgumentsTab.updatePipelineOptionsForm()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2650]
I think the future is completely unnecessary here and solely remains there to increase complexity with no good reason.

`getLaunchConfigurationDialog().run()` returns only after `optionsHierarchyFuture.set(launchConfiguration.getOptionsHierarchy(hierarchy)` is done, which is the most expense call that we wrap. Once the future set, the UI will run the future listener code almost immediately. We should just run the listener code after `run()`.

```java
  private void updatePipelineOptionsForm() {
    final SettableFuture<...> optionsHierarchyFuture = SettableFuture.create();
    optionsHierarchyFuture.addListener(new Runnable() {
      @Override
      public void run() {
        ...
      }
    }, displayExecutor);

    try {
      // blocking call (regardless of "fork"), returning only after the inner runnable completes
      getLaunchConfigurationDialog().run(true, true, new IRunnableWithProgress() {
        @Override
        public void run(IProgressMonitor monitor)
            throws InvocationTargetException, InterruptedException {
          optionsHierarchyFuture.set(launchConfiguration.getOptionsHierarchy(hierarchy));
        }
      });
    } catch (...) {
      ...
    }
  }
```

**Comment by chanseokoh** [comment]
I had been wondering why `BusyIndicator` was never effective here. Basically, it is only useful if the runnable is a (expense) non-UI task, which isn't the case here. Our runnable is entirely about modifying UI components, which fully owns the UI thread from start to end. That is, `BusyIndicator` doesn't even have a chance to do its job until the end.

```java
        BusyIndicator.showWhile(internalComposite.getDisplay(), new Runnable() {
          @Override
          public void run() {
              ...
              pipelineOptionsForm.updateForm(launchConfiguration, optionsHierarchyFuture.get());
              updateLaunchConfigurationDialog();
              ...
          }
        });
```

**Comment by chanseokoh** [comment]
Also noticed that, if we don't call `monitor.beginTask()`, it won't show UI indication that something is running.

```java
    getLaunchConfigurationDialog().run(true, true, new IRunnableWithProgress() {
      @Override
      public void run(IProgressMonitor monitor) throws InvocationTargetException, InterruptedException {
        monitor.beginTask("I am doing something...", IProgressMonitor.UNKNOWN));
```

**Comment by briandealwis** [comment]
> BusyIndicator was never effective here. I realized, basically, it is only useful if the runnable is an (expense) non-UI task

Providing the call is on the SWT thread (which is is here), `BusyIndicator#showWhile()` sets the cursor to the hourglass, runs the runnable, and then restores the cursor.

**Comment by chanseokoh** [comment]
> Providing the call is on the SWT thread (which is is here), BusyIndicator#showWhile() sets the cursor to the hourglass, runs the runnable, and then restores the cursor.

The `BusyIndicator` doesn't work on my machine. The cursor doesn't change. Can you double-check it works on your machine? I can see the options form (the bottom portion where text boxes are dynamically added/removed) adds a lot of UI widgets, but the cursor doesn't change.

**Comment by chanseokoh** [comment]
> Can you double-check it works on your machine?

Never mind. I ended up putting this into the dialog `run()` too.
