### ISSUE TITLE
Does Kokoro only build on googler commits?

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2653]
Quickly reviewing my PR queue, I don't see any build from Kokoro.  Yet I have seen Kokoro builds on PRs from @chanseokoh and @elharo.  We should verify that Kokoro is doing builds for external contributors.

**Comment by briandealwis** [comment]
Datapoint: @chanseokoh and I were working on four PRs, two each: 
  - @chanseokoh: #2659, #2652
  - @briandealwis: #2658, #2656

Chanseok's PRs were built by Kokoro.  None of mine were.

**Comment by elharo** [comment]
Yes, this appears to be WAI. More details offline.

**Comment by elharo** [comment]
Fixes coming in the Kokoro config in google3.
