### ISSUE TITLE
The Google App Engine is not being Installed in my machine !!

### ISSUE THREAD

**Issue by PranjalGupta3105** [GoogleCloudPlatform/google-cloud-eclipse#2661]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.5.0.201712061945
- Google Cloud SDK version: 182.0.0
- Eclipse version: 4.6.3.v20170301-0400
- OS: Windows 8.1 6.3
- Java version: 1.8.0_92

**What did you do?**
I downloaded the Google cloud Sdk from developers site. Tried on Installing it but the installer failed somewhere in between. It say cannot download some files. 
**What did you expect to see?**
I expected to make a google web project for deploying on cloud app engine but that didn't come in my eclipse.
**What did you see instead?**
There are just 2 options:-
1. Standard Java Project.
2. Flexible Java Project.
and 
Cloud Dataflow Java Project.
(screenshots are helpful)

**Comment by elharo** [comment]
This sounds like an issue with the Cloud SDK installer, not CT4E. Next year we will integrate the installer directly into CT4E but until then, a successfully installed Cloud SDK is a prerequisite.

**Comment by PranjalGupta3105** [comment]
@elharo Sir can you please explain CT4E here..!! And what should I do now to continue with my deployment? Is there any other solution apart from this?

**Comment by elharo** [comment]
You need to install the Cloud SDK. That's a separate product. Until that's done, CT4E won't do anything.

**Comment by patflynn** [comment]
Hi @PranjalGupta3105.  Thanks for your feedback. 

You can report issues installing the Cloud SDK [here](https://b.corp.google.com/issues/new?component=187143&template=800102).

**Comment by briandealwis** [comment]
(fixed the link to point to the public issue tracker)

**Comment by briandealwis** [comment]
From the problem metadata, it seems @PranjalGupta3105 actually managed to install the Cloud SDK

> Google Cloud SDK version: 182.0.0

@PranjalGupta3105: you likely want to create a new _Google App Engine Standard Java Project_.  You can create a new project either from the Google Cloud Platform toolbar (shown below) or the new project wizard.

<img width="250" alt="screen shot 2017-12-11 at 1 42 26 pm" src="https://user-images.githubusercontent.com/202851/33847661-4913f7ce-de79-11e7-9ab6-b209362c126d.PNG">

You then place your static web artefacts in `src/main/webapp`.  The generated projects should have an `index.html`, which is the default resource returned as specified as the _welcome_ in the `src/main/webapp/WEB-INF/web.xml` descriptor.  There is a bit of [documentation about this](https://cloud.google.com/appengine/docs/flexible/java/serving-static-files#serving_from_your_application) on the documentation for the App Engine flexible environment, but it also applies to the standard environment too.
