### ISSUE TITLE
Unable to create a new App Engine standard Project

### ISSUE THREAD

**Issue by aerialdancer** [GoogleCloudPlatform/google-cloud-eclipse#2668]
I have just installed Eclipse and Google cloud tools.
I have Version: Oxygen.1a Release (4.7.1a)
Build id: 20171005-1200

(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
Yes have the latest updates
- Cloud Tools for Eclipse version: 1.5.0.201712061945
- Google Cloud SDK version: 182.0.0
- Eclipse version: 4.7.1.v20171009-0410
- OS: Windows 7 6.1
- Java version: 1.8.0_151

**What did you do?**
GC menu -> Create New project -> Google App engine standards Java project

**What did you expect to see?**
 A new project template

**What did you see instead?**
Error message:
Failed to create project: A runtime library is not available locally and cannot be downloaded from the Maven repository: Could not resolve artifact javax.servlet:servlet-api:jar:2.5
Could not resolve artifact javax.servlet:servlet-api:jar:2.5
Failure to transfer javax.servlet:servlet-api:jar:2.5 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact javax.servlet:servlet-api:jar:2.5 from/to central (https://repo.maven.apache.org/maven2): connect timed out
Failure to transfer javax.servlet:servlet-api:jar:2.5 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact javax.servlet:servlet-api:jar:2.5 from/to central (https://repo.maven.apache.org/maven2): connect timed out

(screenshots are helpful)
![image](https://user-images.githubusercontent.com/34441318/33880769-fa86cfc2-df32-11e7-8005-ac84b57ecd29.png)

**Comment by elharo** [comment]
The problem is in the connection to Maven central. You can try deleting the relevant artifact from your .m2 directory and trying again.

**Comment by aerialdancer** [comment]
Sorry, I'm new to this, I don't understand what I should delete? 
![image](https://user-images.githubusercontent.com/34441318/33943129-71e000a8-e018-11e7-81f0-1e9e88ef90b3.png)

**Comment by chanseokoh** [comment]
Make sure you can connect to Maven Central from your machine.

Go to `.m2/repository/javax/servlet` and delete the servlet api 2.5 jar, or just delete everything in it. If all else fails, you can safely delete `repository`.

**Comment by briandealwis** [comment]
@aerialdancer you can read a little bit more about the issue [here](https://books.google.ca/books?id=nGS4CAAAQBAJ&pg=PA99&lpg=PA99&dq=maven+.lastupdated&source=bl&ots=4Z0vFnMaKx&sig=WqOy_U2R_oJPfcjmalbYRY_8mOA&hl=en&sa=X&ved=0ahUKEwikyLP5v4fYAhWsx4MKHYE3AGMQ6AEIbTAJ#v=onepage&q=maven%20.lastupdated&f=false)
