### ISSUE TITLE
Incorporate Cloud Client Libraries wizard with new app creation wizard?

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-eclipse#2670]
Now that we have the wizard to add Cloud Client Libraries to a project, it would be nice to have access to that wizard when creating a new app. Right now, the app creation wizard for App Engine standard only allows you to add Google Cloud Endpoints and Objectify.

**Comment by elharo** [comment]
I'd prefer to keep the wizard simpler. This is not a question all or most projects will need to answer.

**Comment by briandealwis** [comment]
I think making it an optional second page would be very beneficial to get a project up and running quickly.
