### ISSUE TITLE
missing library references for compute engine?

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#2674]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_)
- Cloud Tools for Eclipse version: 1.5.0.201712061945
- Google Cloud SDK version: 182.0.0
- Eclipse version: 4.6.3.v20170301-0400
- OS: Windows 10 10.0
- Java version: 1.8.0_121

**What did you do?**

I'm not sure when this started to happen and whether or not it is related to new plug in or its libraries... but when I try to call a Compute Engine API that used to work I now get:

> Application Default Credentials failed to create the Google App Engine service account credentials class com.google.api.client.googleapis.extensions.appengine.auth.oauth2.AppIdentityCredential$AppEngineCredentialWrapper. Check that the component 'google-api-client-appengine' is deployed.

In Eclipse when I look in Google Cloud Platform Library folder I do not see the component 'google-api-client-appengine' ... the closest thing i see is the component 'google-api-client'  but not the appengine specific one.

Thoughts?

**Comment by elharo** [comment]
This looks like a Cloud SDK installation issue. You may need to run

`gcloud components install app-engine-java`

**Comment by Rob46** [comment]
When I run that it says "All components are up to date"
FYI When I manually add the libraries in Eclipse it works fine. (place in war/lib and change build path to include)

**Comment by briandealwis** [comment]
@Rob46 would you be able to provide a little snippet that reproduces the problem?

**Comment by Rob46** [comment]
Not easily as its already been fixed by manually adding the libs and deployed.
But if you do Config Build Path in Eclipse and do an Add Library > Google Libraries > Compute Engine I suspect you will see that in fact the required lib in the above error message isn't there. (google-api-client-appengine)

**Comment by chanseokoh** [comment]
I do not see `google-api-client-appengine` either, but I am thinking it may not be a requirement to use the GCE API unless you are deploying an app to App Engine.

@Rob46
- Are you deploying an app that uses the GCE API to GAE? If so, deploying to GAE Java 7 or Java 8? (Do you have `<runtime>java8</runtime>` in you `appengine-web.xml`?)
- Are you using Maven, or you have a _Google Platform Libraries_ container like below?
![selection_020](https://user-images.githubusercontent.com/10523105/33953522-3a5fe162-e003-11e7-9092-29bfde2e6450.png)

**Comment by briandealwis** [comment]
Does this happen when running locally with the devappserver?

Sounds like we need to add [that additional library for App Engine use](https://developers.google.com/api-client-library/java/google-api-java-client/setup#google-api-client-appengine).  We should have a test for this, perhaps additional tests that [run nightly](https://docs.travis-ci.com/user/cron-jobs/).

**Comment by Rob46** [comment]
we are on App Engine Std Java 8
and yes, we use GCE API via that (server restart now, but more coming)

RE "but I am thinking it may not be a requirement to use the GCE API unless you are deploying an app to App Engine." Yes, that makes sense. Does it not resolve dependencies though??

![image](https://user-images.githubusercontent.com/25462429/33956216-e5ea7670-e00b-11e7-82e9-add025f8c84e.png)

**Comment by elharo** [comment]
Just to be clear, the base library is this one:

```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-compute</artifactId>
  <version>0.32.0-alpha</version>
</dependency>
```

Or is it something else?

**Comment by elharo** [comment]
The google-cloud-java libraries and docs do not indicate that this jar is required to run on App Engine. Those docs may be wrong, but we need to establish that.

**Comment by elharo** [comment]
Let's see what the google-cloud-java team says: https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2707

**Comment by Rob46** [comment]
The files I downloaded and manually added to build path were:

google-api-services-compute-v1-rev164-1.23.0.jar
google-api-client-appengine-1.23.0.jar

**Comment by elharo** [comment]
Dollars to donuts that google-api-services-compute-v1-rev164-1.23.0.jar is the old compute API, not the google-cloud-java one supported by the CT4E library container.

**Comment by Rob46** [comment]
Yep, I'm importing as follows:

import com.google.api.services.compute.Compute;
import com.google.api.services.compute.model.Operation;

since those new APIs are labeled alpha, I'll stick with the old one until they become GA.
Is there an easy answer as to why the new API?
Incompatiable and requires a rewrite?

**Comment by elharo** [comment]
I'm sure there are, but you'd have to ask the google-cloud-java team.
