### ISSUE TITLE
Gson dependency version warning when building Oxygen target platform

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2680]
The warning shows up only when building a target platform for Oxygen. Observable in any Travis Oxygen build or when building locally. What does it mean?

```
$ mvn -Pide-target-platform -Declipse.target=oxygen package
[INFO] --- tycho-p2-repository-plugin:1.0.0:assemble-repository (default-assemble-repository) @ ide-target-platform.repo ---
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201712112027.Default 1.0.0._pCUEYEcM0Z--EaKb4uwECHUIDanp-LvOyW to com.google.gson [2.7.0].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201712112027.Default 1.0.0._pCUEYEcM0Z--EaKb4uwECHUIDanp-LvOyW to com.google.gson [2.7.0].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201712112027.Default 1.0.0._pCUEYEcM0Z--EaKb4uwECHUIDanp-LvOyW to com.google.gson [2.7.0].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201712112027.Default 1.0.0._pCUEYEcM0Z--EaKb4uwECHUIDanp-LvOyW to com.google.gson [2.7.0].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201712112027.Default 1.0.0._pCUEYEcM0Z--EaKb4uwECHUIDanp-LvOyW to com.google.gson [2.7.0].]
[WARNING] More information on the preceding warning(s) can be found here:
[WARNING] - http://wiki.eclipse.org/Tycho_Messages_Explained#Mirror_tool
```

**Comment by briandealwis** [comment]
This happens for the Oxygen target as the `org.eclipse.wst.web_sdk.feature` feature now pulls in a new feature `org.eclipse.wst.jsdt.nodejs.feature` feature, which requires `com.google.gson 2.7.0.v20170129-0911` (which comes from Eclipse Orbit).

I was worried what this would mean if we moved to Gson 2.8.2 (the latest release).  So I tried specifying com.google.gson 2.8.2 instead and… no warnings, and we end up with `com.google.gson_2.8.2.jar` and `com.google.gson_2.7.0.v20170129-0911.jar`.

I'm not entirely sure why this doesn't work.  The `tycho-p2-repository-plugin:assemble-repository` builds up a list of IUs and publishes some of the Maven artifacts that we pull in using `<dependency>` from Central, like our own `com.google.cloud.tools.appengine`, but it doesn't include `com.google.gson`.  So this would seem to be a (minor) bug in Tycho or p2: maybe something is doing a major-minor-micro comparison and ignoring the qualifier?

But hey, this seems like a good time to update to Gson 2.8.2.
