### ISSUE TITLE
Not able to deploy Spring application v-4 on Google app engine jetty/java environment 

### ISSUE THREAD

**Issue by poojakrishnappa** [GoogleCloudPlatform/google-cloud-eclipse#2694]
(please ensure you are running the latest version of CT4E with _Help > Check for Updates_.)

- Cloud Tools for Eclipse version: eclipse Oxygen version above 4.5
- Google Cloud SDK version: _(run `gcloud version`)_ : 1.9.59
- Eclipse version: _(e.g, 4.5.2.v20160212-1500 or Neon.3)_ : 4.5 Oxygen
- OS: windows 7
- Java version: java 8

**What did you do?**   I tried to deploy my spring application from eclipse oxygen to appengine jetty environment

**What did you expect to see?** I expect my project should be deploy on app engine jetty or java environment
**What did you see instead?** but its showing error after deploy

![capture](https://user-images.githubusercontent.com/34936311/34434225-8f5effd2-ecaa-11e7-9ca3-f5bb61b7f916.PNG)

(screenshots are helpful)

**Comment by elharo** [comment]
This seems unlikely to be a CT4E issue. What happens if you deploy with gcloud?

**Comment by poojakrishnappa** [comment]
Thank you for reply,
Same issue with gcloud.

**Comment by elharo** [comment]
Whatever the issue is, it isn't in CT4E then. Might be a configuration issue in your GCP project.

**Comment by patflynn** [comment]
@poojakrishnappa it could be a misconfiguration of your secure paths.  Sharing your appengine-web.xml could help.
