### ISSUE TITLE
Issue: Could not resolve artifact javax.servlet.jsp:jsp-api:jar:2.1

### ISSUE THREAD

**Issue by poojakrishnappa** [GoogleCloudPlatform/google-cloud-eclipse#2699]
Hi,
I am trying to create App engine standard project from eclipse oxygen but it showing below error.
But I can create app engine java flexible project.
You have nay suggestion to resolve this ?

Failed to create project: A runtime library is not available locally and cannot be downloaded from the Maven repository: Could not resolve artifact javax.servlet.jsp:jsp-api:jar:2.1
Could not resolve artifact javax.servlet.jsp:jsp-api:jar:2.1
Failure to transfer javax.servlet.jsp:jsp-api:jar:2.1 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact javax.servlet.jsp:jsp-api:jar:2.1 from/to central (https://repo.maven.apache.org/maven2): connect timed out
Failure to transfer javax.servlet.jsp:jsp-api:jar:2.1 from https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced. Original error: Could not transfer artifact javax.servlet.jsp:jsp-api:jar:2.1 from/to central (https://repo.maven.apache.org/maven2): connect timed out

Screenshots and stack traces are helpful.
![image](https://user-images.githubusercontent.com/34936311/34560607-6c4df964-f16c-11e7-88ac-7731732e9894.png)

**Comment by elharo** [comment]
Yes, I've seen this myself, and it's very annoying. Behind the scenes CT4E is reading the relevant jars from Maven central. If for some reason that fails, Maven won't try to redownload the artifact for about 24 hours. 

You can force it to update sooner. At the command line try

`mvn dependency:purge-local-repository`

If that doesn't work, try deleting your ~/.m2/repository directory. Unfortunately I don't know any less aggressive way to force an early update.

**Comment by briandealwis** [comment]
You can delete the `.lastUpdated` files: https://stackoverflow.com/a/4556024/600339
