### ISSUE TITLE
Installing App Engine facets probably doesn't require Cloud SDK

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2708]
When installing the (std and flex) facets, we check if the Cloud SDK is installed through `AppEngineFacetInstallDelegate.execute()`. Because of this check, users cannot create a new project without the Cloud SDK. I have been thinking the SDK is required to create the App Engine Server Runtime.

However, I got really suspicious of this, so took a shot on testing this. I moved my local Cloud SDK directory, took down the Cloud SDK checks in code, deleted the App Engine Server Runtime, started a fresh workspace, and was able to create a new project without an error. Creating a new project successfully creates the App Engine Server Runtime if it doesn't exist. Of course, local run fails because CT4E can't find any Cloud SDK locally.

**Comment by chanseokoh** [comment]
My guess is that, probably we wanted to let the user know ahead that the Cloud SDK is eventually needed to anything useful after creating a new project. However, with the new Cloud SDK downloader, this won't be necessary.

**Comment by briandealwis** [comment]
IIRC we used to fetch the different servlet jars from the Cloud SDK, so it was required.  But now we fetch from Maven Central instead.

**Comment by elharo** [comment]
Makes sense. Let's take it out. Unless we want to rename this method to install the Cloud SDK is not present?
