### ISSUE TITLE
Servlet 2.5 and 3.1 via Endpoints in a Maven project

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2731]
Creating a new java8 runtime Maven project pulls in both servlet 2.5 and 3.1; 3.1 from the runtime and 2.5 from the endpoints graph.

Should we add an `exclusion` of servlet api 2.5 to our generated pom.xml to keep this from happening?

**Comment by elharo** [comment]
i.e.

```
  <dependency>
<groupId>com.google.endpoints</groupId>
<artifactId>endpoints-framework</artifactId>
<version>2.0.11</version>
     <exclusions>
        <exclusion>
          <groupId>javax.servlet</groupId>
          <artifactId>servlet-api</artifactId>
        </exclusion>
    </exclusions>
</dependency>
</dependencies>
```

**Comment by elharo** [comment]
This might require some special casing in `Pom.updateDependencies()`

**Comment by patflynn** [comment]
I thought they changed this dep to be provided on the endpoints side.

**Comment by briandealwis** [comment]
It's still marked as `compile`, not `compileOnly` in their `build.gradle` files.

**Comment by patflynn** [comment]
@tangiel

**Comment by elharo** [comment]
https://github.com/cloudendpoints/endpoints-java/pull/129
