### ISSUE TITLE
gcloud crashed (OperationalError): attempt to write a readonly database

### ISSUE THREAD

**Issue by edudoda** [GoogleCloudPlatform/google-cloud-eclipse#2740]
- Cloud Tools for Eclipse version: 1.5.0.201712061945
- Google Cloud SDK version: 185.0.0
- Eclipse version: 4.7.1.v20171009-0410 (Oxygen)
- OS: Mac OS X 10.13.2
- Java version: 1.8.0_20

**What did you do?**

I create a simple ''hello word'' for an  APP Engine Standard Project with Eclipse wizard in 'Cloud Tools for Eclipse'. I can run/deploy it locally:

> 2018-01-19 11:42:27.359:INFO::main: Logging initialized @550ms
> Jan 19, 2018 11:42:27 AM com.google.appengine.tools.development.jetty9.JettyContainerService initContext
> ADVERTÊNCIA: Adding jar org.apache.taglibs.taglibs-standard-spec-1.2.5.jar to WEB-INF/lib. You might want to add a dependency in your project build system to avoid this warning.
> Jan 19, 2018 11:42:27 AM com.google.appengine.tools.development.jetty9.JettyContainerService initContext
> ADVERTÊNCIA: Adding jar org.apache.taglibs.taglibs-standard-impl-1.2.5.jar to WEB-INF/lib. You might want to add a dependency in your project build system to avoid this warning.
> 2018-01-19 11:42:27.846:INFO:oejs.Server:main: jetty-9.3.18.v20170406
> 2018-01-19 11:42:29.531:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=1531ms
> 2018-01-19 11:42:29.924:INFO:oejsh.ContextHandler:main: Started c.g.a.t.d.j.DevAppEngineWebAppContext@730d2164{/,file:///Users/edudoda/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/as_GAE/,AVAILABLE}{/Users/edudoda/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/as_GAE}
> 2018-01-19 11:42:29.937:INFO:oejs.AbstractConnector:main: Started NetworkTrafficSelectChannelConnector@5167f57d{HTTP/1.1,[http/1.1]}{localhost:8080}
> 2018-01-19 11:42:29.953:INFO:oejs.Server:main: Started @3146ms
> Jan 19, 2018 11:42:29 AM com.google.appengine.tools.development.jetty9.JettyContainerService startHotDeployScanner
> INFORMAÇÕES: Full scan of the web app in place every 1s.
> Jan 19, 2018 11:42:29 AM com.google.appengine.tools.development.AbstractModule startup
> INFORMAÇÕES: Module instance default is running at http://localhost:8080/
> Jan 19, 2018 11:42:29 AM com.google.appengine.tools.development.AbstractModule startup
> INFORMAÇÕES: The admin console is running at http://localhost:8080/_ah/admin
> Jan 19, 2018 11:42:29 AM com.google.appengine.tools.development.DevAppServerImpl doStart
> INFORMAÇÕES: Dev App Server is now running

However, I can't deploy to the cloud due to: gcloud crashed (OperationalError): attempt to write a readonly database. I ran the command line: gcloud info --run-diagnostics, and got: ''Reachability Check passed. Network diagnostic (1/1 checks) passed.''

**What did you expect to see?**
APP deployed in production

**What did you see instead?**

Eclipse console:

Reading application configuration data...

> Beginning interaction for module default...
> 0% Scanning for jsp files.
> 2018-01-19 11:28:33.623:INFO::main: Logging initialized @136ms
> 2018-01-19 11:28:33.748:INFO:oejs.Server:main: jetty-9.3.18.v20170406
> 2018-01-19 11:28:33.981:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=88ms
> 2018-01-19 11:28:33.993:INFO:oejq.QuickStartDescriptorGenerator:main: Quickstart generating
> 2018-01-19 11:28:34.008:INFO:oejsh.ContextHandler:main: Started o.e.j.q.QuickStartWebApp@2d6e8792{/,file:///Users/edudoda/eclipse-workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1516368513045/staging/,AVAILABLE}
> 2018-01-19 11:28:34.009:INFO:oejs.Server:main: Started @525ms
> 2018-01-19 11:28:34.012:INFO:oejsh.ContextHandler:main: Stopped o.e.j.q.QuickStartWebApp@2d6e8792{/,file:///Users/edudoda/eclipse-workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1516368513045/staging/,UNAVAILABLE}
> Success.
> Temporary staging for module default directory left in /Users/edudoda/eclipse-workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1516368513045/staging
> {"version": "0.0.1", "verbosity": "ERROR", "timestamp": "2018-01-19T13:28:35.627Z", "message": "gcloud crashed (OperationalError): attempt to write a readonly database"}

Message: gcloud crashed (OperationalError): attempt to write a readonly database
Session data: 
> eclipse.buildId=4.7.1.M20171009-0410
> java.version=1.8.0_20
> java.vendor=Oracle Corporation
> BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=pt_BR
> Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/edudoda/.eclipse_keyring
> Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -data file:/Users/edudoda/eclipse-workspace/ -product org.eclipse.epp.package.jee.product -keyring /Users/edudoda/.eclipse_keyring

**Comment by chanseokoh** [comment]
@znewman01any idea about the below error during gcloud deploy?

`Message: gcloud crashed (OperationalError): attempt to write a readonly database`

**Comment by chanseokoh** [comment]
@edudoda try `chmod +r ~/.config/gcloud` or something to that effect so that the user used to run your Eclipse can read things inside it.

**Comment by edudoda** [comment]
@chanseokoh YES!
I had already made it to the following folders: 
> .../eclipse-workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy 
and 
>/usr/local/google_sdk/google-cloud-sdk

but was missing the: 
> /Users/edudoda/.config/gcloud 

It solves the problem! Thank you very much! =]

**Comment by elharo** [comment]
I'm guessing that the managed Cloud SDK installer work will prevent this in the future. If not, we should probably look into noticing and improving this in the future. And perhaps we should probably report this upstream to gcloud so they can offer a better error message here.

**Comment by edudoda** [comment]
@elharo I agree with you. Its more related to Cloud SDK installer, because it also happened with command line deploying comman, but, to avoid problemns, should be nice to allert about folder privileges.

**Comment by elharo** [comment]
https://b.corp.google.com/issues/72297808

**Comment by manashmndl** [comment]
This worked for me

`sudo chown -R userame /home/username/.config/gcloud`
