### ISSUE TITLE
Install Cloud SDK at App Engine local run

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2755]
As soon as the user starts the dev appserver, the installation process will start if the SDK is not found (and the preference is set to auto-managed). The detailed Cloud SDK install output will be redirected to the local run console.

I'm thinking of not checking or forcing SDK update here.

For the initial iteration, I think there should be some locking mechanism so that

- there will be no concurrent install/update; and
- local run and deploy blocks install/update and vice versa.

**Comment by briandealwis** [comment]
Launching requires a server definition.

There are 3 ways to launch:
  1. via project right-click _> Run As > App Engine_: calls into our `LocalAppEngineStandardLaunchShortcut` which uses our `LaunchHelper` class
  2. via our GCP menu > _Run on App Engine_ or _Debug on App Engine_: calls into our `LaunchAppEngineStandardHandler` class that also uses our `LaunchHelper` class
  3. launching via an existing `.launch` file (e.g., saved to an imported project), which goes through our `LocalAppEngineServerLaunchConfigurationDelegate`.

Although we could put a check in `LaunchHelper`, its purpose is to find or create a server definition with the selected modules and then invoke it, which takes us into the `LocalAppEngineServerLaunchConfigurationDelegate`.

**Comment by chanseokoh** [comment]
How about doing the check in `LocalAppEngineServiceBehavior.startDevServer()`, before calling `initializeDevServer()`?

**Comment by briandealwis** [comment]
That's quite deep into the launch process.  My proposal in a sec.
