### ISSUE TITLE
Install Cloud SDK at opportunistic times other than the start of local run or deploy

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2757]
This is somewhat low priority, but will be nice to have, e.g., so that users don't have to wait for a long time at the very first attempt of starting local run.

**Comment by briandealwis** [comment]
I've been digging into potential entry points, to try and avoid scattering install-checks as much as possible.

## WTP's `internalStartup` listener

WTP offers the `org.eclipse.wst.server.core.internalStartup` extension point to provide for configuring some actions when Server Core is initialized.  This includes opening any WTP views, like the _Servers_ view.  We currently use this with class `com.google.cloud.tools.eclipse.appengine.localserver.server.RegisterAppEngineStandardRuntimeStartup` to create the _App Engine Standard Runtime_ environment instance (shown in _Preferences > Servers > Runtime Environments_).

The downside to hooking into this _internalStartup_ for the SDK installation is that we will trigger the installation even if the user never actually creates one of our servers nor installs a facet.

## Creating the `AppToolsRuntime` instance

The `AppToolsRuntime` is the name of our App Engine Standard server runtime environment.  It has the same downside as the `internalStartup` extension point: it is created early, even if the user never actually creates one of our servers.

## Creating a Server instance

When the IDE begins to create a server (e.g., _New > Servers > Google > App Engine Standard_), it creates an instance of our `LocalAppEngineServerDelegate` server delegate class.  Our _App Engine Standard_ server is often the first element selected, so similar to the _internalStartup_, triggering the install on `initialize()` may be premature.  But we are offered an opportunity to hook in on `save()`: when the server definition has been accepted or modified.  This might be a good time to trigger the background installation.

## Creating a project with an App Engine facet

If the user installs a App Engine Standard facet, then it's definitely our point.

**Comment by briandealwis** [comment]
In digging through these, I frequently triggered WTP's automatic background downloading of server definitions, which was annoying and reminded me of the importance of trying to avoid initiating an installation unnecessarily.
<img width="634" alt="screen shot 2018-02-05 at 4 50 00 pm" src="https://user-images.githubusercontent.com/202851/35830564-a96e6ea0-0a94-11e8-81e6-0c4d5c89b90b.PNG">

**Comment by patflynn** [comment]
It doesn't seem bad to me to install the cloud SDK even when the user
hasn't setup a facet or a server.  The installation of our plugin indicates
intent.  I'd be OK with starting the install immediately after plugin
install, and checking for updates on a periodic basis regardless of project
type/configuration.

**Comment by briandealwis** [comment]
I believe there is an ability to run code immediately on install (vs on restart) via a touchpoint, but it's not something I've played with before.

**Comment by chanseokoh** [comment]
Interesting. But the Eclipse always asked to restart after installing a plugin, so I think it'd be much reliable to check it on every restart. We don't have to be concerned about when the user pushes the restart button while we are installing the SDK after our plugin install.

**Comment by briandealwis** [comment]
I believe this touchpoint code is treated as part of the install (i.e., the restart dialog won't appear until it's complete).  I do recall someone saying it's a bit tricky however.

**Comment by chanseokoh** [comment]
If that's the case, it seems better to not prolong the plugin install time by install the SDK at the same time. We can always install the SDK in the background. Moreover, it does sound tricky to invoke a lot of code before our plugin is active. Determining initial preferences and installing the SDK is not a simple task and error-prone.

**Comment by patflynn** [comment]
It sounds worth looking into at least.  The positive is that you can always
assume that there's a valid Cloud SDK installed if the plugin is active.

**Comment by briandealwis** [comment]
With #2801 we should almost always have the Cloud SDK available.
