### ISSUE TITLE
Out-of-date notification for custom Cloud SDK?

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2759]
Our design doesn't do anything about a custom Cloud SDK (i.e., no update from our side), but it's been suggested in #2750 to show a notification when it is out of date. If we want this, we'll have questions like how often we will show the notification.

In any case, I'm not inclined to offer an automated update on a custom Cloud SDK. For example, users may have to temporarily switch from the auto-managed SDK and pin down a previous Cloud SDK version if something is broken in the latest SDK. In that sense, constantly showing the custom SDK is out of date doesn't fit well.

**Comment by briandealwis** [comment]
My inclination would be to show it on startup as a transient notification.

> Google Cloud SDK 240.0.0 now available ([release notes](https://cloud.google.com/sdk/docs/release-notes)); local installation is 171.0.0.

Ideally appengine-plugins-core would be agnostic to updating the user installation vs the managed installation.

**Comment by patflynn** [comment]
+1.  Just be aware that the update mechanism will depend on the
installation method used.  For instance cloud sdk installed by apt-get
cannot be updated or have the app engine component installed using gcloud
components update/install.

**Comment by briandealwis** [comment]
I'd forgotten about apt-get.
