### ISSUE TITLE
Explore non-blocking, atomically instant update of Cloud SDK

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2760]
We have to periodically update the Cloud SDK, whatever the frequency we do. For the first iteration, when an update is in progress, we'll block local run and deploy (and vice versa).

However, potentially we could make this non-blocking, e.g., if we can do the update at a staging location and switch to the staged SDK instantly and discard the out-of-date SDK at the end. I believe this is not possible with the current workings of appengine-plugins-core. The Cloud SDK may not support this either, so in the end, a not-so-ideal workaround could be to install a fresh SDK whenever there is a new version, and we just switch the directories of the current SDK and the newly installed SDK.

BTW, on the command line, I tried deploying while simultaneously updating the Cloud SDK. Not always, but it is indeed possible to run into a problem:

```
Do you want to continue (Y/n)?  y

Beginning deployment of service [default]...
Building and pushing image for service [default]
ERROR: gcloud crashed (IOError): [Errno 2] No such file or directory

If you would like to report this issue, please run the following command:
  gcloud feedback

To check gcloud for common problems, please run the following command:
  gcloud info --run-diagnostics
```

**Comment by briandealwis** [comment]
Eeek!

**Comment by elharo** [comment]
Please report this upstream to the Cloud SDK team.

**Comment by chanseokoh** [comment]
Personally, I don't regard this as an issue in the SDK, especially from their perspective. The user is doing some crazy thing (using gcloud while the user is updating it), and I'd say it's fair to see it go wrong. It becomes probably to us only because we'll auto-update the SDK without user attention.

**Comment by elharo** [comment]
It's not necessarily that it should work, but the error message should be clearer and more specific.

**Comment by chanseokoh** [comment]
Makes sense. Filed an internal bug 72654481.

**Comment by chanseokoh** [comment]
Related: https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/527

**Comment by diegomarquezp** [comment]
Closing as not planned since.
