### ISSUE TITLE
Google Cloud Platform Libraries dialog needs more padding between columns

### ISSUE THREAD

**Issue by parkjam4** [GoogleCloudPlatform/google-cloud-eclipse#2767]
See the screenshot:

![linux](https://user-images.githubusercontent.com/11820506/35634119-e3d4643e-0678-11e8-9c81-38e365b5d854.png)

**Comment by elharo** [comment]
It may be that given settings the last couple of words are removed rather than truncated


![image](https://user-images.githubusercontent.com/1005544/35696302-16cdc420-0755-11e8-9070-40b59c7a54e8.png)

**Comment by elharo** [comment]
This is set up in `LIbrarySelector.createContents`:

```
  private void createContents(Composite parentContainer, String groupLabel) {
    Group apiGroup = new Group(parentContainer, SWT.NONE);
    apiGroup.setText(groupLabel);

    for (Library library : availableLibraries.values()) {
      Button libraryButton = new Button(apiGroup, SWT.CHECK);
      libraryButton.setText(getLibraryName(library));
      if (library.getToolTip() != null) {
        libraryButton.setToolTipText(library.getToolTip());
      }
      libraryButton.setData(library);
      libraryButton.addSelectionListener(new ManualSelectionTracker());
      libraryButtons.put(library, libraryButton);
    }
    GridLayoutFactory.fillDefaults().generateLayout(apiGroup);
  }
```

**Comment by elharo** [comment]
Part of the problem seems to be that these widgets behave differently on Mac OS X and Linux. On Linux the title of the group is used to set the preferred width of the group. ON Mac it isn't.

**Comment by elharo** [comment]
`ClousLIbrariesPage.createControl` uses a `RowLayout`. We need to pad here.
