### ISSUE TITLE
Exception in init prevents server from starting

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2771]
Bringing over from #2727 

try replacing the code of the init method with this code:

```
    @Override
    public void init() throws ServletException {

        super.init();

        if (true) {
              throw new RuntimeException();
        }

        System.out.println("Print something.");

    }
```

in this way I force an exception to the start. Try to click on Run As -> App Engine and try to stop the server. The server remains hung in "STOPPING" state.

This means that if there is an exception in the startup code the server will not shut down anymore.

(Note: requires using `@WebServlet(… loadOnStartup=1)` or `<load-on-startup>1</load-on-startup>` in `web.xml`.)

**Comment by chanseokoh** [comment]
@briandealwis said this may be #1964. To be seen; I haven't verified it myself.

**Comment by briandealwis** [comment]
The _Servers_ and _Console_ views offer a _Terminate_ button which is only active when the server is in a _Started_ state.  By initiating a terminate, we put the server into _Stopping…_ and so the terminate buttons are no longer enabled.

The _Debug_ view on the other hand, allows multiple terminates until the launch says it is actually terminated.  We have code in our `LocalAppEngineServerBehaviour` to terminate the process if a stop request is initiated and the server is already in a _Stopping…_ state.

@aleguerrini a workaround is to use the _Terminate_ option _twice_ from the _Debug_ view.  The first terminate will put the server into a _Stopping…_ state, and the second terminate will forcibly terminate the process.

**Comment by elharo** [comment]
Apparent dupe of https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/1964
