### ISSUE TITLE
GAE Standard App Engine deploy:  Failed to generate quickstart-web.xml

### ISSUE THREAD

**Issue by blurock** [GoogleCloudPlatform/google-cloud-eclipse#2783]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.5.1.201801292341
- Google Cloud SDK version: 188.0.0
- Eclipse version: 4.7.0.v20170612-0950
- OS: Mac OS X 10.11.6
- Java version: 1.8.0_91

**What did you do?**
Created a new Google App Engine Standard Project.
When I run it locally, there is no problem.
But when I try to Deploy to App Engine Standard
First, without problem, I set my login and choose the listed project..

I originally got this problem with a more complicated GAE project (using the GWT library),
and I get exactly the same problem... 

**What did you expect to see?**
I expected to run the project on the Google Cloud Platform.
Got the error below instead..

**What did you see instead?**
I get the following error, essentually about 'Failed to generate quickstart-web.xml'  ...

Beginning interaction for module default...
0% Scanning for jsp files.
Error: Could not find or load main class com.google.appengine.tools.development.jetty9.QuickStartGenerator
Error while executing: /Library/Java/JavaVirtualMachines/jdk1.8.0_91.jdk/Contents/Home/jre/bin/java -cp /opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-alpn-server-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-annotations-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-client-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-continuation-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-deploy-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-gcloud-memcached-session-manager-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-gcloud-session-manager-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-http-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-infinispan-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-io-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jaas-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jaspi-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jmx-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jndi-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-nosql-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-plus-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-proxy-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-quickstart-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-rewrite-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-schemas-3.1.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-security-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-server-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-servlet-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-servlets-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-util-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-webapp-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-xml-9.3.18.v20170406.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/servlet-api-3.1.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/asm-6.0_BETA.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/asm-commons-6.0_BETA.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/javax.annotation-api-1.2.jar:/opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/tools/quickstart/quickstartgenerator.jar com.google.appengine.tools.development.jetty9.QuickStartGenerator /Users/edwardblurock/workspace-chemconnect/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1518110880972/staging /opt/Google/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/docs/webdefault.xml 
Unable to stage app: Failed to generate quickstart-web.xml.
Please see the logs [/var/folders/wx/rvbwwrrn6nb1m7h9309bhn_c0000gn/T/appcfg1724239399346082915.log] for further information.

I followed the thread about this problem... but reall didn't see a solution'
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2331

Thanks for any help

Screenshots and stacktraces are helpful.

**Comment by briandealwis** [comment]
@blurock this is an issue in the Google Cloud SDK 187.0.0, tracked as [issue 72808542](https://issuetracker.google.com/issues/72808542).  You can work around it by downgrading to Google Cloud SDK 186.0.0 by:
```sh
$ gcloud components update --version 186.0.0
```

**Comment by elharo** [comment]
This sounds like a known regression (bug) in the Cloud SDK 187.0.0. Try upgrading to 188.0.0 which should fix this.

**Comment by blurock** [comment]
Thanks for the help... just for other's reference who happen upon this thread...
I was using 188 and I had this problem...
Going back to 186 worked perfectly...

Thanks

**Comment by briandealwis** [comment]
I'm seeing it on 188.0.1 too :-(

**Comment by NicolaSpreafico** [comment]
I'm seeing it on 188.0.1 too
