### ISSUE TITLE
Some Travis jobs are slow and timing out

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2803]
Recently we've been having Travis failures where one of the builds — often, but not always the Oxygen build — fails because it goes over Travis' limit of 50 minutes.  From looking at the build timestamps, the individual projects are taking 2x to 3x as long.

Timestamps from a good run on Neon (taking 26 minutes):
```sh
$ grep 'INFO\] Building com.google.cloud.tools.eclipse' /tmp/log-good.txt | awk '{ print ($1 - last) / 1000, $0; last=$1; }' | sort -nr | head -10
154.511 950104 [INFO] Building com.google.cloud.tools.eclipse.bugreport.test 0.1.0-SNAPSHOT
141.729 728283 [INFO] Building com.google.cloud.tools.eclipse.appengine.standard.java8.test 0.1.0-SNAPSHOT
125.295 374910 [INFO] Building com.google.cloud.tools.eclipse.appengine.facets.test 0.1.0-SNAPSHOT
98.917 586554 [INFO] Building com.google.cloud.tools.eclipse.appengine.newproject.test 0.1.0-SNAPSHOT
94.631 94631 [INFO] Building com.google.cloud.tools.eclipse.3rdparty.feature 0.1.0-SNAPSHOT
65.764 440674 [INFO] Building com.google.cloud.tools.eclipse.appengine.libraries.test 0.1.0-SNAPSHOT
62.943 248416 [INFO] Building com.google.cloud.tools.eclipse.swtbot 0.1.0-SNAPSHOT
50.674 778957 [INFO] Building com.google.cloud.tools.eclipse.appengine.ui.test 0.1.0-SNAPSHOT
25.419 185473 [INFO] Building com.google.cloud.tools.eclipse.appengine.deploy.test 0.1.0-SNAPSHOT
24.632 994656 [INFO] Building com.google.cloud.tools.eclipse.googleapis.test 0.1.0-SNAPSHOT
```

Timestamps from timed-out run on Oxygen (same PR):
```sh
$ grep 'INFO\] Building com.google.cloud.tools.eclipse' /tmp/log-50.txt | awk '{ print ($1 - last) / 1000, $0; last=$1; }' | sort -nr | head -10
324.369 1993834 [INFO] Building com.google.cloud.tools.eclipse.appengine.standard.java8.test 0.1.0-SNAPSHOT
273.642 2424909 [INFO] Building com.google.cloud.tools.eclipse.bugreport.test 0.1.0-SNAPSHOT
269.74 1669465 [INFO] Building com.google.cloud.tools.eclipse.appengine.newproject.test 0.1.0-SNAPSHOT
263.851 1005934 [INFO] Building com.google.cloud.tools.eclipse.appengine.facets.test 0.1.0-SNAPSHOT
258.521 258521 [INFO] Building com.google.cloud.tools.eclipse.3rdparty.feature 0.1.0-SNAPSHOT
174.012 1179946 [INFO] Building com.google.cloud.tools.eclipse.appengine.libraries.test 0.1.0-SNAPSHOT
154.208 737987 [INFO] Building com.google.cloud.tools.eclipse.swtbot 0.1.0-SNAPSHOT
130.317 1310263 [INFO] Building com.google.cloud.tools.eclipse.appengine.libraries.ui.test 0.1.0-SNAPSHOT
113.758 2107592 [INFO] Building com.google.cloud.tools.eclipse.appengine.ui.test 0.1.0-SNAPSHOT
89.462 1399725 [INFO] Building com.google.cloud.tools.eclipse.appengine.localserver.test 0.1.0-SNAPSHOT
```

**Comment by briandealwis** [comment]
Many of the builds work fine.  The Oxygen builds typically take a few more minutes than the Mars and Neon builds.
![screen shot 2018-02-14 at 1 23 53 pm](https://user-images.githubusercontent.com/202851/36220918-559d0a64-118a-11e8-896c-02ed2aab67aa.PNG)

**Comment by briandealwis** [comment]
Just had a time out on Neon on worker `eb21b1ac-9768-4487-b686-216db71fafe2@1.i-01d31ab-production-2-worker-org-ec2.travisci.net`.

Yesterday saw slowdowns on following workers:
  - `57c18d56-af0b-45d8-93fe-f60a47795b9a@1.i-0994501-production-2-worker-org-ec2.travisci.net`
  - `2e3301e7-479f-4d1d-ae03-4e24cc790c1a@1.i-062ab5a-production-2-worker-org-ec2.travisci.net`
  - `0bfd508b-25ac-4283-9066-c8ea0e008dae@1.i-05dfe6a-production-2-worker-org-ec2.travisci.net`
  - `607eb343-b677-4826-9f9f-5e8310f41b82@1.i-00f683f-production-2-worker-org-ec2.travisci.net`

**Comment by briandealwis** [comment]
Yesterday saw slowdowns on following workers:
  - `57c18d56-af0b-45d8-93fe-f60a47795b9a@1.i-0994501-production-2-worker-org-ec2.travisci.net`
  - `2e3301e7-479f-4d1d-ae03-4e24cc790c1a@1.i-062ab5a-production-2-worker-org-ec2.travisci.net`
  - `0bfd508b-25ac-4283-9066-c8ea0e008dae@1.i-05dfe6a-production-2-worker-org-ec2.travisci.net`
  - `607eb343-b677-4826-9f9f-5e8310f41b82@1.i-00f683f-production-2-worker-org-ec2.travisci.net`

**Comment by elharo** [comment]
The problem seems to be getting worse. More than one build per run is timing out. 

https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/builds/341929046?utm_source=github_status&utm_medium=notification

**Comment by briandealwis** [comment]
Seen again on [Job 11772](https://travis-ci.org/GoogleCloudPlatform/google-cloud-eclipse/jobs/342395916) in both Mars and Oxygen builds:
- 4c72feb9-29e8-4369-8b50-245fa6703ba7@1.i-02b8100-production-2-worker-org-ec2.travisci.net
- ab366a92-b08b-412a-8f10-0a769b55ab6c@1.i-0467777-production-2-worker-org-ec2.travisci.net

Comparing some of the timestamps for executions outside of our actual build, the slow machines seem slow:
  - `git clone`: slow: 2.06s, 1.90s; normal: 0.88s
  - installing mvn wrapper: slow: 22.16s, 19.59s; normal: 5.14s
  
Even the Maven startup is slow — the time from start to the first message where it's "Scanning for projects…" (no network access): slow: 10.546s, 4.156s; normal: 1.615s

**Comment by briandealwis** [comment]
Haven't seen this for a while now.
