### ISSUE TITLE
"Local" SDK is not quite right

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2809]
Both managed and non-managed SDKs are in fact local. 

![image](https://user-images.githubusercontent.com/1005544/36225986-7743d106-119a-11e8-929d-179e24d9fa5b.png)

Instead of "Use Local SDK" maybe "Choose SDK" or "Specify SDK"?

**Comment by patflynn** [comment]
+1. I think 'local' is a bit confusing.  Either of your wordings work for
me.
