### ISSUE TITLE
Stream managed Cloud SDK install output to console for local run

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2838]
We stream the install output to the console when deploying but not for the local run. Currently, it is just a simple job progress, and even if we integrate the newer progress monitoring from appengine-plugins-core later, users won't see the detailed output.

![selection_006](https://user-images.githubusercontent.com/10523105/36558777-20aaff9a-17da-11e8-92ad-36fd19259890.png)

We do have a console for the dev appserver already, so we could simply stream to it.

When install fails, it'd be easier to see what went wrong with the install output. An example is https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/541.

**Comment by briandealwis** [comment]
This is also true on the install-on-startup, which is how most users will have the SDK installed.

**Comment by briandealwis** [comment]
TBH, I think a better approach would be to have the jobs stream the results into a separate context, and add an action (via `IProgressConstants.ACTION_PROPERTY`) to allow them to open a separate installation progress console.

**Comment by chanseokoh** [comment]
I think such optional opportunistic installations are OK with the job progress. They are not critical, could be cancelled by users, and users will eventually hit an installation problem when deploying or running locally.

However, if they could also open a separate console, that'd be useful. But I think it's relatively a low priority for such optional installations.

**Comment by chanseokoh** [comment]
I'm experimenting with `IProgressConstants.ACTION_PROPERTY`. Looks like a promising approach.
