### ISSUE TITLE
CloudSdkPreferenceAreaTest.testVersion() fails if managed Cloud SDK is installed locally

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2841]
The test assumes that there is no managed Cloud SDK installed. This is not a problem on Travis or Kokoro, but locally, we'll likely have a managed SDK in the future.

```
testVersion(com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest)  Time elapsed: 0.017 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<SDK version: [No SDK found]> but was:<SDK version: [190.0.1]>
    at org.junit.Assert.assertEquals(Assert.java:115)
    at org.junit.Assert.assertEquals(Assert.java:144)
    at com.google.cloud.tools.eclipse.sdk.ui.preferences.CloudSdkPreferenceAreaTest.testVersion(CloudSdkPreferenceAreaTest.java:95)
```

**Comment by elharo** [comment]
It's ugly, but maybe test for either condition. No SDK found or \d+\.\d+\.\d+

**Comment by chanseokoh** [comment]
The gist of the test is to see unchecking "Choose SDK" won't return the version of the manual SDK, so I think it's sufficient to check the message does not say the manual version.
