### ISSUE TITLE
Internal browser not available on some machines

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2852]
The internal browser is disabled in Eclipse on some machines. This interferes with one of our integration tests that runs the dev appserver. It brings up an external browser and steals the focus.

![selection_007](https://user-images.githubusercontent.com/10523105/36682945-5a6536d4-1aea-11e8-8304-4abf4ffe2d77.png)

_Help_ > _Welcome_ shows a blank screen.

![selection_008](https://user-images.githubusercontent.com/10523105/36682980-6a448f0a-1aea-11e8-8813-0a499d40cd0f.png)

**Comment by chanseokoh** [comment]
The error message is

```
!MESSAGE Internal browser is not available: No more handles [Browser style SWT.MOZILLA and Java system property org.eclipse.swt.browser.DefaultType=mozilla are not supported with GTK 3 as XULRunner is not ported for GTK 3 yet]
```

Setting `SWT_GTK3=0` gets me

```
!ENTRY org.eclipse.ui.browser 2 0 2018-02-26 11:48:19.676
!MESSAGE Internal browser is not available: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
```

If I set `MOZILLA_FIVE_HOME` to `/usr/lib/mozilla` (with `SWT_GTK3=0`), I get 

```
!MESSAGE Internal browser is not available: No more handles [MOZILLA_FIVE_HOME='/usr/lib/mozilla'] (java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	/usr/local/google/home/chanseok/workspace4E/.metadata/.plugins/org.eclipse.pde.core/gcloud-eclipse-tools-no-gtk3/org.eclipse.osgi/569/0/.cp/libswt-mozilla-gtk-4763.so: libxpcom.so: cannot open shared object file: No such file or directory
	no swt-mozilla-gtk in java.library.path
	/usr/local/google/home/chanseok/.swt/lib/linux/x86_64/libswt-mozilla-gtk-4763.so: libxpcom.so: cannot open shared object file: No such file or directory
	Can't load library: /usr/local/google/home/chanseok/.swt/lib/linux/x86_64/libswt-mozilla-gtk.so
)
```

**Comment by elharo** [comment]
https://stackoverflow.com/questions/37099810/java-xulrunner-error-in-eclipse-swt-in-ubuntu

**Comment by chanseokoh** [comment]
Made it work on my machine. Got an idea from https://stackoverflow.com/a/31191579/1701388.

1. Download XULRunner 24: http://ftp.mozilla.org/pub/xulrunner/releases/24.0/runtimes/
1. Unzip it somewhere: `tar jxvf xulrunner-24.0.en-US.linux-x86_64.tar.bz2`
1. `-Dorg.eclipse.swt.browser.XULRunnerPath=<path to the unzipped XULRunner>`
   - For the hosted debug Eclipse, put it in _Arguments_ > _VM arguments_ of the `gcloud-eclipse-tools` run configuration.
   - For your main Eclipse, put in in `eclipse.ini`.

**Comment by chanseokoh** [comment]
Oops, I forgot to mention it requires disabling with `SWT_GTK3=0`.

**Comment by chanseokoh** [comment]
I was able to make our dev appserver integration test to use the internal browser when I run the test inside Eclipse with the above changes.

However, it still doesn't work on the command line with `mvn -Dswt.gtk3=0 -Dorg.eclipse.swt.browser.XULRunnerPath=<XULRunner path> verify`. I can see it's using GTK2 as expected, but the internal browser is still disabled when I go to _Preferences_ > _Web Broswer_. I see the familar error message `!MESSAGE Internal browser is not available: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]`.

**Comment by briandealwis** [comment]
Your command line is setting the property on the Maven instance, not the launched test instance.  For that, you need to adjust the `tycho-surefire-plugin`'s `<argLine>` as set in our top-level [`pom.xml`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/pom.xml#L322).  You can use the `${os-jvm-flags}` property, which we use to pass along some startup flags required for MacOS with the [`macosx-jvm-flags`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/pom.xml#L376) profile.

**Comment by chanseokoh** [comment]
It makes sense and works! Thanks.

I'll update the release doc to handle this. This issue depends on environments and requires installing XULRunner at a custom location to work around, so I think it's best to handle in the command line.

**Comment by chanseokoh** [comment]
Release doc updated. Closing.
