### ISSUE TITLE
Hands off builds

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2859]
Experiment to see if we can build a binary on a Ubiquity or GCE instance to avoid having to be hands off at the computer while the tests run.

**Comment by patflynn** [comment]
@elharo isn't this what Travis or Kokoro provide?

**Comment by briandealwis** [comment]
See also #551

**Comment by elharo** [comment]
We don't currently receive shippable artifacts from either. If we did, we might use that.

**Comment by patflynn** [comment]
You mean for releases?  Isn't kokoro used for signing?

**Comment by elharo** [comment]
Yes, but it doesn't build the artifacts it signs. We build the artifacts on local developer workstations and upload them to GCS where kokoro reads them. I expect we can improve this.

**Comment by chanseokoh** [comment]
For the release purpose, I've found a simple yet very effective solution: just run the build command with `xvfb-run`:

```
   xvfb-run mvn verify
```

 Everything is done in a virtual X display, you are never distracted with a test Eclipse instance continuously popping up on your monitor, and you never accidentally fail integration tests while building locally. Problem solved!

I'll update the release Wiki.
