### ISSUE TITLE
appengine-web.xml validation doesn't work with staging elements

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2862]
The new staging elements are available for `appengine-web.xml`.

https://cloud.google.com/appengine/docs/standard/java/config/appref#staging_elements

However, XML validation doesn't work and places an error. We don't allow deploying if there is an error.

![selection_001](https://user-images.githubusercontent.com/10523105/36739557-3cfc8f24-1bae-11e8-8f97-c7afa4b6f503.png)

A workaround to force deploying is to temporarily delete the problem marker:

![selection_003](https://user-images.githubusercontent.com/10523105/36739509-1a4edd74-1bae-11e8-8c03-6ed9880c8fea.png)

**Comment by chanseokoh** [comment]
Seems like we can just replace our embedded `appengine-web.xsd` with the most recent one.

**Comment by elharo** [comment]
Try manually validating the file against the schema using Xerces. That may give you a more obvious error message.

**Comment by chanseokoh** [comment]
Looks like the test failures in #2864 are unrelated. I'll file another issue for that.

For the validation failure, it certainly goes away if we update `appengine-web.xsd` with #2864.
