### ISSUE TITLE
Examine some tests in .validation.test that fail if Java 8 facet is available

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#2868]
Examine if the following tests work as intended.

- `WebXmlValidatorTest.testValidateJavaServlet()`
- `XmlSourceValidatorTest.testValidate()`

`WebXmlValidatorTest.testValidateJavaServlet()` expects to see a validation error reported: "App Engine Standard does not support this servlet version" when `web.xml` declares Servlet version 3.1 (i.e., `<web-app version=3.1>`) in an App Engine Java7 project. (BTW, it'd be nice to update the error message to say "App Engine Standard Java 7 ...".)

However, these tests fail when running inside Eclipse. They don't report any validation error. We haven't noticed the failures with `mvn verify`, because the `.validation.test` isn't importing the `.java8` bundle. When we force including the `.java8` bundle (e.g., adding it to `MANIFEST.MF`), `mvn verify` fails as well.

Looking at the code, `AppEngineStandardFacet.checkServletApiSupport()` seems to show different behaviors depending on whether the Java 8 facet is present or not.

I believe `XmlSourceValidatorTest.testValidate()` fails for the same reason or at least for a similar reason.

**Comment by elharo** [comment]
I seem to recall that this is WAI. When java8 is included, servlet 3.1 is supported and that test fails. 

We should consider whether we can now drop the separate java8 bundle. But if we can't do that, we probably don't need to worry about this.

**Comment by chanseokoh** [comment]
But the projects being tested have the App Engine Java 7 facet installed, so it makes sense to fail anyway wih Servlet 3.1. It is weird that the `IProjectFacetVersion` reports Java 8 instead of Java 7 when we add the `.java8` bundle. Very perplexing.

**Comment by briandealwis** [comment]
We configure the [default facet version to be `JRE8`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml#L13).  If that facet version isn't found, then WTP ignores the default and chooses another version.

**Comment by chanseokoh** [comment]
I found a root cause. The problem is that the test project set to be created with JRE7, but the project is auto-converted to JRE8. I put the following debug logs in `TestProjectCreator.addFacets()` for testing:

```java
    IProjectFacetVersion facetVersion = AppEngineStandardFacet.getProjectFacetVersion(getProject());
    System.out.println("1 " + facetVersion);

    if (facetedProject.hasProjectFacet(AppEngineStandardFacet.FACET)) {
      // App Engine runtime is added via a Job, so wait.
      ProjectUtils.waitForProjects(getProject());
    }

    facetVersion = AppEngineStandardFacet.getProjectFacetVersion(getProject());
    System.out.println("2 " + facetVersion);
```

The facet changes to JRE8 after `ProjectUtils.waitForProjects()`:
```
1 App Engine Java Standard Environment JRE7
   ...
2 App Engine Java Standard Environment JRE8
```

So, we explicitly want to create a JRE7 project for testing in `WebXmlValidatorTest` like below, what we end up getting is a JRE8 project.

```java
  @Rule
  public TestProjectCreator projectCreator = new TestProjectCreator().withFacetVersions(
      WebFacetUtils.WEB_25, JavaFacet.VERSION_1_7, AppEngineStandardFacet.JRE7);
```

**Comment by chanseokoh** [comment]
Because of this, some tests in `AppEngineStandardFacetTest` also fail when run inside Eclipse. They are designed to test JRE7 projects, but the projects become JRE8.

**Comment by briandealwis** [comment]
The symptoms sound similar to #2869.

**Comment by briandealwis** [comment]
What's also odd is that `com.google.cloud.tools.eclipse.appengine.standard.java8.AppEngineStandardFacetVersionChangeTests.testChange_AESJ8_AESJ7andJava7()` fails in the IDE, but seemingly not on Travis?  Ah… AppEngineStandardFacetVersionChangeTests doesn't seem to be run!
