### ISSUE TITLE
Use extension registry for object creation

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2874]
We have code which attempts to create an object using `java.lang.reflect` from a class-name provided via an extension point.  This code works as the only extensions are defined within that same bundle.  But `Class.forName()` attempts to resolve a class from the calling bundle's classloader, rather than the extension's bundle, and so will fail for extensions from a different bundle.

**Comment by chanseokoh** [comment]
FTR: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2877#issuecomment-369743602
