### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2892]
Investigate further automating release process so kokoro (or Travis?) can produce a nightly update site. 

Possible Q2 OKR.

**Comment by briandealwis** [comment]
We're already pushing the repos on successful travis builds.  But they don't have the OAuth credentials burned in.

**Comment by chanseokoh** [comment]
Related: #2067.

Set up complete. Tested installing a nightly build automatically released yesterday, and it has a correct nightly suffix. Login also works.
