### ISSUE TITLE
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2901]
During flex deployment on mac a probably gcloud error:

```
Beginning deployment of service [default]...
Building and pushing image for service [default]
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
Started cloud build [9eb0c5e3-052b-4b58-b0b7-64e250bf872f].
```

see http://tips.tutorialhorizon.com/2015/10/01/xcrun-error-invalid-active-developer-path-library-developer-commandline-tools-missing-xcrun/

Likely gcloud needs to predetect this condition and respond accordingly.

**Comment by diegomarquezp** [comment]
Closing as not planned since we don't support GAE + Java 8.
