### ISSUE TITLE
Analytics dialog doesn't have right focus

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2906]
On a new installation, I opened the new _App Engine Flexible Project_ wizard, and had the analytics confirmation prompt.  Although the dialog is on top, the focus is on the new project wizard.

MacOS 10.13.

<img width="833" alt="screen shot 2018-03-07 at 3 22 12 pm" src="https://user-images.githubusercontent.com/202851/37116137-59483458-221b-11e8-9b75-df5d93bcbc10.PNG">

**Comment by chanseokoh** [comment]
This was intended so that it doesn't steal the current focus and users can ignore and leave the Analytics prompt open while continuing to work on the wizard. Users are not disrupted this way. If they want to dismiss the dialog right away, they can do so too.

**Comment by briandealwis** [comment]
The problem is that the dialog looks like it's a modal dialog, and the user clicks on it futilely.

I wonder if using the Mylyn Notifications in a similar way as AERI's initial error notifications would work better.

<img src="https://bugs.eclipse.org/bugs/attachment.cgi?id=253440">

**Comment by chanseokoh** [comment]
If the buttons in the prompt dialog isn't clickable, something is wrong. It should be clickable if the right shell (the shell of the wizard) was given.

**Comment by briandealwis** [comment]
Yup, unresponsive in MacOS.  Here's a video: https://drive.google.com/open?id=1Fek49Psns3sqOEGwPTdb252cI0WlqYry

**Comment by chanseokoh** [comment]
@briandealwis I have pushed up a debug branch that always pops up the confirmation dialog: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/analytics-dialog-test

When you have time, could you check if `AnalyticsPingManager.showOptInDialogIfNeeded()` gets a right shell or `AnalyticsPingManager.findShell()` works OK on Mac?

**Comment by briandealwis** [comment]
When it runs, the `parentShell` provided to `showOptInDialogIfNeeded(parentShell)` is `null`.  So `findShell()` returns the active workbench window.

I think part of the issue here is that the actual call to `sendPingOnShell()` happens in `AppEngineStandardWizardPage#createWizardPage()`, which is called prior to the page actually being rendered.  So `getShell()` returns `null`. 

    @Override
    public AppEngineStandardWizardPage createWizardPage() {
      AnalyticsPingManager.getInstance().sendPingOnShell(getShell(),
          AnalyticsEvents.APP_ENGINE_NEW_PROJECT_WIZARD,
          AnalyticsEvents.APP_ENGINE_NEW_PROJECT_WIZARD_TYPE,
          AnalyticsEvents.APP_ENGINE_NEW_PROJECT_WIZARD_TYPE_STANDARD);

**Comment by chanseokoh** [comment]
Not supposed to be closed.
