### ISSUE TITLE
CreateProcess error=206, The filename or extension is too long

### ISSUE THREAD

**Issue by rbichler** [GoogleCloudPlatform/google-cloud-eclipse#2912]
- Cloud Tools for Eclipse version: 1.5.1.201801292341
- Google Cloud SDK version:
   Google Cloud SDK 185.0.0
   app-engine-java 1.9.60
   app-engine-python 1.9.65
   bq 2.0.28
   core 2018.01.12
   gsutil 4.28
- Eclipse version: Version: Mars.2 Release (4.5.2) Build id: 20160218-0600
- OS: Windows 10
- Java version: 1.8.0_151

**What did you do?**
After adding new libraries the deploy stop working

**Step to reproduce the error**
- Add many dependency library 
- Deploy the application clicking right button over the project then press `Deploy to app Engine standard`

![deploy](https://user-images.githubusercontent.com/37183435/37156272-0083ce08-22bc-11e8-8fa8-c7ebf1d81ad7.jpg)

**What did you expect to see?**
I expect that the deploy  work with many libraries or have a workaround like jar packing o shared libraries

**What did you see instead?**
The deploy stop with this error **CreateProcess error=206, The filename or extension is too long**
Screenshots and stack traces are helpful.

Console message: 
[console.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1793503/console.txt)
Log: 
[appcfg2153149213622102013.log](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1793507/appcfg2153149213622102013.log)

**Comment by elharo** [comment]
Try upgrading to Google Cloud SDK 192.0.0. I feel like thyy may have fixed this issue recently.

**Comment by elharo** [comment]
relevant part: com.google.appengine.tools.admin.AdminException: Unable to stage app: Cannot run program "C:\Program Files\Java\jdk1.8.0_121\jre\bin\java.exe": CreateProcess error=206, The filename or extension is too long

**Comment by elharo** [comment]
This issue is likely that your classpath is now very long:

https://stackoverflow.com/questions/10519558/createprocess-error-206-the-filename-or-extension-is-too-long-when-running-main

The error message might not quite correct. It could be that the command line length has exceeded Windows limits.

**Comment by briandealwis** [comment]
Odd, as invoking AppCfg doesn't list the files.

If you run with `eclipse -consolelog` you should see a log line like the following:
```
Mar 08, 2018 10:56:31 AM com.google.cloud.tools.appengine.cloudsdk.CloudSdk logCommand
INFO: submitting command: /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java -cp /Users/bsd/Library/Application Support/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg —disable_update_check --enable_jar_splitting stage /Users/bsd/Manumitting/Projects/GooglePluginEclipse/runtime-gcloud-CLEAR/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1520524589483/staging-work/exploded-war /Users/bsd/Manumitting/Projects/GooglePluginEclipse/runtime-gcloud-CLEAR/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1520524589483/staging
```
Could you please attach it here?

Windows [command-lines are restricted to 32,768 characters](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx).  An immediate workaround might be to put your workspace / checkout in your disk's root (e.g., `c:\ws`) to try to shorten pathnames as much as possible.

**Comment by elharo** [comment]
The error happens during staging so fixing https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/4 might handle this.

**Comment by rbichler** [comment]
@elharo 

I updated the gcloud components versions and the problem persists. 
New versions:
Google Cloud SDK 192.0.0
app-engine-java 1.9.63
app-engine-python 1.9.67
bq 2.0.29
core 2018.03.02
gsutil 4.28

**Comment by rbichler** [comment]
@briandealwis 
I am trying to run "eclipse -consolelog" but it dosen't show any differences in the console. I added the -consolelog in the eclipse.ini. Is there another way to activate the -consoleLog?

**Comment by briandealwis** [comment]
@rbichler Sorry, I should have been clearer.  You need to run that from a Command Prompt window, and you shoud see output inside the Command Prompt window.  You can also use "eclipsec.exe", which should pop up a command prompt window, but this window will close when Eclipse exits.

**Comment by rbichler** [comment]
@briandealwis 

Thanks for the clarification. This is the image with the consoleLog:

![consolelog](https://user-images.githubusercontent.com/37183435/37205908-f54dfea8-236c-11e8-8e55-77c916607be5.jpg)

To make the consoleLog work, I had to modify in the init file the parameter -vm from javaw.exe to java.exe. More detail in [https://stackoverflow.com/questions/32148765/enable-console-logging-for-eclipse-itself-the-platform](https://stackoverflow.com/questions/32148765/enable-console-logging-for-eclipse-itself-the-platform)

**Comment by briandealwis** [comment]
Huh, that command line looks well within the limitations.  I wonder if that space in your workspace directory (`workspace mars`) might have an effect.

While I try to reproduce, would it be possible for you to trying to run that command as-is from your command-line (you'll need to escape the arguments with the space) and see if you get the same failure message?

And perhaps try renaming the workspace to remove the space?

**Comment by briandealwis** [comment]
Indeed `AppCfg` spawns a call to the `com.google.appengine.tools.development.jetty9.QuickStartGenerator` with all of the jars to create a massive command line:

```
 \-+- 36637 bsd /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/bin/java -cp /Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar com.google.appengine.tools.admin.AppCfg --disable_update_check --enable_jar_splitting stage /Users/bsd/Manumitting/Projects/GooglePluginEclipse/ws-cte/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1520605274230/staging-work/exploded-war /Users/bsd/Manumitting/Projects/GooglePluginEclipse/ws-cte/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1520605274230/staging
   \--- 36639 bsd /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre/bin/java -cp /Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-schemas-3.1.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-alpn-server-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jmx-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-webapp-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-continuation-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/servlet-api-3.1.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-server-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-util-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jaas-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-servlets-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jaspi-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-annotations-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-io-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-nosql-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-gcloud-session-manager-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-infinispan-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jndi-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-plus-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-servlet-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-quickstart-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-security-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-rewrite-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-xml-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-client-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-gcloud-memcached-session-manager-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-deploy-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-http-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-proxy-9.3.18.v20170406.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/asm-commons-6.0_BETA.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/javax.annotation-api-1.2.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/asm-6.0_BETA.jar:/Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/tools/quickstart/quickstartgenerator.jar com.google.appengine.tools.development.jetty9.QuickStartGenerator /Users/bsd/Manumitting/Projects/GooglePluginEclipse/ws-cte/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1520605274230/staging /Users/bsd/Manumitting/Projects/GooglePluginEclipse/SDKs/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/docs/webdefault.xml
```

**Comment by briandealwis** [comment]
@rbichler if you're not required to use Java 8, a workaround is to deploy to the App Engine Java 7 runtime (remove the `<runtime>java8</runtime>` from the `appengine-web.xml`).  It doesn't use the QuickStart generation.

**Comment by briandealwis** [comment]
@rbichler I've been trying to reproduce this, but haven't had any success.  Using a workspace with a space in its name (`c:\…\workspace test`) made no difference.  How many dependencies does your project have?

**Comment by rbichler** [comment]
@briandealwis 

I don't think that the problems is the space (workspace mars), because the problem start happen after I added new dependency and if I comment some dependencies it work.

We requiered the project work with Java 8.

Attached you can find the pom.xml with all the dependencies.
[pom.zip](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1802545/pom.zip)

**Comment by briandealwis** [comment]
Thanks for posting your pom @rbichler!  The `com.ispcloudservices:isputilities` is your own artifact.  Can you give me a sense of how many dependencies it has?  You should be able to use the M2Eclipse POM editor and open the Dependency Hierarchy, or use `mvn dependency:tree`, or even just count the number of jars in the `staging-work/exploded-war` directory listed for the `AppCfg` command on the console.

**Comment by rbichler** [comment]
@briandealwis 

com.ispcloudservices:isputilities is a internal artifact that doesn't have dependency

Attached the dependencies tree. [maven_dependency_tree.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1803648/maven_dependency_tree.txt)

**Comment by briandealwis** [comment]
@rbichler This is really puzzling as I'm unable to reproduce it even if I add `org.eclipse.birt.runtime:org.eclipse.birt.runtime:4.4.1`, which brings in 50+ dependencies.

I wonder if your command-line for the Jetty Quickstart generation is different from what I'm seeing. If you don't mind, let's try running the same `AppCfg` that's being executed, but with some logging enabled.

Would you mind copying the following logging configuration into a file `log.properties`:
```
handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level=FINE
com.google.appengine.tools.admin.level=FINE
```
and then run the following command, replacing the `(((log.properties)))` with the location of the above file, and the `(((XXX)))` with the ID number from the console:
```
"C:\Program Files\Java\jdk1.8.0_121\bin\java.exe" -Djava.util.logging.config.file=(((log.properties))) -cp "C:\Users\Rony Bichler\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\appengine-tools-api.jar" com.google.appengine.tools.admin.AppCfg —disable_update_check --enable_jar_splitting stage "D:\developer\workspace mars\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\(((XXX)))\staging-work\exploded-war" "D:\developer\workspace mars\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\(((XXX)))\staging"
```
From what you pasted above the `(((XXX)))` would be `15209595367870`.

(Basically this should be the same as what you see in the console with the addition of the `-Djava.util.logging.config.file=(((log.properties)))`)

**Comment by briandealwis** [comment]
Oh, you'll need to delete the `(((XXX)))/staging directory` before running this.

**Comment by rbichler** [comment]
@briandealwis 
I executed the command as you specified but I don't see more detail in the logs.

This is the command I executed

`"C:\Program Files\Java\jdk1.8.0_121\bin\java.exe" -Djava.util.logging.config.file=log.properties -cp "C:\Users\Rony Bichler\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\appengine-tools-api.jar" com.google.appengine.tools.admin.AppCfg -—disable_update_check --enable_jar_splitting stage "D:\developer\workspace mars\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1520595367870\staging-work\exploded-war" "D:\developer\workspace mars\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1520595367870\staging"`

I tryed to executed the command in differences ways **-Djava.util.logging.config.file=c:\log.properties** and **-Djava.util.logging.config.file="c:\log.properties"**. Also I moved the properties file to C:\Program Files\Java\jdk1.8.0_121\bin\ and executed the command with **-Djava.util.logging.config.file=log.properties**

This is the console log and log file for one of the test I made

log file : [appcfg543975957362246326.log](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1804244/appcfg543975957362246326.log)

Console:

> C:\>"C:\Program Files\Java\jdk1.8.0_121\bin\java.exe" -Djava.util.logging.config.file="C:\Program Files\Java\jdk1.8.0_121\bin\log.properties" -cp "C:\Users\Rony Bichler\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\lib\appengine-tools-api.jar" com.google.appengine.tools.admin.AppCfg --disable_update_check --enable_jar_splitting stage "D:\developer\workspace mars\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1520595367870\staging-work\exploded-war" "D:\developer\workspace mars\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1520595367870\staging"
Reading application configuration data...
Mar 12, 2018 3:14:39 PM com.google.appengine.tools.admin.RepoInfo getSourceContext
FINE: not a git repository or problem calling git
Beginning interaction for module default...
0% Scanning for jsp files.
0% Compiling jsp files.
Unable to stage app: Cannot run program "C:\Program Files\Java\jdk1.8.0_121\jre\bin\java.exe": CreateProcess error=206, The filename or extension is too long
Please see the logs [C:\Users\RONYBI~1\AppData\Local\Temp\appcfg543975957362246326.log] for further information.

**Comment by briandealwis** [comment]
The fact that you have the following means that the logging properties were in effect:

> Mar 12, 2018 3:14:39 PM com.google.appengine.tools.admin.RepoInfo getSourceContext
> FINE: not a git repository or problem calling git

Oh of course, you have JSPs! 🤦‍♂️  Ok, now I can reproduce.  _AppCfg_ attempts to invoke the JSP compiler (`com.google.appengine.tools.development.jetty9.LocalJspC`) _with all of the classpath dependencies provided on the command-line_.  With my pom including `org.eclipse.birt.runtime`, and all of the dependencies staged into `C:\Users\IEUser\workspace test\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1520868867512\staging-work\exploded-war` (a fairly typical staging location for CT4E), that classpath string is 32787 bytes!

@rbichler Since you're using Maven, a workaround is to use `mvn appengine:deploy` from the command-line.  `appengine:deploy` generates the WAR inside the project in the `target/` directory, so if you checkout your project into a directory close to your root then the resulting command-line lengths will be greatly reduced.

**Comment by briandealwis** [comment]
Filed upstream as https://issuetracker.google.com/issues/74515248

**Comment by rbichler** [comment]
@briandealwis 

We found a work around, we don't like it because we are losing one of the main reason for using maven, but we can continue deploying until Google come out with the fix.

The workaround we are doing is create all new libraries in pom.xml with the tag `<scope>provided</scope>` and add manually the new jars in **WEB-INF\lib**.

I saw you report the issue in Google. We are going to wait until Google create a fix

Thanks for all you help, We really appreciate it

**Comment by briandealwis** [comment]
[The issue has been fixed upstream](https://issuetracker.google.com/issues/74515248#comment9):
> A fix has been pushed to the internal repository...
> Usually, it takes 1-2 weeks before it shows up in the public Cloud SDK.
