### ISSUE TITLE
Google LLC

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#2916]
New Google standard is that this takes the form 

```
 * Copyright 2016 Google LLC. All Rights Reserved.
```

That is,

* Google LLC, not Google Inc.

https://g3doc.corp.google.com/company/teams/opensource/copyright.md?cl=head

**Comment by elharo** [comment]
This is now

 * Copyright 2016 Google LLC.

It should be

 * Copyright 2016 Google LLC. All Rights Reserved.

**Comment by briandealwis** [comment]
Oops, I missed that component.  Sorry.

**Comment by elharo** [comment]
NVM. There's conflicting internal documentation about whether All Rights Reserved is required or not. I kicked this up the chain, and the official response is we shouldn't use "All Rights Reserved".
