### ISSUE TITLE
Cannot launch DirectPipeline without a Google Account selected

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2925]
1. Create new Dataflow project.  Do not set any account defaults.
2. Launch with _Debug As > Dataflow Pipeline_.  
   1. Select the _StarterPipeline_
   2. On the _Pipeline Arguments_ tab, select the DirectRunner and ensure the _Use default Dataflow options_ is checked.
3. Click the _Debug_ button.

![screen shot 2018-03-08 at 3 27 11 pm](https://user-images.githubusercontent.com/202851/37174676-35775c78-22e5-11e8-9940-10df7648011d.PNG)

Selecting a Google account either in the launch configuration or the project settings is enough to get this working.

**Comment by chanseokoh** [comment]
So, the user forgot to select an account or the account is logged out. What should be done? Improve the error message? (It's our message supposed to be friendly than the error message Dataflow will throw when actually executed.)

**Comment by briandealwis** [comment]
I don't think an account needed to be selected at all.

**Comment by chanseokoh** [comment]
I had the same question: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2002#issuecomment-316533003

@tgroh said an account may still be used even if running locally with `DirectPipelineRunner`. That's why I made it require an account. @tgroh I'm wondering again if we have to force users set an account with running locally.

**Comment by briandealwis** [comment]
If we run something that requires a GCP project (e.g., the dataflow runner) and a project isn't selected then an error pops up during the deploy.

**Comment by chanseokoh** [comment]
> an error pops up during the deploy

You actually mean during the deploy (i.e., before the job actually starts running) or at some point of the job running locally?

In any case, I agree it's OK to relax the constraint for the local run. Maybe it was too stringent. If the job fails due to lack of auth, let's just have the dataflow job complain it.

**Comment by tgroh** [comment]
Certain pipelines (e.g. those that read from/write to any Google Cloud Platform service, especially notable for Cloud Storage) won't work if there's no account that we can auth with; for direct API use I believe this is true including for world-readable cloud storage buckets. It's not a strict requirement for running an arbitrary pipeline, though

**Comment by lak-proddev** [comment]
I think we should alert before the launch.

**Comment by lak-proddev** [comment]
@elharo Is there any dev communication channel for discussing?
Meanwhile, I have this issue while updating TP. Any suggestions?

$ mvn -Pide-target-platform
[INFO] Scanning for projects...
Downloading from central: http://nexus.crowncastle.com:8081/content/groups/public/org/eclipse/tycho/tycho-maven-plugin/1.3.0/tycho-maven-plugin-1.3.0.pom
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:1.3.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:1.3.0 @
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.google.cloud.tools.eclipse:eclipse-setup:0.1.0-SNAPSHOT (D:\git\Others\google-cloud-eclipse\eclipse\pom.xml) has 1 error
[ERROR]     Unresolveable build extension: Plugin org.eclipse.tycho:tycho-maven-plugin:1.3.0 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.eclipse.tycho:tycho-maven-plugin:jar:1.3.0: Could nottransfer artifact org.eclipse.tycho:tycho-maven-plugin:pom:1.3.0 from/to central (http://nexus.crowncastle.com:8081/content/groups/public/): nexus.crowncastle.com: Unknown host nexus.crowncastle.com -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/PluginManagerException

**Comment by briandealwis** [comment]
@lak-proddev that seems to be a problem with your local setup:
```
Could nottransfer artifact org.eclipse.tycho:tycho-maven-plugin:pom:1.3.0 from/to central (http://nexus.crowncastle.com:8081/content/groups/public/): nexus.crowncastle.com: Unknown host nexus.crowncastle.com -> [Help 2]
```
Maven will record that it had problems by placing `xxx.lastUpdated` files in your local repository (`~/.m2/repository`) and refuse to check again for some time period.  You should be able to force Maven to check with `mvn -U`, but I find I sometimes need to remove the corresponding `.lastUpdated` file in `~/.m2/repository` though ([details](https://stackoverflow.com/a/4556024/600339)).

**Comment by lak-proddev** [comment]
okay, thanks.  will check.
and 
How to create a pull request for a new commit? I try to create for 
https://github.com/lak-proddev/google-cloud-eclipse/commit/490e9158b551cc9c5f23b9f2f0588b3d7eadadc9

But, it's creating with my earlier commits. Can I directly push to the original repository instead of from fork?

**Comment by briandealwis** [comment]
You have to make your commits start from HEAD.  You can use `cherry-pick` to pull out a series of commits from a branch.  You can also use `rebase` to pull in a range, but I never remember the right order.
