### ISSUE TITLE
Launching a Maven app blocked on Building workspace… even though it was asleep

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#2929]
1. Created a new Maven AESv7 project.
2. Modified the HelloWorldServlet to output more information.
3. Started to launch project with _Debug As > App Engine_.
4. The launch was blocked on _Building workspace…_ but that job was asleep.

I tried killing the _Building workspace…_ job, but then I saw this odd cycling behaviour in the progress area (not in the view) where some job was continuously started/stopped.  I ended up having to restart Eclipse.

**Comment by briandealwis** [comment]
This is a bit of a heisenbug.

**Comment by diegomarquezp** [comment]
Closing as not planned.
