### ISSUE TITLE
Cannot Install CT4E in Eclipse Oxygen due to possible read permission error on update site

### ISSUE THREAD

**Issue by jamesmortensen** [GoogleCloudPlatform/google-cloud-eclipse#2933]
Before reporting a possible bug:

- Cloud Tools for Eclipse version:  Not installed - Trying to install from Marketplace.
- Google Cloud SDK version:  190.0.1
- Eclipse version: Oxygen
- OS: Mac OS High Sierra
- Java version:  1.8.0_152

**What did you do?**

I uninstalled CT4E 1.5.1 so I could get the latest version, 1.6.0

**What did you expect to see?**

I expected to get the latest version.

**What did you see instead?**

I saw error messages that indicate that perhaps the new version is not accessible or available, and the previous 1.5.1 version is not available either.  My Eclipse is now "broken" for compiling, building, and running App Engine Projects.

This message I got when trying to install CT4E:

<img width="550" alt="screen shot 2018-03-13 at 12 11 43 pm" src="https://user-images.githubusercontent.com/1315816/37326520-819cdfd4-26b8-11e8-9bfc-53a1fb16dfa5.png">

At the top, you can see an error message indicating that the "provisioning operation cannot be completed"
<img width="600" alt="screen shot 2018-03-13 at 12 13 26 pm" src="https://user-images.githubusercontent.com/1315816/37326532-8af710e0-26b8-11e8-83af-8ab14038f11b.png">

When I tried to visit the download URL, https://dl.google.com/eclipse/google-cloud-eclipse/stable/, for the stable version of CT4E, it says I don't have read permission for 1.6.0...

<img width="857" alt="screen shot 2018-03-13 at 12 14 28 pm" src="https://user-images.githubusercontent.com/1315816/37326559-a9273644-26b8-11e8-907b-c02d77bf700e.png">

Hope this helps.  
James

**Comment by chanseokoh** [comment]
It is normal that the URL itself (the root directory) is not accessible. Files under the root should be accessible, e.g., https://dl.google.com/eclipse/google-cloud-eclipse/stable/content.jar.

That said, something seems to have gone wrong during uninstallation and reinstallation. Let me dig into it.

**Comment by briandealwis** [comment]
@jamesmortensen  Just do a _Help > Update_ and you should pick up the new changes.

We renamed our main feature, but forgot to update the Marketplace entry.  That's why you saw the provisioning error.  https://dl.google.com/eclipse/google-cloud-eclipse/stable/ is a p2 repo and although there is an [`index.html`](https://dl.google.com/eclipse/google-cloud-eclipse/stable/index.html) there it isn't being served (#2934).

**Comment by chanseokoh** [comment]
Should work now. Feel free to re-open if you still encounter an issue.
