### ISSUE TITLE
gcloud deploy with Eclipse Error Staging Failed

### ISSUE THREAD

**Issue by Patrick-Petit** [GoogleCloudPlatform/google-cloud-eclipse#2946]
Eclipse IDE for Java Developers
Version: Oxygen.2 Release (4.7.2)    under windows 10
appengine api SDK 1.9.63
jre1.8.0_162

I have create project Google App Engine  Standard Java Project
When i want deploy project i have a message error:
Staging failed. Check the error message in the Console View.
Validation Error: Java App Engine components not installed. Fix by running 'gcloud components install app-engine-java' on command-line.

I installed components app-engine-java with powershel on my console, but  always not deploying

Any ideas ?

**Comment by chanseokoh** [comment]
Hi,

Go to _Window_ > _Preferences_ > _Google Cloud Tools_. If _Choose SDK_ is checked, uncheck it. Once it is unchecked, our plugin will auto-download a new Cloud SDK with the app-engine-java component and use it.

![selection_004](https://user-images.githubusercontent.com/10523105/37487182-2a24ddbe-2867-11e8-8dd1-61bbf6c0236a.png)

If it is already checked, then something is wrong. If so, please let me know, and I will dig into it.

Finally, if you the preference page doesn't have the _Choose SDK_ checkbox, you are not using the latest plugin. Try _Help_ > _Check for Updates_ and install CT4E 1.6.0.

**Comment by chanseokoh** [comment]
> If it is already checked, then something is wrong.

Sorry, typo. If it is already **unchecked**, then something is wrong.

**Comment by chanseokoh** [comment]
Also, next time you file a new issue, please use the built-in menu. It will auto-populate information about your environment (such as CT4E version, Cloud SDK, etc.).

![selection_005](https://user-images.githubusercontent.com/10523105/37488493-36ba5d34-286b-11e8-9712-76c7664f47d2.png)

**Comment by chanseokoh** [comment]
I see you filed #2949. I'll follow up there.

**Comment by IanDex** [comment]
### _`ssssss****_
