### ISSUE TITLE
cannot install Google Cloud SDK Gcloud deploy

### ISSUE THREAD

**Issue by Patrick-Petit** [GoogleCloudPlatform/google-cloud-eclipse#2949]
- Cloud Tools for Eclipse version: 1.6.0.201803071812
- Google Cloud SDK version: 193.0.0
- Eclipse version: 4.7.2.v20171130-0510
- OS: Windows 10 10.0
- Java version: 1.8.0_162

I have create project standard Java when i deploy  a message error:
Deploy failed: cannot install Google Cloud SDK
Failed to install the Google Cloud SDK.
Process failed with exit code: 1

any ideas

**Comment by chanseokoh** [comment]
When you started deploying, it should have opened up a console:

![selection_006](https://user-images.githubusercontent.com/10523105/37491217-7a2591da-2873-11e8-977b-5ac730395cb5.png)

You may need to select a right console if another console is at the front. The name of the console starts with "App Engine Deploy - &lt;your GCP project&gt;".

![selection_007](https://user-images.githubusercontent.com/10523105/37491337-d753a41e-2873-11e8-9411-3392eb1de24e.png)

Do you see any error or message on the console? Also, if you happen to have a console named "Configuring Google Cloud SDK" like the screenshot above, check that console too. Do you see anything?

Also, can you check _Window_ > _Show View_ > _Error Log_? I think you'll be able to find relevant errors log there.

**Comment by Patrick-Petit** [comment]
I have ce message in the log:
null
com.google.cloud.tools.eclipse.appengine.deploy
Error
Thu Mar 15 22:22:35 CET 2018
Deploy failed: cannot install Google Cloud SDK

org.eclipse.core.runtime.CoreException: Failed to install the Google Cloud SDK.
	at com.google.cloud.tools.eclipse.appengine.deploy.DeployJob.runInWorkspace(DeployJob.java:96)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: com.google.cloud.tools.managedcloudsdk.command.CommandExitException: Process failed with exit code: 1
	at com.google.cloud.tools.managedcloudsdk.command.CommandRunner.run(CommandRunner.java:59)
	at com.google.cloud.tools.managedcloudsdk.install.Installer.install(Installer.java:68)
	at com.google.cloud.tools.managedcloudsdk.install.SdkInstaller.install(SdkInstaller.java:118)
	at com.google.cloud.tools.eclipse.sdk.internal.CloudSdkInstallJob.modifySdk(CloudSdkInstallJob.java:65)
	at com.google.cloud.tools.eclipse.sdk.internal.CloudSdkModifyJob.run(CloudSdkModifyJob.java:97)
	... 1 more

any ideas ?

**Comment by chanseokoh** [comment]
What about the consoles? Looking at the stack trace, at least the console should have printed

"[Installing Google Cloud SDK]"

. (Like in my first screenshot above.)

One frequent reason of failures is that your Eclipse cannot have permission to create files on your home directory. The default location where the SDK is automatically installed is `C:\Users\<username>\AppData\Local\google-cloud-tools-java\managed-cloud-sdk\LATEST`. Make sure to run your Eclipse as your user account, for example.

**Comment by chanseokoh** [comment]
BTW, I don't think you have a permission problem. I am sure files have already been downloaded into `C:\Users\<username>\AppData\Local\google-cloud-tools-java\managed-cloud-sdk\LATEST\google-cloud-sdk\`, and it seems like running `install.bat` in that directory fails for some unknown reason. I think your console should show you what went wrong.

**Comment by Patrick-Petit** [comment]
The SDK not install. The message is python problem

![image](https://user-images.githubusercontent.com/37417420/37493791-782c0228-28a6-11e8-8b39-b6bf0f3b8e94.png)

I am going remove google-cloud -tools-java and reinstall SDK 

Thanks for your help

**Comment by chanseokoh** [comment]
I'm not a Python expert, but looks gcloud is picking up Python 2.5 under `C:\csvn\Python25`, which doesn't have a necessary module (`_sqlite3`) for gcloud.

The auto-donwloaded gcloud has a Python bundled at `C:\Users\<username>\AppData\Local\google-cloud-tools-java\managed-cloud-sdk\LATEST\google-cloud-sdk\platform\bundledpython\python.exe`, as can be seen in your screenshot. If you set `CLOUDSDK_PYTHON` and re-execute `install.bat`, I think the script will run fine.

I can think of more workarounds if this doesn't work.

**Comment by Patrick-Petit** [comment]
Ok thanks i will continue tomorow it is later in France

**Comment by chanseokoh** [comment]
No problem. In any case, Python 2.5 is too old, and I suggest upgrading it.

**Comment by Patrick-Petit** [comment]
Ok i am going to tried  Python 2.5 and after update

**Comment by patflynn** [comment]
@chanseokoh I wonder why it's not using the bundled python by default.

**Comment by chanseokoh** [comment]
I am wondering that too. I was suspecting if some other variable (such as `PYTHONHOME` or `PYTHONPATH`) is defined in the environment and taking precedence in the middle. @vilasj also think it is strange, because gcloud is aware of the bundled python but for some reason it is looking outside the bundled python for that library.

**Comment by Patrick-Petit** [comment]
Many thanks,

It was PYTHONHOME !  I deleted it and deployed my project, the SDK dowmload in automatic and  my  project work in browser.

Thank you  very much for your help very fast.
Patrick

**Comment by chanseokoh** [comment]
@Patrick-Petit thank you very much for letting us know what the problem was. We will work on fixing this issue.
