### ISSUE TITLE
As soon as I hit run server (with or without added application) I get the error "Server App Engine Standard at localhost failed to start."

### ISSUE THREAD

**Issue by SandeepHooda** [GoogleCloudPlatform/google-cloud-eclipse#2950]
- Cloud Tools for Eclipse version: 1.6.0.201803071812
- Google Cloud SDK version: 193.0.0
- Eclipse version: 4.7.2.v20171130-0510
- OS: Windows 10 10.0
- Java version: 1.8.0_121

**Comment by chanseokoh** [comment]
Can you give us more details?

- There must be some output of the local run in your console (_Window_ > _Show View_ > _Console_). You may have multiple consoles, so please check all the consoles you have.
- Also check _Window_ > _Show View_  > _Error Log_ to see if any relevant error is there.

**Comment by SandeepHooda** [comment]
Hi chanseokoh,

I was trying to fix this since last 10 hours non stop. Finally I uninstalled everything eclipse/Google cloud SDK/Servers and then did a fresh start not I am able to get it published. Thanks for your quick response though.

**Comment by chanseokoh** [comment]
> not I am able to get it published

Since you closed the bug, I assume you had a typo and it actually reads "_now_ I am able to ...". Feel free to re-open if you still have problems. Thanks.
