### ISSUE TITLE
Gson in a Servlet 3.1 not workink on  app engine

### ISSUE THREAD

**Issue by Patrick-Petit** [GoogleCloudPlatform/google-cloud-eclipse#2952]
- Cloud Tools for Eclipse version: 1.6.0.201803071812
- Google Cloud SDK version: 193.0.0
- Eclipse version: 4.7.2.v20171130-0510
- OS: Windows 10 10.0
- Java version: 1.8.0_162

i would like use Gson object in a Servlet 3.1 with app engine it is not work.
Any ideas ?

**Comment by briandealwis** [comment]
@Patrick-Petit please provide more detail.  What did you do, what did you see.

**Comment by Patrick-Petit** [comment]
Gson is ok. i have set correctly in maven.
But i have another problem: my sevlet is not authorised now. before i was java 7 and eclipse luna on appengine, and since i migrated on java 8 and SDK 1.9.63  and eclipse oxygen the cross domain not working in my servlet

The code of my servlet for cross domain:
resp.addHeader("Access-Control-Allow-Origin", "*");
resp.addHeader("Content-Type", "text/plain");

Any ideas ?

**Comment by briandealwis** [comment]
Sorry @Patrick-Petit but such questions belong on StackOverflow.  It sound like you might be hitting https://stackoverflow.com/a/13147554

**Comment by Patrick-Petit** [comment]
Thank you Brian,
Have a good day.
