### ISSUE TITLE
NoClassDefFoundError in Production

### ISSUE THREAD

**Issue by DanPascariu** [GoogleCloudPlatform/google-cloud-eclipse#2972]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.6.0.201803071812
- Google Cloud SDK version: 194.0.0
- Eclipse version: 4.7.3.v20180301-0715
- OS: Windows 10 10.0
- Java version: 1.8.0_161

**What did you do?**
1. create a new App Engine Standard Java Project using Google Cloud Tools for Eclipse
2. modify the generated HelloAppEngine servlet to add a reference to Query.Filter class like this:
```
        Query.Filter filter = Query.FilterOperator.EQUAL.of("name", "boo");
        response.getWriter().print("Hello: " + filter);
```
3. run the modified HelloAppEngine on the dev server - it works fine
6. deploy the modified HelloAppEngine to appspot.com

**What did you expect to see?**
- in the browser: Hello: name = boo

**What did you see instead?**
- in the browser: 500 Server Error 
- in the logs: java.lang.NoClassDefFoundError: com/google/appengine/api/datastore/Query$Filter 

**Notes**
- I deployed the same code from IntelliJ IDEA and it worked as expected
- I also created this issue: https://issuetracker.google.com/issues/76144204

Screenshots and stacktraces are helpful.

**Comment by elharo** [comment]
1. Were you using Maven or an Eclipse native project?
2. Did you try deploying this app with gcloud from the command line? 
3. What other imports did you need?

**Comment by DanPascariu** [comment]
Hi elharo, to answer your questions:

1. Were you using Maven or an Eclipse native project?
Eclipse native project - like this:
a. Click the Google Cloud Platform icon - Create New Project - Google App Engine Standard 
b. Enter Project name, Java package (nothing else) - click Finish
c. Deploy the generated HelloAppEngine  - works fine
d. Modify the generated HelloAppEngine as shown in my original post - with a reference to Query.Filter
e. Deploy again - it fails

2. Did you try deploying this app with gcloud from the command line?
Yes, I tried like this - but it still throws the error:
```
cd D:\path-to-eclipse-workspace\my-project
gcloud app deploy src\main\webapp\WEB-INF\appengine-web.xml -v v1
```
3. What other imports did you need?
No other imports - just the standard template project - and added the imports for Query:
`import com.google.appengine.api.datastore.Query;`
I attached my java class.

[HelloAppEngine.java.txt](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/1844431/HelloAppEngine.java.txt)

Thanks!

**Comment by elharo** [comment]
When I try this at head I see a different problem:

```
Beginning interaction for module default...
0% Scanning for jsp files.
Error: Could not find or load main class com.google.appengine.tools.development.jetty9.QuickStartGenerator
Error while executing: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/bin/java -cp /Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-schemas-3.1.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-alpn-server-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jmx-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-webapp-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-continuation-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/servlet-api-3.1.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-server-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-util-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jaas-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-servlets-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jaspi-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-annotations-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-io-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-nosql-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-gcloud-session-manager-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-infinispan-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-jndi-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-plus-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-servlet-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-quickstart-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-security-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-rewrite-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-xml-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-client-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-gcloud-memcached-session-manager-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-deploy-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-http-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/jetty-proxy-9.3.18.v20170406.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/asm-commons-6.0_BETA.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/javax.annotation-api-1.2.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/jetty93/jetty-distribution/lib/annotations/asm-6.0_BETA.jar:/Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/tools/quickstart/quickstartgenerator.jar com.google.appengine.tools.development.jetty9.QuickStartGenerator /Users/elharo/workspaces/runtime-gcloud-eclipse/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1521907512788/staging /Users/elharo/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/docs/webdefault.xml 
Unable to stage app: Failed to generate quickstart-web.xml.
Please see the logs [/var/folders/c_/5zfczd_j2rz9c4_4jst82j7h0028bc/T/appcfg4825438253282919637.log] for further information.
```

**Comment by elharo** [comment]
Using the managed SDK fixes my problem, and I can't reproduce the original one reported.

**Comment by lvalladares** [comment]
I dont know if it is the same case but when i deploy i get the following error: 
`java.lang.NoClassDefFoundError: com/google/appengine/api/utils/SystemProperty`

When checking on the java classpath this class is in there.

I last deployed 5 days ago and everything where fine, today without updating anything, adding or removing any libraries this error appeared.

Besides this error, the deploy is taking long than usual, normal deploys take about 3 minutes, today deploys are taking 10-15 minutes

I tried updating gcloud components and eclipse plugin today, and the problem still there.

Your current Cloud SDK version is: 194.0.0
Eclipse version: Mars.2 Release (4.5.2)
Google Cloud Platform for Eclipse	1.6.0.201803071812	
Windows 10

**Comment by chanseokoh** [comment]
I can reproduce this with `gcloud app deploy` and `mvn -DskipTests=true clean appengine:deploy`. As such, this is not a CT4E issue. This seems almost like an App Engine platform issue.

**Comment by chanseokoh** [comment]
@lvalladares @DanPascariu please see https://b.corp.google.com/issues/76144204#comment46 for a fix or a workaround.

The server has made a breaking change (precisely speaking, fixed a long-overdue bug) that always provided the App Engine API, and now you need to explicitly place the `appengine-api-1.0-sdk` JAR into your `WEB-INF/lib`. (Precisely speaking, the JAR `appengine-api-1.0-sdk` in your `WEB-INF/lib` still won't get deployed, but if such a JAR is there, the server will continue to auto-provide the App Engine API in that case.)

**Comment by chanseokoh** [comment]
FTR, the server has rolled back the change, so it will always auto-provide the App Engine API on the server-side for some time. But eventually, it plans to apply the breaking change going forward. Users should assume the API is not auto-provided.
