### ISSUE TITLE
Missing wizard names

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3000]
This is in hosted mode, so this may be a false alarm but:

![image](https://user-images.githubusercontent.com/1005544/38222681-3c9afeaa-36b4-11e8-96f8-eae2b98a0d57.png)

That is, the non-dataflow wizard names seem to have gone missing. Anyone else seeing this? We should hold the release cut until we either fix this or determine it's not happening on other systems.

**Comment by chanseokoh** [comment]
This may happen if appengine-plugins-core is not loaded for any reason. Can happen after upgrading appengine-plugins-core and the IDE target platform is not re-built and reloaded.

**Comment by briandealwis** [comment]
There are a lot of items missing from that menu.  I don't see any problem with a just-rebuilt IDE TP.

<img width="487" alt="screen shot 2018-04-02 at 9 15 52 pm" src="https://user-images.githubusercontent.com/202851/38223856-21985ad8-36bb-11e8-81f9-9970e91f7c1f.PNG">
