### ISSUE TITLE
JSP 2.3.0 or 2.3.1

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3004]
Creating a Java 8 Maven project with the wizard uses JSP 2.3.1.
Creating a Java 8 native project with the wizard uses JSP 2.3.0.

Which one is right? i.e. provided by the server? That's the one both types of project should use.

**Comment by elharo** [comment]
There's one jar in the classpath on the server: /base/java8_runtime/runtime-shared.jar

seems to be built by this target: https://cs.corp.google.com/piper///depot/google3/java/com/google/apphosting/BUILD?q=runtime-shared.jar&l=839

**Comment by elharo** [comment]
As best I can tell backtracking through the repo this originally comes from tomcat-jsp-api-8.0.5.jar

**Comment by elharo** [comment]
This is from March 24 2014:

http://search.maven.org/#artifactdetails%7Corg.apache.tomcat%7Ctomcat-jsp-api%7C8.0.5%7Cjar

**Comment by briandealwis** [comment]
#2465 has some discussion, and the actual change for Flex was made in #2476.  I don't know why I didn't change the `<library>` version for the JSP API though.

**Comment by elharo** [comment]
Official word is its whatever jar we pick up from Jetty 9.3.18.

**Comment by elharo** [comment]
And on a related note for JSTL we should use these two:

org.apache.taglibs:taglibs-standard-spec:jar:1.2.5
org.apache.taglibs:taglibs-standard-impl:jar:1.2.5

This is all for standard. I'm not yet sure what flex is using.

**Comment by chanseokoh** [comment]
> org.mortbay.jasper:apache-jsp:jar:8.0.33

My understanding around these API JARs (servlet-api, jsp-api, etc) is basically like this: https://stackoverflow.com/a/25256855/1701388

AFAIK, those JAR contains only the "interface" (the API) of the Servlet/JSP Specification, without any actual implementation. When developing a web app compatible with Servlet Specification, you don't need any actual implementation, hence only the lightweight API. And anyone could provide their own implementations if they need to, as long as it satisfies the Specification (the API). One of the parties that have to provide an actual implementation is Servlet/JSP/JEE containers, who need to actually execute users' servlet web apps. There are many popular containers and they have their own names for the API implementation JARs.

Also one of its comments provides additional details:

> servlet-api.jar contains only the API. The jars in the container contain the API plus the implementation classes. You have to note it when running tests outside of the container : you may have to stub or mock the implementation classes (or get a full jar from Oracle Glassfish for example).

**Comment by elharo** [comment]
This is not a regression so we don't have to fix this issue in this release, but it's still a high priority bug.

The jars we are adding now do contain implementations. They are *not* interfaces only. And we are not adding exactly the same ones that will be used in production. We need to fix this.

**Comment by elharo** [comment]
The jstl dependency does not have provided scope so we may not need to change that.

**Comment by briandealwis** [comment]
> The jars we are adding now do contain implementations

That should be ok since not included in the .war, including when launching with the devappserver.

**Comment by elharo** [comment]
And they are used when running unit tests inside Eclipse so even non-API level differences can have an effect. We really, really should use the same jar the server provides.

**Comment by elharo** [comment]
The above jar may not be accurate. Post-deployment I don't see classes I expect to find in org.mortbay.jasper:apache-jsp:jar:8.0.33

```
com.google.apphosting.runtime.jetty9.JettyLogger warn: Error for /hello
java.lang.NoClassDefFoundError: org/apache/jasper/util/ExceptionUtils
	at c.g.HelloAppEngine.doGet(HelloAppEngine.java:23)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
```

**Comment by elharo** [comment]
Correct answer may be:

```
    <dependency>
      <groupId>org.eclipse.jetty</groupId>
      <artifactId>apache-jsp</artifactId>
      <version>9.3.18.v20170406</version>
      <classifier>nolog></classifier>
      <scope>provided</scope>
    </dependency>
```

**Comment by elharo** [comment]
FYI, none of the Maven sample achetypes use JSPs at all, just the servlet API and JSTL.
