### ISSUE TITLE
CloudLibrariesPage should prevent creating multiple containers

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3005]
We don't want to allow having multiple _Google Cloud Libraries_ classpath containers on a project.  Since JDT does not provide any mechanism to control creating new containers, then we should change `CloudLibrariesPage` to detect the situation and create an error page and prevent the creation/editing of the new container.

Basically our `#initialize()` is called with the project's current classpath entries.  `setSelection()` will be called with `null` to indicate a new container.  We should then check in `createControl()` if there's a current container.

**Comment by chanseokoh** [comment]
Fixed by https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/2999/commits/a074cf503f89c5dd604644de17986b5c1ce4a290 in #2999. Closing.
