### ISSUE TITLE
Don't put exception into menu

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3006]
We need a better message here, and it should fit in the menu.

![image](https://user-images.githubusercontent.com/1005544/38325258-7d773e2c-3810-11e8-9d2a-25038683ee0c.png)

We should distinguish between no network connectivity locally and an actual problem on GCP.

**Comment by briandealwis** [comment]
Also seen: `NoRouteToHostException`.

**Comment by elharo** [comment]
Any exception at all probably means a local network failure.
