### ISSUE TITLE
Maven Bill Of Materials for dataflow

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3007]
Can/should we use a BOM in the pom.xml for new dataflow projects?

**Comment by chanseokoh** [comment]
We create a project from a Maven archetypes, so I think we should add a BOM there.

**Comment by duncdrum** [comment]
what would be the use? `pom.xml` is UTF-8 xml and doesn't need a BOM. Many xml streaming tasks will trip up if a BOM is inserted at the beginning of an xml doc, ie before `<?…`. So unless there is a strong case for it, i would rather not have BOM inserted.

**Comment by elharo** [comment]
Sorry. In context BOM == Maven Bill of Materials

BOM != Unicode Byte Order Mark.

**Comment by duncdrum** [comment]
@elharo 😆 as you can see i was debugging something with the other one, which is how i stumbled across this, Bill away…, but don't byte order please
