### ISSUE TITLE
Count downloads

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3008]
That is, plugin installs from our Cloud Storage bucket.

**Comment by briandealwis** [comment]
We can configure p2 to ping a stats URL: https://wiki.eclipse.org/Equinox_p2_download_stats

**Comment by elharo** [comment]
This seems to be the way to do it now:

https://cloud.google.com/logging/docs/audit/

**Comment by elharo** [comment]
This is where to start. https://cloud.google.com/logging/docs/audit/configure-data-access

See the gcloud examples further down the page

**Comment by elharo** [comment]
Logs are now being collected. Now we need a counter:

https://cloud.google.com/logging/docs/logs-based-metrics/counter-metrics

**Comment by elharo** [comment]
https://app.google.stackdriver.com/services/gcs/cloud-tools-for-eclipse:cloud-tools-for-eclipse?project=cloud-tools-for-eclipse

**Comment by JoeWang1127** [comment]
close as not planned
