### ISSUE TITLE
just upgraded CT4E  - now I have lots of broken imports

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#3010]
- Cloud Tools for Eclipse version: 1.6.1.201804031530
- Google Cloud SDK version: 196.0.0
- Eclipse version: 4.6.3.v20170301-0400
- OS: Windows 10 10.0
- Java version: 1.8.0_121

After upgrading CT4E I now have a lot of broken library references. For example, EntityNotFound exceptions for Datastore. Also UserServiceFactory is missing.

How best to restore the missing libraries?

**Comment by chanseokoh** [comment]
Looks like #2976. You need to provide `appengine-api-1.0-sdk-*.jar` yourself, like any arbitrary library you would do with. For non-Maven projects, this usually means placing the JAR under `WEB-INF/lib`. For Maven projects, you will put a `<dependency>` (it should not have `<scope>provided</scope>`).

**Comment by chanseokoh** [comment]
Ah, @elharo is right. It is best to use the menu rather than adding it yourself, especially for non-Maven projects.

**Comment by Rob46** [comment]
Does this mean I can now safely remove  WEB-INF/lib/appengine-api-1.0-sdk-1.9.31.jar
that I recently added (to overcome #2976.)??

**Comment by elharo** [comment]
Yes, you can remove that provided you add it back as described above. But it does need to be in your classpath somewhere.
