### ISSUE TITLE
gcloud crashed (IOError): [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by issow** [GoogleCloudPlatform/google-cloud-eclipse#3021]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.6.1.201804031530
- Google Cloud SDK version: 197.0.0
- Eclipse version: 4.7.2.v20171130-0510
- OS: Windows 10 10.0
- Java version: 1.8.0_162

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

Screenshots and stacktraces are helpful.

**Comment by chanseokoh** [comment]
Could you provide more details? What were you doing specifically? Is it reproducibe?

Also, check _Windows_ > _Views_ > _Error Log_ and _Windows_ > _Views_ > _Consoles_ to see if there is any relevant information. For the console view, there might be multiple consoles accumulated, so circle through all consoles, if any.
