### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by kerwinkfs** [GoogleCloudPlatform/google-cloud-eclipse#3031]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.6.1.201804031530
- Google Cloud SDK version: 198.0.0
- Eclipse version: 4.7.3.v20180330-0640
- OS: Mac OS X 10.13.4
- Java version: 1.8.0_162

**What did you do?**
Try to deploy a war file to the app engine

**What did you expect to see?**
running/deployed application
**What did you see instead?**
Error - java.lang.IllegalStateException: No Available Context at com.google.cloud.runtimes.jetty9.DeploymentCheck.lifeCycleStarted(DeploymentCheck.java:46) at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarted(AbstractLifeCycle.java:179) at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1584) at org.eclipse.jetty.xml.XmlConfiguration$1.run(XmlConfiguration.java:1508) at java.security.AccessController.doPrivileged(Native Method) at org.eclipse.jetty.xml.XmlConfiguration.main(XmlConfiguration.java:1507)
Screenshots and stacktraces are helpful.
/ ---> o.e.j.w.WebAppContext@1e127982{/,[file:///var/lib/jetty/webapps/root/, jar:file:///var/lib/jetty/webapps/root/WEB-INF/lib/bootstrap-3.1.1.jar!/META-INF/resources, jar:file:///var/lib/jetty/webapps/root/WEB-INF/lib/jquery-1.9.0.jar!/META-INF/resources],UNAVAILABLE}{/root.war} [failed]

**Comment by briandealwis** [comment]
@kerwinkfs could you please provide a bit more detail about this project, and the steps that you performed?  Where is this war file from?

**Comment by elharo** [comment]
At first read, this sounds like a server side error. Some questions:

1. Where/when exactly did you see this stack trace? On deployment in the Eclipse console? After deployment in the browser?
2. Is it reproducible?
3. If it is reproducible, do you get the same error if you try deploying from the command line with gcloud?

It sounds like a real issue, but I suspect the problem is not in CT4E and we'll need to transfer it to another team.
