### ISSUE TITLE
Following official install doc can't ever install Docker Editor and YEdit

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3033]
https://cloud.google.com/eclipse/docs/quickstart

The drag-and-drop method doesn't list Docker Editor or YEdit.

![selection_007](https://user-images.githubusercontent.com/10523105/39210949-393f53de-47d8-11e8-8d7b-9998b5101edd.png)

Also, installing through the Marketplace doesn't prompt installing Docker or YEdit. Considering that it will be extremely rare to install CT4E from the direct install URL (we don't mention it anywhere), almost all users could not have installed the extra plugins.

**Comment by briandealwis** [comment]
We need to list those feature IDs on the marketplace entry.  I'll take this.

**Comment by briandealwis** [comment]
Fixed.  Made Dockerfile Editor and YEdit be optional but selected by default.  Also updated _Google Inc._ &rarr; _Google LLC_.

<img width="595" alt="screen shot 2018-04-24 at 4 25 28 pm" src="https://user-images.githubusercontent.com/202851/39212284-44a74bce-47dc-11e8-9fbb-5ef0dfbab530.PNG">
