### ISSUE TITLE
Replace String constant with value provided by app-tools-lib in AppEngineSdkClasspathContainer

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#305]
`com.google.cloud.tools.eclipse.appengine.facets.AppEngineSdkClasspathContainer` uses a String constant to store the path to App Engine SDK jar files. Once [app-tools-lib](https://github.com/GoogleCloudPlatform/app-tools-lib-for-java) provides this value by fixing [Expose Jar directory](https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/issues/134) issue, it should be retrieved from there.

**Comment by elharo** [comment]
class no longer exists
