### ISSUE TITLE
CT4E and conversion to Maven project

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#3069]
- Cloud Tools for Eclipse version: 1.6.1.201804031530
- Google Cloud SDK version: 201.0.0
- Eclipse version: 4.6.3.v20170301-0400
- OS: Windows 10 10.0
- Java version: 1.8.0_121

I have not been using Maven yet, but have installed M2E in Eclipse.

Is it safe to convert my Google App Engine Std project (in Eclipse using CT4E) by right clicking on Project > Configure > Convert to Maven Project? Are there any issues with Google libraries I should be aware of, or is this conversion "clean"?

**Comment by elharo** [comment]
Interesting question. The maven plugin and that menu item are outside our control and scope. I suggest making a backup, trying it, and see if it works. I'm guessing that you'll need to add some extra stuff to the pom.xml that process generates. It may not create a ready-to-run App Engine project, but it shouldn't bork anything irreparably.

**Comment by elharo** [comment]
I tried that out. It looks like that menu item simply adds a very basic pom.xml to the project that doesn't even collect the relevant dependencies. It also adds the Maven Builder to the project. So after you use this, you'll have a lot of errors in your project. You'll need to fix up the pom manually. It would almost be easier to write your own pom.xml. 

It won't, however, remove, move, or change any files you already have.

**Comment by elharo** [comment]
FYI, I filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=535491 against m2e.
