### ISSUE TITLE
Objectify 6.0

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3073]
Objectify 6.0 is out. Should we recommend this version to users in our wizards? Does it work on App Engine?

https://github.com/objectify/objectify/wiki/UpgradeVersion5ToVersion6

The release notes seem to reference Cloud SDK. I'm unclear why this matters to Objectify.

Objectify v6 does work with Flexible, and we seem to be picking up 6.0 automatically anyway. If we do want version 5, we have to pin the version.

**Comment by chanseokoh** [comment]
As of now, we are adding v6. Looks like we try to get the latest all the time.

**Comment by elharo** [comment]
Also, it's likely Objectify 6.0 no longer depends on the App Engine API SDK.
