### ISSUE TITLE
App Engine content block circling indefintely

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3077]
![selection_001](https://user-images.githubusercontent.com/10523105/40376009-3be51a8a-5dbb-11e8-967b-6a7b81fae991.png)

I have an empty `datastore-indexes.xml`.

```xml
<?xml version="1.0" encoding="utf-8"?>
<datastore-indexes autoGenerate="true">
</datastore-indexes>
```

**Comment by briandealwis** [comment]
Um, that's not helpful.

**Comment by briandealwis** [comment]
Doh! It was a last-minute change to `AppEngineContentProvider#getProject()` that brought this on:
```
        IResource resource = ((IAdaptable) inputElement).getAdapter(IResource.class);
        if (resource != null) {
          return ProjectFacetsManager.create(resource.getProject());
        }
```
as `AppEngineResourceElement#getAdapter()` checks if the element's configuration file is an instance of the provided class — and an `IFile` is an instance of `IResource` — and so this `AppEngineResourceElement` can be adapted to a project. And so the App Engine Content Block is applied.

My `MockWorkspace` makes this hard to test as it tries to workaround creating an `IFacetedProject` via `ProjectFacetsManager.create(IProject)`.  I'll see if I can make this work quickly or else revert to using `TestProjectCreator` and accept the slowdown of creating and working against real projects.

**Comment by chanseokoh** [comment]
Something that I don't understand with `AppEngineContentProvider.isStandard()`.

```java
  /** Return {@code true} if the project is an App Engine Standard project. */
  static boolean isStandard(IProject project) {
    Preconditions.checkNotNull(project);
    IFacetedProject facetedProject = AppEngineContentProvider.getProject(project);
    return facetedProject != null && AppEngineStandardFacet.hasFacet(facetedProject);
  }
```

The method gets `IProject`. The only callers of this method are `AppEngineLabelProvider.getImage()` and `getStyledText()`. Both callers pass a valid `IProject` object to `isStandard()`. Then, can't we just do `ProjectFacetsManager.create(project)` instead of calling `AppEngineContentProvider.getProject()`?
