### ISSUE TITLE
Images disappear when Project folder is moved to another directory (or computer)

### ISSUE THREAD

**Issue by franciscoreis** [GoogleCloudPlatform/google-cloud-eclipse#3079]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.6.1.201804031530
- Google Cloud SDK version: 199.0.0
- Eclipse version: 4.7.3.v20180330-0640
- OS: Windows 10 10.0
- Java version: 1.8.0_171

**What did you do?**
Moved Project Folder to another directory

**What did you expect to see?**
The images that were stored show up

**What did you see instead?**
The <img> place holder but with no valid image downloaded
The solution is to erase all the local database and start again which is a 
problem when you change often the computer where you use for work.

Screenshots and stacktraces are helpful.
![images error](https://user-images.githubusercontent.com/470000/40381421-885652ca-5df3-11e8-8f39-97236c2ff93f.jpg)

**Comment by elharo** [comment]
Can you elaborate? I'm not sure which images you're referring to. Is this a Cloud Tools for Eclipse issue?

**Comment by franciscoreis** [comment]
This issue is in Google Cloud Tools but was also present in the previous Google Plugin.
When we use something like«
ImagesServiceFactory.getImagesService()..getServingUrl(ServingUrlOptions.Builder.withBlobKey(ba.imageKey).secureUrl(true))

The resulting URL is invalid if the Eclipse Project is moved to another directory.
Local datastore continues to work normally but images are no longer fetched by the URL.

**Comment by elharo** [comment]
There may be a real issue here, but it doesn't sound like Eclipse or its plugins is at the root of this. I suspect similar things would happen in a Maven build.

**Comment by franciscoreis** [comment]
Sorry, but it doesn't look as having nothing to do with Eclipse or the Maven Build:
Change Project Directory, local Datastore continues to work, ImagesServiceFactory.getImagesService().getServingUrl is no longer working.
Both are implemented by the Cloud Tools, aren't they? They both replace the respective cloud services.
Thanks, for you attention! If it is too hard to fix, I just continue deleting the database.
By the way, what is the new most direct way inside Eclipse to delete the local Datastore as 
{project root}/WEB-INF/appengine-generated/local_db.bin  no longer exists?

**Comment by briandealwis** [comment]
> By the way, what is the new most direct way inside Eclipse to delete the local Datastore as
{project root}/WEB-INF/appengine-generated/local_db.bin no longer exists?

From the _Servers_ view, right-click on the server instance and choose _"Clean…"_

**Comment by briandealwis** [comment]
@franciscoreis could you please describe how you are move the project to a different directory?  What steps do you do within Eclipse, and why are you doing this?

**Comment by elharo** [comment]
No, neither datastore nor ImagesServiceFactory.getImagesService().getServingUrl are implemented by Cloud Tools for Eclipse.

**Comment by chanseokoh** [comment]
@franciscoreis so there's what I think is happening:

- As you noticed, we don't store the local Datastore and Blobstore cache under `{project root}/.../WEB-INF/appengine-generated/`, unlike GPE. Therefore, for example, if you zip up your project root and move it to another computer, you will lose all the Datastore and Blobstore data you generated through the local dev server.
- We create a temporary directory outside your project where we stage your app for running the local sever. That is, we don't run the server directly against your project build directory. As such, the local dev server will maintain the Datastore and Blobstore data under this temporary staging directory.
- The exact location of the staging directory is `{your workspace directory}/.metadata/.plugins/org.eclipse.wst.server.core/tmp{some number}/{your project name}/WEB-INF/appengine-generated/`. Note the path contains the name of your project, so this is probably why you lose all the server-generated data when changing your project directory. For example, following is the location and the directory structure of my test project:
   ```
   .../eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/my-test-project

   ├── my_test-project
   │   ├── index.jsp
   ...
   │   └── WEB-INF
   │       ├── appengine-generated
   │       │   ├── local_db.bin
   │       │   └── mq8ku8RCIfDQpvYRs4alcg
   │       ├── appengine-web.xml
   │       ├── classes
   ...
   │       ├── lib
   │       │   ├── appengine-api-1.0-sdk-1.9.63.jar
   ...
   │       └── web.xml
   ```
   As you can see, my test app has an image (i.e., a Blob key `mq8ku8RCIfDQpvYRs4alcg`) and the Datastore storage (`local_db.bin`) under this staging directory.
- You can see the exact staging location from the logs of the dev server when starting it:
`
2018-05-23 13:57:27.246:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=1229ms
2018-05-23 13:57:27.520:INFO:oejsh.ContextHandler:main: Started c.g.a.t.d.j.DevAppEngineWebAppContext@200606de{/,file:///.../eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/my-test-project/,AVAILABLE}{...}
`
- The temporary staging directory is cleared when you delete the corresponding "App Engine Server" instance from the IDE, or you order "Clean..." as @briandealwis said in https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3079#issuecomment-391376215. That said, as long as you don't delete your "Server" instance, you can keep your cache and accumulate data for multiple local runs.

I hope this is probably why you hit this problem.

**Comment by franciscoreis** [comment]
Thanks a lot! Coming recently from the old Eclipse plugin I would have taken a lot of time to discover all those changes. I made a huge investment since 2008 on the PaaS from Google so it's great to see it is being taken care by very competent people. The hiccup of abandoning the old plugin frightened/frustrated me but, indeed, let's move forward!!!
