### ISSUE TITLE
The exception when run app engine in cloud which are not occur when run local

### ISSUE THREAD

**Issue by ducnhuan** [GoogleCloudPlatform/google-cloud-eclipse#3080]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.6.1.201804031530
- Google Cloud SDK version: 201.0.0
- Eclipse version: 4.7.3.v20180330-0640
- OS: Windows 10 10.0
- Java version: 1.8.0_171

**What did you do?**
I using the API for java to connect with Firebase database. These will run on the server. It will make the request to Firebase and return the value.
**What did you expect to see?**
It will run properly in local also in the cloud 
**What did you see instead?**
It run perfectly in local but when deploy to the cloud it have exception about MappableContainerException.
Screenshots 
![2018-05-23](https://user-images.githubusercontent.com/19953750/40382221-11cb506c-5e28-11e8-8d28-147e6a691a71.png)

![2018-05-23 1](https://user-images.githubusercontent.com/19953750/40382392-887c2cf4-5e28-11e8-9e5b-606deb6af559.png)

**Comment by briandealwis** [comment]
I suspect you're using the App Engine standard environment for Java 8, and your project does not have  billing enabled? If so, your project's `appengine-web.xml` to include a `<url-stream-handler>urlfetch</url-stream-handler>`. See [the docs on `<url-stream-handler>`](https://cloud.google.com/appengine/docs/standard/java/config/appref).
