### ISSUE TITLE
Investigate promoting nightly build to official release

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3083]
Now people can directly install our nightly builds (if we make them publicly accessible), regardless of whether they install it on top of any previous release or nightly builds. Nightly builds will also be auto-upgraded seamlessly when a new release rolls out.

It will be very convenient for us if there is a way to directly promote a nightly build to a release without rebuilding anything. I don't see an immediate solution yet. This needs more investigation.

**Comment by chanseokoh** [comment]
One simple way could be to

1. Use the forward-looking version numbering at HEAD. In other words, specify a version anticipated in the next release in our source repo: `pom.xml`, `feature.xml`, and `gcp-repo/metadata.product`. Currently our version in these files are backward-looking (i.e., the version of the last release).
1. Do not give any extra suffix to versions when building nightly builds. Currently, we add `-post-release-nightly`. Then, all builds, whether built manually or nightly, will just have the same timestamp version format.

The biggest downside is that, it will be very inconvenient to check if the build in our GCS bucket is regular or nightly or if the version populated in the user reported issue is regular or nightly.

**Comment by briandealwis** [comment]
We could use the SHA prefix instead of the `-post-release-nightly` since the rest of the timestamp is the build timestamp and so it should sort ok.

**Comment by briandealwis** [comment]
`git rev-parse —short HEAD`

**Comment by chanseokoh** [comment]
That's a very nice idea for the source repo tagging problem. (I guess you meant SHA suffix rather than prefix?). Seems very promising.

**Comment by briandealwis** [comment]
The git convention abbreviates to a 7 character prefix of the SHA1.  Though they could have used the suffix too.

**Comment by chanseokoh** [comment]
Ah, sorry, I misunderstood. Never mind.

**Comment by diegomarquezp** [comment]
Closing as not planned.
