### ISSUE TITLE
Unsigned JARs from Docker Editor and YEdit

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3088]
When selecting to install them together, I got the security warning. I don't particularly remember this before, so it's a bit weird. Installing without them is OK.

![security warning _001](https://user-images.githubusercontent.com/10523105/40492159-e10efd2c-5f3d-11e8-8260-f544d8861245.gif)

**Comment by briandealwis** [comment]
This is from the marketplace entry?

**Comment by chanseokoh** [comment]
No, I was trying our release candidate from the direct install URL.

**Comment by chanseokoh** [comment]
Interesting... I tried installing all of them on a fresh Neon as a second attempt, and I didn't hit the issue.

**Comment by chanseokoh** [comment]
Now I think the unsigned JARs were my cached remnants that came in when I was testing the new release pipeline.
