### ISSUE TITLE
App Engine Content Block refresh

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3090]
1. Create a project with the wizard.
2. Add a cron.xml to the project in WEB-INF/lib
3. Observe no scheduled tasks in the content block.
4. Refresh
5. Scheduled Tasks shows up.
6. Delete cron.xml
7. Scheduled Tasks is still present.
8. Double click scheduled tasks:
9. The marketplace opens?!

![image](https://user-images.githubusercontent.com/1005544/40502184-2ee178d0-5f58-11e8-98cc-31f45c3ee430.png)

**Comment by briandealwis** [comment]
That implies you don't have the WTP XML support installed.  Did you install into a _Eclipse for Java Developers_ or _Eclipse for JavaEE Developers_, or something else entirely?

**Comment by briandealwis** [comment]
Hmm, never mind: you have an XML file open in the background.

**Comment by briandealwis** [comment]
Oh!  I missed that you had deleted the `cron.xml` in (6).  Interesting. On Windows I get an error instead:

![screen shot 2018-05-24 at 2 53 02 pm](https://user-images.githubusercontent.com/202851/40505453-2fb2a2d4-5f62-11e8-829f-5f7a81b7ac06.PNG)

What's also interesting is that creating the file from the App Engine content block (right click > New > File…) does refresh the content block immediately.
