### ISSUE TITLE
Content Block Descriptors should recognize YAML

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3091]
E.g. cron.yaml as well as cron.xml; etc.

**Comment by chanseokoh** [comment]
If the AppCfg staging can handle the YAML files too, it makes sense to support them. (The content block is enabled only for App Engine Standard.)

**Comment by elharo** [comment]
cloud.google.com docs claim we support YAML files:

"If you are using Cloud SDK-based tooling, such as the gcloud command line, or Cloud SDK-based Maven, Gradle, Eclipse, or IntelliJ plugins, refer to the Cron reference in YAML format."

https://cloud.google.com/appengine/docs/standard/java/config/cronref

If this isn't true, that's a serious docs bug we need to fix ASAP.

**Comment by briandealwis** [comment]
Whereas https://cloud.google.com/appengine/docs/standard/java/configuration-files has a call-out that says:
> * Note: Although your application source code uses XML configuration files, the files are converted to YAML during the deployment to App Engine.

**Comment by patflynn** [comment]
That looks like a docs bug to me.  For standard users we still recommend
xml based configs.

**Comment by briandealwis** [comment]
That said, this is easy to support — since we don't offer any real functionality for these files yet — and future proofs us.

**Comment by chanseokoh** [comment]
I see support in the content block is technically easy. But for App Engine Standard, YAML files aren't really working now:

- We deploy the auto-generated YAML files under `WEB-INF/appengine-generated/`, e.g., `app.yaml`, `index.yaml`, `dos.yaml`, etc. Files under the source repo `src/main/webapp/WEB-INF/*.yaml` won't probably be picked up.
- The dev appserver always uses `datastore-indexes.xml`. Having `index.yaml` as a source of truth won't work nicely with merging the indexes auto-generated by the dev server.

**Comment by briandealwis** [comment]
Good points.  We'd need to modify `AppEngineProjectDeployer` to look for the config files in both the staging directory as well as the `appengine-generated`.  The `datastore-indexes-auto.xml` is a tough one.

**Comment by briandealwis** [comment]
Add some validation rules to error/warn when there are both an .xml and .yaml file found.

**Comment by patflynn** [comment]
Could someone file an issue with the App Engine docs team to make it clear
that App Engine Standard Java users should stick to xml config files?
