### ISSUE TITLE
Cannot deploy Java 7 + Objectify 6.0 App Engine standard project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3111]
Select Java 7 and check Objectify when creating a standard project.

Beginning interaction for module default...
0% Warning: Google App Engine Java 7 runtime is deprecated.
0% Warning: See https://cloud.google.com/appengine/docs/deprecations/java7
Unable to stage app: Class file is Java 8 but max supported is Java 7: com/googlecode/objectify/annotation/AlsoLoad.class in /usr/local/google/home/chanseok/tmp/tmp-eclipse-workspace/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1527610188675/staging-work/exploded-war/WEB-INF/lib/objectify-6.0.jar
Please see the logs [/tmp/appcfg816241382410754489.log] for further information.

~~Interestingly, this doesn't happen with Maven projects.~~

**Comment by chanseokoh** [comment]
> Interestingly, this doesn't happen with Maven projects.

Wrong. I just forgot to select Java 7. Happens with Maven too.

**Comment by elharo** [comment]
To be clear, this only happens on deploy, not on project creation?

**Comment by chanseokoh** [comment]
On deploy, not on project creation.

**Comment by patflynn** [comment]
Doesn't Objectify 6 use the google-cloud-java datastore API?

Should we be using it at all for App Engine standard apps?  I thought that
would not work with the current java devappserver.

There could also be performance implications of users switching to this.
