### ISSUE TITLE
Do not ask for merging auto-generated datastore-indexes.xml if it is empty

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3118]
```xml
<!-- Indices written at Wed, 30 May 2018 13:33:43 EDT -->

<datastore-indexes/>
```

We should suppress the pop-up when no index was actually generated like the above.

**Comment by elharo** [comment]
This should be an easy fix. In `DatastoreIndexUpdateData` we just need to add a check for some contents here: 

``
    if(!datastoreIndexesAutoXml.toFile().exists()) {
      return null;
    }
```
