### ISSUE TITLE
SDK Problem

### ISSUE THREAD

**Issue by aman30mishra** [GoogleCloudPlatform/google-cloud-eclipse#3131]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.7.0.201805302000
- Google Cloud SDK version: 203.0.0 (auto-managed)
- Eclipse version: 4.7.3.v20180301-0715
- OS: Windows 10 10.0
- Java version: 1.8.0_171

**What did you do?**

**What did you expect to see?**

**What did you see instead?**
Failed to install the Google Cloud SDK.
Process failed with exit code: 1

ERROR: (gcloud.components.update) Your current working directory is inside the Cloud SDK install root: C:\Users\aman mishra\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk.  In order to perform this update, run the command from outside of this directory.

This will install all the core command line tools necessary for working with
the Google Cloud Platform.

Screenshots and stacktraces are helpful.

**Comment by briandealwis** [comment]
Could you please describe what you were attempting to do?  Some screenshots would be very helpful!

**Comment by chanseokoh** [comment]
It is the limitation of glcoud that it can't update itself when the gcloud binary is called inside the gcloud directory. Now the question is, why the working directory was set to `C:\Users\aman mishra\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk`.

@aman30mishra did you have an open command terminal at `C:\Users\aman mishra\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk` or started Eclipse from there by any chance?

**Comment by elharo** [comment]
Is there an open bug in the Cloud SDK about this?

In the meantime, would it be possible for us to early detect this condition in appengine-plugins-core before we attempt an update?

**Comment by chanseokoh** [comment]
I don't get how @aman30mishra got into this situation, but there is an easy and permanent solution: give a root directory as a working directory when launching the gcloud process.

**Comment by rvidalo** [comment]
I have exactly same problem than aman30mishra. 
I downloaded the last version of eclipse Oxygen, I've Java 1.8(u172) in Windows 7 PRO x64. Eclipse is in C:\eclipse and workspace is in C:\eclipse\workspace 
After that I downloaded google cloud from marketplace of Ecliplse, and after that Eclipse restarted trying to install the new plugin. Then I found the next in Eclipse console:

```
[Installing Google Cloud SDK]
Welcome to the Google Cloud SDK!

Your current Cloud SDK version is: 205.0.0
Installing components from version: 204.0.0

ERROR: (gcloud.components.update) Your current working directory is inside the Cloud SDK install root: C:\Users\Ricardo\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk.  In order to perform this update, run the command from outside of this directory.

This will install all the core command line tools necessary for working with
the Google Cloud Platform.
```

Any solution?

**Comment by elharo** [comment]
You should be able to manually install the Cloud SDK 204.0.0 and set Eclipse to point to it in the preferences.
See https://cloud.google.com/eclipse/docs/manage-sdk#self-managed_sdk

**Comment by chanseokoh** [comment]
Fixed after #3165. This won't happen in the future releases.

**Comment by srinurp** [comment]
Same issue while trying to update gcloud from eclipse plugin

[Installing Google Cloud SDK]
Welcome to the Google Cloud SDK!


Your current Cloud SDK version is: 207.0.0
Installing components from version: 207.0.0

ERROR: (gcloud.components.update) Your current working directory is inside the Cloud SDK install root: C:\Users\sriu\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk.  In order to perform this update, run the command from outside of this directory.

This will install all the core command line tools necessary for working with
the Google Cloud Platform.

**Comment by chanseokoh** [comment]
Will be fixed in the next release. See the comments above for possible workarounds.

**Comment by ummarbhutta** [comment]
Facing same issue

**Output from eclipse (oxygen) console**

```
[Installing Google Cloud SDK]
Welcome to the Google Cloud SDK!


Your current Cloud SDK version is: 207.0.0
Installing components from version: 207.0.0

ERROR: (gcloud.components.update) Your current working directory is inside the Cloud SDK install root: C:\Users\m.iqbal\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk.  In order to perform this update, run the command from outside of this directory.

This will install all the core command line tools necessary for working with
the Google Cloud Platform.

[Installing Google Cloud SDK]
```

Is there any easy way to get it fixed?

**Comment by chanseokoh** [comment]
@chintansureliya we plan to release next week. Sorry for the wait.

@ummarbhutta you should be able to manually install the Cloud SDK and set Eclipse to point to it in the preferences. Please see https://cloud.google.com/eclipse/docs/manage-sdk#self-managed_sdk

**Comment by chanseokoh** [comment]
@aman30mishra @rvidalo @chintansureliya @ummarbhutta @srinurp CT4E 1.7.1 released today, fixing this working directory issue when installing the Cloud SDK.  If you installed the SDK manually to work around this, you can now switch back to the auto-managed Cloud SDK and delete the SDK you installed manually. (Of course, you can leave and continue to use your own SDK if you want.)

**Comment by chintansureliya** [comment]
@chanseokoh Thanks, Have updated the SDK to CT4E 1.7.1 and the issue has been fixed.
Keep up the good work! :)

**Comment by chanseokoh** [comment]
Hi @behzad4190 I think you are talking about the Android SDK on the Android Studio (which is based on IntelliJ). This repo is about the CT4E Eclipse plugin, and the SDK we are talking about in this issue is the Google Cloud SDK, not the Android SDK.

**Comment by ummarbhutta** [comment]
Thanks @chanseokoh , Its working with latest upgrade.

**Comment by mirsirk** [comment]
I am facing the same issue in version 307. I faced this issue when i tried to execute the 'gcloud components update' command.

Your current Cloud SDK version is: 307.0.0
You will be upgraded to version: 308.0.0

ERROR: (gcloud.components.update) Your current working directory is inside the Cloud SDK install root: D:\Softwares\google-cloud-sdk-307.0.0-windows-x86_64-bundled-python\google-cloud-sdk.  In order to perform this update, run the command from outside of this directory.
Press any key to continue . . .

Can anyone help and suggest a solution to resolve it.

**Comment by chanseokoh** [comment]
@mirsirk you are probably running `gcloud components update` inside the `D:\Softwares\google-cloud-sdk-307.0.0-windows-x86_64-bundled-python\google-cloud-sdk` directory (or any sub-directory)? Perhaps you can do
```
> cd \
> Softwares\google-cloud-sdk-307.0.0-windows-x86_64-bundled-python\google-cloud-sdk\bin\gcloud components update
```
