### ISSUE TITLE
Cloud SQL issue on local dev app server

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3136]
From a [SO question](https://stackoverflow.com/questions/50705839/cloudsql-eclipse-java-standard-gae-java-lang-unsatisfiedlinkerror).

I can reproduce this locally, although the error message is not exactly same. The code works with `mvn appengine:run` but not on our local server. I've done some preliminary investigation and will be able to update details soon.

**Comment by chanseokoh** [comment]
The specific cause of this issue is the difference of the environment variable `GAE_RUNTIME` on `mvn appengine:run` and our local server. On our local server, the following code prints `java8`, whereas `mvn appengine:run` prints `null`.

```java
public class HelloAppEngine extends HttpServlet {

  @Override
  public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException {
      
    response.setContentType("text/plain");
    response.setCharacterEncoding("UTF-8");

    response.getWriter().print("GAE RUNTIME: " + System.getenv("GAE_RUNTIME"));

  }
}
```

It's not yet clear who sets `GAE_RUNTIME` for our server. Eventually, we end up calling the following command to run the dev appserver against the app in a temporary staging area. Surprisingly, executing the command directly on the command line (which does exactly the same thing when done inside IDE) does not set `GAE_RUNTIME`.
```
.../jdk1.8.0_161/bin/java \
    -Dappengine.fullscan.seconds=1 \
    -Duse_jetty9_runtime=true \
    -D--enable_all_permissions=true \
    -Dappengine.sdk.root=.../google-cloud-sdk/platform/google_appengine/google/appengine/tools/java \
    -cp .../google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar \
    com.google.appengine.tools.development.DevAppServerMain \
        --address=localhost --port=8080 \
        --allow_remote_shutdown --disable_update_check \
        --no_java_agent \
    .../.metadata/.plugins/org.eclipse.wst.server.core/tmp0/test-project
```

**Comment by chanseokoh** [comment]
FTR, below is the code of `com.google.cloud.sql.mysql.SocketFactory.connect()` that depends on `GAE_RUNTIME`. The class is in `mysql-socket-factory-1.0.8.jar`

```java
  public Socket connect(String hostname, int portNumber, Properties props) throws IOException {
    ...
    // This env will be set by GAE OR set manually if using Cloud SQL Proxy
    String runtime = System.getenv("GAE_RUNTIME");

    if (runtime == null || runtime.isEmpty()) {  // Use standard SSL (direct connection)
      this.socket = SslSocketFactory.getInstance().create(instanceName);
    } else { // Use Unix Socket
      logger.info("Using GAE Unix Sockets");
      UnixSocketAddress socketAddress = new UnixSocketAddress(...);
      this.socket = UnixSocketChannel.open(socketAddress).socket();
    }
    return this.socket;
  }
```
As obvious from the code, when `GAE_RUNTIME` is set, it will log `Using GAE Unix Sockets`.

```
Jun 05, 2018 6:44:46 PM com.google.cloud.sql.mysql.SocketFactory connect
INFO: Connecting to Cloud SQL instance [...].
Jun 05, 2018 6:44:46 PM com.google.cloud.sql.mysql.SocketFactory connect
INFO: Using GAE Unix Sockets
```

Otherwise, logs will show `SslSocketFactory` being used.
```
Jun 05, 2018 5:50:07 PM com.google.cloud.sql.mysql.SocketFactory connect
INFO: Connecting to Cloud SQL instance [...].
Jun 05, 2018 5:50:07 PM com.google.cloud.sql.core.SslSocketFactory getInstance
INFO: First Cloud SQL connection, generating RSA key pair.
Jun 05, 2018 5:50:08 PM com.google.cloud.sql.core.SslSocketFactory fetchInstanceSslInfo
```

**Comment by chanseokoh** [comment]
It's `appengine-plugins-core` that puts `GAE_RUNTIME`. The code was committed 9 months ago: https://github.com/GoogleCloudPlatform/appengine-plugins-core/pull/452/files#diff-99f2a89bc597c0a1009b63d4b06c2414R264

It may be that we (and the user) are using a very old version of `app-maven-plugin`, or we've not released any new version for a very long time?

Anyways, it's still not clear to me if `com.google.cloud.sql.mysql.SocketFactory.connect()` is not designed to work locally if `GAE_RUNTIME` is set.

**Comment by chanseokoh** [comment]
> It may be that we (and the user) are using a very old version of com.google.cloud.tools:appengine-maven-plugin

Indeed. The version we put for projects created from our project wizard is 1.3.1, which is released in May 2017. Upgrading it to the latest 1.3.2 (released in Nov 2017) will put `GAE_RUNTIME`, which will make `mvn appengine:run` stop working as it does not work currently in Eclipse.

So, the issue is not specific to CT4E. I just wonder what the correct way to connect to Google MySQL from the local dev server using JDBC.

**Comment by elharo** [comment]
So normally I'd say we need to upgrade to 1.3.2, but that might just go from bad to worse. OTOH at least it would be consistently broken everywhere.

**Comment by chanseokoh** [comment]
I think I am getting close to this. If `GAE_RUNTIME` is defined, the library assumes it is running on prod GAE and therefore there exists a Unix socket file `/cloudsql/gcp-project-id:region:mysql-instance-id`. So on prod, instead of using the standard socket to make a direct network connection to the MySQL server, the library decides to "open" this Unix socket file (i.e., using the [Unix Domain Socket](https://en.wikipedia.org/wiki/Unix_domain_socket), which is IPC on the same host OS according to Wikipedia).

> A Unix domain socket or IPC socket (inter-process communication socket) is a data communications endpoint for exchanging data between processes executing on the same host operating system.

Of course, when running locally, the user won't have this socket file at all, so the connection will inevitable fail. (On Linux, I just get "java.io.IOException: No such file or directory".)

However, there exists a SQL proxy for local development, which can create the socket file under `/cloudsql/`. The doc also mentions `dev_appserver.py`, so this might be the way in this case:

https://cloud.google.com/appengine/docs/standard/php/cloud-sql/using-cloud-sql-mysql#testing-dev-env

**Comment by chanseokoh** [comment]
But the Unix socket is completely out of reach on Windows.

It feels like `com.google.cloud.sql:mysql-socket-factory` is designed intrinsically with the assumption that `GAE_RUNTIME` is not set locally, especially on Windows. I'll file an issue on the library to fall back to use the standard socket if it is on Windows or the socket file could not be found.

**Comment by chanseokoh** [comment]
Filed https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/77.

**Comment by chanseokoh** [comment]
Unfortunately, they could not suggest an immediate workaround. They are working on a fix. Closing.

**Comment by ishanrakitha** [comment]
Spring boot 2 app stuck in GKE with the following.

```
Connecting to Cloud SQL instance [<INSTANCE CONNECTION NAME>] via SSL socket.
First Cloud SQL connection, generating RSA key pair.
```

**Comment by dshetty312** [comment]
I am facing the same problem with Spring boot app.

Connecting to Cloud SQL instance [<INSTANCE CONNECTION NAME>] via SSL socket.
First Cloud SQL connection, generating RSA key pair.

**Comment by ishanrakitha** [comment]
> I am facing the same problem with Spring boot app.
> 
> Connecting to Cloud SQL instance [] via SSL socket.
> First Cloud SQL connection, generating RSA key pair.

I was able to resolve this by using cloud sql proxy approach. 

https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine

**Comment by dshetty312** [comment]
> > I am facing the same problem with Spring boot app.
> > Connecting to Cloud SQL instance [] via SSL socket.
> > First Cloud SQL connection, generating RSA key pair.
> 
> I was able to resolve this by using cloud sql proxy approach.
> 
> https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine

**Comment by dshetty312** [comment]
Thanks ishan.

The issue was do with the version of guava library (18) that was causing the Spring boot app to hang on cloudsql instance creation via ssl.

After updating the version of guava to latest in the Pom ,it worked for me.
