### ISSUE TITLE
'"python.exe"' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by AIMMOTH** [GoogleCloudPlatform/google-cloud-eclipse#3137]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_.

2. If the problem occurs when you deploy or after the application has been deployed,
try deploying from the command line using `gcloud` or Maven. 
If the problem does not go away, then the issue is very likely
not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version:
1.7.0.201805302000

- Google Cloud SDK version: _(run `gcloud version`)_
Google Cloud SDK 204.0.0
app-engine-java 1.9.64
app-engine-python 1.9.70
bq 2.0.34
core 2018.06.04
gsutil 4.31

- Eclipse version: _(e.g, 4.5.2.v20160212-1500 or Neon.3)_
Eclipse Java EE IDE for Web Developers.

Version: Neon.3 Release (4.6.3)
Build id: 20170314-1500

- OS:
Windows 10 home

- Java version:
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

**What did you do?**

Use Eclipse to deploy my app to Standard App Engine Java 

**What did you expect to see?**

A deploy

**What did you see instead?**

Temporary staging for module default directory left in C:\dev\workspace\carls-2018-1\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1528267388615\staging
'"python.exe"' is not recognized as an internal or external command,
operable program or batch file.

Screenshots and stack traces are helpful.

Message: Process exited with error code 1
Stacktrace: An exception stack trace is not available. 
Session Data:
eclipse.buildId=4.6.3.M20170301-0400
java.version=1.8.0_171
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=sv_SE
Framework arguments:  -Dcom.ibm.icu.util.TimeZone.DefaultTimeZoneType=ICU -product org.eclipse.epp.package.jee.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -Dcom.ibm.icu.util.TimeZone.DefaultTimeZoneType=ICU -product org.eclipse.epp.package.jee.product

Console output:
jun 06, 2018 8:43:13 FM java.util.prefs.WindowsPreferences <init>
VARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Reading application configuration data...

Beginning interaction for module default...
0% Scanning for jsp files.
2018-06-06 08:43:17.301:INFO::main: Logging initialized @123ms
2018-06-06 08:43:17.414:INFO:oejs.Server:main: jetty-9.3.18.v20170406
2018-06-06 08:43:19.923:INFO:oeja.AnnotationConfiguration:main: Scanning elapsed time=2110ms
2018-06-06 08:43:19.937:INFO:oejq.QuickStartDescriptorGenerator:main: Quickstart generating
2018-06-06 08:43:19.955:INFO:oejsh.ContextHandler:main: Started o.e.j.q.QuickStartWebApp@61dc03ce{/,file:///C:/dev/workspace/ca...8-1/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1528267388615/staging/,AVAILABLE}
2018-06-06 08:43:19.956:INFO:oejs.Server:main: Started @2779ms
2018-06-06 08:43:19.959:INFO:oejsh.ContextHandler:main: Stopped o.e.j.q.QuickStartWebApp@61dc03ce{/,file:///C:/dev/workspace/ca...8-1/.metadata/.plugins/com.google.cloud.tools.eclipse.appengine.deploy/tmp/1528267388615/staging/,UNAVAILABLE}
jun 06, 2018 8:43:20 FM com.google.appengine.tools.admin.Application createStagingDirectory
Success.
INFO: We detected that you have a large number of .class files in WEB-INF/classes. You may be able to reduce request latency by packaging your .class files into jars. To do this, supply <enable-jar-classes>true</enable-jar-classes> in the <staging> tag in appengine-web.xml or one of the following methods: You can supply the --enable_jar_classes flag when using appcfg on command line. If you're using the Cloud SDK based app-maven-plugin, add <stage.enableJarClasses>true</stage.enableJarClasses> in the plugin's <configuration> tag. If you are using the AppCfg based appengine-maven-plugin, supply <enableJarClasses>true</enableJarClasses> in the plugin's <configuration> tag. Note that this flag will put the jar in WEB-INF/lib rather than WEB-INF/classes. The classloader first looks in WEB-INF/classes and then WEB-INF/lib when loading a class. As a result, this flag could change classloading order, which may affect the behavior of your app.
Temporary staging for module default directory left in C:\dev\workspace\carls-2018-1\.metadata\.plugins\com.google.cloud.tools.eclipse.appengine.deploy\tmp\1528267388615\staging
'"python.exe"' is not recognized as an internal or external command,
operable program or batch file.

**Comment by chanseokoh** [comment]
Looks like CT4E is configured to use your own Cloud SDK. I expect that _Choose SDK_ is checked when you go to _Window_ > _Preferences_ > _Google Cloud Tools_.

![selection_012](https://user-images.githubusercontent.com/10523105/41047220-0d49ecbc-697a-11e8-84f7-11f4349fef5b.png)

One simple fix would be to uncheck _Choose SDK_ as in the screenshot above so that CT4E downloads and manages its own, separate Cloud SDK.

Another alternative is to install Python 2 yourself on your machine, configure `%PATH%` so that you can execute `python.exe` from any directory, and restart Eclipse.

**Comment by briandealwis** [comment]
I believe @AIMMOTH has Python installed. @AIMMOTH submitted this issue via Github directly, since there's no `(auto-managed)`/`(non-managed)` tags on the Cloud SDK versions, and was able to run `gcloud version` which does execute Python.  But it's possible that his Python isn't on the `PATH` for the Eclipse process?

With using devappserver1, we don't actually have many places where we call out to `gcloud` except for deployment.

**Comment by chanseokoh** [comment]
Just emphasizing again that unchecking _Choose SDK_ would be a simple solution without needing to deal with configuring Python yourself.

**Comment by AIMMOTH** [comment]
Re-installing worked. Thank you.
