### ISSUE TITLE
Upgrade com.google.cloud.tools:appengine-maven-plugin to 1.3.2

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3141]
Upgrade com.google.cloud.tools:appengine-maven-plugin to 1.3.2.

At same time consider if we need to check for the latest version of this artifact.

**Comment by chanseokoh** [comment]
Related Cloud SQL issue: https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/issues/77

**Comment by elharo** [comment]
Underlying bug is fixed in  mysql-socket-factory-connector-j-8 1.0.10

**Comment by elharo** [comment]
This appears to be fixed by #3198
