### ISSUE TITLE
Port 8080 is in use.

### ISSUE THREAD

**Issue by aman30mishra** [GoogleCloudPlatform/google-cloud-eclipse#3144]
![2018-06-08](https://user-images.githubusercontent.com/29807754/41134765-b2b0fb4c-6aeb-11e8-8d3c-debd70470b7a.png)
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.7.0.201805302000
- Google Cloud SDK version: 204.0.0 (auto-managed)
- Eclipse version: 4.7.3.v20180301-0715
- OS: Windows 10 10.0
- Java version: 1.8.0_171

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

Screenshots and stacktraces are helpful.

**Comment by elharo** [comment]
You probably ran it more than once, and the existing server is still running.
Open the Eclipse Servers view and click the red square to stop the existing server.
We have a couple of  open bugs to improve this experience.
It's also possible there's another process somewhere on your system that's holding that port.
