### ISSUE TITLE
Full exception stack trace not being reported from tests

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3161]
I deliberately threw an artificial NPE from `BugReportCommandHandler.getCloudSdkVersion()`:

```java
  private static String getCloudSdkVersion() {
    throw new NullPointerException("yes!");
  }
```

But I don't get the full stack trace from doing `mvn verify` locally when running the test `BugReportCommandHandlerTest`.

```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.064 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.bugreport.ui.BugReportCommandHandlerTest
testFormatReportUrl(com.google.cloud.tools.eclipse.bugreport.ui.BugReportCommandHandlerTest)  Time elapsed: 0.063 sec  <<< ERROR!
java.lang.NullPointerException: yes!
        at com.google.cloud.tools.eclipse.bugreport.ui.BugReportCommandHandlerTest.testFormatReportUrl(BugReportCommandHandlerTest.java:36)


Results :

Tests in error:
  BugReportCommandHandlerTest.testFormatReportUrl:36 » NullPointer yes!
```

Something happened to our setup. Don't know how long this has been.

**Comment by briandealwis** [comment]
Must be the change to Tycho 1.2.

**Comment by briandealwis** [comment]
So it seems it's [surefire's `trimStackTrace`](http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#trimStackTrace) setting.  But it has defaulted to `true` since being introduced in surefire 2.2, whereas Tycho 1.2 updated surefire from 2.17 to 2.19.1.

**Comment by briandealwis** [comment]
Hmm, `tycho-surefire` doesn't provide for the `trimStackTrace` value.  I wonder if surefire's stack trimming has become more aggressive.

I think the best thing for now is to revert to Tycho 1.1.

**Comment by briandealwis** [comment]
Surefire only spits out stacktraces when a test fails :-)
