### ISSUE TITLE
Setting up EGit local repo results in error for App Engine project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3173]
This is not possible to test in the hosted dev Eclipse, since EGit is not available on the dev target platform. Maybe it's a good idea to include it.

Steps to reproduce:
1. Install CT4E on some actual Eclipse instance.
1. Create an App Engine standard env project.
1. _Team_ > _Share Project..._
1. _Create..._. A dialog pops up. The default location would work. _Finish_.
1. _Finish_.

The error is

Archive for required library: '.../workspace/my-project/src/main/webapp/WEB-INF/lib/jstl-1.2.jar' in project 'my-project' cannot be read or is not a valid ZIP file

This could be a general problem of EGit when a project contains a library inside it. I tried the same steps on a plain Java project that embeds some JAR, and I got the same error.

**Comment by briandealwis** [comment]
Works for me.  Something's wrong with your zip file.

**Comment by chanseokoh** [comment]
The root cause:

All files in the project move to a new location. In my case, the project was originally under `<my eclipse workspace>/my-project/`, but after sharing the project, the directory moves to `$HOME/git`. Then the "Web App Libraries" container (of WTP) shows the error that `<my eclipse workspace/my-project/src/main/webapp/WEB-INF/lib/jstl-1.2.jar` is missing, which is true as the files were physically moved.

So we are not at fault, but I'd say this is rather the limitation or bug of EGit that breaks library containers.

**Comment by briandealwis** [comment]
That's odd as the _Web App Libraries_ container just reflects the contents of the `WEB-INF/lib` folder.  If those items were properly moved, then all should be well.  Does a _Project &rarr; Clean_ fix things?

**Comment by diegomarquezp** [comment]
Closing as not planned since GAE with Java 8 is not supported. cc: @blakeli0
