### ISSUE TITLE
No section for CT4E and WTP in welcome screens

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3190]
They seem to appear in other sections depending on what else is installed. E.g. Data Tools Platform or Task-focused Programming

![image](https://user-images.githubusercontent.com/1005544/42186109-519115fe-7e19-11e8-9c45-582ac8086ef1.png)

![image](https://user-images.githubusercontent.com/1005544/42186116-5ac934a8-7e19-11e8-979c-e5923c145fb9.png)

**Comment by elharo** [comment]
see https://help.eclipse.org/photon/topic/org.eclipse.platform.doc.isv/guide/ua_intro.htm?cp=2_0_19_0

but I can't find any UI guidelines for this content.

**Comment by elharo** [comment]
Fixing this means adding a label attribute to the group element like so:

```
    <group style-id="content-group" label="Google Cloud Tools for Eclipse">
```

Not clear whether we should do this when we only have a single link in the section.

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
