### ISSUE TITLE
No Migrate section on Welcome Page 

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3191]
Per test plan, "Click on the Home button in the Welcome toolbar and select Migrate. Ensure Migration from the Google Plugin for Eclipse (GPE) is shown. Clicking on the entry should take you to the CT4E Convert Existing Projects webpage."

I see no such Migrate  heading.

**Comment by chanseokoh** [comment]
The migration link may appear differently depending on the size of the view and the flow.

- "Help" > "Welcome" on a small view
![selection_004](https://user-images.githubusercontent.com/10523105/42382645-f9f5c3d4-8102-11e8-962d-79b0e987a6b9.png)

- "Help" > "Welcome" on a large view. There are two links
![selection_005](https://user-images.githubusercontent.com/10523105/42382718-2ba7af3c-8103-11e8-912d-dd053e1377ed.png)

- After clicking on the small "Home" button in the Welcome toolbar (on the top right corner of the view)
![selection_006](https://user-images.githubusercontent.com/10523105/42382750-4170e18a-8103-11e8-9beb-089c56ee2996.png)

**Comment by elharo** [comment]
Here's what I see:

![image](https://user-images.githubusercontent.com/1005544/42383016-02103d3c-8104-11e8-913c-4069dff3a887.png)


No Migrate section.

**Comment by elharo** [comment]
Looks like this section may be optional and is turned off by default:

![image](https://user-images.githubusercontent.com/1005544/42385371-8e75da38-810a-11e8-8987-f50449265584.png)
