### ISSUE TITLE
Cancelling login is not an error

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3194]
I started the login process from Eclipse and hit cancel rather than typing un my credentials when I realized I'd picked the wrong account. I was presented with two errors. However this is not an error. It's a deliberate user choice, and CT4E did exactly what the user asked. We need to distinguish user cancel form authentication failure.

![image](https://user-images.githubusercontent.com/1005544/42218018-444ca0c6-7e95-11e8-9d5c-ad2df368ebe9.png)

![image](https://user-images.githubusercontent.com/1005544/42218025-4af67b5e-7e95-11e8-8430-72951829bde2.png)

**Comment by chanseokoh** [comment]
This is not feasible, unfortunately. The "access_denied" is the error code from the server given back to our callback, and there is no way from our side to distinguish that this is user cancellation.

`LocalServerReceiver` code:
```java
  public String waitForCode() throws IOException {
    ...
    if (error != null) {
      throw new IOException("User authorization failed (" + error + ")");
    }
    ...
  }
```

```java
    @Override
    public void handle(
        String target, HttpServletRequest request, HttpServletResponse response, int dispatch)
        throws IOException {
        ...
        error = request.getParameter("error");
        ...
        if (error == null && successLandingPageUrl != null) {
          response.sendRedirect(successLandingPageUrl);
        } else if (error != null && failureLandingPageUrl != null) {
          response.sendRedirect(failureLandingPageUrl);
        } else {
```

**Comment by chanseokoh** [comment]
But at least we should first verify if there is any other request parameters than "error" that may hold a more detailed error description.

**Comment by diegomarquezp** [comment]
Closing as not planned.
