### ISSUE TITLE
1 Modules

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3195]
See screenshot. This popup should be "1 module" (not plural)

![image](https://user-images.githubusercontent.com/1005544/42218865-ee1908fe-7e97-11e8-8af5-67aaa7fc2101.png)

If so, file the bug there and close this.

**Comment by chanseokoh** [comment]
Also when using Tomcat, so WTP problem. I'll file a bug on Eclipse.

![selection_001](https://user-images.githubusercontent.com/10523105/42236697-997e5c7c-7ec9-11e8-8278-74c760426b3b.png)

**Comment by chanseokoh** [comment]
Filed https://bugs.eclipse.org/bugs/show_bug.cgi?id=536658
