### ISSUE TITLE
/hello not found

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3196]
This one's a blocker:

Java 8 
standard environment
native project
possibly rerun of server only
non-default service

![image](https://user-images.githubusercontent.com/1005544/42219245-48ddb7f2-7e99-11e8-80a8-545494e98fba.png)

**Comment by elharo** [comment]
Having trouble reproducing.

**Comment by chanseokoh** [comment]
This is the symptom that Jetty hasn't registered (maybe yet) `HelloAppEngine` as a Servlet class and its Servlet mapping. For example, if you remove the `@WebServlet` annotation and relaunch the server, you will see the exact same error message.

```java
@WebServlet(
    name = "HelloAppEngine",
    urlPatterns = {"/hello"}
)
public class HelloAppEngine extends HttpServlet {
```

Likewise, another way to reproduce is to uncheck _Build Automatically_, clean the the project while unchecking _Start a build immediately_, and launch the server.

That said, I think the likely cause is that the `HelloAppEngine.class` file has not been published to the server somehow. Heisenbug observed in #2149?

**Comment by chanseokoh** [comment]
> I hit this today!

Sorry, I'll take this back. _Build Automatically_ was not ticked in my Eclipse instance.

**Comment by kesavamuthuM** [comment]
Hi I am also facing the same issue. In another project of GAE its showing the ouput. For newly created project only it's showing /hello 404

**Comment by chanseokoh** [comment]
@kesavamuthuM are you seeing the exact same message

"WARNING: No file found for /hello"

in the _Console_ view as in the screenshot? Did you check _Project_ > _Build Automatically_? Can you clean and rebuild the project? It is always reproducible? If it is, can you tell us how you created the project exactly?

**Comment by kesavamuthuM** [comment]
I created the project using google cloud platform icon in that selected GAE standard project didn't select any maven and App engine API. Also, I chose the build Automatically and rebuild. Even though it's obtaining. 

In the console, I am seeing the same warning error.

**Comment by chanseokoh** [comment]
Can you go to the _Servers_ view, select the server you created, right-click on it, select `Publish` (stop it first if necessary), and run the server again to see if it resolves the issue?

If not, can you check the contents of the publish folder? You'll see a log line like this:

```
2019-04-08 12:58:29.655:INFO:oejsh.ContextHandler:main: Started c.g.a.t.d.j.DevAppEngineWebAppContext@7ef82753{/,file:<...>/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/alice/,AVAILABLE}{/usr/local/google/home/chanseok/runtime-gcloud-eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/alice}
```

While leaving the server running (don't stop it), can you go to that directory and do `tree` for example below this?

```
chanseok@chanseok1:~/runtime-gcloud-eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/alice$ tree
.
├── favicon.ico
├── index.html
├── META-INF
│   └── MANIFEST.MF
└── WEB-INF
    ├── appengine-generated
    │   └── datastore-indexes-auto.xml
    ├── appengine-web.xml
    ├── classes
    │   └── HelloAppEngine.class
    ├── lib
    │   └── jstl-1.2.jar
    ├── logging.properties
    └── web.xml
```

**Comment by kesavamuthuM** [comment]
Yes, it's working now.

**Comment by kesavamuthuM** [comment]
Actually, It started to throw 404 after importing the project from a repository. After I cloned the bookshelf web app tutorial from GCP.

**Comment by chanseokoh** [comment]
Could you create a new issue with details about what the project is, how did you import it, whether you converted it to an App Engine project, error messages, what you've done and tried, etc? I am sure the bookshelf app doesn't respond to `/hello`.

**Comment by kesavamuthuM** [comment]
Initially I cloned this in git clone https://github.com/GoogleCloudPlatform/getting-started-java.git using git bash in windows 10. After that In eclipse File -> Import -> General -> existing project into workspace. Then I selected the project directory after that lots of project got imported including bookshelf. Eclipse downloaded lot of things showing the green line.
I didn't know what are those. After that, only the newly created projects started to show /hello not found.
Eventhough old GAE projects created by me running without any problem but changes in servlet file won't reflect in the browser.

**Comment by chanseokoh** [comment]
I can't reproduce that. From what you said, I wonder if your Eclipse installation got corrupted or some global config has been altered after importing getting-started-java. Given that you said it works after manual publishing, it might be that auto-publishing in Eclipse WTP is broken somehow.

I'd also check _Preferences_ > _Server_ > _Launching_ and _Preferences_ > _Server_ > _Overlays_ to see if auto-publishing is checked.

![Selection_001](https://user-images.githubusercontent.com/10523105/55746535-e6811180-5a07-11e9-8bc3-83b5e5c8ac22.png)
![Selection_002](https://user-images.githubusercontent.com/10523105/55746553-f39e0080-5a07-11e9-8055-d65ad684ac1a.png)

And on the _Servers_ view, double-click on each server to open up the _Overview_ page and see if _Automatically publish when resources change_ is checked and the _Publishing interval_ is set to 0 second.

![Selection_003](https://user-images.githubusercontent.com/10523105/55746642-32cc5180-5a08-11e9-824e-89a589726cfe.png)

If all things look good, maybe the fastest solution is to ditch the current workspace and Eclipse installation and start afresh with installing a new Eclipse. Given you this started to happen after importing an unrelated project, I believe it should work when starting afresh.

**Comment by kesavamuthuM** [comment]
Yes while importing the file it's not in a workspace of an eclipse. The project is in another folder. Then I removed all the projects. After clicking check for updates everything works well.
