### ISSUE TITLE
Target Photon by default and set up Kokoro CI for Photon builds

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3205]
We have Neon and Photon but not Oxygen.

**Comment by chanseokoh** [comment]
Okay, I've checked this again. We have all of them covered on Travis. We are running three Travis builds, one for each. By default, `mvn verify` will target Oxygen.

What we need to do is to add a Photon build on Kokoro. Currently, we only have Oxygen.

And, do we want to target Photon by default now? The target in our dev env is Oxygen.
