### ISSUE TITLE
not able to modify.gcp project on app engine on localhost

### ISSUE THREAD

**Issue by priyaranjan061** [GoogleCloudPlatform/google-cloud-eclipse#3231]
Before reporting a possible bug:

1. Please ensure you are running the latest version of CT4E with _Help > Check for Updates_
2. If the problem occurs when you deploy or after the application has been deployed, try deploying from the command line using gcloud or Maven. If the problem does not go away, then the issue is likely not with Cloud Tools for Eclipse.

- Cloud Tools for Eclipse version: 1.7.1.201807071456
- Google Cloud SDK version: 211.0.0 (auto-managed)
- Eclipse version: 4.7.3.v20180330-0640
- OS: Windows 7 6.1
- Java version: 1.8.0_25

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

Screenshots and stacktraces are helpful.

**Comment by briandealwis** [comment]
Hi @priyaranjan061 could you please provide some detail about the issue you're reporting, and some steps to repeat?  Is this happening during _Debug_ or _Run_?

**Comment by elharo** [comment]
reopen if there are more details.
