### ISSUE TITLE
Set up target for JDK 11

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3232]
JDK 11 releases September 25, 2018.  We should test and verify.

**Comment by briandealwis** [comment]
https://docs.travis-ci.com/user/languages/java/#using-java-10-and-later

**Comment by elharo** [comment]
One thing we'll need to check is that our new projects still set up Java 8 as the build environment.

**Comment by briandealwis** [comment]
We're blocked on having support in [Tycho for JDK-11](https://bugs.eclipse.org/bugs/show_bug.cgi?id=532302), which is itself blocked on having JDT support for JDK-11, which officially only happens once JDK-11 is released.

I wonder if we can save aside the test fragments and run them independently with a JDK-11 JVM.

**Comment by briandealwis** [comment]
Ah, figured out a way, and it's actually pretty nice.
