### ISSUE TITLE
Can't add libraries in Eclipse IDE

### ISSUE THREAD

**Issue by NewProgUser** [GoogleCloudPlatform/google-cloud-eclipse#3237]
I have been trying to add google loud Client Libraries in an Eclipse Project. As documented in this link
https://cloud.google.com/eclipse/docs/libraries?utm_source=github&utm_medium=google-cloud-java&utm_campaign=ToolsforEclipse
I have correctly updated my pom.xml file, however, i can't see the option of google library in Add Library window. Is there any other way to configure the google cloud libraries than what is documented in the link above?

Here are the screenshots of the library window and pom.xml file

<img width="1065" alt="screen shot 2018-08-27 at 7 46 33 pm" src="https://user-images.githubusercontent.com/42652080/44692775-81594c80-aa32-11e8-8f2f-a7cf49d3a028.png">

<img width="1680" alt="screen shot 2018-08-27 at 7 46 14 pm" src="https://user-images.githubusercontent.com/42652080/44692687-10b23000-aa32-11e8-907e-1bc22341d8f3.png">

**Comment by chanseokoh** [comment]
It is probably because your project is set up to use Java 5, and since you closed this issue, I believe you already resolved it.

**Comment by elharo** [comment]
From the screenshot it appears that Cloud Tools for Eclipse is not installed. And as @chanseokoh said, Java 7 or later is required anyway.
