### ISSUE TITLE
Multiple google cloud tools icon in status bar (Eclipse Oxygen 3.a / Fedora 28)

### ISSUE THREAD

**Issue by kerosene** [GoogleCloudPlatform/google-cloud-eclipse#3238]
Multiple google cloud icons are appearing in my status bar, one more every time I start eclipse
I'm using eclipse Oxygen.3a Release (4.7.3a) in Fedora 28.

![imagen](https://user-images.githubusercontent.com/440257/44731086-d0e25b80-aab8-11e8-8827-40188b13a4b9.png)

**Comment by briandealwis** [comment]
This is [an Eclipse bug](https://bugs.eclipse.org/bugs/show_bug.cgi?id=527896).  Cause is unknown, unfortunately.  If you have a way to reproduce this (see [comment 25](
https://bugs.eclipse.org/bugs/show_bug.cgi?id=527896#c25)) please chime in there.
