### ISSUE TITLE
Check whether we're using JSON-RPC

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3253]
Per instructions on this page:

https://developers.googleblog.com/2018/03/discontinuing-support-for-json-rpc-and.html

If so, upgrades are in order.

**Comment by briandealwis** [comment]
We're using the client libraries, but we have a [test that the `Storage` API returns a `www.googleapis.com` element](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.googleapis.test/src/com/google/cloud/tools/eclipse/googleapis/internal/GoogleApiFactoryTest.java#L87).

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
