### ISSUE TITLE
Fix flakey m2e-related tests on Photon

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3258]
In trying to fix #3256 we found that `com.google.cloud.tools.eclipse.integration.appengine.FlexMavenPackagedProjectStagingDelegateTest` and `com.google.cloud.tools.eclipse.integration.appengine.ImportMavenAppEngineStandardProjectTest` were flaking on Photon, for reasons that we have not been able to figure out.  These tests work fine locally.

**Comment by chanseokoh** [comment]
Is it possible to disable them only on Photon with `Assume.assumeFalse()`? We don't want to spend too much time on it though.

**Comment by diegomarquezp** [comment]
Closing as not planned.
