### ISSUE TITLE
Server App Engine Standard at localhost failed to start

### ISSUE THREAD

**Issue by ChidambaramR** [GoogleCloudPlatform/google-cloud-eclipse#3265]
- Cloud Tools for Eclipse version: 1.7.1.201807071456
- Google Cloud SDK version: app-engine-java 1.9.65
- Eclipse version: Eclipse Java EE IDE for Web Developers., 2018-09 (4.9.0)
- OS: MacOs Sierra, 10.12.6
- Java version: 1.8

**What did you do?**
Selected project in Eclipse -> right click -> Run as App engine

**What did you expect to see?**
Some message of the form "App engine started". The app engine gets started when I run it through command line

**What did you see instead?**
Server App Engine Standard at localhost failed to start

Similar issues: 
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/2027
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2464

It is always accompanied by this error found from eclipse error logs

Google Cloud SDK: Error starting server: java.nio.file.NoSuchFileException: /Users/chidr/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/teammates/WEB-INF/appengine-web.xml

eclipse.buildId=4.9.0.I20180906-0745
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_IN
Framework arguments:  -product org.eclipse.epp.package.jee.product -product org.eclipse.epp.package.jee.product -keyring /Users/chidr/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -data file:/Users/chidr/eclipse-workspace/ -product org.eclipse.epp.package.jee.product -keyring /Users/chidr/.eclipse_keyring

I checked the mentioned directory and these are the contents. Indeed there is no such file as application-web.xml

8c8590633a34:teammates chidr$ ls /Users/chidr/eclipse-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/teammates/WEB-INF/
appengine-web.template.xml
cron.xml		
lib			
queue.xml		
web.xml
classes			
datastore-indexes.xml	
logging.properties	
tags

**Comment by elharo** [comment]
Interesting. The error is correct. You need an appengine-web.xml and you don't have one. However it's worth digging deeper into this.

1. Why do you have appengine-web.template.xml? Where did that come from? I don't think Eclipse has such a file, but maybe from a maven archetype?

2. Is this problem (missing appengine-web.xml) something CT4E can and should surface in a more friendly fashion before we try to launch the local server?

**Comment by chanseokoh** [comment]
I guess `appengine-web.template.xml` is like a sample template that you need to update and rename to `appengine-web.xml`?

**Comment by ChidambaramR** [comment]
> I guess `appengine-web.template.xml` is like a sample template that you need to update and rename to `appengine-web.xml`?

Interesting. That did do the trick. The local server has started now

**Comment by ChidambaramR** [comment]
> Interesting. The error is correct. You need an appengine-web.xml and you don't have one. However it's worth digging deeper into this.
> 
> 1. Why do you have appengine-web.template.xml? Where did that come from? I don't think Eclipse has such a file, but maybe from a maven archetype?
> 2. Is this problem (missing appengine-web.xml) something CT4E can and should surface in a more friendly fashion before we try to launch the local server?

Thanks for the response. I am a newbie to this. I have no idea how the appengine template file came to life. I was trying to set up a local instance of a project called **teammates**

Here is the actual step which gave an error

https://github.com/TEAMMATES/teammates/blob/master/docs/development.md#managing-the-dev-server

Before coming to this step, I did the following
1. ./gradlew setupEclipse
2. Import existing gradle project in eclipse
3. Set some preferences like disabling validation, indentation etc
4. Start the local server from eclipse.

According to their doc, it should work without anyother configuration

These are the setting wrto Google-cloud-eclipse
1. In project preferences, I chose the google sdk that I downloaded (chosen from here: https://cloud.google.com/sdk/install).
2. Installed the sdk with this command ( ./install.sh --path-update true )
3. Installed app-engine as follows ( gcloud -q components install app-engine-java )

NOTE: I did not initialise the sdk 

I am not sure if I should leave this issue open. If you think is a non-issue, please feel free to close it

**Comment by wkurniawan07** [comment]
Greetings everyone, apologies for the false alarm. I am one of the maintainers of the project @ChidambaramR cloned. The error is exactly what @chanseokoh described; it is caused by a step that @ChidambaramR missed during setup.

This issue can be closed.
