### ISSUE TITLE
gcloud app deploy src/main/webapp/WEB-INF/appengine-web.xml  OR mvn appengine:update

### ISSUE THREAD

**Issue by iatomic** [GoogleCloudPlatform/google-cloud-eclipse#3274]
we have an app for GAE standard that runs fine locally with

1. mvn appengine:devserver

Options 2 or 3 below ....execute OK yet no app is deployed or reachable....

2. gcloud app deploy src/main/webapp/WEB-INF/appengine-web.xml
OR
3.mvn appengine:update
execute OK yet the app does not even show up, all we see is
Error: Not Found

We cannot fine ANY meaningful logs of startup either....

**Comment by iatomic** [comment]
Additional issues we have for app flex.

ERROR: failed to push because we ran out of retries.
ERROR
ERROR: error pushing image "eu.gcr.io/thetow-220011/appengine/default.20181028t040251:latest": exit status 1

**Comment by elharo** [comment]
Doesn't seem that Eclipse is involved here.

**Comment by iatomic** [comment]
I think it does. 
![image](https://user-images.githubusercontent.com/42481030/47644859-99069b80-db6f-11e8-9658-b0f9364322bd.png)

**Comment by iatomic** [comment]
I think it does - here is the errors we SOMETIMES get 
![image](https://user-images.githubusercontent.com/42481030/47644942-de2acd80-db6f-11e8-8686-5bc4b371cf50.png)

in general, gcloud tooling is totally unreliable with error reporting close to cryptic

**Comment by elharo** [comment]
This is the bug tracker you need for these sorts of issues:

https://issuetracker.google.com/savedsearches/559662

**Comment by elharo** [comment]
This is the bug tracker you need for these sorts of issues:

https://issuetracker.google.com/savedsearches/559662

**Comment by briandealwis** [comment]
@iatomic as a software developer yourself, I'm sure you realize that (1) mixing several problems together in an issue makes it difficult to tease apart, and (2) we need information to figure out what's going on: the maven build logs, the deploy logs, your configuration files (appengine-web.xml, pom.xml, ...).

You can obtain logs from the [Cloud Console](https://console.cloud.google.com)'s [App Engine version page](https://console.cloud.google.com/appengine/versions) for your project.  For each version you should see a "Tools" menu from which you can get your logs.

**Comment by iatomic** [comment]
the determination of those problems being MIXED is not correct. It seems like one problem.

>You can obtain logs from the Cloud Console's App Engine version page for your project. 
this is the problem, I do not think you get container startup logs there (the ones I get when I see output starting it locally with mvn appserver:devserver for example))

>For each version you should see a "Tools" menu from which you can get your logs.

if you would please point me to ONE output log there that contains the output we see in stdout when running mvn appengine:devserver. Sepearting bug tracking for cloud tools from bug tracking for cloud
is like running in stock trades in tunnels.

**Comment by iatomic** [comment]
if you happen to have an idea how often this happens I would appreciate. to us it has happened like 20 times so far.

![image](https://user-images.githubusercontent.com/42481030/47689181-13273680-dbe9-11e8-90c8-a316c259724d.png)

**Comment by briandealwis** [comment]
@iatomic I'd find hitting these issues to be very frustrating too. Although they may seem similar —  your deploy is failing — there are a number of steps involved in the deploy process.  We do create bug reports when we receive issues with self-contained or reproducible demonstrations, or where we have enough information from build logs.

Try the following link to see the console logs:

   https://console.cloud.google.com/logs/viewer?resource=gae_app&minLogLevel=0&expandAll=false&customFacets=resource.labels.module_id&limitCustomFacetWidth=true

That selects all logging records for your App Engine application regardless of service (previously called "module") or version.  It also adds a column showing the service (_resource.labels.module_id_) that handled the request.  I used the normal log viewer from a specific App Engine service + version, and then relaxed the log source to just be _GAE Application_, and then used _View Options > Modify custom fields_ to pull out the service ID from the logging payload.

**Comment by briandealwis** [comment]
@iatomic from what I've been able to find, the _time out_ error usually indicates one of two things:

1. You've hit a quota on allocated IP addresses (default is 8): with App Engine flexible environment, you have a VM running.  Unless you explicitly assign a version when deploying your app, each deploy will be assigned a unique version.  All versions are accessible unless stopped.  It may be that you currently have 8 versions of your app currently running.  Stopping or deleting some of those instances may fix the issue.  You can avoid this by redeploying to the same version when it makes sense (e.g., "iatomic-devel").  From reports I've seen elsewhere, you may even get better deployment performance.

2. Your default app engine service account may be missing the "editor" role.  Check your [IAM Service Accounts page](https://console.cloud.google.com/iam-admin/serviceaccounts).

Source: https://issuetracker.google.com/issues/114006548

**Comment by briandealwis** [comment]
With regards to your "_INVALID_ARGUMENT: unable to resolve source_" error, how often are you seeing this?  App Engine flexible uses Google Cloud Builder under the hood, and you may have some useful information in the build logs found on the [Cloud Builder history page in the Cloud Console](https://console.cloud.google.com/cloud-build/builds).

**Comment by iatomic** [comment]
we will look it up and try to post. thanks for the hint.

**Comment by briandealwis** [comment]
Can you please describe what issues you're seeing with the facets synchronization and Maven?

**Comment by iatomic** [comment]
to make long story short. in this project we cannot swap between flex and standard.

![image](https://user-images.githubusercontent.com/42481030/47738577-b58bfc00-dc73-11e8-93f9-9e66b814abf1.png)
