### ISSUE TITLE
Document how to run tests

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3308]
After a few months working on other projects, I notice I have forgotten the incantations necessary to run the tests such that they pass. Given that the usual `git clone,,,;mvn test...` workflow is insufficient, we should document exactly what needs to be done to checkout and run the codebase such that tests pass. 

The integration tests seem to be the problem and if we ever wrote down what how to run these I can't find it:

```
[INFO] com.google.cloud.tools.eclipse.util.test ........... SUCCESS [  0.130 s]
[INFO] com.google.cloud.tools.eclipse.welcome.test ........ SUCCESS [  0.136 s]
[INFO] com.google.cloud.tools.eclipse.integration.appengine FAILURE [  0.277 s]
[INFO] gcp-eclipse-photon ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.971 s
[INFO] Finished at: 2018-12-16T07:04:47-05:00
[INFO] Final Memory: 198M/487M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project com.google.cloud.tools.eclipse.integration.appengine: Could not resolve dependencies for project com.google.cloud.tools.eclipse:com.google.cloud.tools.eclipse.integration.appengine:eclipse-test-plugin:0.1.0-SNAPSHOT: Failure to find com.google.cloud.tools.eclipse:com.google.cloud.tools.eclipse.suite.feature:jar:1.7.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
```

**Comment by briandealwis** [comment]
I set `GOOGLE_CLOUD_SDK_HOME` since I don't have `gcloud` on my `PATH` and my Cloud SDK is installed in a non-standard location, but otherwise a `mvn verify` works for me.

I have noticed that running tests from maven from the command-line seems to interfere more ifdue to interference with a location with

**Comment by chanseokoh** [comment]
If you only want to run the test, actually it's mostly just `mvn verify`.

1. Have Java, Maven, and Cloud SDK (with the  `app-engine-java` component) ready.
   - Cloud SDK install:
      1. `curl https://sdk.cloud.google.com | bash`
      1. `gcloud components install app-engine-java`
1. `$ git clone https://github.com/GoogleCloudPlatform/google-cloud-eclipse.git`
1. `$ mvn verify` (read below)

However, `mvn verify` launches the integration tests on your monitor, and if you touch anything, they will fail. (Non-integration tests are not affected.) Therefore, you'll almost certainly want to do this:

[`$ xvfb-run mvn verify`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2859#issuecomment-373196131)

**Comment by chanseokoh** [comment]
Not sure if MacOS has [Xvfb](https://linux.die.net/man/1/xvfb) or it is easy to install it though.
