### ISSUE TITLE
Bad Error message with servlet 3.1 in a Java 7 project

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3315]
1. Create new Java 8 servlet 3.1 app using the wizard
2. In appengine-web.xml change java8 to java7 or Remove the runtime element. A listener converts the project to Java 7/servlet 2.5.
4. This causes various errors. One is a marker on web.xml that says "App Engine Standard does not support this servlet version"

That message is incorrect. It should be "The java7 runtime for App Engine Standard does not support servlet version 3.1."

Low priority right now except that I think investigating this is likely to show us other details we need to worry about as we remove Java 7 support.

**Comment by JoeWang1127** [comment]
close as not planned
