### ISSUE TITLE
Decouple servlet version from java runtime in New Project Wizard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3316]
I've verified that it's possible to deploy a servlet 2.5 app on the java8 runtime. This combination is a little tricky to create with our current plugin though.

Let's consider separating the runtime choice from the servlet API choice. This may matter more if additional runtimes and servlet APIs (e.g. 4.0, 11) are added in the future.

For now, It may be easier for an interim step to just add Java 8, Servlet 2.5 to the existing dropdown as we remove the Java 7 options.

**Comment by chanseokoh** [comment]
> It may be easier for an interim step to just add Java 8, Servlet 2.5 to the existing dropdown

Agreed.

> Let's consider separating the runtime choice from the servlet API choice.

On the other hand, there will be inherent coupling between a runtime and its available Servlet choices (e.g., Java 8 Runtime doesn't support Servlet 4.0), so I'm not certain at this point what would be the best code structure and UI. The current UI could still work fine.

**Comment by chanseokoh** [comment]
> It may be easier for an interim step to just add Java 8, Servlet 2.5 to the existing dropdown

Will do this for now.

**Comment by chanseokoh** [comment]
Adding Java 8 Servlet 2.5 in the UI and materializing files in Servlet 2.5 was easy to implement, but I realized there is a little complication in adding the Dynamic Web Modules 2.5 facet. Currently, our code tries to infer the highest satisfying version that we can install according to the given runtime restrictions, so it always ends up installing the 3.1 web facet. I'll look into this a bit more.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
