### ISSUE TITLE
Remove appengine.standard.java8 bundle?

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3317]
The Java 8 facet is defined in that bundle. For every code that needs to reference that facet, it has to import packages from that bundle. I think the motivation for an independent bundle was mainly for nice conceptual separation. For example, you could drop the `.java8` bundle (or the `.java8` bundle is failed to install for any reason), and the whole system is guaranteed to work seamlessly without any Java 8 support. That is nice, but I doubt if this "nice" property is going to be useful at all. Some people may disagree, but I rather feel that at least the Java 8 facet is a core, integral part of the CT4E App Engine feature. With Java 7 being deprecated, I think it is even harder to completely set apart App Engine Java 8 stuff in CT4E architecture.

I also remember a problem that sometimes, it creates a circular dependency. For example, some core functionality bundle wants to use the Java 8 facet, but the `.java8` bundle depends on that core functionality.

**Comment by briandealwis** [comment]
I'll disagree and argue that the fact that Java 7 is so entwined in our code is why we should separate these runtimes into different bundles.  It may seem like more work, but the decoupling pays dividends down the road.

**Comment by chanseokoh** [comment]
Okay, I think that's a fair point.

I just remember cases where I'd want to use the Java 8 facet (especially in tests, maybe `.localserver.test` or something) but it was a headache or not really feasible to do so due to not being able to depend on the `.java8` bundle.

**Comment by elharo** [comment]
I think we originally had separate bundles because java8 was whitelisted. Now imagine a world in which there are 2 or 3 supported runtimes, e.g. java7, java8, and java11. Does it make sense to have a separate bundle for each? I'm not sure.

FYI, I'm told we shouldn't yet remove java7 support completely due to legacy customers.

**Comment by JoeWang1127** [comment]
close as not planned
