### ISSUE TITLE
Unable to install Google Cloud SDK on MacOS

### ISSUE THREAD

**Issue by abhiram-vedullapalli** [GoogleCloudPlatform/google-cloud-eclipse#3329]
- Cloud Tools for Eclipse version: 1.7.1
- Google Cloud SDK version:  Unable to install
- Eclipse version: 12-18
- OS: MacOS
- Java version: 1.8.0_111

**What did you do?**
I installed Google cloud tools plugin from Eclipse market place. 
**What did you expect to see?**
I am trying to run my project.
**What did you see instead?**
My project is not running on local host. Instead I am getting an error that "Cloud SDK is not installed"

![screenshot 2018-12-24 at 7 58 31 pm](https://user-images.githubusercontent.com/39947022/50401866-d24a3900-07b7-11e9-8346-eb76e4f7ce49.png)

![screenshot 2018-12-24 at 7 59 28 pm](https://user-images.githubusercontent.com/39947022/50401869-dd9d6480-07b7-11e9-8ebc-9946bcc0ff04.png)

![screenshot 2018-12-24 at 7 59 45 pm](https://user-images.githubusercontent.com/39947022/50401874-ec841700-07b7-11e9-9be7-d79bcbb9f31e.png)

I tried installing using this [https://cloud.google.com/sdk/docs/downloads-interactive](url) also. The error I got is

![screenshot 2018-12-24 at 8 13 06 pm](https://user-images.githubusercontent.com/39947022/50401943-6f0cd680-07b8-11e9-9fec-aba17618033c.png)

**Comment by chanseokoh** [comment]
Hi @abhiram-vedullapalli,

> Active configuration name could not be read from: [/User/abhiram/.config/gcloud/active_config].

> Ensure you have sufficient read permissions on required active configuration in [/Users/abhiram/.config/gcloud/configurations].

> Unable to read file [/User/abhiram/.config/gcloud/active_config]: [Errorno 13] Permission defined: '/User/abhiram/.config/gcloud/active_config'

Probably `chown -R $(whoami) ~/.config/gcloud` and `chmod +r ~/.config/gcloud` will resolve the issue.

**Comment by abhiram-vedullapalli** [comment]
I changed the permissions and it got resolved. Thank you.
