### ISSUE TITLE
The Eclipse Welcome view does not open to the Overview page.

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3332]
Per test plan:

The Eclipse Welcome view should open to the Overview page.
Ensure Cloud Tools for Eclipse is highlighted. Clicking on the entry should take you to the CT4E Product Overview webpage.

I think this is an error in the test plan but let's make sure.

Also, "Ensure Cloud Tools for Eclipse is highlighted." should probably be "Select Cloud Tools for Eclipse." That is, I don't think it's supposed to auto-highlight.

**Comment by chanseokoh** [comment]
Yeah, nothing is to be highlighted on Eclipse 2018-09. Unsure if it was possible to highlight an entry in past Eclipse versions, but we can just say "Select Cloud Tools for Eclipse in the Overview page."

**Comment by chanseokoh** [comment]
Removed all the places mentioning "highlighted".

**Comment by briandealwis** [comment]
Odd because it's definitely highlighted on 2018-12.  This highlighting should be shown on restart after installing CT4E.

<img width="589" alt="screen shot 2019-01-11 at 10 18 24 am" src="https://user-images.githubusercontent.com/202851/51042413-3cb9f200-158a-11e9-87c0-bcaa120bce82.png">

**Comment by chanseokoh** [comment]
I know there are at least two different rendering styles in an Eclipse browser depending on environments, and I think it is related.

![selection_009](https://user-images.githubusercontent.com/10523105/51043823-9b349f80-158d-11e9-9e2d-e5d63d4c9184.png)

Interestingly, these two are the same 2018-09 running on my machine. Not sure how I got them different even on the same machine.

That said, I think #3374 is also related, happening only with the left-side rendering.
