### ISSUE TITLE
Migrate is missing

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3333]
Per test plan:

Click on the Home button in the Welcome toolbar and select Migrate. Ensure Migration from the Google Plugin for Eclipse (GPE) is highlighted. Clicking on the entry should take you to the CT4E _Migrating from the Google Plugin for Eclipse_ webpage.

I can't find this anywhere.

**Comment by chanseokoh** [comment]
This is it: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3191#issuecomment-403057170 (The settings page can be open by clicking on the "customize" toolbar button of the Welcome page.)

**Comment by chanseokoh** [comment]
Updated the test plan.
