### ISSUE TITLE
Status message

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3334]
Per test plan:

The status hover / GCP menu item should show java.net.UnknownHostException: status.cloud.google.com

The test plan is probably incorrect here, but what is shown is 

![image](https://user-images.githubusercontent.com/1005544/50654182-f9dc9680-0f59-11e9-9e97-4dc655ac28ee.png)

**Comment by elharo** [comment]
see https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3130

**Comment by elharo** [comment]
Updated test plan. However this should probably be some symbol other than a checkmark.

**Comment by JoeWang1127** [comment]
close as not planned
