### ISSUE TITLE
Upgrade to Java 8 runtime quickfix should also change maven.compiler.source and maven.compiler.target in pom.xml

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3338]
It stays 1.7:

```
  <properties>
    <appengine.maven.plugin.version>1.3.2</appengine.maven.plugin.version>
    <appengine.api.sdk.version>1.9.71</appengine.api.sdk.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <maven.compiler.source>1.7</maven.compiler.source>
    <maven.compiler.target>1.7</maven.compiler.target>
    <maven.compiler.showDeprecation>true</maven.compiler.showDeprecation>
  </properties>
```

Or maybe we should only update the target?
How important is this?

**Comment by chanseokoh** [comment]
I believe those things are tied and controlled by the Java facet (probably through m2e).

For native (non-Maven) projects, we adjust a few things (changes the App Engine facet between JRE7 and JRE8, switches project JDK between 7 and 8), but AFAIK, we've never supported (or we could never be able to support) changing runtimes for Maven projects. Looks like a dup of #2919.

**Comment by JoeWang1127** [comment]
close as not planned
