### ISSUE TITLE
Java 7 quickfix warning even if <runtime>java8 present

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3340]
Not sure how I got into this. Was applying the quickfix and doing Ctrl+z / Ctrl+Shift+z. Note that the _Problems_ view does not have the corresponding warning entry.

![selection_002](https://user-images.githubusercontent.com/10523105/50704871-e1867d80-1026-11e9-8a37-45a10fb60cf8.png)

![selection_001](https://user-images.githubusercontent.com/10523105/50704874-e4816e00-1026-11e9-9664-22b188958688.png)

**Comment by chanseokoh** [comment]
I found out.

- Remove `<runtime>java8</runtime>` to trigger the warning.
- Manually enter `<runtime>java8<runtime>`.

Then the warning in the _Problems_ view go away, but the warning marker in the left gutter doesn't disappear.

**Comment by chanseokoh** [comment]
Also, by repeating the process, it adds more quick fixes.

![selection_004](https://user-images.githubusercontent.com/10523105/50705162-e697fc80-1027-11e9-9ece-ae012b652af3.png)

**Comment by elharo** [comment]
Problem may be that we're not deleting markers in XmlSourceValidator.validate although we are in XmlValidator.validate.

**Comment by elharo** [comment]
Nope, that didn't do it. :-(

**Comment by elharo** [comment]
To repro place cursor at very first location in file and use Command-1
