### ISSUE TITLE
Lightbulb on XSLTQuickFix sidebar icon

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3346]
The sidebar does not show the lightbulb to indicate a quick fix is available although the problems view does:

![image](https://user-images.githubusercontent.com/1005544/50768440-699a9c00-124e-11e9-8d75-66dd6aa69a78.png)

This is in 1.7.1, not a regression.

**Comment by lak-proddev** [comment]
It's not implemented yet for WTP XML editors. See this bug for more info
https://bugs.eclipse.org/bugs/show_bug.cgi?id=285717

**Comment by lak-proddev** [comment]
after the WTP fix  https://git.eclipse.org/r/#/c/141574/

![image](https://user-images.githubusercontent.com/39690425/57135125-fc46e400-6dc5-11e9-8c4b-638ad092eec2.png)

**Comment by lak-proddev** [comment]
WTP bug #285717 was fixed and will be available in the next release. I think we can close it.

**Comment by mpeddada1** [comment]
Thank you for attaching the link to the fix! Closing.
