### ISSUE TITLE
min-instances can be zero

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3351]
Problem you have encountered:
There is inconsistency between documentation and validation of appengine-web.xml on whether `<min-instances>` can be set to 0 for `<automatic-scaling>`.

In appengine-web-xml reference (https://cloud.google.com/appengine/docs/standard/java/config/appref#scaling_elements_automatic_scaling), it says `<min-instances>` can be set to zero for `<automatic-scaling>`:
"Specify a value from 0 to 1000. You can set the parameter to the value 0 to allow scaling to 0 instances to lower costs when no requests are being served. Note that you are charged for the number of instances specified whether they are receiving traffic or not."

In eclipse, validation fails when trying to set <min-instances> to 0 with the following error message:
Multiple annotations found at this line:
        - cvc-type.3.1.3: The value '0' of element 'min-instances' is not valid.
        - cvc-minInclusive-valid: Value '0' is not facet-valid with respect to minInclusive '1' for type 
         'positiveInteger'.

What you expected to happen:
Either one should be able to set <min-instances> to 0, or the documentation should not imply this is possible.

Steps to reproduce:
In Eclipse xml editor, add the following to appengine-web.xml and save the file:
```
  <automatic-scaling>
    <min-instances>0</min-instances>
  </automatic-scaling>
```

**Comment by chanseokoh** [comment]
This is an easy fix in the current setup. We embed `appengine-web.xsd`, so we need to update it.

Ideally, we should auto-populate `appengine-web.xsd` from the Cloud SDK.
