### ISSUE TITLE
ID and IDREF in validation plugin.xml

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3354]
This is at head and earlier. In this code fragment, [markerType is supposed to be an IDREF pointing to an extension element](https://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Freference%2Fextension-points%2Forg_eclipse_ui_ide_markerResolution.html). However it points to com.google.cloud.tools.eclipse.appengine.validation.applicationMarker instead of the actual ID which is simply applicationMarker. This does seem to work. Are the Eclipse extension point docs wrong? Is there some weird undocumented namespacing happening here? 

```
  <extension
      id="applicationMarker"
      name="%appengine.blacklist.marker"
      point="org.eclipse.core.resources.markers">
    <super type="com.google.cloud.tools.eclipse.appengine.validation.appEngineBlacklistMarker" />
    <persistent value="true" />
  </extension>

  <extension
      point="org.eclipse.ui.ide.markerResolution">
    <markerResolutionGenerator
      class="com.google.cloud.tools.eclipse.appengine.validation.AppEngineWebMarkerResolutionGenerator"
      markerType="com.google.cloud.tools.eclipse.appengine.validation.applicationMarker">
    </markerResolutionGenerator>
  </extension>
  </extension>
```

**Comment by briandealwis** [comment]
*Typically* when given `<extension id="xxx">` an unqualified `xxx` will be prefixed with the bundle's symbolic name.  The markers code seems to *always* prefix the ID with the BSN. So in this code, the marker is defined in `com.google.cloud.tools.eclipse.appengine.validation` and so the marker ID is `com.google.cloud.tools.eclipse.appengine.validation.applicationMarker`.

**Comment by briandealwis** [comment]
> The markers code seems to always prefix the ID with the BSN. 

The [relevant code that loads the marker definitions](https://git.eclipse.org/c/platform/eclipse.platform.resources.git/tree/bundles/org.eclipse.core.resources/src/org/eclipse/core/internal/resources/MarkerTypeDefinitionCache.java?h=master#n135) 
uses [`IExtension.getUniqueIdentifer()`](https://git.eclipse.org/c/equinox/rt.equinox.bundles.git/tree/bundles/org.eclipse.equinox.registry/src/org/eclipse/core/runtime/IExtension.java?h=master#n179) to create the marker ID, which is documented as returning the namespace ID (the BSN) with the simple ID (the `id` value).

**Comment by elharo** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=543302

**Comment by JoeWang1127** [comment]
close as not planned
