### ISSUE TITLE
Delete our own markers only in XmlValidator#deleteMarkers()

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3364]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3356#issuecomment-452409860

Probably we should delete our own markers only.

**Comment by elharo** [comment]
It may be more complex than that. We run some of the XML checks and we should delete those markers too.

**Comment by briandealwis** [comment]
Unless I misremember, I don't think we explicitly run any XML checks.  Rather we provide XSDs that are then validated by WTP XML.

**Comment by elharo** [comment]
That's what I was thinking of. Like you said on the other thread, we delete and reform the file so everything is deleted and recalculated anyway.
