### ISSUE TITLE
Add support for enabling Dataflow APIs

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3377]
When selecting a project for Dataflow, there is no way for the user to request enabling Dataflow for a project.  Enabling the APIs from Pantheon is surprisingly non-obvious, requiring the user to proceed through the word-count tutorial.

**Comment by elharo** [comment]
@briandealwis Do you have access to Buganizer these days so you can file bugs against Pantheon?

**Comment by briandealwis** [comment]
Filed feedback on the Pantheon page.

**Comment by elharo** [comment]
Thanks. :-)

**Comment by mpeddada1** [comment]
Closing as not planned.
