### ISSUE TITLE
BOM in non-BOM Maven projects

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3380]
When adding a cloud client library to a Maven project (including non App Engine projects) that does not import the google-cloud-bom, add the BOM. There are two cases here:

1. The dependencyManagement section does not include google-cloud-bom.
2. There is no dependencyManagement section.

**Comment by lak-proddev** [comment]
@elharo  Can you explain a little bit more?

**Comment by elharo** [comment]
Set the dependency versions from a dependencyManagement section that imports google-cloud-bom like so:

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-bom</artifactId>
        <version>0.96.0-alpha</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```
