### ISSUE TITLE
Unable to install Google Cloud Tools for Eclipse

### ISSUE THREAD

**Issue by basementaspirations** [GoogleCloudPlatform/google-cloud-eclipse#3388]
- Cloud Tools for Eclipse version:
- Google Cloud SDK version: 29.0.0
- Eclipse version: 2018-12 (4.10.0)
- OS: MacOS
- Java version: 1.8.0_144

**What did you do?**
Drag and drop the link to eclipse from the document to install CT4E

**What did you expect to see?**
Installing CT4E
**What did you see instead?**
Exception error. I got the same error on a windows machine too
The following solutions are not available: Google Cloud Tools for Eclipse 1.8.0 (id=eu.openanalytics.editor.docker.feature.group, site=https://dl.google.com/eclipse/google-cloud-eclipse/stable/)

eclipse.buildId=4.10.0.I20181206-0815
java.version=1.8.0_144
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_CA
Framework arguments:  -product org.eclipse.epp.package.jee.product -keyring /Users/GlaxGraces/.eclipse_keyring
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -product org.eclipse.epp.package.jee.product -keyring /Users/GlaxGraces/.eclipse_keyring

**Comment by elharo** [comment]
Interesting. For the moment, try installing from **Help > Install New Software** using the update site https://dl.google.com/eclipse/google-cloud-eclipse/stable/

which shouldn't give you the docker feature option. I wonder why that's showing up in drag and drop?

**Comment by briandealwis** [comment]
Oops, sorry: we dropped the Docker Editor in #3234 in favour of the [Docker Tooling from the Eclipse Linux Tools project](https://www.eclipse.org/linuxtools/projectPages/docker/), but I failed to remove the feature from the Marketplace entry.  I've removed it now.
