### ISSUE TITLE
Using Java 9 hangs new project wizard

### ISSUE THREAD

**Issue by npsabnis** [GoogleCloudPlatform/google-cloud-eclipse#3394]
Eclipse: Oxigen
Google Cloud SDK : installed
Maven : installed 3.6
OS: windows 7

Just installed the eclipse plugin for google app engine cloud: cloud tools. 
When creating the standard project using the plugin menu, progress looks like entered in never ending loop while the background process description: Configuring for javascript (Blocked...) 
project creation wizard shows message : installing app engine java standard environment facet.

But this process never finishes..please find the screenshot as follows

![image](https://user-images.githubusercontent.com/3809293/52365322-3e81b300-2a6d-11e9-94fd-a7c932f26ec0.png)

**Comment by briandealwis** [comment]
HI @npsabnis.  Could you please do the following:
  - use the `jstack` tool to get a stack trace: that will help us see what's blocked
  - kill and restart Eclipse with `-console` on the command-line: this will pop up a console window showing additional information.  Copy and paste that here too.
  - let us know what other plugins do you have installed; check out the information in _Help > About_

**Comment by elharo** [comment]
"Configuring for javascript (Blocked...)" is weird. I din't think anything we do should make that happen. Unless maybe there's something else that does that when it sees us creating an HTML file?

**Comment by npsabnis** [comment]
The problem looks like resolved when i changed the project java version from jdk 9 to jdk 8.

**Comment by elharo** [comment]
That would do it alright. I do wonder if we should add some checks around this though, either to warn if the user has set Java 9+ or just to auto-set to Java 8. App Engine only supports Java 8 at this time.

**Comment by npsabnis** [comment]
User can be notified that compiler is set to 1.8 when he create or convert project using Google app engine plugin..

**Comment by briandealwis** [comment]
@npsabnis did you have a Java 8 JRE configured?  (_Window > Preferences > Java > Installed JREs_)

**Comment by npsabnis** [comment]
Now I have it. It was not before the issue occurrence.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant.
