### ISSUE TITLE
Test failures probably due to gcloud blocking GAE Java7 staging?

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3400]
Just saw the error log. I haven't tried reproducing. Perhaps this always fails locally; I think there's no target GCP project involved.

```
.../java -cp .../google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/appengine-tools-api.jar \
    com.google.appengine.tools.admin.AppCfg \
    --disable_update_check \
    --enable_jar_splitting \
    stage \
    .../safe-work-directory/exploded-war \
   .../staging-result
```

```
    [Cloud SDK] Reading application configuration data...
    [Cloud SDK] 2019-04-05 10:37:44.577:INFO::main: Logging initialized @235ms to org.eclipse.jetty.util.log.StdErrLog
    [Cloud SDK] 
    [Cloud SDK] 
    [Cloud SDK] Beginning interaction for module default...
    [Cloud SDK] Unable to stage app: GAE Java7 is not supported anymore.
    [Cloud SDK] Please see the logs [/tmp/appcfg1254035475743571136.log] for further information.
```

**Comment by chanseokoh** [comment]
We can fix the tests, but this implies people can no longer deploy App Engine Java 7 apps, unless there's a special switch for Java 7 staging.

**Comment by chanseokoh** [comment]
If Java 7 is completely turned down (need to confirm), there may be some code we could clean up.

**Comment by elharo** [comment]
Java 7 is not completely turned down.

**Comment by ludoch** [comment]
There is no switch anymore and Java7 runtime is prod is now only used by a few customers that are actively tracked.
In any case, a potential customer can always downgrade the Cloud SDK to the previous version.  That would be the equivalent of a switch.
