### ISSUE TITLE
[Unable to satisfy dependenc  to  com.fasterxml.jackson.core.jackson-core 

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3406]
[WARNING] Mirror tool: Problems resolving provisioning plan.: [Unable to satisfy dependency from 201902071901.Default 1.0.0.A_DyEWscLWvnhEhUibRWgKz0DBaROP-LvOyW to org.eclipse.equinox.p2.iu; com.fasterxml.jackson.core.jackson-core [2.9.2.v20180207-1730,2.9.2.v20180207-1730].; Unable to satisfy dependency from 201902071901.Default 1.0.0.A_DyEWscLWvnhEhUibRWgKz0DBaROP-LvOyW to org.eclipse.equinox.p2.iu; com.google.gson [2.8.2,2.8.2].]

**Comment by JoeWang1127** [comment]
close as not planned
