### ISSUE TITLE
See if we can stop bundling  jars in googleapiclient package

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3413]
See

https://github.com/googleapis/google-api-java-client/issues/1018

And even if we can't they need to be upgraded

Bundle-Classpath: .,
 lib/google-api-client-1.25.0.jar,
 lib/google-api-services-appengine-v1-rev80-1.25.0.jar,
 lib/google-api-services-bigquery-v2-rev405-1.25.0.jar,
 lib/google-api-services-cloudresourcemanager-v1-rev507-1.25.0.jar,
 lib/google-api-services-compute-v1-rev198-1.25.0.jar,
 lib/google-api-services-dataflow-v1b3-rev259-1.25.0.jar,
 lib/google-api-services-datastore-v1-rev63-1.25.0.jar,
 lib/google-api-services-iam-v1-rev261-1.25.0.jar,
 lib/google-api-services-oauth2-v2-rev141-1.25.0.jar,
 lib/google-api-services-pubsub-v1-rev403-1.25.0.jar,
 lib/google-api-services-servicemanagement-v1-rev412-1.25.0.jar,
 lib/google-api-services-storage-v1-rev138-1.25.0.jar,
 lib/google-http-client-1.25.0.jar,
 lib/google-http-client-jackson-1.25.0.jar,
 lib/google-http-client-jackson2-1.25.0.jar,
 lib/google-oauth-client-1.25.0.jar,
 lib/google-oauth-client-java6-1.25.0.jar,
 lib/google-oauth-client-jetty-1.25.0.jar,
 lib/plugins-login-common-0.2.2.jar

**Comment by elharo** [comment]
The OSGI metadata generation code in these libraries was broken. I pushed some changes to these libraries to fix that but we need to wait for these to be released.

**Comment by JoeWang1127** [comment]
close as not planned
