### ISSUE TITLE
Error writing data to TLS socket: The specified session has been invalidated for some reason.

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3424]
From Welcome Screen I clicked on Google Cloud Tools for Eclipse link and got:

Error writing data to TLS socket: The specified session has been invalidated for some reason.

Not yet sure if this is reproducible, but logging here in case it is. 

![image](https://user-images.githubusercontent.com/1005544/57705087-2eabd900-7631-11e9-9946-12e0ca02c5c3.png)

**Comment by elharo** [comment]
This might be an issue with certs in older versions of the Eclipse internal browser.

**Comment by briandealwis** [comment]
If it happens again, please check the console or error log.  Perhaps an explanation was logged.

**Comment by JoeWang1127** [comment]
close as not planned
