### ISSUE TITLE
Performance  issues while changing the settings on "Pipeline Argument Tab"

### ISSUE THREAD

**Issue by lak-proddev** [GoogleCloudPlatform/google-cloud-eclipse#3434]
Try to change the settings on "Pipeline Argument Tab". we can see some performance issues as shown  in below SS
For instance
1. Change "Runner" options.
2. Change "Use default Dataflow options".
3. Type some text on  "Service account key"

![image](https://user-images.githubusercontent.com/39690425/58090305-8e335700-7be4-11e9-8368-844e954c4573.png)

**Comment by chanseokoh** [comment]
Is this a dup of #2287?

**Comment by lak-proddev** [comment]
> Is this a dup of #2287?
It seems to be duplicate. UI freezing for a simple change.
