### ISSUE TITLE
No icon for "Pipeline Argument Tab"

### ISSUE THREAD

**Issue by lak-proddev** [GoogleCloudPlatform/google-cloud-eclipse#3436]
No icon is shown for "Pipeline Argument Tab" Like, How the other tabs are shown.

![image](https://user-images.githubusercontent.com/39690425/58178919-bb573680-7cc4-11e9-847f-d88df71fc2ba.png)

**Comment by elharo** [comment]
Not sure we have an appropriate icon to use here.

**Comment by chanseokoh** [comment]
Fixed by #3447.
