### ISSUE TITLE
Layout issue on Run/Debug on Server wizard

### ISSUE THREAD

**Issue by lak-proddev** [GoogleCloudPlatform/google-cloud-eclipse#3438]
STEPS:
1. Create a new "Google App Engine Flexi Java Project".
2.Right click on project and  Debug -> Debug On server 
3. It will open a launch wizard with an option  "Manual define a server".The server type tree is compressed. See below image

![image](https://user-images.githubusercontent.com/39690425/58261138-62a39e80-7d95-11e9-9d59-bbe3ce277ad4.png)

**Comment by chanseokoh** [comment]
I believe the dialog is owned and rendered by WTP except for the bottom fields that we inject through an extension, so it is not clear if we can have control over the size of the tree UI.

**Comment by lak-proddev** [comment]
> I believe the dialog is owned and rendered by WTP except for the bottom fields that we inject through an extension, so it is not clear if we can have control over the size of the tree UI.

Yes, you are right.  But, I suspect this is the class that we can fix it our side. com.google.cloud.tools.eclipse.appengine.localserver.ui.ServerPortExtension

**Comment by lak-proddev** [comment]
Filed an issue on WTP board  https://bugs.eclipse.org/bugs/show_bug.cgi?id=547641

**Comment by lak-proddev** [comment]
https://git.eclipse.org/r/143595 will fix the WTP issue. 
SS after fix
![image](https://user-images.githubusercontent.com/39690425/59157033-c0d4bf00-8ac1-11e9-9464-45ab4781b4dc.png)

**Comment by JoeWang1127** [comment]
close as not planned
