### ISSUE TITLE
Icons missing in welcome view

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3451]
This is in Eclipse 2018-09 on Linux.

![image](https://user-images.githubusercontent.com/1005544/59056878-22e5b800-8867-11e9-9d50-ec8748446ff5.png)

**Comment by elharo** [comment]
same on all the other pages

**Comment by elharo** [comment]
![image](https://user-images.githubusercontent.com/1005544/59057259-fed6a680-8867-11e9-9ef9-4b5400e13f87.png)

**Comment by briandealwis** [comment]
@chanseokoh saw this too with 2018-09.
Duplicate of #3374

**Comment by elharo** [comment]
closing as dupe, but we should still fix this if at all possible. Any idea what might be happening?
