### ISSUE TITLE
Dataflow sample code indentation is off

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3459]
Does not follow Google style:

```java
    p.apply(Create.of("Hello", "World"))
    .apply(MapElements.via(new SimpleFunction<String, String>() {
      @Override
      public String apply(String input) {
        return input.toUpperCase();
      }
    }))
    .apply(ParDo.of(new DoFn<String, Void>() {
      @ProcessElement
      public void processElement(ProcessContext c)  {
        LOG.info(c.element());
      }
    }));
```

This might need to be fixed in Maven archetypes somewhere.

**Comment by lak-proddev** [comment]
What's the bug here?

**Comment by elharo** [comment]
The sample code in a new dataflow project is not indented per Google code style. It should be:

```java
    p.apply(Create.of("Hello", "World"))
        .apply(MapElements.via(new SimpleFunction<String, String>() {
          @Override
          public String apply(String input) {
            return input.toUpperCase();
          }
        }))
        .apply(ParDo.of(new DoFn<String, Void>() {
          @ProcessElement
          public void processElement(ProcessContext c)  {
            LOG.info(c.element());
          }
        }));
```

or something close to that.

**Comment by elharo** [comment]
also we shouldn't be using single letter variable names here; i.e. c --> context

**Comment by lak-proddev** [comment]
@elharo  Do we have any eclipse template file to import for formatting?
Actually, Recently I have fixed a similar issue in jdt repository. Can you check that it's the same?
https://bugs.eclipse.org/bugs/show_bug.cgi?id=476636

**Comment by elharo** [comment]
We follow Google Java style: https://google.github.io/styleguide/javaguide.html

There's a slightly out of date Eclipse plugin for this floating round somewhere. I think this is it:

https://github.com/google/styleguide/blob/gh-pages/eclipse-java-google-style.xml

**Comment by lak-proddev** [comment]
> also we shouldn't be using single letter variable names here; i.e. c --> context
the code is generated by maven. We can format the code. I don't think to change the variable names easily.

**Comment by chanseokoh** [comment]
Ah, right. The code is from Maven archetypes. We should update the archetypes (if deemed necessary) rather than trying to post-process in CT4E. Personally, I don't think we really have to force Google-style on users' code.
