### ISSUE TITLE
Pipeline Options area is not scrollable

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3460]
As seen here when DataflowRunner is selected it contains many more options than fit in the box, even before they're expanded.

![image](https://user-images.githubusercontent.com/1005544/59118272-b5e12980-891d-11e9-9498-75c506466837.png)

**Comment by chanseokoh** [comment]
This used to work. There has been a recent change to the tab (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3429/files#diff-dd016fdad7541a88ded3c32da9041aac) where it removed `ScrolledComposite`. Could this be it?

**Comment by briandealwis** [comment]
The overall _Pipeline Arguments_ tab is scrollable, but the _Pipeline Options_ section's height doesn't seem to be taking effect.  @lak-proddev ?

![pipeline-arguments optimize](https://user-images.githubusercontent.com/202851/59128270-9b1bae80-8937-11e9-93b7-77c64a57df90.gif)

**Comment by lak-proddev** [comment]
Ha  Yes.  I will correct it.
