### ISSUE TITLE
"Pipeline Argument Tab" UI is messed up in new workspace

### ISSUE THREAD

**Issue by lak-proddev** [GoogleCloudPlatform/google-cloud-eclipse#3462]
STEPS:
1. Create a new workspace.
2. Open launch configurations dialog
3. Create a new  "Dataflow Pipeline"  launch configuration.
4. Open the "Pipeline Arguments" tab.
5. UI is messed up. No Runner options and pipeline options.

![image](https://user-images.githubusercontent.com/39690425/59159377-5eda8080-8ae6-11e9-9265-4c67b46b3083.png)

** Not reproducible after launch with a dataflow project.

**Comment by chanseokoh** [comment]
The runner options and pipeline options are dynamically identified and generated based on which Dataflow version is used in a project. They appear only after a Dataflow project is selected in the "Main" tab. Not that this is necessarily the best UI.

**Comment by lak-proddev** [comment]
I agree. But, I believe there should show a dummy panel with a message like "No runner options available. To show more options, You need to select a Dataflow project in the "Main Tab". 
A similar message for "Pipeline options" also.

**Comment by elharo** [comment]
Sounds reasonable. We also need to make sure that this is not shown as an error (as opposed to incomplete), which it looks like now it is. The general UI principle in play is that we should never start a UI in an error state. We violate this in several places.

**Comment by JoeWang1127** [comment]
close as not planned
