### ISSUE TITLE
Google Cloud Dataflow SDK for Java 2.5.0 is deprecated

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3474]
When running the test plan, the cloud console shows this:

Google Cloud Dataflow SDK for Java 2.5.0
This version of the SDK is deprecated and will eventually be no longer supported. Learn more

I suppose we need to revise the archetypes and plugin to use Beam instead.

**Comment by elharo** [comment]
This might be as simple as changing the artifact IDs used here to point to beam-sdks-java-maven-archetypes-examples instead:

```
public enum DataflowProjectArchetype {
  STARTER_POM_WITH_PIPELINE(
      "Starter project with a simple pipeline",
      "google-cloud-dataflow-java-archetypes-starter",
      ImmutableSortedSet.of(MajorVersion.QUALIFIED_TWO, MajorVersion.TWO)),
  EXAMPLES(
      "Example pipelines",
      "google-cloud-dataflow-java-archetypes-examples",
      ImmutableSortedSet.of(MajorVersion.QUALIFIED_TWO, MajorVersion.TWO));
```

or it might require adding new templates.

**Comment by JoeWang1127** [comment]
close as not planned
