### ISSUE TITLE
Convert to Google App Engine project action

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#348]
Probably in a context menu;

Remove old nature and facets; add new facets

**Comment by chanseokoh** [comment]
Looks like we need more discussion, so I guess this won't happen very soon. Some ideas popped up in #1188:

- Moving this to a submenu of _Configure_ seems right. The label _Convert to (Google) App Engine Project..._ seems okay too.
![selection_005](https://cloud.githubusercontent.com/assets/10523105/21780488/cf64c370-d679-11e6-8c33-7fa6dee7e17b.png)
- Perhaps it's a good idea to have a dialog for confirming the conversion, primarily for messaging.
- Removing obsolete natures and facets? (What to remove and how?)
- Move this to a new bundle. This isn't only for GPE-compatibility, so I think a name like `projectconversion` is better suited.

- Anything else?

**Comment by elharo** [comment]
No confirmation please. The user told us to do it. We do it. There are very few truly irrevocable actions where you should ask for confirmation.

I don't think you need paretheses around Google. Just "Convert to Google" App Engine Project" or maybe just "Convert to  App Engine Project" Ellipses only if it brings up a dialog. 

We should remove the natures used by GPE.

**Comment by elharo** [comment]
https://cloud.google.com/eclipse/docs/converting
