### ISSUE TITLE
Deploying first app to a service fails

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3480]
The issue is with

  <service>newqa</service>

when a default app has not yet been deployed ot this project.

Apparently, the first service you upload to a new application must be the 'default' service. Not sure why that's true and there's not a lot we can do about it. However,

1. We should notice if that's what we're about to do and warn the user.

2. The error dialog formatting here is awful. We should do better, probably for a lot of similar messages we get.

(gcloud.app.deploy) INVALID_ARGUMENT: The first service (module) you upload to a new application must be the 'default' service (module). Please upload a version of the 'default' service (module) before uploading a version for the 'newqa' service (module). See the documentation for more information. Python: (https://developers.google.com/appengine/docs/python/modules/#Python_Uploading%%20modules) Java: (https://developers.google.com/appengine/docs/java/modules/#Java_Uploading%%20modules)
- '@type': type.googleapis.com/google.rpc.DebugInfo
  detail: "[ORIGINAL ERROR] generic::invalid_argument: The first service (module)\
    \ you upload to a new application must be the 'default' service (module). Please\
    \ upload a version of the 'default' service (module) before uploading a version\
    \ for the 'newqa' service (module). See the documentation for more information.\
    \ Python: (https://developers.google.com/appengine/docs/python/modules/#Python_Uploading%%20modules)\
    \ Java: (https://developers.google.com/appengine/docs/java/modules/#Java_Uploading%%20modules)\
    \ [google.rpc.error_details_ext] { code: 3 message: \"The first service (module)\
    \ you upload to a new application must be the \\'default\\' service (module).\
    \ Please upload a version of the \\'default\\' service (module) before uploading\
    \ a version for the \\'newqa\\' service (module). See the documentation for more\
    \ information. Python: (https://developers.google.com/appengine/docs/python/modules/#Python_Uploading%%20modules)\
    \ Java: (https://developers.google.com/appengine/docs/java/modules/#Java_Uploading%%20modules)\"\
    \ }"

![image](https://user-images.githubusercontent.com/1005544/59860334-89c99d80-934c-11e9-9ba1-17c72adff1b6.png)

**Comment by sebastianovide** [comment]
hi @elharo , I'm just having the same problem. Any workaround ?

**Comment by chanseokoh** [comment]
@sebastianovide see https://stackoverflow.com/a/26767693/1701388 and https://stackoverflow.com/q/42360790/1701388

For some reason, you first need to have deployed a "default" module in order to be able to deploy other modules. ("module" is previously called "service".)

**Comment by JoeWang1127** [comment]
close as not planned
