### ISSUE TITLE
Version 1.8.1 release 20-june-2019 does not allow debugging

### ISSUE THREAD

**Issue by franciscoreis** [GoogleCloudPlatform/google-cloud-eclipse#3482]
On the Eclipse Debug view there is the line:
"Waiting for vm to connect at port xxxxx..."

Debug is not active so no breakpoints or the stack can be viewed.
Used many versions of Eclipse but the problem seams to lie in 1.8.1 CTE version.

**Comment by franciscoreis** [comment]
On the Eclipse Debug view there is the line:
"Waiting for vm to connect at port xxxxx..."

Debug is not active so no breakpoints or the stack can be viewed.
Used many versions of Eclipse but the problem seams to lie in 1.8.1 CTE version.

**Comment by franciscoreis** [comment]
I'm using Dev App Server in Local Mode (Standard)

**Comment by elharo** [comment]
Took a quick look and I can reproduce this. In my case, Mac, Eclipse 4.8.0, Cloud SDK 249.0.0. I have no immediate hypothesis why this might happen or how to fix it though. The only change we made that goes anywhere near this is the kokoro release process. @briandealwis any ideas?

**Comment by elharo** [comment]
Happens in Maven projects too.

**Comment by franciscoreis** [comment]
No. I was yesterday from 6PM to today 6 AM trying to solve this  (changing
HOSTS file and changing many settings) with no real advance.
This morning I copied from another computer an Eclipse installation that
still has the 1.8.0 plugin. It worked. of course.

Thanks for looking into it. It would be nice if we could access old
versions.

Best regards,
Francisco

**Comment by elharo** [comment]
@franciscoreis could you provide details of Eclipse, OS, and JDK versions where you saw this? Thanks.

**Comment by elharo** [comment]
Updated test plan to check debugging in future.

**Comment by franciscoreis** [comment]
Never worked in Windows 10, Eclipse 2018-9 and 2019-6, JDK/Oracle 177 and
211.

You said the same happens in MacOS so it must me some settings in the CT4E.
In another github issue they talk about java -Xdebug and other arguments.

Hope it helps!

Elliotte Rusty Harold <notifications@github.com> escreveu em sáb,
22/06/2019 às 13:23 :

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/v1.8.1D/plugins/com.google.cloud.tools.eclipse.appengine.localserver/src/com/google/cloud/tools/eclipse/appengine/localserver/server/LocalAppEngineServerLaunchConfigurationDelegate.java#L507

It used to be that `devServerRunConfiguration` was a mutable object which we modified JVM flags, but it became immutable in the newer appengine-plugins-core. This line is ineffective, as it doesn't do anything about the `devServerRunConfiguration` object passed as an argument. The change is effective only locally in the method.

**Comment by briandealwis** [comment]
I think the easiest fix is for `setupDebugTarget()` to return the revised `RunConfiguration`.

**Comment by franciscoreis** [comment]
Thanks for the effort. I guess, then, there will be another version of CT4E
soon with the fix.

**Comment by chanseokoh** [comment]
1.8.2 with the fix is released and live.

**Comment by franciscoreis** [comment]
Great, that was fast, thanks a lot!
