### ISSUE TITLE
Simplify RunConfiguration configuration logic in LocalAppEngineServerLaunchConfigurationDelegate

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3491]
We shouldn't need to turn a `RunConfiguration` to a `RunConfiguration.Builder` to be turned back into a `RunConfiguration` within the same class.

Context: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3485

**Comment by JoeWang1127** [comment]
close as not planned
