### ISSUE TITLE
Dataflow run configuration shows "[Pipeline Arguments]: No Google account selected for this launch" error initially

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#3496]
Our test plan says

> 8. _Run_ > _Run Configurations_.... Select _Dataflow Pipeline_ and click the new icon to create a new run configuration.
>
> 9. In the _Main_ tab, select the project you created. Select or enter `com.example.StarterPipeline` in _Main class:_.
>
> 10. Click _Run_. Verify the _Console_ window shows `INFO: WORLD` and `INFO: HELLO`.

After (9), the dialog shows the error "[Pipeline Arguments]: No Google account selected for this launch", which I think is a false alarm. The _Run_ button becomes active. The error goes away as soon as I switch to the `Pipeline Arguments` tab, or close and reopen the dialog, or switch to a different run configuration and come back.

**Comment by elharo** [comment]
Did you do step 4? Select an Account:.

**Comment by chanseokoh** [comment]
I did. I tried reproducing this multiple times in various ways, and I can certainly reproduce this.

**Comment by JoeWang1127** [comment]
close as not planned
