### ISSUE TITLE
There are no projects in your workspace. Create an App Engine Project

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3497]
We should be able to include our new project wizards here in the Project Explorer:

![image](https://user-images.githubusercontent.com/1005544/60132252-233be980-9769-11e9-8ec7-225306610a44.png)

**Comment by lak-proddev** [comment]
We already have these shortcuts in the project explorer and package explorer.
**Google Cloud Tools for Eclipse
Version: 1.8.2.201906242031**

![image](https://user-images.githubusercontent.com/39690425/60205466-e1956680-986e-11e9-9f1a-5753115c550e.png)

**Comment by elharo** [comment]
Hmm, so why didn't I see them?

Also, looks like it should be "Create an..." instead of "Creates an..."

**Comment by lak-proddev** [comment]
It's a new feature of eclipse version v4.11 (2019-03).
https://www.eclipse.org/eclipse/news/4.11/platform.php#onboarding-text
Dev target platform is a v4.8.which doesn't include this feature.

**Comment by lak-proddev** [comment]
"Dataflow" project is not showing in **New**  menu. Is it by design ?
![image](https://user-images.githubusercontent.com/39690425/60236074-a5dabb00-98c7-11e9-8267-63841d8c0d37.png)

**Comment by elharo** [comment]
Yes, this is only in 4.11 and later but I don't think that's it. That would explain why nothing shows up, not why the GCP wizards specifically don't show up.

**Comment by lak-proddev** [comment]
Ha right. What is your target platform? Where can I find it?

**Comment by chanseokoh** [comment]
Could it be that Eclipse dynamically decides which wizards to show based on, for example, usage history or recency?

**Comment by lak-proddev** [comment]
> Could it be that Eclipse dynamically decides which wizards to show based on, for example, usage history or recency?

https://git.eclipse.org/c/platform/eclipse.platform.ui.git/plain/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/internal/views/helpers/EmptyWorkspaceHelper.java
#readProjectWizardActions()

As I can see that It should show all the wizard shortcuts without any filters.

**Comment by lak-proddev** [comment]
> Hmm, so why didn't I see them?
Seems to be a bug for old workspaces. Can you try in the new workspace?

**Comment by elharo** [comment]
fixed in 4.11
