### ISSUE TITLE
New app engine Maven project with library double spaces

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3510]
This only happens when adding a library such as Endpoints to the new project:`

```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
      
    <modelVersion>4.0.0</modelVersion>
      
    <packaging>war</packaging>
      
    <version>0.1.0-SNAPSHOT</version>
      
    <groupId>ep</groupId>
      
    <artifactId>test</artifactId>
      
    <properties>
            
```

**Comment by elharo** [comment]
It also overindents, four spaces instead of two. Something is reformatting the code along this code path.

**Comment by lak-proddev** [comment]
Spaces issue can be easily fixed once this commit is merged. https://github.com/lak-proddev/google-cloud-eclipse/commit/e59d265891b54bc7398bdbd3c17af08a7c071c58
We can use the utility method to fix the issue.
 @elharo  Can you provide detail steps?

**Comment by elharo** [comment]
This shouldn't require extra fixup It didn't use to happen, so something changed to add the spaces (more likely to reformat the whole file). That's what we need to fix.

**Comment by elharo** [comment]
And now I'm not seeing this.  wonder if it's platform dependent? This is the sort of thing that might only happen on Mac or Windows depending on local linebreak conventions.

**Comment by diego92sigma6** [comment]
Closing as non reproducible - please feel free to reopen if it happens again
