### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Mathanagopal97** [GoogleCloudPlatform/google-cloud-eclipse#3514]
- Cloud Tools for Eclipse version: 1.8.0.201901101851
- Google Cloud SDK version: 250.0.0 (non-managed)
- Eclipse version: 4.12.0.v20190605-1800
- OS: Windows 10 10.0
- Java version: 12.0.1

**I tried to run the app on app-engine**

**Expected - A working app**

**Reality - Server unable to start**

![image](https://user-images.githubusercontent.com/29875835/62845547-7ac8f100-bce6-11e9-8ee7-e64d9552dd1b.png)

Stacktrace
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.appengine.tools.development.StreamHandlerFactory (file:/C:/Users/HP/AppData/Local/Google/Cloud%20SDK/google-cloud-sdk/platform/google_appengine/google/appengine/tools/java/lib/impl/appengine-local-runtime.jar) to method java.net.URL.getURLStreamHandler(java.lang.String)
WARNING: Please consider reporting this to the maintainers of com.google.appengine.tools.development.StreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Aug 12, 2019 9:49:03 AM com.google.appengine.tools.development.SystemPropertiesManager setSystemProperties
INFO: Overwriting system property key 'java.util.logging.config.file', value 'C:\Users\HP\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\google_appengine\google\appengine\tools\java\config\sdk\logging.properties' with value 'WEB-INF/logging.properties' from 'D:\Mathan\Eclipse Workspace For AppEngine\.metadata\.plugins\org.eclipse.wst.server.core\tmp2\DummyProject\WEB-INF\appengine-web.xml'
java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at java.base/java.util.Properties.put(Properties.java:1316)
	at java.base/java.util.Collections$CheckedMap.put(Collections.java:3636)
	at com.google.appengine.tools.development.SharedMain.setTimeZone(SharedMain.java:219)
	at com.google.appengine.tools.development.SharedMain.postServerActions(SharedMain.java:188)
	at com.google.appengine.tools.development.DevAppServerMain$StartAction.apply(DevAppServerMain.java:398)
	at com.google.appengine.tools.util.Parser$ParseResult.applyArgs(Parser.java:45)
	at com.google.appengine.tools.development.DevAppServerMain.run(DevAppServerMain.java:257)
	at com.google.appengine.tools.development.DevAppServerMain.main(DevAppServerMain.java:248)

**Comment by elharo** [comment]
From the stack trace (very helpful, thanks) my first guess is that this is an issue in the App Engine Java SDK, specifically the devappserver,  when run with Java 11. Things ot check to help narrow it down:

1. Can you try running with Java 8 instead?
2. Update gcloud to 257.0
3. Try running the devappserver from the command line.

If you let us know what happens with each of those, that can narrow down the problem. Thanks.

**Comment by Mathanagopal97** [comment]
Hi, thanks for the response. I actually have an another eclipse work space where the app runs perfectly. But in an new repository and when I try to run the basic app I'm getting the same error. I am attaching the preferences file along with this comment. 

P.S. I ave installed the latest version of gcloud, I was using Java 8 and still I am not able to run the app in an new work space.
Entire prefences - [Eclipse Workspace Prefs.zip](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/3555461/Eclipse.Workspace.Prefs.zip)
The preferences file - [preferences.zip](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/files/3555440/preferences.zip)
Java version - 
![image](https://user-images.githubusercontent.com/29875835/63939011-d5eb3980-ca83-11e9-9ed8-42c5177c75e3.png)
Gcloud vresion - 
![image](https://user-images.githubusercontent.com/29875835/63939106-121e9a00-ca84-11e9-8dac-69e89562a6b4.png)
Installed gcloud components - 
![image](https://user-images.githubusercontent.com/29875835/63939073-fc10d980-ca83-11e9-8c99-6ea886c34863.png)

Please help me understand what I have done and what I should have done. Thanks in advance.

**Comment by chanseokoh** [comment]
> WARNING: An illegal reflective access operation has occurred

This shows that you are using a Java 9+ JRE to run the dev appsever, not Java 8. I believe the [dev appserver doesn't support Java > 8](https://issuetracker.google.com/issues/65200034#comment40). Please use Java 8 JVM as mentioned in the issue tracker.

> Java version: 12.0.1

You already mentioned that the Java version is 12. From the screenshot above, I see you do have Java 8 installed in your machine, but it's obvious it is not being used to run the dev appserver. Check your JDK/JRE settings of your workspace as well as the project settings.

**Comment by Mathanagopal97** [comment]
I imported the preferences from the work space that is working fine. Thanks for the assistance.
