### ISSUE TITLE
 error installing google sdk

### ISSUE THREAD

**Issue by freytefaby** [GoogleCloudPlatform/google-cloud-eclipse#3515]
- Cloud Tools for Eclipse version: 1.8.2.201906242031
- Google Cloud SDK version: 260.0.0 (auto-managed)
- Eclipse version: 4.12.0.v20190605-1800
- OS: Windows 10 10.0
- Java version: 1.8.0_221

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

This will install all the core command line tools necessary for working with
the Google Cloud Platform.

```
Traceback (most recent call last):
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\\bin\bootstrapping\install.py", line 222, in <module>
    main()
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\\bin\bootstrapping\install.py", line 200, in main
    Install(pargs.override_components, pargs.additional_components)
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\\bin\bootstrapping\install.py", line 141, in Install
    InstallOrUpdateComponents(to_install, update=update)
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\\bin\bootstrapping\install.py", line 184, in InstallOrUpdateComponents
    ['--quiet', 'components', verb, '--allow-no-backup'] + component_ids)
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\lib\googlecloudsdk\calliope\cli.py", line 1009, in Execute
    self._HandleAllErrors(exc, command_path_string, specified_arg_names)
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\lib\googlecloudsdk\calliope\cli.py", line 1042, in _HandleAllErrors
    exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\lib\googlecloudsdk\calliope\exceptions.py", line 512, in HandleError
    known_exc, print_error = ConvertKnownError(exc)
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\lib\googlecloudsdk\calliope\exceptions.py", line 494, in ConvertKnownError
    new_exc = known_err(exc)
  File "C:\Users\tmjback\AppData\Local\Google\ct4j-cloud-sdk\LATEST\google-cloud-sdk\lib\googlecloudsdk\core\exceptions.py", line 108, in __init__
    'reach.'.format(message=message))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 41: ordinal not in range(128)
```

**Comment by chanseokoh** [comment]
Hi @freytefaby,

This is a [known issue](https://issuetracker.google.com/80344082) on the Cloud SDK side and unrelated to CT4E. Please track the bug on the issue tracker and update there if necessary.

**Comment by freytefaby** [comment]
That was fixed, now please help me with this new error when I run the gcloud components install app-engine-java command, I get the following error:
WARNING: This is a PUBLIC issue tracker, and as such, anybody can read the
information in the report you file. In order to help diagnose the issue,
we've included some installation information in this report. Please look
through and redact any information you consider personal or sensitive
before submitting this issue.

Issue running command [gcloud components install].

What steps will reproduce the problem?


What is the expected output? What do you see instead?


Please provide any additional information below.


Trace:
gcloud_main.py:187
 gcloud_cli.Execute()
calliope\cli.py:1009
 self._HandleAllErrors(exc, command_path_string, specified_arg_names)
calliope\cli.py:1042
 exceptions.HandleError(exc, command_path_string, self.__known_error_handler)
calliope\exceptions.py:512
 known_exc, print_error = ConvertKnownError(exc)
calliope\exceptions.py:494
 new_exc = known_err(exc)
core\exceptions.py:108
 'reach.'.format(message=message))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 41: ordinal not in range(128)


Installation information:

Google Cloud SDK [259.0.0]

Platform: [Windows, x86_64] ('Windows', 'DESKTOP-QLJAMQ2', '8', '6.2.9200', 'AMD64', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
Locale: ('es_CO', 'cp1252')
Python Version: [2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)]]
Python Location: [C:\Python27\python.exe]
Site Packages: [Disabled]

Installation Root: [${HOME}\Downloads\googlesdk\google-cloud-sdk]
Installed Components:
  core: [2019.08.16]
  beta: [2019.05.17]
  gsutil: [4.42]
  cloud-datastore-emulator: [2.1.0]
  alpha: [2019.05.17]
  bq: [2.0.46]
System PATH: [${HOME}\Downloads\googlesdk\google-cloud-sdk\bin\sdk;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\WINDOWS\system32,C:\Program Files\Java\jdk1.8.0_221\bin;${HOME}\Downloads\googlesdk\google-cloud-sdk\bin;${HOME}\AppData\Local\Microsoft\WindowsApps]
Python PATH: [${HOME}\Downloads\googlesdk\google-cloud-sdk\lib\third_party;${HOME}\Downloads\googlesdk\google-cloud-sdk\lib;C:\Windows\SYSTEM32\python27.zip;C:\Python27\DLLs;C:\Python27\lib;C:\Python27\lib\plat-win;C:\Python27\lib\lib-tk;C:\Python27]
Cloud SDK on PATH: [False]
Kubectl on PATH: [False]

Installation Properties: [${HOME}\Downloads\googlesdk\google-cloud-sdk\properties]
User Config Directory: [${CLOUDSDK_CONFIG}]
Active Configuration Name: [default]
Active Configuration Path: [${CLOUDSDK_CONFIG}\configurations\config_default]

Account: [m..y@g..m]
Project: [t..k]

Current Properties:
  [core]
    project: [t..k]
    account: [m..y@g..m]
    disable_usage_reporting: [True]
  [compute]
    region: [us-east1]
    zone: [us-east1-b]

Logs Directory: [${CLOUDSDK_CONFIG}\logs]
Last Log File: [${CLOUDSDK_CONFIG}\logs\2019.08.29\10.59.21.463000.log]

git: [NOT AVAILABLE]
ssh: [OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
]

**Comment by chanseokoh** [comment]
You pasted a wrong output? The error message is same.

```
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 41: ordinal not in range(128)
```

**Comment by freytefaby** [comment]
[image: image.png]
Friend, installed the most current version of google sdk in a windows
virtual machine, however I still get the same errors, help me

**Comment by chanseokoh** [comment]
@freytefaby I'm afraid you need to follow up on the bug filed against the Cloud SDK: https://issuetracker.google.com/80344082 Our team here on GitHub works on CT4E, and the Cloud SDK team should really look into fixing, this since the bug is coming from the Cloud SDK.

**Comment by chanseokoh** [comment]
The Cloud SDK issue was recently fixed. See https://issuetracker.google.com/80344082
