### ISSUE TITLE
Run As App Engine is not available

### ISSUE THREAD

**Issue by Meister1867** [GoogleCloudPlatform/google-cloud-eclipse#3516]
- Cloud Tools for Eclipse version:
- Google Cloud SDK version: 
- Eclipse version: 
- OS:
- Java version:

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by briandealwis** [comment]
Closing but will reopen if you could please provide some detail.

**Comment by Meister1867** [comment]
apologies, I think I submitted my message before I had a chance to get the information together.  I've attached screen shots and more details in the main message

**Comment by chanseokoh** [comment]
@Meister1867 you are running the dev appserver on Java >= 9. See https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3514#issuecomment-526227991

**Comment by Meister1867** [comment]
> @Meister1867 you are running the dev appserver on Java >= 9. See [#3514 (comment)](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3514#issuecomment-526227991)

You are... right :(

I was reading another post where someone had a similar issue.  I have Java 12 and Java 8 installed, but Eclipse was set to Java 12 in the Preferences.  Once I changed it to point to Java 8, it worked !!!


<img width="684" alt="settings" src="https://user-images.githubusercontent.com/21352398/64563393-4106fc80-d31d-11e9-8555-cc7d4fcee04d.png">


<img width="651" alt="working" src="https://user-images.githubusercontent.com/21352398/64563385-3e0c0c00-d31d-11e9-9b4c-155095e81acc.png">
