### ISSUE TITLE
The plugin does not help how to do a Google App Engine Standard Java11 simple project

### ISSUE THREAD

**Issue by ludoch** [GoogleCloudPlatform/google-cloud-eclipse#3518]
Google App Engine Java11 project should be a valid target by now.

It could  just create a jar maven target, and add a simple 1 liner app.yaml with 

runtime: java11

And hook the Cloud SDK deployment process which exists for the other targerts and should work as is.

Not having such a simple wizard gives the impression that the plugin is not up to date to the latest Google Cloud product targets, or not maintained anymore.

**Comment by elharo** [comment]
Is there a quickstart for Java 11 app engine somewhere to copy from?

**Comment by elharo** [comment]
Java 11 App Engine is still beta. Have we announced a release date?

**Comment by ludoch** [comment]
Soo(days)n

**Comment by ludoch** [comment]
https://cloud.google.com/appengine/docs/standard/java11/

**Comment by elharo** [comment]
https://cloud.google.com/appengine/docs/standard/java11/java-differences has a good basic Jetty app we can use. Lighterweight than the quickstart.

**Comment by ludoch** [comment]
Java11 GAE is GA today.

**Comment by mhopkins-dynactive** [comment]
I am looking into upgraded to Java11 and could not find an easy way to upgrade using my current eclipse/web.xml project. Any news on an easy way to upgrade with the eclipse plugin? As it looks right now, it seems to upgrade we would have to abandon the eclipse plugin. Is this true? Do you guys suggest any specific strategy for upgrading to java11?

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant.
