### ISSUE TITLE
Google cloud SDK installation fails if PostgreSQL 9.6 is already installed

### ISSUE THREAD

**Issue by katsuperu** [GoogleCloudPlatform/google-cloud-eclipse#3529]
If you try to install google cloud SDK bud you have already installed PostgreSQL database installation fails.

Logs:

Output folder: C:\Users\kacpe\AppData\Local\Google\Cloud SDK
Downloading Google Cloud SDK core.
Extracting Google Cloud SDK core.
Create Google Cloud SDK bat file: C:\Users\kacpe\AppData\Local\Google\Cloud SDK\cloud_env.bat
Installing components.
Welcome to the Google Cloud SDK!
  File "C:/Program Files/PostgreSQL/9.6/pgAdmin 4/venv/Lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
  File "C:/Program Files/PostgreSQL/9.6/pgAdmin 4/venv/Lib\site.py", line 177
    file=sys.stderr)
        ^
SyntaxError: invalid syntax
Failed to install.

**Comment by elharo** [comment]
Interesting. Probably a Cloud SDK bug.

**Comment by katsuperu** [comment]
So I need to move this issue to another project ?
Excuse me then I will move it to correct project - it is https://issuetracker.google.com/savedsearches/559662 isn't it?

**Comment by chanseokoh** [comment]
@katsuperu exactly. Also the link for "Create new Cloud SDK issue" is listed in https://cloud.google.com/support/docs/issue-trackers.

**Comment by katsuperu** [comment]
I already created issue there thanks 🙂
