### ISSUE TITLE
mvn clean doesn't fully clean

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3533]
E.g. eclipse/ide-target-platform/target/targetPlatformRepository/content.xml

is not removed by `mvn clean`

**Comment by chanseokoh** [comment]
`mvn -Pide-target-platform clean` will clean it, so maybe it's the matter of `mvn clean` to activate the `ide-target-platform` profile or include the `eclipse/ide-target-platform` module somehow.

**Comment by briandealwis** [comment]
Aha, `eclipse/ide-target-platform` is only included with the `ide-target-platform` profile.  So `mvn -Pide-target-platform clean` should work.

**Comment by chanseokoh** [comment]
I noticed you should go into the `eclipse` directory first. `cd eclipse && mvn -Pide-target-platform clean`.

**Comment by briandealwis** [comment]
It's odd as the root [.gitignore](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/12c7c6335ae02a9901e6de43c0e82cb38d95bc49/.gitignore#L4) should cause `target/` to be ignored.
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/12c7c6335ae02a9901e6de43c0e82cb38d95bc49/.gitignore#L4

**Comment by elharo** [comment]
Can we configure the root pom.xml so that `mvn clean` also runs `mvn -Pide-target-platform clean`?

**Comment by briandealwis** [comment]
Not that I'm aware of.

**Comment by JoeWang1127** [comment]
close as obsolete
