### ISSUE TITLE
Two Eclipse license agreements on plugin install

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3548]
One from 2017, on form 2014

![image](https://user-images.githubusercontent.com/1005544/69181857-e688da00-0add-11ea-956d-0e107b975469.png)

**Comment by chanseokoh** [comment]
This may not be our issue. Today I ran "Check for Updates" and I've seen ~6 licenses with the same name. It may be that the Eclipse platform is just populating every licence of the plugins being installed/updated.

**Comment by briandealwis** [comment]
This isn't our problem.  There were [errors in earlier versions of the `org.eclipse.license` feature](https://bugs.eclipse.org/bugs/show_bug.cgi?id=537927) and so new versions were released (2.0.1 and 2.0.2). So you're seeing features that reference different versions of the license feature, and so they are shown as distinct entries.
