### ISSUE TITLE
Project errors

### ISSUE THREAD

**Issue by masciadri** [GoogleCloudPlatform/google-cloud-eclipse#3556]
- Cloud Tools for Eclipse version: 1.8.2.201906242031
- Google Cloud SDK version: 272.0.0 (non-managed)
- Eclipse version: 4.13.0.v20190916-1045
- OS: Windows 10 10.0
- Java version: 1.8.0_231

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by chanseokoh** [comment]
Not reproducible and no details.
