### ISSUE TITLE
Error "Project is not enabled for Cloud Dataflow"

### ISSUE THREAD

**Issue by SMukherjee4** [GoogleCloudPlatform/google-cloud-eclipse#3584]
- Cloud Tools for Eclipse version:  
Google Cloud Tools for Eclipse
Version: 1.8.2.201906242031

- Google Cloud SDK version: 
Google Cloud SDK 272.0.0
core 2019.11.16
- Eclipse version: 
- OS: win 10
- Java version: 1.8

**What did you do?**
I am trying to create a Google Cloud Dataflow Project but  once I provide my Account & selected the GCP Project its says 

"Verifying that project is enabled for dataflow..." for few sec and getting the below error

"Project is not enabled for Cloud Dataflow"

![image](https://user-images.githubusercontent.com/22317436/70862380-a2181f00-1f61-11ea-8d57-16f71e0bd879.png)

I have tried to enable the API as mentioned in the below doc 

https://cloud.google.com/eclipse/docs/quickstart-dataflow

in Point #3, but didn't work. 

Can anyone guide if i am missing something

**Comment by elharo** [comment]
This is definitely an issue with the server, probably how the individual project is configured. You're looking in the right place, but I don't have access to see exactly what might be missing.
