### ISSUE TITLE
I cant see the option for creating maven google app java project 

### ISSUE THREAD

**Issue by dotun-ogundare** [GoogleCloudPlatform/google-cloud-eclipse#3586]
Hello,

I just configured the google app engine on my STS IDE. But I am not able to create a maven project. I didn't see option for create maven google app java project. I only saw the following options under create new project tab: 

Google app engine standard java project 
Google app engine flexible java project 
Google cloud dataflow java project

![maven missing](https://user-images.githubusercontent.com/50335434/71493641-a0dbd180-2840-11ea-92c5-a6d43b70fee8.png)

**Comment by chanseokoh** [comment]
Click on "Google App Engine Standard/Flexible Java Project" to open the wizard. The first wizard page has a checkbox option to create a Maven project.
