### ISSUE TITLE
But all GCP that exists where is in gcp tools? I can't create cloud function, cloud run, cloud athos,....

### ISSUE THREAD

**Issue by vincenzo-mazzotta** [GoogleCloudPlatform/google-cloud-eclipse#3615]
- Cloud Tools for Eclipse version: 1.8.4.202002191941
- Google Cloud SDK version: 286.0.0 (auto-managed)
- Eclipse version: 4.14.0.v20191210-0610
- OS: Windows 10 10.0
- Java version: 13.0.2

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by elharo** [comment]
Point taken
