### ISSUE TITLE
No projects found when deploying to App Engine Standard

### ISSUE THREAD

**Issue by bashoogzaad** [GoogleCloudPlatform/google-cloud-eclipse#3616]
- Cloud Tools for Eclipse version: 1.8.3
- Google Cloud SDK version: 253.0.0
- Eclipse version: 4.12.0
- OS: 10.14.6
- Java version: 8

**What did you do?**
Deploying new code to App Engine Standard just like always

**What did you expect to see?**
My projects and then choose one to upload to.

**What did you see instead?**
No projects found and the following error:

An error occurred while retrieving projects: com.google.api.client.googleapis.json.GoogleJsonResponseException: 500 Internal Server Error
{
  "code" : 500,
  "errors" : [ {
    "domain" : "global",
    "message" : "Internal error encountered.",
    "reason" : "backendError"
  } ],
  "message" : "Internal error encountered.",
  "status" : "INTERNAL"
}

**Comment by elharo** [comment]
That's an issue in App Engine, not  CT4E. It is a bug, it is not the fault of your code, and that, I'm afraid, is as much as I know. It can't be fixed in CT4E. If you have a support contract, try filing a ticket against App Engine.
