### ISSUE TITLE
Dataflow projects will not run in Java project in Eclipse - Classloader fails 

### ISSUE THREAD

**Issue by ckangai** [GoogleCloudPlatform/google-cloud-eclipse#3620]
- Cloud Tools for Eclipse version:    1.8.4.202002191941
- Google Cloud SDK version:    297.0.1
- Eclipse version:  Platform: 4.16.0.v20200604-0951
- OS:  Windows 10 
- Java version:  14.0.1

**What did you do?**  
I used this page to install Google Tools for Eclipse and tried to run the WordCount example after following the instructions to create a Dataflow project: https://cloud.google.com/eclipse/docs/quickstart
**What did you expect to see?**
I expected to see a Dataflow job 

**What did you see instead?**
Error message, here is the screenshot:
![image](https://user-images.githubusercontent.com/13393198/85132081-fca37800-b22f-11ea-93a0-9f43d9c7e279.png)

**Comment by chanseokoh** [comment]
@elharo hmm... does the Dataflow version we put support Java 14?

**Comment by elharo** [comment]
We don't specifically not support it, but I woudln't be at al surprised if the dataflow SDK is doing something that doesn't work in java 14.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
