### ISSUE TITLE
Unclear error message when deploying to a GCP project that does not have an App Engine app

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#3627]
![image](https://user-images.githubusercontent.com/1005544/95589834-50baae00-0a13-11eb-8c5a-0cef5a13ed2a.png)

related to internal docs bug b/62873043

**Comment by elharo** [comment]
```
An error occurred while retrieving projects: com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error" : "invalid_grant",
  "error_description" : "Bad Request"
}
com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error" : "invalid_grant",
  "error_description" : "Bad Request"
}
```

**Comment by elharo** [comment]
Hmm, problem is real but might not be caused by what I thought it was. The fix was not creating an app engine application in the project. rather I needed to sign out in Eclipse and login again. Whatever the root cause is, we should understand it and provide better guidance to the end user.

**Comment by henry0801** [comment]
Thank you very much for the anwser of the problem which i have faced too

**Comment by mpeddada1** [comment]
Thank for helping with unblocking the issue @elharo! @henry0801 We are glad you found this useful.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant

**Comment by elharo** [comment]
Again, this is still relevant and pretty important.

**Comment by diegomarquezp** [comment]
Closing as not planned. GAE with Java 8 runtime is not supported anymore.
