### ISSUE TITLE
server error

### ISSUE THREAD

**Issue by mujang** [GoogleCloudPlatform/google-cloud-eclipse#3628]
- Cloud Tools for Eclipse version: 1.8.4.202002191941
- Google Cloud SDK version: 313.0.1 (non-managed)
- Eclipse version: 4.17.0.v20200902-1800
- OS: Windows 10 10.0
- Java version: 14.0.2

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by elharo** [comment]
not enough info here to reproduce
