### ISSUE TITLE
Creater index fail on GAE(JAVA)

### ISSUE THREAD

**Issue by riyalab** [GoogleCloudPlatform/google-cloud-eclipse#3631]
- Cloud Tools for Eclipse version: 1.8.4.202002191941
- Google Cloud SDK version: 222.0.0 (non-managed)
- Eclipse version: 4.9.0.v20180906-0745
- OS: Mac OS X 10.15.7
- Java version: 1.8.0_191

**What did you do?**
Deploy a new java project to gae(Standard).
**What did you expect to see?**
Datastore indexes create successfully. 

**What did you see instead?**
Some indexes create fail(Status is [Indexing] always).

![Screen Shot 2020-11-20 at 08 45 26](https://user-images.githubusercontent.com/44351446/99741724-dea6b000-2b0c-11eb-92e1-9eedf388f125.png)

**Comment by chanseokoh** [comment]
Are they still stuck? I found [this doc](https://cloud.google.com/appengine/kb?csw=1#stuck_indexes) and also an [old thread](https://groups.google.com/g/google-appengine/c/ASI7lfGHAKE).

**Comment by riyalab** [comment]
Chanseok:

Thanks for your reply, indexes are still stuck.

But I have solve the problem:

1. Use "gcloud datastore indexes cleanup" to delete the stuck indexes.

2. Recreate deleted indexes by "gloud datastore indexes create".

YL Hsu

>

**Comment by chanseokoh** [comment]
Thanks for sharing your solution. I'll close the bug. This issue is independent of the Eclipse plugin anyway.
