### ISSUE TITLE
Server App Engine Standard at localhost failed to start.

### ISSUE THREAD

**Issue by Firelytical** [GoogleCloudPlatform/google-cloud-eclipse#3632]
- Cloud Tools for Eclipse version: 1.8.4.202002191941
- Google Cloud SDK version: 319.0.0 (non-managed)
- Eclipse version: 4.17.0.v20200902-1800
- OS: Windows 10 10.0
- Java version: 15.0.1

**What did you do?**

I created defult app and tried to run it to see if it is working.

**What did you expect to see?**

I was expecting to see that the program is working fine.

**What did you see instead?**

Server App Engine Standard at localhost failed to start.

![image](https://user-images.githubusercontent.com/75361725/100849873-0e9e6d80-3494-11eb-879e-71aeaa5e3f7e.png)
![image](https://user-images.githubusercontent.com/75361725/100850069-52917280-3494-11eb-821c-e1dfe0573985.png)

**Comment by briandealwis** [comment]
Hi @firefox1221 — sorry, missed this.  The App Engine local emulator (called the "dev app server") requires a Java 8 VM.  Try installing a Java 8 VM from [AdoptOpenJDK.net](https://adoptopenjdk.net/?variant=openjdk8&jvmVariant=hotspot) or some other provider, and then:
  1. configure that VM in Eclipse's _Preferences > Java > Installed JREs_, and 
  2. configure that VM as the default for `JavaSE-1.8` in _Preferences > Java > Installed JREs > Execution Environments_.

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
