### ISSUE TITLE
Can't sign in to Google to trust Cloud Tools for Eclipse

### ISSUE THREAD

**Issue by tdanard** [GoogleCloudPlatform/google-cloud-eclipse#3633]
Versions:
- Cloud Tools for Eclipse version: 1.8.4.202002191941
- Google Cloud SDK version: 323.0.0 (auto-managed)
- Eclipse version: 4.18.0.v20201202-1800
- OS: Windows 10 10.0
- Java version: 15.0.1

I try to sign in using the Google App Engine "Sign In to Google ...." menu.

The browser opens (Chrome Version 87.0.4280.141 (Official Build) (64-bit)), I log in, I confirm that I trust Cloud Tools for Eclipse, I get the confirmation message in the browser ("Eclipse is now authorized to access your account"), and then Eclipse shows this;

![image](https://user-images.githubusercontent.com/9469240/104788660-6816df00-5758-11eb-97fd-ddf9dbe8ba40.png)

**Comment by elharo** [comment]
I'll take a look. Anything in the Eclipse log abut this?

**Comment by tdanard** [comment]
It's working this morning, without any changes
