### ISSUE TITLE
App Engine flexible sample apps fail to deploy

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3638]
- Cloud Tools for Eclipse version: 1.8.4
- Google Cloud SDK version: 334.0.0
- Eclipse version: 2021‑03
- OS: macOS 11.2.3 for Apple M1
- Java version: 15.0.2

**What did you do?**

1. _Create New Project > Google App Engine Flexible Java Project..._  Reproduced with both native and Maven projects.
2. Right-click on the project and select _Deploy to App Engine Flexible_
3. Deployment fails: `(gcloud.app.deploy) Error Response: [4] Your deployment has failed to become healthy in the alloteted time and therefore was rolled back. If you believe this was an error, try adjusting the 'app_start_timeout_sec' setting in the 'readiness_check' section.`
4. The Maven project fails if I add the `jetty-maven-plugin` and run with `mvn jetty:run`.

And the Maven sample projects had a further error and warning:
  - Error: `There is '1' error in 'javaee_7.xsd'.` pointing to the project's WEB-INF/web.xml
  - Warning: `schema_reference.4: Failed to read schema document 'platform:/plugin/org.eclipse.xsd/cache/www.w3.org/2001/xml.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.` pointing to the project's WEB-INF/web.xml

**What did you expect to see?**

The sample app should deploy and run.

**Comment by diegomarquezp** [comment]
`2021-03` is not supported anymore (before 1.9.1). I could deploy an App Engine flex app on 2021-06/Windows though.

Adding `maven-jetty-plugin` and running `mvn jetty:run` could start a local server.

```
[INFO] Configuring Jetty for project: test4
[INFO] webAppSourceDirectory not set. Defaulting to /usr/local/google/home/diegomarquezp/eclipse-workspace-21/test4/src/main/webapp
[INFO] Reload Mechanic: automatic
[INFO] Classes = /.../eclipse-workspace-21/test4/target/test4-0.1.0-SNAPSHOT/WEB-INF/classes
[INFO] Context path = /
[INFO] Tmp directory = /.../eclipse-workspace-21/test4/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
[INFO] web.xml file = file:/.../eclipse-workspace-21/test4/src/main/webapp/WEB-INF/web.xml
[INFO] Webapp directory = /.../eclipse-workspace-21/test4/src/main/webapp
[INFO] jetty-8.1.16.v20140903
[INFO] No Transaction manager found - if your webapp requires one, please configure one.
[WARNING] !RequestLog
[INFO] Started SelectChannelConnector@0.0.0.0:8080
[INFO] Started Jetty Server

```
