### ISSUE TITLE
Bundle gcloud

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#364]
Not happening anytime soon, but I would like to remove the dependency on a locally installed gcloud SDK. I.e. we should bundle gcloud directly into the plug-in and use that if a more recent one is not available locally.

**Comment by akerekes** [comment]
Will it be downloaded on demand? Like users can install GWT and App Engine SDK from an update site for GPE.

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/246
