### ISSUE TITLE
CTE should open deployed apps on the deployed URL

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#3641]
- Cloud Tools for Eclipse version: 1.8.4
- Google Cloud SDK version: 334.0.0
- Eclipse version: 2021‑03
- OS: macOS 11.2.3 for Apple M1
- Java version: 15.0.2

**What did you do?**

Deployed an App Engine standard app.  The `gcloud` output showed that the app was available as ‘https://xxx.uc.r.appspot.com/hello’ but our browser was opened on ‘https://xxx.appspot.com/hello’ (note the `uc.r` from the [new region ID included in URLs](https://cloud.google.com/appengine/docs/standard/java/how-requests-are-routed#additional_details_about_urls)).

**Comment by lqiu96** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
