### ISSUE TITLE
error after upgrading eclipse

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#3659]
After upgrading eclipse I am getting this error and don't know how to resolve it:

An internal error occurred during: "Initializing Java Tooling".
Cannot invoke "com.google.cloud.tools.eclipse.appengine.libraries.persistence.LibraryClasspathContainerSerializer.loadContainer(org.eclipse.jdt.core.IJavaProject, org.eclipse.core.runtime.IPath)" because "this.serializer" is null

- Cloud Tools for Eclipse version: 1.8.5.202108061424
- Google Cloud SDK version: 366.0.0 (non-managed)
- Eclipse version: 4.22.0.v20211124-1800
- OS: Windows 10 10.0
- Java version: 17

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by craigmit** [comment]
Rolling back to Eclipse 2021-09 fixes it (obviously not ideal).

**Comment by zhumin8** [comment]
@Rob46 and @craigmit, Thank you for reporting and adding extra info, we'll investigate more into this.

**Comment by vbresan** [comment]
Any news or other workaround except rolling back to Eclipse 2021-09?

**Comment by Shawn-in-Tokyo** [comment]
The following worked fine for me: 

Eclipse Version: 2021-12 (4.22) Build id: I20211124-1800
Google Cloud Platform for Eclipse 1.8.5.202108061424 
Google Cloud SDK 368.0.0


If I install Eclipse m2e - Maven support in Eclipse IDE (from the Eclipse Marketplace) then I do get the reported error that ...
An internal error occurred during: "Initializing Java Tooling".
Cannot invoke "com.google.cloud.tools.eclipse.appengine.libraries.persistence.LibraryClasspathContainerSerializer.loadContainer(org.eclipse.jdt.core.IJavaProject, org.eclipse.core.runtime.IPath)" because "this.serializer" is null

**Comment by vbresan** [comment]
Unfortunately I can not uninstall m2e as Google Cloud Platform plugin depends on it. Perhaps GCP is not compatible with the latest version of m2e?

![Clipboard01](https://user-images.githubusercontent.com/288855/149502579-f5b00e50-80c8-4fa3-bee5-55e993b03283.jpg)

**Comment by chanseokoh** [comment]
Please use Eclipse 2021-09 while we are working on #3661. If anyone can help fixing failures in #3661, we'd greatly appreciate it.

**Comment by Shawn-in-Tokyo** [comment]
> Unfortunately I can not uninstall m2e as Google Cloud Platform plugin depends on it. Perhaps GCP is not compatible with the latest version of m2e?
> 
> ![Clipboard01](https://user-images.githubusercontent.com/288855/149502579-f5b00e50-80c8-4fa3-bee5-55e993b03283.jpg)

Eclipse EE 2021-12 will add in M2E 1.19 which is the problem.  An Eclipse install of 2021-12 and then the Google Cloud Platform for Eclipse 1.8.5. will use M2E 1.18.1.20210618-2246 which works fine.  

Then you can install Git, Mylyn, Eclipse Java EE Developer Tools etc to get the EE functionality.  Just don't update M2E.

**Comment by chanseokoh** [comment]
@briandealwis M2E 1.19 causing the failure while 1.18.1 is OK is an integrating report.

**Comment by vbresan** [comment]
I can confirm that the plugin is not working with eclipse 2022-03.

**Comment by diegomarquezp** [comment]
The latest supported version of CT4E is 4.21 (see https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/3681)
