### ISSUE TITLE
can't create GAE java 8 project

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#3660]
I get the following:

!project.creation.failed!
java.lang.NullPointerException

This is a clean install of Eclipse and CT4E. Ideas?

- Cloud Tools for Eclipse version: 1.8.5.202108061424
- Google Cloud SDK version: 366.0.0 (non-managed)
- Eclipse version: 4.22.0.v20211124-1800
- OS: Windows 10 10.0
- Java version: 11.0.12

**Comment by zhumin8** [comment]
Thanks for reporting, we'll look into this. 
At the meantime, this looks like a problem related to the latest Eclipse version 4.22. Perhaps try with an older version of Eclipse like 4.21 (2021-09) as workaround.

**Comment by diegomarquezp** [comment]
Closing as the solution is stated in the README (use up to 4.21)
