### ISSUE TITLE
libraries not available in App Engine

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#3666]
Everything was working fine util I choose Add Library, selected Google Cloud Platform libraries, Next, then I clicked Finish (the selected libraries were already selected... I did not add or remove anything).
![image](https://user-images.githubusercontent.com/25462429/146695178-7fde66a6-3d68-4079-8581-67efe3f0f757.png)

This seemed to take forever with JPA messages seemingly in an infinate loop. Several minutes passed and I quit eclipse and restarted.

Ever since then, when I upload my project to App Engine, the JDBC driver for mariadb isn't available (suspect not on class path).
I've tried everything I can think of to fix this, but its still completely broken.
I've removed the library and added it back, restarted Eclipse, reinstalled Eclipse from scratch, etc.
The library shows on the class path and there are no error messages until I go to use the app on app engine.
here in web-inf/lib
![image](https://user-images.githubusercontent.com/25462429/146695220-fc5c081b-5165-49da-b64d-b38585531b19.png)

Any guidance as to what might have brokenand how to fix would be hugly helpful!!

Thank you!

- Cloud Tools for Eclipse version: 1.8.5.202108061424
- Google Cloud SDK version: 366.0.0 (non-managed)
- Eclipse version: 4.14.0.v20191210-0610
- OS: Windows 10 10.0
- Java version: 1.8.0_311

**Comment by elharo** [comment]
Ate you using Maven or a pure Eclipse project? 

Interesting. Thanks for the report. mariadb is not a Google library or managed by CT4E, which doesn't mean it isn't our problem. It probably is. My first guess is that the logic for managing dependencies in a non-Maven project neglected to consider the case of a library from outside the  list of Google specific dependencies, and is somehow managing to delete or perhaps just not upload it. @chanseokoh @briandealwis either of you have time to look at this?

@Rob46 can you confirm whether you're using Maven or not in this project?

**Comment by Rob46** [comment]
Hi it's a non maven project.
This has been working for years and I update and add non GCP libraries all
the time (once a qtr at least).

The only thing I did different this time was click finish on the panel in
my original posting.

Thankfully I had a full backup of the project folder including the hidden
folders and a restore has it working again.

**Comment by elefeint** [comment]
@Rob46 Any chance you could check if this issue is reproducible by (after taking backup) attempting to follow the same path?

**Comment by zhumin8** [comment]
Closing as part of cleanup. Please re-open if it's still relevant.
