### ISSUE TITLE
Missing app-engine-java components

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#367]
We do not recognize or handle the case where gcloud is installed but the app-engine-java components are not:

If not previously installed, install the app-engine-java components into the gcloud SDK: $ gcloud components install app-engine-java 

They are not installed by default with the gcloud SDK, and need to be installed as an extra step.

**Comment by akerekes** [comment]
Should not installing components  be part of the common-lib?

**Comment by elharo** [comment]
Possibly. If they aren't, though, we at least need to give a better error message on our end.

**Comment by elharo** [comment]
Yes

**Comment by YnR** [comment]
Should also check that the right SDK folder was passed. I gave it the bin, and it failed silently.

**Comment by briandealwis** [comment]
@YnR how did you "give it the bin"?  Via the `GOOGLE_CLOUD_SDK_HOME` env var, or via the _Google Cloud Platform_ preference page?  If the latter, there should have been a warning if the directory didn't validate.

**Comment by elharo** [comment]
Initial check is committed. We should still add a better message telling the user what to do when they hit this. Possibly with a hidden label saying to run

gcloud components install app-engine-java

at command line

**Comment by branflake2267** [comment]
The link to installing the sdk in the preferences dialog is opaque because it doesn't mention App Engine.

**Comment by elharo** [comment]
We only validate the app engine java components when the cloud SDK location is explicitly changed. We don't do this when a project is created.

**Comment by rdayal** [comment]
status on this one?

**Comment by elharo** [comment]
I'm verifying it now. There are a couple more pieces we want to do, but I think we've got enough of this done to remove the beta blocker label if not quite close it out.

**Comment by elharo** [comment]
This isn't quite done--I still want to include better instructions for installing the app-engine-java components on the preferences page--but I think we've got enough of it done that we can take it off the beta blockers list for now. If we find users still have problems because appengine-java-components is not available, we can reprioritize additional notifications.

**Comment by elharo** [comment]
Next steps in this dialog:

1. Consider moving the appengine-java-components missing error message below everything else, rather than replacing the "Google Cloud Tools" title at the top.
2. Add instructions for installing the component to the error message.
3. Make sure the error message fires when the dialog starts up.
4. Make sure the  the error message fires when the location is edited. Right now it fires on Apply, OK, or changing the Usage Statistics preference but *not* immediately when the location is changed. 


![image](https://cloud.githubusercontent.com/assets/1005544/19689044/5689f954-9acc-11e6-9f08-427e99ff4769.png)

**Comment by elharo** [comment]
Basic work done. Any further work on this will be in more specific issues.
