### ISSUE TITLE
Deploy to App Engine Standard dialog doesn't appear 

### ISSUE THREAD

**Issue by udhaya21** [GoogleCloudPlatform/google-cloud-eclipse#3703]
- Cloud Tools for Eclipse version: 1.9.1.202211291623
- Google Cloud SDK version: 411.0.0 (auto-managed)
- Eclipse version: 4.26.0.v20221123-1800
- OS: Mac OS X 13.0.1
- Java version: 17.0.5

**What did you do?**
I've a GAE project. I'm trying to deploy.
**What did you expect to see?**
Deploy Dialog with the list of GAE projects.
**What did you see instead?**
I don't find the dialog.

https://www.dropbox.com/s/i06xvbdrksue8c6/Deploy%20Eclipse.mov?dl=0

**Comment by udhaya21** [comment]
I installed 03-2022 eclipse version and then installed Google Cloud Tools plugin. Then I updated the eclipse version to the latest i.e 12-2022.

**Comment by rickz21** [comment]
The dialog doesn't appear for me either. I was trying in Eclipse 2022-12 but then I saw 
https://marketplace.eclipse.org/content/google-cloud-tools-eclipse  
Which lists in "Additional Details" the supported Eclipse versions. So, now I am trying with 2021-09 (4.21) but I am getting errors in log. No success yet.  What did you see in your log?

**Comment by udhaya21** [comment]
@rickz21 I didn't try in 09-2021 because it is not available for AArch64. You can install eclipse version 03-2022 and then install Google Cloud Tools plugin, as the error appears from 06-2022 version.

**Comment by udhaya21** [comment]
The problem with eclipse version 03-2022 is I'm unable to traverse through the `.java` files.

**Comment by udhaya21** [comment]
[An internal error occurred during: "Requesting Java AST from selection". 'boolean com.ibm.icu.text.UTF16.isSurrogate(char)'](https://stackoverflow.com/questions/74751823/an-internal-error-occurred-during-requesting-java-ast-from-selection-boolea)

**Comment by rickz21** [comment]
I got that error too. But, I am working with JSP only. I didn't need any .java files.  So, I was able to work around that.  
I finally was able to deploy my project to the app engine using  Eclipse  2021-09 (4.21).

**Comment by meltsufin** [comment]
Closing, since this seems to have been resolved.
