### ISSUE TITLE
Unable to install Google Cloud tools for eclipse

### ISSUE THREAD

**Issue by katarya** [GoogleCloudPlatform/google-cloud-eclipse#3705]
I am following the documentation from https://cloud.google.com/eclipse/docs/quickstart
1) Downloaded eclipse 2022-12.
2) Next step "Installing Cloud tools for Eclipse"  ---> It fails. Hence the issue:
This is available on Market place
![Snap24](https://user-images.githubusercontent.com/50753978/207927377-c2be241f-feda-4a8c-a659-6348ffd51d30.png)
This is the message I get when installing:
![Snap26](https://user-images.githubusercontent.com/50753978/207927847-dcf71a8b-4fbd-4d86-bbef-34a9c32e06a2.png)

**Comment by katarya** [comment]
![Snap27](https://user-images.githubusercontent.com/50753978/207928386-34299de3-8f3e-492b-9f70-12bbbd519ad7.png)

**Comment by udhaya21** [comment]
@katarya 
https://stackoverflow.com/questions/73004696/unable-to-install-google-cloud-tool-for-eclipse-ide
Check if this solution works for you

**Comment by diegomarquezp** [comment]
Hi @katarya. CT4E [is supported by Eclipse 4.9 - 4.21](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/c695a2477bd2bb8fc5149570933b806c471345a3/README.md?plain=1#L28). Please consider this besides @udhaya21's suggestion

**Comment by meltsufin** [comment]
Please re-open if you're still having problems installing with Eclipse 4.9-4.21.

**Comment by JAndrassy** [comment]
I installed Eclipse 2021-06. It is 4.20, but it is the latest version running on Java 11 and Java 11 is declared as required.
But the plugin doesn't work. I get
```
!project.creation.failed!: Could not initialize class org.eclipse.jst.j2ee.project.facet.IJ2EEFacetConstants
```
maybe it requires an update to a specific version of the WTP plugin, but I guess every newer version would require Java 17.

In newer versions of Eclipse I have an AppEngine project semi working, but I can't run local server (Unrecognized option: --add-opens) and add libraries (Unhandled event loop exception).
