### ISSUE TITLE
getting error when trying to install CT4E on 2021-09 with java 11

### ISSUE THREAD

**Issue by Rob46** [GoogleCloudPlatform/google-cloud-eclipse#3720]
I installed Eclipse 2021-09 (4.21) with its Java 11 JRE.
I tried both to install CT4E by dragging the Install button from this location:
https://cloud.google.com/eclipse/docs/quickstart
and using the Eclipse Marketplace directly.

Neither worked. In both cases the install starts and then ends with:

`An error occurred while collecting items to be installed
session context was:(profile=C__Users_rober_eclipse_jee-2021-09_eclipse, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
Result of processing steps.
OK
OK
OK
Public key not found for -9147676190077153272.
OK
Result of processing steps.
OK
OK
OK
Public key not found for -9147676190077153272.
OK
Result of processing steps.
OK
OK
OK
Public key not found for 8122282445186051625.
OK
`

Any idea how to get around this?

We are trying to migrate from GAE Java 8 to 11 as a first step.

**Comment by diegomarquezp** [comment]
Confirmed on `4.21`
Using `4.15` goes around this error

**Comment by dangazineu** [comment]
Java 11 support is not planned. Please see https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3710 for alternatives.
