### ISSUE TITLE
invalid app-engine-apis xml element in appengine-web.xml

### ISSUE THREAD

**Issue by emarin** [GoogleCloudPlatform/google-cloud-eclipse#3725]
- Cloud Tools for Eclipse version:1.8.4
- Google Cloud SDK version: 425.0.0
- Eclipse version: 4.23.0 (I am unable to install the google cloud eclipse plugin for versions below this one)
- OS: Ubuntu 22.04
- Java version: openjdk 11.0.18 2023-01-17

The `app-engine-apis` xml element added to an appengine-web.xml is marked as invalid. Xml file is in error and project cannot be deployed.
This element is to be used when migrating to standard java gen2 environment, with legacy bundled services : https://cloud.google.com/appengine/docs/standard/java-gen2/services/access#installing

Error in xml file is : `cvc-complex-type.2.4.a: Invalid content was found starting with element '{"http://appengine.google.com/ns/1.0":app-engine-apis}'
`

**Comment by diegomarquezp** [comment]
Hi @emarin. I tried this on Eclipse 4.15. The `app-engine-apis` is used to enable legacy services in `Java 11/17` applications, but the plugin only supports `Java 8` ([reference](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/3710)), making the xml element to be considered unexpected.
