### ISSUE TITLE
Not able to deploy  JAVA web project on google app engine

### ISSUE THREAD

**Issue by nitinaltered21** [GoogleCloudPlatform/google-cloud-eclipse#3741]
- Cloud Tools for Eclipse version: 1.10.1.202306072020
- Google Cloud SDK version: 437.0.1 (non-managed)
- Eclipse version: 4.28.0.v20230605-0440
- OS: Windows 11 10.0
- Java version: 17.0.7

**What did you do?**

**What did you expect to see?**

**What did you see instead?**

**Comment by alicejli** [comment]
@nitinaltered21 Can you please add some more details / some reproducible code of what you were trying to do?

**Comment by diegomarquezp** [comment]
Hi @nitinaltered21, [the highest supported eclipse version is 4.22](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/79e7672d5d99cfcd7b3e1792e71f69471430d3a6/README.md?plain=1#L28)

**Comment by burkedavison** [comment]
Closing this issue as answered based on supported Eclipse versions.
