### ISSUE TITLE
Add a verification check when a new GAE runtime is created

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#375]
When creating an app-tools-lib-for-java runtime, there is no check that the cloud sdk exists on the system (that we have a valid path to the cloud sdk install). This step is done when the user attempts to run/debug the runtime (check is done CloudSdk.Builder#build).

Should we be calling PathResolver.INSTANCE.getCloudSdkPath() to check that is returns a path when a new runtime is created? If we do this, the user can input the path if we didn't find it or prompt the user to install gcloud if they dont have it.

**Comment by nbashirbello** [comment]
@elharo @briandealwis

**Comment by elharo** [comment]
How would this affect he new project wizard which creates a (possibly invalid) runtime?

**Comment by nbashirbello** [comment]
We could have the check in the new project wizard too. If we cannot resolve the location of the cloud sdk (that is after the path resolver and after prompting the user for the location), the new project creation will fail. My thought is you cannot use the App Engine features without the cloud sdk and user can always create a dynamic web module and install the facet later after they install cloud sdk.

**Comment by briandealwis** [comment]
@nbashirbello use `CloudSdkPrompter` — it does what you're looking for.

**Comment by elharo** [comment]
@nbashirbello Is this now done and/or obsolete?

**Comment by nbashirbello** [comment]
This bug still exists. I will work on it
