### ISSUE TITLE
Allow to configure service name other than those in appengine-web.xml

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#382]
Current deploy to App Engine Standard obtains project ID and version from the appengine-web.xml file. Users might want to be able to specify a different value for any of these or specify a service/module name for deployment.

**Comment by akerekes** [comment]
Note: Service/module name is stored in appengine-web.xml, so it must be handled differently than project ID and version (which we pass to gcloud as command line arguments).

**Comment by patflynn** [comment]
yeah service name is not passed as a flag. it has to be part of the config
file.

**Comment by akerekes** [comment]
Specifying project ID and version is covered by #642 
Specifying service/module needs to be done in the appengine-web.xml thus needs more careful planning (provided it's a useful feature), so for now I'll remove the `beta-blocker` label.

**Comment by elharo** [comment]
I think this is now done, or WAI

**Comment by Motaz-Al-Zoubi** [comment]
why did close the ticket it is a required feature @elharo ?
