### ISSUE TITLE
Allow easy way to provide environment variables for Cloud emulators

### ISSUE THREAD

**Issue by salrashid123** [GoogleCloudPlatform/google-cloud-eclipse#429]
Local emulators for  gcloud-java (https://github.com/GoogleCloudPlatform/gcloud-java)  for datastore  and pubsub sets environment variable in the current shell.

that is, if i run
gcloud beta emulators datastore start
it will set
export DATASTORE_LOCAL_HOST=localhost:8087
and the gcloud-java datastore client will use that to connect locally.

Its not clear how to set that variable in the eclipse tools (i tried setting it in the launch config manually but also saw the following:
![launch_config_tabs](https://cloud.githubusercontent.com/assets/11149054/17065603/9a07a322-4ff7-11e6-808e-0845098dff84.png)

Bonus to find some automagic or easy way to read in these variables without manually adding them in to the runtime every time.   NOTE: I dont' think the dev_appserver allows for dynamic env variables (you need to declare them directly in appengine-web.xml or app.yaml
see:
https://cloud.google.com/appengine/docs/java/config/appref

**Comment by briandealwis** [comment]
_Environment_ tab was removed in #1139 and we didn't have the settings wired up to the devappserver anyways.

**Comment by briandealwis** [comment]
https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/379

**Comment by briandealwis** [comment]
- commit adding environment tab: https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/506
- values can be retrieved by `AbstractJavaLaunchConfigurationDelegate#getEnvironment(configuration)` [source](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/1139#issuecomment-267695952)

**Comment by briandealwis** [comment]
Requires updating to appengine-plugins-core 0.3.2 (#1868).
