### ISSUE TITLE
Rename GoogleLoginService methods

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#455]
Some of the methods do not convey clearly what they are intended to do. E.g. `getCachedActiveCredentials` is basically returns the active user's credential if logged in. Maybe calling it `getActiveLoggedInUserCredential` would be better (although it's slightly more verbose).
Also `getActiveCredential` gets the active logged in user's credential and requests the user to log in case there's no logged in user. Here I don't have a suggestion currently, but I believe we could come up with something more descriptive.

And as a bonus: it would be useful to add a method `isLoggedIn` that returns a boolean by executing `getCachedActiveCredential() != null`. It would help the readability of the code.

**Comment by chanseokoh** [comment]
This issue is no longer relevant, as we don't have the notion of an active account. Closing.
