### ISSUE TITLE
Server launch tabs in launch configuration

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#467]
Figure out which tabs we want to add to AppEngineTabGroup
Possibilities are here:
http://git.eclipse.org/c/jetty/org.eclipse.jetty.wtp.git/tree/org.eclipse.jst.server.jetty.ui/src/org/eclipse/jst/server/jetty/ui/internal/JettyLaunchConfigurationTabGroup.java

**Comment by briandealwis** [comment]
We should have a `dev_appserver` flags page to allow setting:
  - max module instances
  - log level
  - providing the JRE (need to provide to `CloudSdk` somehow to set `JAVA_HOME`?)

Some functionality-related settings (perhaps only shown if we go for finer-grained facets)?
  - SMTP settings
  - datastore settings
  - search index settings
  - mysql/cloudsql settings

**Comment by branflake2267** [comment]
This may be a duplicate or related. https://github.com/GoogleCloudPlatform/cloud-tools-for-eclipse/issues/719

**Comment by elharo** [comment]
It is. Do you have a specific need for an arguments tab?

**Comment by branflake2267** [comment]
I'm interested in where the server is hosting it's bit so I can stick another directory in it. I want to tell the GWT CodeServer to push it's bits to the war output directory.

**Comment by elharo** [comment]
This is really hard to find:

1. Open Servers view
2. Right click on the server to configure
3. Open
4. Open Launch Configuration

http://help.eclipse.org/neon/index.jsp?topic=%2Forg.eclipse.jdt.doc.user%2Ftasks%2Ftasks-java-local-configuration.htm

**Comment by elharo** [comment]
The common tab doesn't appear to actually work. Probably there's other stuff we need to do.

**Comment by elharo** [comment]
The classpath tab also doesn't work as expected out of the box, and I'm not convinced the sourcepath will either.

**Comment by elharo** [comment]
So I think what's going on here with all this is that the various properties set by this tab such as environment variables and console output file apply to the Java program we launch. 

However none of this gets passed along as far as the user's servlet code that's running in the devappserver which is at least one, maybe two processes removed from what eclipse launches.

**Comment by chanseokoh** [comment]
> This is really hard to find:
> 
> Open Servers view
> Right click on the server to configure
> Open
> Open Launch Configuration

FYI, another way is _Run_  > _Run Configuration_ or _Debug_ > _Debug Configuration_.

![selection_001](https://cloud.githubusercontent.com/assets/10523105/21270843/5fae9732-c386-11e6-8287-e8ddc29a17d1.png)
