### ISSUE TITLE
JRE Whitelist Problem reports

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#48]
This is the red squiggly lines under classes not supported by the App Engine Standard environment.

**Comment by elharo** [comment]
The canonical list is in java/com/google/apphosting/runtime/security/WhiteList.java
 
Need to figure out if this lives in the open anywhere or if we can open source it.

**Comment by briandealwis** [comment]
https://cloud.google.com/appengine/docs/java/jrewhitelist

**Comment by rdayal** [comment]
I'm taking the high-priority label off of this.

**Comment by elharo** [comment]
No longer releavant in Java 8 runtime
