### ISSUE TITLE
Empty run configuration pane

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#481]
![empty_run_config_pane](https://cloud.githubusercontent.com/assets/10523105/17259547/0a963b24-559a-11e6-9841-8fd310318ab3.png)

However, if you resize the dialog, it will show the contents, so it could be a matter of not refreshing the tab.

Steps to reproduce:
1. Clear any existing App Engine Standard run configurations
2. Do "Run on Server..." (or "Debug")
   - This will automatically create a new launch config called "App Engine Standard at localhost".
3. Open the Run Configurations dialog with "Run Configurations..." (or "Debug")
   - "App Engine Standard at localhost" created in Step 2 is auto-selected, and the tab is empty. (If something else is auto-selected, then you must have run that before Step 3. Follow the steps precisely.)

**Comment by chanseokoh** [comment]
This is so weird. Adding a `CommonTab` in `AppEngineTabGroup.createTabs()` prevents this issue:

```java
  @Override
  public void createTabs(ILaunchConfigurationDialog dialog, String mode) {
    ILaunchConfigurationTab[] tabs = new ILaunchConfigurationTab[3];
    tabs[0] = new ServerLaunchConfigurationTab(SERVER_TYPE_IDS);
    tabs[0].setLaunchConfigurationDialog(dialog);
    tabs[1] = new EnvironmentTab();
    tabs[1].setLaunchConfigurationDialog(dialog);
    tabs[2] = new CommonTab();
    tabs[2].setLaunchConfigurationDialog(dialog);
    setTabs(tabs);
  }
```

Still, I cannot think of any good reason why we hit this bug. This feels like a bug of the underlying framework.

**Comment by briandealwis** [comment]
Are there any exceptions logged?

**Comment by chanseokoh** [comment]
No exception is being logged. Adding the third _common_ tab seems like a workaround, if doing so is acceptable or reasonable. The fact that this workaround prevents the bug is a mystery.

**Comment by chanseokoh** [comment]
I duplicated the `CommonTab` code and started stripping out its code until it hits this bug. The reason that the presence of the `CommonTab` prevents this bug was that it schedules an update job by calling this function:

`AbstractLaunchConfigurationTab.scheduleUpdateJob()`

As such, I think this is actually an Eclipse bug. Calling this function from one of the tabs fixes this bug. I'll create a PR shortly.

**Comment by elharo** [comment]
Have you filed a bug on Eclipse? We should, and perhaps send them a patch.

**Comment by chanseokoh** [comment]
I just created a new eclipse.org account to report this bug, but seems like I have to wait for a few days before the account is activated. I'll follow up.

**Comment by briandealwis** [comment]
It looks like bugs [470870](https://bugs.eclipse.org/bugs/show_bug.cgi?id=470870) and [476823](https://bugs.eclipse.org/bugs/show_bug.cgi?id=476823) which are specific to GTK3.  @chanseokoh confirmed that the problems disappear when running with `SWT_GTK3=0` in his environment, forcing SWT to use GTK2.  He further confirmed that he is running Ubuntu 14.04 which has a known old and broken version of GTK3.

That said, the `scheduleUpdateJob()` workaround doesn't hurt.  But Ubuntu 14.04 users using GTK3 (which is out of our control) will likely see similar rendering issues on other tabs.
