### ISSUE TITLE
Enhanced UI for login: show avatar images and account names

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#488]
Changing icons, showing emails and avatars, showing more information such as projects, showing a list of added accounts, etc.

**Comment by chanseokoh** [comment]
I'm thinking of adding `ImageStore` (`ImageCache`, `ImageRepository`, or whatever) to fetch pictures (in a background job) and keep them in-memory. This will be kind of a util class, which can be completely independent of login stuff. Should be a single instance, so I guess it's better to define it as an OSGi service? @briandealwis

**Comment by briandealwis** [comment]
Please don't define a global image cache; it's almost never going to be needed. It's particularly bad on Windows where UI resources are at a premium.  You could use a JFace `ImageRegistry`.
