### ISSUE TITLE
Use proper source hierarchy when creating maven and non-maven GAE projects

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#490]
When creating GAE projects, the source hierarchy is src/main/java for both maven and non-maven projects. Non-maven projects should just be src.

The proper src folder should be used when configuring and installing the Java 1.7 facet

**Comment by elharo** [comment]
search for 
TODO use "src/main/java" for only maven projects
in AppEngineStandardFacet
