### ISSUE TITLE
Preserve screenshots and test outputs from Travis

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#501]
It would be useful to upload the test outputs from the Travis build to somewhere.  These outputs include things like screenshots of failed SWTBot tests and surefire test reports.

*Update*
  - build artifacts now available at `http://console.cloud.google.com/storage/browser/travis_artifacts/travis` (for team members), and includes test logs and SWTBot screenshots (when generated)
  - on successful builds, p2 repository accessible at: `https://storage.googleapis.com/travis_artifacts/travis/NNNN/repository` where NNNN is the Travis Build ID

**Comment by elharo** [comment]
Probably send to Google Cloud Storage with gsutil

**Comment by briandealwis** [comment]
A few notes:
  1. we can use a service-account and `gsutil` to copy files up; the downside is that gs-util doesn't preserve the relative path.  So something like the following merges all screenshots into a single `screenshots` directory and all surefire-reports into a single `surefire-reports`, which works since the files are uniquely named:
    ```
    find plugins \( -name screenshots -o -name surefire-reports \) -print \
        | gsutil -m cp -r -I gs://bucket/build-id
    ```
   I've pushed a branch that does this to https://github.com/GoogleCloudPlatform/google-cloud-eclipse/tree/i501-upload2gcs.  That uses a bucket I created (and can reassign etc.).

  2. Travis supports [deploying files to GCS](https://docs.travis-ci.com/user/deployment/gcs/).  I haven't explored this approach yet.

**Comment by briandealwis** [comment]
Some notes on Travis:
  - [the environment variables available](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables)
  - [the `deploy` steps do not occur on failed builds](https://stackoverflow.com/a/39056573)
  - the build is run from the main directory of the git checkout
  - `openssl` and `rsync` are available

**Comment by briandealwis** [comment]
Once #2673 is committed, remaining work:
- [ ] Configure the storage bucket as described in `.travisci/README.md` in _ Configuring Auto-Deletion for the GCS Bucket_.
- [ ] Create service account for Travis for destination project with _Storage Object Creator_ role as described in `.travisci/README.md` in _Configuring the Service Account Key_.
- [ ] Update `.travis.yml` to:
   - change `GCS_BUILD_BUCKET` in `.travis.yml` to point to storage bucket
   - decrypt service account key (the `openssl` command in `after_script`)
   - re-enable `gsutil cp` commands (commented out with `###`)
