### ISSUE TITLE
Create custom Eclipse expression to test if a project is for App Engine

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#509]
A common expression that would check if a project is App Engine Standard or Flex (or none of them) could be used in extension point enablement. Testing for Standard is rather straightforward by checking for the presence of the facet, but the case for Flex might be more complicated requiring a custom property tester.

**Comment by akerekes** [comment]
@elharo @briandealwis is this obsolete? We have `com.google.cloud.tools.eclipse.appengine.onlyInGCPProjects` in the `c.g.c.t.e.appengine.deploy.ui` package that will support Flex project via checking for the Flex facet.

**Comment by elharo** [comment]
I expect so. You opened the issue. If you don't need this any more, please close it.
