### ISSUE TITLE
Visible indicator of login. 

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#531]
There should be some obvious indicator to the user of whether they're logged in or not. Maybe the G icon could change in some way to indicate the login state? We need to hash out a visual design for this before we implement.

**Comment by chanseokoh** [comment]
For the moment, we could use the two icons (colored and grayed) from the old GPE.

Ultimately, we will want to show an Google user avatar in place of the icon as proposed in the internal design doc about IDE login. (@nbashirbello pointed me to the doc a while ago.) Our IntelliJ plugin follows this design. (However, we are not exactly following the doc, e.g., we placed the icon at the bottom right.)

**Comment by elharo** [comment]
#488 covers this
