### ISSUE TITLE
UX design for multiaccount login

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#532]

**Comment by chanseokoh** [comment]
@nbashirbello pointed me to an internal design doc about this. I see that our IntelliJ plugin follows the UX design in the doc faithfully. (However, IMHO, the design doc is about personalized IDE experience much like the Chrome login feature, e.g., saving IDE user preferences on cloud, so I think the context is a little bit different.)

**Comment by elharo** [comment]
@chanseokoh This is done, right?
