### ISSUE TITLE
Analytics Tracking for deploy actions

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#536]

**Comment by chanseokoh** [comment]
Blocked by #439.

**Comment by elharo** [comment]
I think this goes in StandardDeployCommandHandler.launchDeployJob

**Comment by elharo** [comment]
@chanseokoh do you think standard and flex deploys should be two types of events or one type with different metadata?

**Comment by chanseokoh** [comment]
For me, one type seems reasonable. IntelliJ went this way.

**Comment by elharo** [comment]
see https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/37caa4e18018932e092a6fd989e48f35a824cda5/google-cloud-tools-plugin/src/com/google/cloud/tools/intellij/appengine/cloud/AppEngineStandardDeployTask.java for how IntelliJ does it

**Comment by elharo** [comment]
This uses labels which are set by el=labelvalue in the post data.

**Comment by elharo** [comment]
See https://support.google.com/analytics/answer/1033068?hl=en

It seems to me that the label would be the project ID (which we want to *not* track), the action would be deploy, and the category would be flex or standard.

**Comment by elharo** [comment]
public void sendPing(String eventName, String metadataKey, String metadataValue) {
    sendPing(eventName, metadataKey, metadataValue, null);
  }

eventName ~= "deploy"
metadataKey =  flex | standard | compat
metadataValue = null

**Comment by elharo** [comment]
closed by #739
