### ISSUE TITLE
Warn user if appengine-web.xml includes project ID

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#544]
Somehow (popup dialog? red error text) we need to warn the user on deploy if the project ID they specify manually does not match the one in appengine-web.xml

**Comment by briandealwis** [comment]
JFace's [Field Assist](http://help.eclipse.org/mars/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fjface_fieldassist.htm) supports showing little error or warning markers on controls.

http://toedter.com/wp-content/uploads/2008/12/validationdecoration.png

**Comment by elharo** [comment]
Blocked pending outcome of discussions about how gcloud treats project ID in appengine-web.xml
