### ISSUE TITLE
In CodeTemplates#materialize, address the scenario where the project is not empty

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#552]

**Comment by chanseokoh** [comment]
I wonder if this is really relevant. The native project wizard doesn't allow creating a project if the directory already exists. How can't a new project be not empty?

![selection_019](https://cloud.githubusercontent.com/assets/10523105/20108298/9636808a-a5a9-11e6-9248-15009945ff81.png)
