### ISSUE TITLE
Create success/failure landing pages after login

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#557]
For example,

https://cloud.google.com/tools/intellij/auth_success
https://cloud.google.com/tools/intellij/auth_failure

However, `LocalServerReceiver` doesn't support customizing landing pages: https://github.com/google/google-oauth-java-client/issues/128. IntelliJ solved this limitation by duplicating the `LocalSeverReceiver` code.

**Comment by chanseokoh** [comment]
https://github.com/google/google-oauth-java-client/issues/128 has been fixed.

Not sure how and when they the library team make a new release though. I created [another PR](https://github.com/google/google-oauth-java-client/pull/136) on that repo, so we might want to wait for a bit more before pushing them to make a release. However, the latter PR is more like something nice to have but not critical.

Alternatively, since we are actually embedding the library jar, we might not have to wait for an official release. (Maybe SNAPSHOT would do?)

**Comment by chanseokoh** [comment]
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/939#issuecomment-258038813

**Comment by chanseokoh** [comment]
[google-oauth-java-jetty 1.23.0 released just recently](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.oauth-client%22%20AND%20a%3A%22google-oauth-client-jetty%22), which has [the fix to customize landing pages](https://github.com/google/google-oauth-java-client/issues/128). If we upgrade the libraries, we can fix this.

**Comment by elharo** [comment]
Not our highest priority but worth doing if it's not too hard.

**Comment by chanseokoh** [comment]
@parkjam4

**Comment by parkjam4** [comment]
Plan is to copy the auth success and failure pages from CT4IJ.
Will get this task following the doc updates for the release.

**Comment by chanseokoh** [comment]
The pages are ready. I'll wire them.

https://cloud.google.com/eclipse/auth_failure
https://cloud.google.com/eclipse/auth_success
