### ISSUE TITLE
Make facets for JSR107 cache library and appengine-api-labs?

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#558]
@ludoch [recommends](https://github.com/GoogleCloudPlatform/gcloud-eclipse-tools/issues/550#issuecomment-239460625) not including the AppEngine API Labs jar and JSR107 caching by default:

> api lab should not be there by default, as it is a user decision to play
> with experimental lab apis (not recommended as not stable, only for gurus
> wanting to try potential new stuff).
> _jsr107_: same: only if it make sense for the developer. Remove it for
> default projects.
> 
> the api jar is mandatory when you use GAE apis. If you don't you do not
> need it. It is used local by the devappserver, for local runs and stripped
> out in the deploy staging phase, as the server side will replace the one
> you provide (potentially an old version) with the latest version in
> standard.

**Comment by patflynn** [comment]
@ludoch Why not simply provide it in the dev appserver if we do so in the prod environment?

**Comment by briandealwis** [comment]
If we create these facets, we'd likely want separate analytics events for each facet.

**Comment by briandealwis** [comment]
Handled as part of #682
