### ISSUE TITLE
Include src jars in new projects

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#579]
e.g. for servlet.jar and appengine jars; makes debugging and browsing a lot nicer

**Comment by briandealwis** [comment]
The src files don't seem to be included in the Google Cloud SDK.  Unlike javadoc, source jars must be local.

**Comment by elharo** [comment]
possibly a dup of #575 ?

**Comment by akerekes** [comment]
Fixed by #956
