### ISSUE TITLE
Enable configuring local run data store settings

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#601]
gcloud provides a few options to tweak how the local data store emulator is run when testing the App Engine project on the local dev server. Extend the UI to enable configuring these options.

**Comment by elharo** [comment]
I'm not sure what the best place for this is. We could add a separate local server panel in the properties under Google Cloud Platform.

Or perhaps it belongs as a run or server configuration tab:

![image](https://cloud.githubusercontent.com/assets/1005544/26725752/019889fc-476e-11e7-9ceb-aa463235c25e.png)
