### ISSUE TITLE
Should classpath containers hide `com.google.appengine.repackaged.**` and other unrelated classes?

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#606]
Developers using content-assist / completion on _Datas_, looking for Datastore, will see a host of internal classes that don't make sense to be exposed to App Engine developers.

<img width="389" alt="screen shot 2016-08-24 at 10 17 29 am" src="https://cloud.githubusercontent.com/assets/202851/17933935/ff5ee766-69e3-11e6-96ee-05580c849ad7.PNG">

This list includes classes from:
  - `com.google.appengine.repackaged.*` and `comp.google.appengine.labs.repackaged.**`
  - `com.google.apphosting.client.*`

It's hard to wade through and determine what are actually the useful classes.

From the [javadocs](https://cloud.google.com/appengine/docs/java/javadoc/), it looks like we could add access rules to the App Engine Runtime container and the App Engine SDK container to either:
  1. only expose `com.google.appengine.api.**`, `com.google.appengine.api.labs.**`, and `com.google.apphosting.api.**`
    - but it looks like there are some other useful packages to include, like `com.google.appengine.spi`, `com.google.appengine.tools.**`, `com.google.cloud.sql.**`, `com.google.cloudsearch.**`, `com.google.storage.**`, `com.google.protos.**`, `javax.**`, `org.apache.**`, `net.sf.jsr107cache`,
  2. hide `com.google.appengine.repackaged.**`, `com.google.appengine.labs.repackaged.**` and `com.google.apphosting.**` except for `com.google.apphosting.api.**`.

Option 1 seems a bit like playing whackamole.  Option 2 seems the least error prone.  We could make this optional on some 'expert' preference.

**Comment by patflynn** [comment]
This question fits into a broader discussion we need to have about
including App Engine APIs in native IDE projects.  I'm working on a doc
that I'll share with you today or tomorrow discussing this.

**Comment by akerekes** [comment]
Implemented as part of #732
