### ISSUE TITLE
Implement custom project ID input dialog with decoration

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#635]
The default SWT InputDialog does not decorate the validation error messages and thus it's less obvious that the message is not just another line of information in the dialog. We should implement a simple input dialog based on the SWT one that provides a `ControlDecoration` that is used to highlight the error message.

**Comment by elharo** [comment]
I agree we should better decorate the error messages around this. I don't think this should be a separate free-standing window.

**Comment by akerekes** [comment]
This is the dialog that pops up when the user executes the deploy and has set the "Prompt for project ID on deploy" checkbox previously in the deploy preferences (and not the input field for project ID on the deploy preferences dialog). I think it should be a separate free-standing window.

**Comment by briandealwis** [comment]
I'd rather like a general deploy dialog that allowed me to override values for *this* deploy.

**Comment by elharo** [comment]
OK, I misunderstood that. Sounds good.

**Comment by chanseokoh** [comment]
The current deploy dialog already addresses this issue. Closing.
