### ISSUE TITLE
Add a checkbox to persist deploy preferences given at deploy time

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#643]
Once #642 is implemented, we should add a checkbox to the new prompt dialog which is when set would ensure that the preferences set by the user during deploy are persisted and the next time the user opens the deploy preferences page or the prompt dialog is shown it'll use the values set in the previous run.

**Comment by elharo** [comment]
I feel like I'm getting a bit of preference fatigue. Every checkbox we add increases cognitive load for the dialog and requires documentation. If the user wants to change the defaults, they can change them in the preference pane. It might make sense to limit this dialog to just the things we're passing to gcloud: project ID, version, promote or no

**Comment by akerekes** [comment]
The idea here is that the user could see the previously set values if that checkbox is set. Otherwise it would come up with always the ones saved through the preference page. If they want to quickly deploy one after each other, it's useful to see that previous version deployed was 1, now the user sets 2, and on the next deploy he/she will see that the next version is 3 (probably, based on his/her versioning schema).

If we don't give the option to save it, they may need to think more/go back to the pref page and change there.

We can also save these values by default (no checkbox to enable/disable) and have this issue here and if users vote/ask for it, we could implement later.

**Comment by elharo** [comment]
The combinatorial complexity is making my brain explode. :-)

Here's an idea: what if we remove the visible deploy preferences completely? Instead, the user enters them in the pop-up dialog as needed; and we remember those values as defaults for next time. That way the user only has to think about this when they're thinking about deployment. No confusion about where the values are coming from or where to set them.

**Comment by briandealwis** [comment]
+1 to only showing a dialog on each deploy.  Nobody looks at the project properties anyways.

**Comment by chanseokoh** [comment]
Speaking of the project properties, one big difference from IntelliJ is project-level preferences vs. deploy configurations. That is, our Eclipse plugin can have only one deploy setting per project, while IntelliJ can have an arbitrary number of "Deploy Configurations" (actually Run/Debug Configurations re-purposed).

**Comment by briandealwis** [comment]
That's pretty interesting.  Do we have any detail on how people use such deploy configurations?  We could consider doing something similar with the launch configurations.  The Google Dataflow plugin creates Dataflow launch configurations.
