### ISSUE TITLE
Received verification code when we didn't

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#649]
After denying permissions on login:

![screen shot 2016-08-31 at 4 06 52 pm](https://cloud.githubusercontent.com/assets/1005544/18144530/129e740c-6f95-11e6-91ec-86a2e30a6a1b.png)

However Eclipse still tells us the login failed.

**Comment by chanseokoh** [comment]
Yeah, funnily, this is a canned response no matter what happens (including login errors): https://github.com/google/google-oauth-java-client/blob/dev/google-oauth-client-jetty/src/main/java/com/google/api/client/extensions/jetty/auth/oauth2/LocalServerReceiver.java#L219

#557 will fix this.

**Comment by diegomarquezp** [comment]
Closing as not planned since Java 8 is not supported in GAE. cc: @blakeli0
