### ISSUE TITLE
Project Selector

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#656]
Where ever we ask for a project ID, we should consider implementing a popup that reads the available project IDs from the server and supplies them. 

We will need to filter out GCP projects that do not have App Engine applications attached (though per #505 we want to add the ability to attach a new App Engine application to an existing GCP project. We may want to design the UI of the two features at the same time.)

**Comment by chanseokoh** [comment]
> We will need to filter out GCP projects that do not have App Engine applications attached

I believe the updated design doc suggests we show an indicator that a project doesn't have the application resources instead of filtering the project out.

**Comment by patflynn** [comment]
+1.

**Comment by elharo** [comment]
`gcloud projects list` returns all IDs, though it might be nicer to use the cloud resource manager API: https://cloud.google.com/resource-manager/reference/rest/v1beta1/projects/list

In any case this will go into appengine-plugins-core

**Comment by patflynn** [comment]
On Tue, Jan 10, 2017 at 9:59 AM, Elliotte Rusty Harold <
notifications@github.com> wrote:

> gcloud projects list returns all IDs, though it might be nicer to use the
> cloud resource manager API: https://cloud.google.com/
> resource-manager/reference/rest/v1beta1/projects/list
>
> +1 don't use gcloud for things you can do easily from an available API.

> In any case this will go into appengine-plugins-core
>
If you do this you'll add the google client library dependency tree to our
maven/gradle plugins which is undesirable.

**Comment by akerekes** [comment]
This issue will track the initial selector with minimal features. The selector will be a table widget displaying name+ID for each existing project ordered alphabetically on name.

**Comment by akerekes** [comment]
- [ ] #1353 

- [ ] #1349 

- [ ] #1350 

- [ ] #1351 

- [ ] #1352 

- [ ] #505 

- [ ] #843
