### ISSUE TITLE
Local run and debug should have option to start emulators

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#667]
There are emulators for
[Cloud Datastore](/datastore/docs/tools/datastore-emulator),
[Cloud PubSub](/pubsub/docs/emulator), and
[Cloud Bigtable](/bigtable/docs/emulator).
Use the `gcloud` command to start them before you run your app:

```
gcloud beta emulators datastore start
gcloud beta emulators pubsub start
gcloud beta emulators bigtable start
```

**Comment by chanseokoh** [comment]
Note that each emulator requires its own gcloud component(s) installed.

**Comment by elharo** [comment]
At least part of this likely belongs in appengine-plugins-core. Ideally we shouldn't need more than a few checkboxes here (without data binding, please).

We may be able to piggyback off the work the VS team is doing.

**Comment by elharo** [comment]
Executing with 

gcloud --quiet

should avoid the need to worry about these components being preinstalled.

**Comment by elharo** [comment]
FYI, as of Objectify 6 the old dev_appserver based datastore emulator no longer works. We need the new gcloud datastore emulator. See https://stackoverflow.com/questions/50456158/projectid-must-match-the-following-pattern-exception-when-running-objectify-on for more details on how to configure that manually. However we should make this simpler and not require the developer to open a terminal.

**Comment by diego92sigma6** [comment]
Closing as not planned. Please reopen if needed
