### ISSUE TITLE
Uniform name for plug-ins

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#681]
Our plugin names are a mix of Cloud Tools for Eclipse and Gcloud:

![image](https://cloud.githubusercontent.com/assets/1005544/18437984/6841cd32-78cd-11e6-9c71-f88f790a4d71.png)

Once official naming is finalized, make these consistent.

**Comment by elharo** [comment]
@arouzrokh Assigning to you for an official decision on what we call this in public. Once you've got that, assign back to me and I'll make the change. Thanks.

**Comment by arouzrokh** [comment]
Cloud Tools for Eclipse please universally. Thank you.
