### ISSUE TITLE
Design and implement an API attacher

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#682]
We don't want to add these jars by default but we do want to enable users to add them to projects easily:

appengine-api-1.0-sdk:LATEST
appengine-endpoints:LATEST
com.googlecode.objectify.objectify:LATEST
jsr107cache-1.1 AND appengine-jsr107cache:

and possibly 

appengine-api-labs.jar

Requirements:
1. These MUST got into the WEB-INF/lib folder in a non-maven project
2. maven pom.xml MUST be updated, if it's a maven project
3. Jars MUST be loaded from Maven central
4. Facets MAY be used.

**Comment by patflynn** [comment]
For reference:
https://docs.google.com/a/google.com/document/d/1gjtvqTvuDo585l9BcZTu_QOhIQL6QSlyJShWbQ0Fvz8/pub

**Comment by rdayal** [comment]
how is this one looking?

**Comment by elharo** [comment]
@akerekes What remains here? Is Objectify and transitive dependencies going to be available? I think that's the big remaining piece in standard.

**Comment by akerekes** [comment]
Objectify needs only Guava, so I think for the beta release we can simply pin down the Objectify and Guava versions in the library definitions and once #865 is fixed (which should happen either before beta or not long after) we can use latest version of Objectify and let the resolution logic figure out the required Guava version.

**Comment by elharo** [comment]
I think all beta blocking work on this is now done and checked in. @akerekes is there any more actual work here that is not tracked in other bugs, or can we close this one out?
