### ISSUE TITLE
Maven task to check toolchains

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#685]
This one bit me recently. It would be nice if we could check this before starting to compile and fail earlier with an obvious error message. 

We use Tycho's support for Maven Toolchains to ensure that Java 8 features do not creep into the code. This support is enabled by compiling with the useJDK=BREE setting that ensures bundles are compiled with a JDK that matches the bundle's Bundle-RequiredExecutionEnvironment. This setting requires configuring Maven's toolchains to point to appropriate JRE installations. Tycho further requires that a toolchain defines an id for the specified Execution Environment identifier. For example, a ~/.m2/toolchains.xml to configure Maven for a Java 7 toolchain on a Mac might be:

```
<?xml version="1.0"?>
<toolchains>
  <toolchain>
    <type>jdk</type>
    <provides>
      <id>JavaSE-1.7</id> <!-- the Execution Environment -->
      <version>1.7</version>
      <vendor>oracle</vendor>
    </provides>
    <configuration>
      <jdkHome>/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/jre</jdkHome>
    </configuration>
  </toolchain>
</toolchains>
```

Note that jdkHome above specifies the jre/ directory: Tycho sets the default boot classpath to jdkHome/lib/_, jdkHome/lib/ext/_, and jdkHome/lib/endorsed/*. For many JDKs, including Oracle's JDK and the OpenJDK, those directories are actually found in the jre/ directory. Compilation errors such as java.lang.String not found and java.lang.Exception not found indicate a misconfigured jdkHome.

You can disable the use of toolchains by setting the tycho.toolchains property to SYSTEM.

**Comment by briandealwis** [comment]
Closing as we no longer need to maintain our own toolchains.
