### ISSUE TITLE
Disable link in deploy dialog if there's no project ID

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#686]
If there's no project ID set by the user, the link to App Engine versions page will not contain a project ID and the user is taken to the versions page of the last project he opened in the web console which may confuse the user.
We should probably disable the link until a project ID is set and a tooltip (on hover) should explain why it is disabled.

**Comment by chanseokoh** [comment]
Should the link be updated on the fly while a user is typing in the project ID? And what if the project ID entered by the user is invalid?

**Comment by elharo** [comment]
Don't worry if project ID does not map to a real project. We'll eventually fix this with a project ID selector.

Update on the fly only if it's easier than not updating on the fly.

**Comment by elharo** [comment]
To be specific the link we're talking about here is

https://console.cloud.google.com/appengine/versions?project=

to manually promote a version.
