### ISSUE TITLE
Update Google Login sign out message box 

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#695]
Sign out message box should should have buttons “Yes” and “No”, instead of “Ok” and “Cancel”

**Comment by elharo** [comment]
Actually, it should be "Sign out." "Don't Sign Out"

**Comment by elharo** [comment]
This is the relevant code in GoogleLoginCommandHandler

    } else {
      if (MessageDialog.openConfirm(HandlerUtil.getActiveShell(event),
          Messages.LOGOUT_CONFIRM_DIALOG_TITILE, Messages.LOGOUT_CONFIRM_DIALOG_MESSAGE)) {
        loginService.clearCredential();  // Log out on confirmation.
      }
    }
