### ISSUE TITLE
Help button in Create New App Engine Standard wizard should have more tailored content.

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#696]
Help button could point to App Engine standard documentation. Maybe this https://cloud.google.com/appengine/docs/java/ or the wiki page

**Comment by elharo** [comment]
see http://stackoverflow.com/questions/7322489/cant-put-content-behind-swt-wizard-help-button

**Comment by elharo** [comment]
This: http://www.vogella.com/tutorials/EclipseRCPHelpSystem/article.html#project-with-help

**Comment by elharo** [comment]
![image](https://user-images.githubusercontent.com/1005544/30115495-ef8445b4-92e8-11e7-8ef2-21abee151fd2.png)
