### ISSUE TITLE
Explore github projects

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#704]
Would this help us to organize our work better than milestones and tags?

https://github.com/GoogleCloudPlatform/cloud-tools-for-eclipse/projects

**Comment by branflake2267** [comment]
If you're interested I setup projects and so far it feels useful. https://github.com/gwt-plugins/gwt-eclipse-plugin/projects/2

**Comment by elharo** [comment]
So here are my initial thoughts after playing with it. It looks
promising, but it isn't there yet unless you use third party tools
(e.g. Zenhub) that have security issues. In particular:

* I don't see any way to divide up work into epics, stories, and
tasks. The cards are all just issues, git notes, or pull requests. It
doesn't give us any extra visibility into the project.

* There's no way to assign points to cards or columns, so it's not
very helpful for estimating work using story points and comparing it
with capacity.

We could perhaps use this as a slightly more visual view into our
existing issue tracker. For instance we could group all the analytics
stories into a single column. However this needs to be manually
curated. As far as I see, there's no way to automatically connect
labels and milestones to columns in the project view.

My recommendation is that we revisit after github adds a few more
features to this.
