### ISSUE TITLE
Publish plugin to Eclipse marketplace

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#713]
so users don't have to use our download site:

http://marketplace.eclipse.org/quickstart

(via JavaOne)

**Comment by elharo** [comment]
@arouzrokh I started looking into this one. It's fairly easy, but we are going to need an icon that is 110 by 80 pixels (i.e. not square like our existing icons.) Can you let us know which icon we should use for the plugin as a whole, and see if we can get it at that size? We could add extra horizontal blank space to a square icon if we don't want to create one from scratch.

**Comment by arouzrokh** [comment]
Did Bryan already gave you the icon? I saw it in another thread.

>

**Comment by elharo** [comment]
Nope

**Comment by briandealwis** [comment]
Process is to [add a new listing](https://marketplace.eclipse.org/node/add/resource).  We need:
  - [ ] a 110x80 logo (or something with that aspect ratio
  - [ ] select up to 5 categories
  - [ ] specify a set of tags
  - [ ] decide whose account will create the entry

Categories:

I'm thinking _Build and Deploy_, _J2EE Development Platform_, _Web_, _Web Services_, _Web, XML, Java EE and OSGi Enterprise Development_.  Or _Application Development Frameworks_?

1. Application Development Frameworks
2. Application Management
3. Application Server
4. BIRT
5. Build and Deploy
6. Business Intelligence, Reporting and Charting
7. Code Management
8. Collaboration
9. Database
10. Database Development
11. Database Persistence
12. Documentation
13. EclipseRT Target Platform Components
14. Editor
15. Entertainment
16. General Purpose Tools
17. Graphics
18. IDE
19. Internet of Things (IoT)
20. J2EE Development Platform
21. J2ME
22. Kura Apps
23. Languages
24. Linux Tools
25. Logging
26. Mobile and Device Development
27. Modeling
28. Modelling Tools
29. Myelin Connectors
30. Network
31. Other
32. Process
33. Profiling
34. Programming Languages
35. Reporting
36. Rich Client Applications
37. SCM
38. Search
39. SOA Development
40. Source Code Analyzer
41. Systems Development
42. Team Development
43. Testing
44. Tools
45. UI
46. UML
47. Web
48. Web Services
49. Web, XML, Java EE and OSGi Enterprise Development
50. XML
51.

**Comment by arouzrokh** [comment]
Elliotte can you use the same logo of app engine that we spoke of before? that can be resized if it's not the right size with Gimp or something. Let me know if you need help with this Icon. I agree with Bryan's categories.

**Comment by briandealwis** [comment]
Here's the App Engine icon resized to 110x80 with whitespace:

![app-engine-marketplace](https://cloud.githubusercontent.com/assets/202851/21774643/17812626-d661-11e6-87d6-02c178c566f1.png)

**Comment by branflake2267** [comment]
Can you allude to a date range for this goal yet? I'm looking at providing a lightning talk at the GDG Seattle on the cloud tools plugins.

**Comment by elharo** [comment]
@arouzrokh Is the App Engine logo Brian provided good, or should we find a GCP logo?

**Comment by elharo** [comment]
This is the logo we'll use per @arouzrokh 

![gcp-logo](https://cloud.githubusercontent.com/assets/1005544/23517642/f6eeb9bc-ff3e-11e6-9bda-34f713eecd0a.png)


I still need to resize it to a rectangle.

**Comment by elharo** [comment]
Here's the logo with extra space:

![gcp logo 110x80](https://cloud.githubusercontent.com/assets/1005544/23523058/4aa994dc-ff53-11e6-991f-2d18a6c45642.png)

**Comment by elharo** [comment]
http://marketplace.eclipse.org/content/google-cloud-tools-eclipse

**Comment by branflake2267** [comment]
Nice Job!!!!!
