### ISSUE TITLE
Project configurator

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#714]
In neon there's a universal import function we can plug into for app engine projects. 

http://www.eclipse.org/eclipse/news/4.6/M7/

"The import strategies are contributed via the new extension point org.eclipse.ui.ide.projectConfigurator, so that other IDE components can contribute detection and configuration specific to the technology they're supporting."

**Comment by chanseokoh** [comment]
Only for Neon?

**Comment by briandealwis** [comment]
It is Neon-specific.  It's intent is to simplify importing non-Eclipse artifacts.  As we're using WTP or Maven, which already has facet installation, what would we do differently?

**Comment by chanseokoh** [comment]
> @briandealwis The smart-import stuff is centred around a set of ProjectConfigurators (org.eclipse.ui.wizards.datatransfer) and the org.eclipse.ui.ide.projectConfigurators extension point
