### ISSUE TITLE
Missing target libraries

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#716]
Project setup: I'm trying to setup the repo and after target platform install and import I noticed a couple libraries which seem to be missing. I added the target repository and installed the dependencies but these two are not found.
- org.hamcrest 1.1.0
- com.google.cloud.tools.appengine

![screen shot 2016-09-19 at 4 00 19 pm](https://cloud.githubusercontent.com/assets/1326504/18651811/93c5a5ae-7e82-11e6-8fd1-a86187ba5a8b.png)
![screen shot 2016-09-19 at 4 00 29 pm](https://cloud.githubusercontent.com/assets/1326504/18651812/94f2c240-7e82-11e6-8123-4e21ef60dc09.png)

**Comment by briandealwis** [comment]
We pull some dependencies out of Maven Central.  These can't be pulled in from `.target` files unfortunately, so you must do a first build on the command-line with the `ide-target-platform` profile.  There are some instructions in the [README.md](https://github.com/GoogleCloudPlatform/cloud-tools-for-eclipse/blob/master/README.md).
