### ISSUE TITLE
No arguments tab in runtime panel

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#719]
Opening the server launch configuration, to find the launcher args isn't working. 

Left is the app engine selection and dialog result. On the right, it what tomcat looks like. 
![screen shot 2016-09-19 at 4 54 01 pm](https://cloud.githubusercontent.com/assets/1326504/18652854/8245ea5c-7e8a-11e6-87ec-c5833d914a77.png)

**Comment by elharo** [comment]
OK, I understand this. The report is that there's no arguments tab in our runtime panel. The reason there isn't is that I haven't put it there yet. So far we haven't found a need for this.

This is easy enough to add if there's a definite use case; but I don't want to add it unless it's actually needed.

**Comment by elharo** [comment]
If we add this, it is done com.google.cloud.tools.eclipse.appengine.localserver.ui.AppEngineTabgroup.createTabs()

**Comment by branflake2267** [comment]
Ah. So this looks to be a duplicate of #467 then.
