### ISSUE TITLE
App Engine project ID is not saved to preferences for new Maven based projects

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#731]
#646 fixed this for native projects, but not for Maven-based project generation.

**Comment by elharo** [comment]
arguably, we should fix this by removing the project ID field from the wizard

**Comment by akerekes** [comment]
Or saving the ID just like we do for native projects.

**Comment by elharo** [comment]
I don't think we can remove the project ID from the wizard just yet because tool bugs require it in pom.xml. Once those are fixed we can simply remove the project ID here since we don't want to put it in pom.xml
