### ISSUE TITLE
Implement API attacher for new native Eclipse projects

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#732]
Part of #682 

This issue covers adding App Engine APIs to a new native project.

Tasks:

 - update the new project wizard UI
 - upon creating the project, add the selected APIs to the build path

**Comment by YnR** [comment]
Is this related to what we saw in the UX study with libraries?

**Comment by akerekes** [comment]
It will fix some of the problems we have seen there, but it originates from the intention of downloading APIs for App Engine, Endpoints and Objectify instead of pulling them from CloudSDK. However this will not make us independent of CloudSDK and the path issues we have seen will need to be addressed separately.
