### ISSUE TITLE
convert com.google.cloud.tools.eclipse.preferences.areas.exsd to real schema

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#751]
convert plugins/com.google.cloud.tools.eclipse.preferences/schema/com.google.cloud.tools.eclipse.preferences.areas.exsd to a correct XSD with an automatic unit test of plugin.xml validity

**Comment by diegomarquezp** [comment]
Closing as not planned. cc: @blakeli0
