### ISSUE TITLE
Allow saving null Project ID (i.e., make it optional) in project preferences

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#761]
For a project created without a project ID given, when the Deploy preference page is open, a user is forced to enter a project ID before the user can move to another preference page or dismiss the dialog. If the user tries to select another preference node, it shows the following error:

![selection_019](https://cloud.githubusercontent.com/assets/10523105/19008763/98c1b34c-873b-11e6-843b-e09abf2d00f7.png)

This could be annoying particularly for a user who doesn't know what project ID means or what to enter.

**Comment by elharo** [comment]
Makes sense. We should allow this to be empty, even if it wasn't empty before.

**Comment by elharo** [comment]
This is tricky because we're using the same code for the deployment dialog, where we must have an account; and the preferences page, where it's optional. 

I'm tempted to remove the preferences page completely. It feels redundant with the deploy dialog.

**Comment by elharo** [comment]
Now fixed
