### ISSUE TITLE
Add plugin for Go (golang)

### ISSUE THREAD

**Issue by cliveb** [GoogleCloudPlatform/google-cloud-eclipse#762]
A Golang plugin would make me more productive. True Go wasn't designed to need an IDE. However an IDE helps me  switch back and forth between Java, GWT and others. Also a plugin helps me mentor new full stack developers in Go on GCP. 

- [Google Trends GWT vs Go] (https://www.google.com/trends/explore?q=GWT,golang)
- [Full stack development in Go] (https://medium.com/@ic/full-stack-development-and-go-26a64c70f387#.e4yirbimz)

**Comment by elharo** [comment]
This is is not within the scope of this project.

**Comment by patflynn** [comment]
@cliveb Hi Clive!  Thanks for filing this FR.  

This plugin is currently focused entirely on Google Cloud Platform integration (App Engine, Compute Engine, things like that).  Language support is not in our purview, and is also probably logically provided through a different plugin focused on Go users (regardless of cloud platform).  

You may want to check the [Go team](https://golang.org/project/) if an Eclipse plugin is in their plans.
