### ISSUE TITLE
Question: Will thanking Google be a problem? 

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#766]
I've added a sponsors section to the GWT Eclipse Plugin. Will this be a problem to say thanks to the Google Cloud Tools team? 

https://github.com/gwt-plugins/gwt-eclipse-plugin
![screen shot 2016-10-02 at 9 37 09 am](https://cloud.githubusercontent.com/assets/1326504/19022050/cf02b386-8883-11e6-92c9-fa32256b599a.png)

**Comment by elharo** [comment]
@arouzrokh @branflake2267 Is this taken care of?

**Comment by branflake2267** [comment]
I'm going to close it. I mentioned it just in case it was an issue.
