### ISSUE TITLE
Provide actionable development urls 

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#768]
Would it be possible to get the launcher urls or have them provided in some way where the user could easily access and click on them to launch them? Or maybe provide a App engine view. Not sure what you want to do. Below I'll show you what I did for the GWT users. 

Here is what I did in the GPE-Fork, I retrieved the urls that the user could launch. I always found it annoying that I had to look up the admin url because I'd forget. 
<img width="1027" alt="screen shot 2016-10-02 at 12 48 54 pm" src="https://cloud.githubusercontent.com/assets/1326504/19023252/bd1797f2-889e-11e6-8fcd-5305c471e7e3.png">

Example of starting the App Engine server and the urls show up in the the DevMode View. 
https://youtu.be/SUueCocqf_U?t=76

**Comment by elharo** [comment]
I'm not sure what you mean by "launcher URLs". Are you referring to the URL of the local server? and if so, which ones? There can be many.

**Comment by briandealwis** [comment]
We have an open-browser-on-launch option that will open the main page.

@branflake2267 is referring to the all the URLs that are output by the `dev_appserver`: the main launch page, the admin page, etc.
```
INFO     2016-08-19 19:49:38,095 devappserver2.py:769] Skipping SDK update check.
INFO     2016-08-19 19:49:38,161 api_server.py:205] Starting API server at: http://localhost:60320
INFO     2016-08-19 19:49:38,166 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-08-19 19:49:38,172 admin_server.py:116] Starting admin server at: http://localhost:8000
Aug 19, 2016 7:49:39 PM com.google.appengine.tools.development.AbstractContainerService configure
WARNING: Null value for containerConfigProperties.get(devappserver.portMappingProvider)
Aug 19, 2016 7:49:39 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Logging to JettyLogger(null) via com.google.apphosting.utils.jetty.JettyLogger
Aug 19, 2016 7:49:39 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: jetty-6.1.x
Aug 19, 2016 7:49:40 PM org.apache.jasper.EmbeddedServletOptions <init>
WARNING: Warning: Invalid value for the initParam keepgenerated. Will use the default value of "false"
Aug 19, 2016 7:49:40 PM org.apache.jasper.EmbeddedServletOptions <init>
WARNING: Warning: Invalid value for the initParam fork. Will use the default value of "true"
Aug 19, 2016 7:49:40 PM com.google.apphosting.utils.jetty.JettyLogger info
INFO: Started SelectChannelConnector@localhost:60329
Aug 19, 2016 7:49:40 PM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:60329/
Aug 19, 2016 7:49:40 PM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:60329/_ah/admin
Aug 19, 2016 7:49:40 PM com.google.appengine.tools.development.devappserver2.DevAppServer2Impl doStart
INFO: Dev App Server is now running
INFO     2016-08-19 19:49:40,913 module.py:788] default: "GET / HTTP/1.1" 200 582
```
We should at least integrate the `com.google.cloud.tools.eclipse.ui.util.console.PatternToHyperlinkConverter` on our launch console.

**Comment by briandealwis** [comment]
_(Meant to put this comment on this issue)_

Hmm, I wonder if we could pull out the module/service information from the server logs to provide with [`org.eclipse.wst.server.core.model.IURLProvider`](https://github.com/gwt-plugins/gwt-eclipse-plugin/blob/master/plugins/com.gwtplugins.gwt.eclipse.wtp/src/com/google/gwt/eclipse/wtp/facet/GwtLaunchableAdapterDelegate.java#L34):
```
INFO     2016-07-28 01:33:21,421 dispatcher.py:197] Starting module "default" running at: http://localhost:8080
INFO     2016-07-28 01:33:21,424 admin_server.py:116] Starting admin server at: http://localhost:8000
```
[…]
```
Jul 28, 2016 1:33:23 AM com.google.appengine.tools.development.AbstractModule startup
INFO: Module instance default is running at http://localhost:54220/
Jul 28, 2016 1:33:23 AM com.google.appengine.tools.development.AbstractModule startup
INFO: The admin console is running at http://localhost:54220/_ah/admin
```
Unfortunately the log formats are different, and the `default` module port is different too.
