### ISSUE TITLE
Test util bundle

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#771]
We should create a bundle that can contain utility classes used in tests. For now the only candidate I';m aware of is the `com.google.cloud.tools.eclipse.appengine.libraries.TestProject` in the `com.google.cloud.tools.eclipse.appengine.libraries.test` bundle (which at the time of filing this bug lives only on the i732_3 branch which will be merged eventually).

**Comment by akerekes** [comment]
Another candidate after refactoring it into its own class is the mock registry implementation in `com.google.cloud.tools.eclipse.appengine.libraries.AppEngineLibraryContainerInitializerTest`

**Comment by akerekes** [comment]
Another candidate after refactoring it into its own class is the mock OSGi service registration implementation in `com.google.cloud.tools.eclipse.appengine.libraries.LibraryClasspathContainerTest`

**Comment by elharo** [comment]
And XmlTest

**Comment by akerekes** [comment]
`/com.google.cloud.tools.eclipse.appengine.libraries.test/src/com/google/cloud/tools/eclipse/appengine/libraries/TestLibraryRepositoryService.java`

**Comment by briandealwis** [comment]
ReflectionUtil

**Comment by chanseokoh** [comment]
`com.google.cloud.tools.eclipse.appengine.login.test/src/com/google/cloud/tools/eclipse/appengine/login/ui/ShellTestResource.java`

(Also see the TODO in MavenArchetypeProjectWizardTest.java.)

**Comment by chanseokoh** [comment]
We have the `....eclpise.test.dependencies` bundle, and I wonder if we can reuse this.

**Comment by akerekes** [comment]
com.google.cloud.tools.eclipse.appengine.localserver.TestEclipseContext

**Comment by akerekes** [comment]
com.google.cloud.tools.eclipse.appengine.localserver.server.TestProject

**Comment by chanseokoh** [comment]
Since this issue records possible candidates, I think it's better to re-open this to track them.

**Comment by akerekes** [comment]
@chanseokoh thanks, it was closed accidentally, I should have used a different phrasing in #935 .

**Comment by akerekes** [comment]
Fixed by #941
