### ISSUE TITLE
Remove the login icon at the bottom right

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#778]
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/951

It also makes sense to remove it in our plugin.

I think we have no problem removing it anytime after merging #742, since
1) deploy actions will always ask users to select an account through UI (which allows adding new accounts there); and
2) we have the menu item "Manage Google Accounts...", which shows a panel listing all signed-in accounts and enables logging out accounts.

**Comment by chanseokoh** [comment]
If we remove it, we may want to convert the `AccountsPanel` (which is a `PopupDailog` that has a transient nature) into a full dialog having a title area, if it seems more suitable.

**Comment by elharo** [comment]
Let's see what the UX studies say about this one before we do anything.
