### ISSUE TITLE
Changing GAE Facets in the Property Dialog is not updating the deployment settings page

### ISSUE THREAD

**Issue by nbashirbello** [GoogleCloudPlatform/google-cloud-eclipse#783]
What happens when the user unselects the facet and goes back to the GAE deployment page?

**Comment by elharo** [comment]
Can you elaborate on this? I'm not totally clear on the issue. Thanks.

**Comment by nbashirbello** [comment]
If you open the Properties dialog of an App Engine Standard project it will contain both the App Engine Deployment page and the Project Facets page. If you uninstall the App Engine Standard facet or change it to the App Engine Flex facet, the App Engine Deployment tab will not be updated to either hide the App Engine Deployment for Standard (as in the first case) or show the App Engine Deployment for Flex.

**Comment by akerekes** [comment]
Fixed by #1567
