### ISSUE TITLE
artifact in package name or not?

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#790]
In the maven wizard the default Java package name is 

groupId.artifactId

but if you generate at the command line it's just

groupId

by default. Which makes more sense? We should be consistent.

**Comment by akerekes** [comment]
using groupId looks better, as people frequently use `-` in their artifact id (e.g. hamcrest-core) which would result in invalid package name.

**Comment by elharo** [comment]
makes sense. Let's remove the code that adds the artifact to the package name in the wizard.
