### ISSUE TITLE
select single default account

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#794]
In the deployment dialog, even when exactly one account is signed in, it comes up with an empty dialog for account. In this case, it should select that account automatically.

**Comment by elharo** [comment]
Perhaps related to #759 but doesn't seem quite the same

**Comment by YnR** [comment]
Is this related to the bug where the user is signed into two different accounts in gcloud and Eclipse?

**Comment by elharo** [comment]
No, this is is when the user is only signed into one account in Eclipse (the common case, we think). In this case, the popup should preselect that single account. No reason to make the user choose form a list of one.
