### ISSUE TITLE
API attacher - Download source artifact and set its location in the classpath entry

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#800]
When a source uri is defined for a library, we need to download the file pointed by the URI and add the local path to the classpath entry.
If there's no source URI defined we can try to resolve the source artifact using Maven.

**Comment by briandealwis** [comment]
Two things that occurred to me:

We shouldn't block the library from being added until all of the { artifact, source, javadoc } are downloaded.  Once the artifact is here, the container should be set, and updated as the source and javadoc come available.

And we should do this in a job.  Ideally we'd use a `JobGroup` to manage the jobs to allow controlled parallelism.

**Comment by akerekes** [comment]
@briandealwis I filed #810 to cover async resolution
