### ISSUE TITLE
Make API attachment async

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#810]
We shouldn't block the library from being added until all of the { artifact, source, javadoc } are downloaded. Once the artifact is here, the container should be set, and updated as the source and javadoc come available.

And we should do this in a job. Ideally we'd use a JobGroup to manage the jobs to allow controlled parallelism.

**Comment by elharo** [comment]
Do we currently at least put up a progress dialog while these download?

**Comment by akerekes** [comment]
No, we don't.
