### ISSUE TITLE
Run Button on Toolbar

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#811]
Does same as Run > Run on Server

**Comment by elharo** [comment]
@ynr @saturnism Yann, you offered to find us an icon to use here.

**Comment by YnR** [comment]
Adding @hray2003 (I cannot assign it to her for some reason)

**Comment by elharo** [comment]
had to add @hray2003 as a collaborator before issues could be assigned.
