### ISSUE TITLE
Obtain App Engine libraries from extension point contribution

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#819]
In `com.google.cloud.tools.eclipse.appengine.newproject.AppEngineStandardWizardPage#getLibraries()` we should obtain the libraries from the extension registry or the `ILibraryRepositoryService` instead of hard-wiring them.

**Comment by elharo** [comment]
now AppEngineLibraries.getAvailableLibraries();
