### ISSUE TITLE
Ensure Platform.inDevelopmentMode returns false in releases

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#820]
We have a couple of places where we call this function. We need to make sure that our release binaries do return false on them. We also need to eliminate any future possibility of regression.

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.usagetracker/src/com/google/cloud/tools/eclipse/usagetracker/AnalyticsPingManager.java

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.login/java-templates/com/google/cloud/tools/eclipse/appengine/login/Constants.java#L14

(In the latter code, the fact that login works doesn't warrant that it returns false, because the property names are identical regardless of what the function returns.)

**Comment by elharo** [comment]
Waiting for #142

**Comment by chanseokoh** [comment]
Note that we can't rely sole on #142, because it's possible that some users may not upgrade our plugin and our old version is set up properly to send Analytics pings.

**Comment by elharo** [comment]
What are you proposing to do here?

**Comment by chanseokoh** [comment]
After taking some time looking at [`Constants.java`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.login/java-templates/com/google/cloud/tools/eclipse/appengine/login/Constants.java#L14), it looks like login will simply not work on production if `Platform.inDevelopmentMode()` returns true. So, I think we are good.
