### ISSUE TITLE
Expose Servlet and JSP api in API Attacher

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#824]
Currently these two libraries are added to all projects by default, however the JSP library is not required to run web apps on App Engine (unless they use JSPs of course). Therefore:

 - servlet API should be displayed among the libraries with a disabled and selected checkbox
 - JSP jar should be displayed among the libraries with an editable, unselected checkbox (like to other libraries except Servlet API)

**Comment by briandealwis** [comment]
These libraries are supposed to be provided by the Server Runtime, and versions chosen based on the _Dynamic Web Module_ versions.  They are not included in the resulting `.war`.

**Comment by akerekes** [comment]
Closed in favor of #870
