### ISSUE TITLE
Force m2eclipse to check remote repository for latest artifact version when library is defined to use the latest version

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#830]
If m2eclipse is set to not check for latest version automatically in remote repositories (`Window/Preferences/Maven/Do not automatically update dependencies from remote repositories`), then if the user has an older version of any of the libraries we're adding to the classpath via the API Attacher, it will use that jar, and download the latest for those that are not present locally. This can lead to having App Engine API 1.9.40 and App Engine Endpoints 1.9.44 on the classpath (assuming that App Engine API 1.9.40 was present in the local repo, no App Engine Endpoints jar was available locally and the latest version is 1.9.44)

**Comment by chanseokoh** [comment]
Also, when we later download servlet-api.jar, we need to specifically pin a certain version.

**Comment by akerekes** [comment]
You can specify an explicit version for a library already.

**Comment by chanseokoh** [comment]
Right. The title of this issue suggests to force using latest artifact versions, so I was making a note that servlet-api.jar is an exception. It should be 2.5 for App Engine standard.

**Comment by akerekes** [comment]
Title updated. Also for clarification: this issue has nothing to do with artifacts that are configured with a specific version, only with those that use 'LATEST' as version.

**Comment by akerekes** [comment]
I have digged into this issue, but I could not find a good way to override the preferences setting for a given request. I don't think we should change the user's preference just to make this work, so I'm not sure how we could achieve this (apart from deleting all local artifacts of for the given Maven coordinates to ensure that the lookup will hit the remote repo, but this also seems excessive).

**Comment by branflake2267** [comment]
Could a m2e configurator pick up the version on an maven update and then reconfigure the api used? I do some configuring on m2e updates. Although I've noticed once I add a lifecycle, I have to run that lifecycle in eclipse m2e.

**Comment by briandealwis** [comment]
I suspect the best we can do is log the situation.

**Comment by briandealwis** [comment]
The M2Eclipse preference is `MavenPreferenceConstants.P_GLOBAL_UPDATE_NEVER` (boolean), managed by `org.eclipse.m2e.core.ui.internal.preferences.MavenPreferencePage`.  This preference is used by m2e when generating its `MavenConfigurationImpl` to create an Aether repository update policy (`org.eclipse.aether.repository.RepositoryPolicy.UPDATE_POLICY_NEVER`).

There's also `MavenPreferenceConstants.P_UPDATE_INDEXES`…  I don't know what the impact is there.

**Comment by elharo** [comment]
This has been made obsolete. New retrievers always grab the latest version.
