### ISSUE TITLE
Deploy dialog may complain to select an account even if it is selected

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#831]
This requires some steps to reproduce:

1) Select and save an account as project preferences.
2) Log out.
3)  Do 'Deploy to App Engine Standard...'. (The deploy dialog pops up, no account is selected, and the only item in the account combo box is `<Add a new account...>`.)
4) Select `<Add a new account...>`, and log in with the account previously saved.
5) Observe that the account is selected in the dialog, but the dialog complains to select an account.

I suspect there is a databinding sync issue with the control and the data model. Triggering a sync may be necessary.

**Comment by chanseokoh** [comment]
Turns out this is quite tricky to solve in our situation. The underlying databinding framework doesn't trigger dialog re-validation if the email saved in the preferences already matches the email selected in the account selector, which is what's happening in our situation. There doesn't seem to exist a mechanism to force re-validation.

**Comment by elharo** [comment]
Maybe we shouldn't be using the databinding framework here? When we bring up the dialog we could manually check the preference and fill as needed.
