### ISSUE TITLE
CTE feature missing .jdt.launching

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#832]
So if we make a change to a running instance, which triggers a re-publish event, the relaunched JVM fails:
```
INFO     2016-10-14 13:38:49,167 module.py:402] [default] Detected file changes:
  WEB-INF\classes\foo\bar
  WEB-INF\classes\foo\bar\HelloAppEngine.class
FATAL ERROR in native method: JDWP No transports initialized, jvmtiError=AGENT_ERROR_TRANSPORT_INIT(197)
ERROR    2016-10-14 13:38:51,230 http_runtime.py:396] bad runtime process port ['']
ERROR: transport error 202: connect failed: Connection refused
ERROR: JDWP Transport dt_socket failed to initialize, TRANSPORT_INIT(510)
JDWP exit error AGENT_ERROR_TRANSPORT_INIT(197): No transports initialized [debugInit.c:750]
ERROR    2016-10-14 13:38:51,230 http_proxy.py:116] bad runtime process port ['']
```

**Comment by chanseokoh** [comment]
Closed by #833. @briandealwis open this again if it's not the case.

**Comment by patflynn** [comment]
This looks like it's related to
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/972
and
https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1026

Basically in IDE debugging scenarios 'automatic_restart' should always be
false.

**Comment by chanseokoh** [comment]
In fact, we fixed a bug in Eclipse (or a limitation in some sense) on our end (#609), and we do support 'automatic_restart=true' (i.e., auto-reloading apps on the fly). This issue here was simply that we forgot to package our fix into our releases.

**Comment by patflynn** [comment]
You probably want to turn this off by default, since cycling the server on
every change will be a lot slower than hotswap.

**Comment by briandealwis** [comment]
Better yet would be to avoid reloading just for class changes.  I've opened #836 to track this.

**Comment by patflynn** [comment]
You want to avoid reloading for static resource changes too don't you?

**Comment by briandealwis** [comment]
One wrinkle we have to deal with is `m2e-wtp`, which tweaks output paths such that Maven doesn't compile into an exploded-war format in `target/<artifact>-<version>` as is the default (I haven't quite figured out the rationale yet).  So we use the WTP Publish step before launching to ensure we have an exploded-war structure on-disk.

**Comment by briandealwis** [comment]
After a bit of thought, I think you're right @patflynn — with he publishing step, we update the on-disk files, so the running instances should pick up the changed files. But I don't think JVMs pick up changes to on-disk .class files (that seems to be a feature of JRebel), so it won't DTRT for modules sharing a library.

**Comment by patflynn** [comment]
Yeah I've been wondering about this.  I know that while in 'debug' mode in
IJ on-disk class changes are being reloaded, but I'm not sure if that
requires special configuration of the server.  Joao tried this with the dev
appserver in IntelliJ and it apparently worked without any special
configuration on our part. May be worth just testing out on Eclipse.
Obviously there are also cases when .class changes include un-hotswappable
schema changes that requires a restart.
