### ISSUE TITLE
Maven Wizard doesn't check if directory is writable

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#834]
When creating a project in a user specified directory outside the workspace, we don't check that the directory exists. It doesn't fail until a couple of screens later when we try to create the project:

Unable to create project from archetype [com.google.appengine.archetypes:appengine-standard-archetype:LATEST]
org.apache.maven.archetype.exception.ArchetypeGenerationFailure: Error merging velocity templates: /usr/tmp/foo/pom.xml (No such file or directory)

**Comment by briandealwis** [comment]
On Windows, I see in the console:
```
[INFO] ----------------------------------------------------------------------------
[INFO] Using following parameters for creating project from Archetype: appengine-standard-archetype:0.3.0
[INFO] ----------------------------------------------------------------------------
[INFO] Parameter: groupId, Value: abc
[INFO] Parameter: artifactId, Value: def
[INFO] Parameter: version, Value: 0.1.0-SNAPSHOT
[INFO] Parameter: package, Value: abc
[INFO] Parameter: packageInPathFormat, Value: abc
[INFO] Parameter: useJstl, Value: true
[INFO] Parameter: gcloud-version, Value: 2.0.9.121.v20160815
[INFO] Parameter: useEndpoints2, Value: false
[INFO] Parameter: useEndpoints1, Value: false
[INFO] Parameter: useObjectify, Value: false
[INFO] Parameter: useAppEngineApi, Value: false
[INFO] Parameter: appengine-version, Value: 1.9.42
[INFO] Parameter: application-id, Value: def
[INFO] project created from Archetype in dir: c:\temp\foo\bar\baz\def
```
I wonder if this is something about the archetype not being resolved in your local repository.  I'm not sure how to force a refresh though.

**Comment by elharo** [comment]
Maybe a Unix thing then, when the user doesn't have permission to create or write to the specified directory.

**Comment by briandealwis** [comment]
Ah yes I see it if I use `/this/is/a/test` as a normal user.

**Comment by elharo** [comment]
After further investigation the problem is permissions to write into the directory, not the non-existence; error message notwithstanding:

![image](https://cloud.githubusercontent.com/assets/1005544/19744073/2d87092e-9bcc-11e6-84d9-0cd25ef96076.png)

I'll update the PR.

**Comment by elharo** [comment]
Workspace.validateProjectLocation might help us out here (or not).
