### ISSUE TITLE
Use proper icons for GCP resources

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#84]
Use App Engine icon for local dev server in the Eclipse UI.
Also we can add icons for GCE,GKE for future usage.

**Comment by joaoandremartins** [comment]
Ping!

We should also probably switch the generic Cloud icon by an App Engine one at project creation time, as we discussed.

**Comment by elharo** [comment]
@arouzrokh 

Can you establish what are the official icons we're supposed to use here?

**Comment by arouzrokh** [comment]
Please use the same icon as used in IntelliJ. Thanks!

**Comment by elharo** [comment]
That's these?

https://github.com/GoogleCloudPlatform/google-cloud-intellij/tree/master/google-cloud-tools-plugin/resources/icons

I think we're going to need some larger ones. If I recall, Eclipse likes 64 by 64.

**Comment by elharo** [comment]
FYI, we've determined that:

1. We should use the blue airplane icon currently used in the deploy dialog in the new project wizard as well.

![image](https://cloud.githubusercontent.com/assets/1005544/20507244/7627a9a8-b027-11e6-8882-06b3f3a68c54.png)

This is already in the repo somewhere and should replace the rainbow colored icon on the App Engine Standard Project and Maven based App Engine Standard Project wizard pages. 

2. We'll need a small version of this icon for the select a wizard page. 

![image](https://cloud.githubusercontent.com/assets/1005544/20507263/97511d6c-b027-11e6-8a14-420412211cb9.png)
