### ISSUE TITLE
warmup-requests-enabled

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#840]
new project templates for appengine-web.xml should probably set warmup-requests-enabled to false since we don't provide warmup handlers

**Comment by briandealwis** [comment]
We would need to change the docs for [configuring a custom warmup servlet](https://cloud.google.com/appengine/docs/java/warmup-requests/configuring#using_a_custom_warmup_servlet) to mention this setting.

**Comment by elharo** [comment]
doesn't matter with devappserver1
