### ISSUE TITLE
Check for Google Cloud SDK and App Engine Java component before creating a maven project

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#847]
In the new Maven App Engine Project wizard

![image](https://cloud.githubusercontent.com/assets/1005544/19498432/cfeca5bc-955e-11e6-9e8e-93b3a426b3db.png)

The selected wizard could not be started.
Plug-in "com.google.cloud.tools.eclipse.appengine.newproject" was unable to instantiate class "com.google.cloud.tools.eclipse.appengine.newproject.StandardProjectWizard".
Google Cloud SDK path was not provided and could not be found in any known install locations.

**Comment by chanseokoh** [comment]
It's worth nothing that, at the current state, if the Cloud SDK isn't found, we get a misleading error dialog:

![selection_008](https://cloud.githubusercontent.com/assets/10523105/19746600/1c6f30d4-9ba5-11e6-9028-7c72e3c95345.png)

**Comment by elharo** [comment]
I wonder if we could make the validateAppEngineJava check tell us whether the app-engine-java component is missing or the whole Cloud SDK?

**Comment by briandealwis** [comment]
The wizard can use the `CloudSdkProvider` class to obtain the SDK — if it's unavailable, it prompts the user.
