### ISSUE TITLE
Documentation: Update Google Plugin for Eclipse Wikipedia page with links to this plugin

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#854]
Document the transition to this plugin on the wikipedia page of GPE.

https://en.wikipedia.org/wiki/Google_Plugin_for_Eclipse

**Comment by elharo** [comment]
There's a wikipedia page? Isn't there some rule about notability? :-)

Anyway, thanks for the heads up.

**Comment by branflake2267** [comment]
I had the same thought when I found it. I'm laughing at the notability comment, true. :) You can close this, I'd say it's noise.
