### ISSUE TITLE
Use pom.xml to resolve dependencies of libraries

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#865]
E.g. Objectify depends on guava. We need to extract which version of guava is needed to be attached along with the Objectify jar (and the App Engine API jar which is another dependency).

**Comment by elharo** [comment]
I doubt the specific Guava version is that important here. We should probably just pick one and see if it works. I'd like to get the entire project on a single version of Guava, maybe 17 or 18?

**Comment by akerekes** [comment]
Our project being dependent on a certain Guava version (set in the
Manifest.mf files) and using another version for Objectify (set in the
library extension point) are two independent concerns. Nevertheless I agree
we should standardize on our Guava version dependency.

**Comment by akerekes** [comment]
This feature allows us to not explicitly define the dependencies the libraries need, but rely on what they declare in their pom.xml. E.g. we don't need to explicitly add Guava to the Objectify library, because it will be resolved from Objectify's pom.xml.

**Comment by briandealwis** [comment]
We now use m2e/aether, which should be doing this.
