### ISSUE TITLE
DeployPropertyPageTest fails locally on a Mac

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#876]
Watching it run, appears to need a slightly longer wait time, or maybe there's some way we can check more directly if the operation is complete. 

![image](https://cloud.githubusercontent.com/assets/1005544/19649252/65fd025e-9a05-11e6-8da3-2ea91374c6f5.png)

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 32.333 sec <<< FAILURE! - in com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest
testPropertyPageTitle_standardProject(com.google.cloud.tools.eclipse.integration.appengine.DeployPropertyPageTest)  Time elapsed: 25.19 sec  <<< ERROR!
org.eclipse.swtbot.swt.finder.widgets.TimeoutException: Timeout after: 10000 ms.: Shell New App Engine Standard Project did not close

**Comment by elharo** [comment]
Looks like the problem may be that the project is created (which we wait for) but then runtime components are installed (which we don't wait for).

**Comment by briandealwis** [comment]
That message is what happens if somebody tries to close the shell.  Hoping this is fixed with #1383, where we were waiting for a window change, rather than the window being closed.  Re-open if we see it again.
