### ISSUE TITLE
Source locator in debugger does not appear to work

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#887]
Steps to repeat:
1. Create new native example project.
2. Place a breakpoint in `HelloAppEngine#doGet()`
3. Launch the project in debug mode (_Debug As Server_ etc) and trigger the servlet
4. Double-clicking on the frame should open the source for `HelloAppEngine#doGet()`.

Right-clicking on the frame and choosing _Open Declared Type_ opens the source in an editor, but in a different editor than if the source was previously open.

**Comment by akerekes** [comment]
Is this related to #575?

**Comment by briandealwis** [comment]
No, I don't think so: in this case, double-clicking on the source does nothing where in #575 it would open up the source-not-found editor.
