### ISSUE TITLE
Package suggestion bug in maven project wizard

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#889]
Steps to reproduce:

1. Type 'a' in the Group ID.
2. Observe that the Java package field has the same value: 'a'.
3. Delete 'a' with a backspace in the Group ID.

Observe that 'a' still remains in the Java package field.

**Comment by elharo** [comment]
Package or group ID? I cannot reproduce this. Is this on Windows?

**Comment by chanseokoh** [comment]
Happens on Windows and Linux. I updated the description to be more specific.

**Comment by elharo** [comment]
Now I understand and can reproduce. Thanks. Yes, we should fix this but it's not a high priority or a beta blocker right now.
