### ISSUE TITLE
Sign the plugin

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#89]

**Comment by elharo** [comment]
http://www.codetrails.com/blog/sign-your-eclipse-project

**Comment by elharo** [comment]
We can use the jarsigner plugin:

http://maven.apache.org/plugins/maven-jarsigner-plugin/usage.html

**Comment by elharo** [comment]
kokoro is blocked on b/31800655 (and then probably other things). Exploring other options.

**Comment by elharo** [comment]
May be able to use kokoro to sign even if we don't build there. Cloud SDK does this. See

https://cs.corp.google.com/piper///depot/google3/third_party/cloudsdk/component_build/kokoro/
https://critique.corp.google.com/#review/133996378

**Comment by elharo** [comment]
Or manual signing https://g3doc.corp.google.com/googleclient/kokoro/linux_manual_signing/README.md?cl=head

**Comment by branflake2267** [comment]
I haven't used GPG on tycho, but we use it on our other distributions at work. I see they have a reference to doing it for tycho. It looks like `mvn verify gpg:sign`. https://wiki.eclipse.org/GPG and it links to https://wiki.eclipse.org/Releasing_Tycho.

**Comment by elharo** [comment]
Blocked by multiple kokoro bugs including:

b/32276126

We may need to consider releasing the first beta unsigned.

**Comment by rdayal** [comment]
Punting this one off the beta blocker list.

**Comment by elharo** [comment]
FYI, it seems very strange that this process requires us to sign third party jars we have not inspected or audited. Is this really WAI?

**Comment by elharo** [comment]
Latest release is signed.
