### ISSUE TITLE
"No JUnit tests found" in Maven-based Hello World project

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#890]
Steps to reproduce:
1. Create a new Maven-based Hello World project
2. Right click on `HelloAppEngineTest` > _Run As_ > _JUnit Test_.

A dialog saying "No JUnit tests found" pops up. Note that this works for native Hello World project.

**Comment by elharo** [comment]
@lesv This may be an archetype bug. Looks like it's putting the test in the wrong package/folder:

![image](https://cloud.githubusercontent.com/assets/1005544/19734810/466088d0-9ba9-11e6-8e56-9e58a007fc21.png)

I.e. there's an extra test folder.

**Comment by chanseokoh** [comment]
Extra `java` folder in `test/f/g/java`, I think.

**Comment by akerekes** [comment]
should be `src/test/java/f/g`

**Comment by lesv** [comment]
I'll look at it, it works in Maven & Gradle.

**Comment by elharo** [comment]
Are you sure it's not just reporting success because it doesn't find any tests?

**Comment by lesv** [comment]
Yes - I printout the result from the test.  (both of them don't seem to care about layout, just tags)

I've verified that it's wrong.  I'll fix it today, probably be Monday when the Archetype releases.

**Comment by lesv** [comment]
0.4.0 of appengine-standard-archetype was released to maven central today -- will show up on Monday for you, though you can test w/ it today by installing it locally.  (Should publish in about two hours).  I checked appengine-flexible-archetype and it does the right thing.

**Comment by akerekes** [comment]
Fixed.
