### ISSUE TITLE
Unable to deploy App Engine Standard app: missing app id

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#892]
On Windows, with Google Cloud SDK 132.0.0.

Steps to repeat:
  1. New > Google App Engine Standard Java Project
  2. Right click and choose _Deploy to App Engine Standard_
  3. Provide details and start deploy.
  4. Deploy fails.  Console shows:
```
Oct 26, 2016 9:19:06 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
Reading application configuration data...
Bad configuration: No app id supplied and XML files have no <application> element
Please see the logs [C:\Users\IEUser\AppData\Local\Temp\appcfg462285303502776323.log] for further information.
```
_appcfgXXX.log_:
```
com.google.apphosting.utils.config.AppEngineConfigException: No app id supplied and XML files have no <application> element
	at com.google.appengine.tools.admin.Application.<init>(Application.java:234)
	at com.google.appengine.tools.admin.Application.readApplication(Application.java:421)
	at com.google.appengine.tools.admin.AppCfg.readWar(AppCfg.java:297)
	at com.google.appengine.tools.admin.AppCfg.readApplication(AppCfg.java:288)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:217)
	at com.google.appengine.tools.admin.AppCfg.<init>(AppCfg.java:119)
	at com.google.appengine.tools.admin.AppCfg.main(AppCfg.java:115)
```

**Comment by patflynn** [comment]
@etanshaul @loosebazooka Do you have the latest Cloud SDK update?

**Comment by elharo** [comment]
Has anyone else tried a deploy today?

**Comment by chanseokoh** [comment]
I'm hitting the same error on Windows with the latest SDK 132.

I'm also having a deploy error on Linux, but that seems a bit different. I'm trying to understand what's happening on Linux first.

**Comment by etanshaul** [comment]
Just tried this with 131 without application/version specified and it worked. Have not tried with 132 yet.

**Comment by briandealwis** [comment]
It's working for me on OS X with 132.

**Comment by loosebazooka** [comment]
Can someone elaborate? Were we expecting the change that makes application id optional to be in 132?

**Comment by briandealwis** [comment]
Sorry it was a false alarm: my command window was picking up different `gcloud` installation from my Eclipse.  Confirmed working on Windows with 132.0.0.
