### ISSUE TITLE
Check for Google Cloud SDK for deploy

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#901]
Similar to #847 and #900, we need to check the Cloud SDK for deploy. (Probably anywhere before we use the Cloud SDK.)

If the Cloud SDK isn't found, we see a misleading error dialog. (This one bit me. I did `gcloud components install app-engine-java` numerous times and couldn't understand why this is failing.)

![problem occurred _007](https://cloud.githubusercontent.com/assets/10523105/19746345/020e6210-9ba4-11e6-8d78-4d8296f6da8d.png)

Steps to reproduce:
1) Update the Cloud SDK path in the preferences to an invalid directory.
2) Deploy.

**Comment by elharo** [comment]
I don't see an easy way to add this to the data binding that controls the deploy button so I think what we can do is add a check to this method in DeployPreferencesDialog:

  @Override
  protected void okPressed() {
    content.savePreferences();
    super.okPressed();
  }

If the cloud SDK is not configured pop up an error dialog here.
