### ISSUE TITLE
Objectify and Endpoints do not fully lock the App Engine API dependency

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#903]
1. Create a new project with wizard.
2. Check all three libraries.
3. Uncheck Objectify

What happens:
Objectify and App Engine API are unchecked

What should happen:
Only Objectify is unchecked. App Engine API (needed for endpoints) should remain checked.

Related bug:
1. Manually check App Engine API. 
2. Check Endpoints.
3. Uncheck endpoints

What happens:
Endpoints and App Engine API are unchecked

What should happen:
Only Endpoints is unchecked. App Engine API (needed for endpoints) should remain checked.

I suggest we simply require that App Engine API not be automatically unchecked without user action. There may also be an issue that as long as one of the two other dependencies is checked, App Engine API  should not be able to be unchecked.

**Comment by elharo** [comment]
This state shouldn't be possible:

![image](https://cloud.githubusercontent.com/assets/1005544/19765235/91affb06-9c47-11e6-851f-ae4b72599ca5.png)

**Comment by chanseokoh** [comment]
This also happens in the native project wizard.

**Comment by elharo** [comment]
Yes, they share this code. Fixing one should fix the other. I love the smell of code reuse in the morning. :-)

**Comment by elharo** [comment]
I'm re-opening this one. I don't think #909 fully fixed it though it is heading in the right direction. What I currently see is that if App Engine API is added by Objectify (for example) it can be removed by removing Objectify. However it is entirely possible the project still depends on it directly, not simply as a transitive dependency of Objectify, and removing it may break the project.

I suggest that all removals of libraries require explicit user choice. I.e. unchecking the checkbox. It is not enough to remove a different dependent library. I suspect this will make the code simpler too.

**Comment by akerekes** [comment]
If the user explicitly selected App Engine API, then select Objectify/Endpoints/both and finally removes any of Objectify/Endpoints or both, App Engine API will remain selected. If the user never selected (or selected and unselected it) it will become unselected if one of the other libraries are unselected.

**Comment by elharo** [comment]
Yes, this is what happens. I am saying we should not do that. However the App Engine API became attached to the project, the user's code may depend on it directly. Since we're not checking actual dependencies, we should follow the safest path and leave it in until the user tells us they want to remove it.

**Comment by elharo** [comment]
NVM. I'm wrong. Since this is only in the wizard, and does not appear after that this behavior makes sense.
