### ISSUE TITLE
Improve library selector data binding

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#911]

**Comment by chanseokoh** [comment]
See below for details:

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/909#pullrequestreview-6284421
https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/909#discussion_r85582052

**Comment by briandealwis** [comment]
Another improvement would be to make `ManualSelectionTracker` self-contained:
  - move the `BUTTON_MANUAL_SELECTION` into `ManualSelectionTracker`
  - turn the `getData(BUTTON_MANUAL_SELECTION) != null` test in `AppEngineLibrariesSelectorGroup` into a static method on `ManualSelectionTracker`
