### ISSUE TITLE
Auto detect cloud sdk location

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#913]
There is an opportunity to auto detect the default install locations for the cloud sdk tools and add that to the preferences. 

![screen shot 2016-10-29 at 9 32 47 pm](https://cloud.githubusercontent.com/assets/1326504/19834505/6a66e71a-9e1f-11e6-9960-b909b177b534.png)

**Comment by briandealwis** [comment]
The Cloud SDK binding already has some auto-detection logic: we search the `PATH` for `gcloud`, and we also look for at some other somewhat-common installation locations.

We could perhaps add a _Scan_ or _Search_option here that might do search local drives?

**Comment by branflake2267** [comment]
It's not finding the cloud sdk path b/c it's `gcloud`, that's not working for my path. 

- Notice the sdk path does not include gcloud. 
```
echoBrandons-MacBook-Pro-2:~ branflake2267$ echo $PATH
/Users/branflake2267/bin/google-cloud-sdk/bin:/Users/branflake2267/google-cloud-sdk/bin:/Users/branflake2267/bin/Sencha/Cmd/6.0.1.76/..:/Users/branflake2267/bin/Sencha/Cmd:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/branflake2267/.rvm/gems/ruby-2.0.0-p247/bin:/Users/branflake2267/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/branflake2267/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/branflake2267/.rvm/bin:/Users/branflake2267/Library/Android/sdk/tools:/Users/branflake2267/Library/Android/sdk/platform-tools:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/MacGPG2/bin
Brandons-MacBook-Pro-2:~ branflake2267$ 

```

**Comment by chanseokoh** [comment]
@branflake2267 I think your `$PATH` contains the SDK path (to be precise, the directory where `gcloud` is located) as the first entry: `/Users/branflake2267/bin/google-cloud-sdk/bin`, doesn't it?

**Comment by branflake2267** [comment]
Oh, yeah gcloud is there. 
![screen shot 2016-10-31 at 9 25 06 am](https://cloud.githubusercontent.com/assets/1326504/19862025/f22fb118-9f4b-11e6-8daa-418b117e5c4a.png)

**Comment by elharo** [comment]
This should be working, at least at head. If you can reproduce this, please reopen with the exact path where the cloud SDK is located and not found.
