### ISSUE TITLE
Provide IURLProvider adapter for LocalAppEngineServerBehaviour

### ISSUE THREAD

**Issue by branflake2267** [GoogleCloudPlatform/google-cloud-eclipse#916]
Goal read the web url either from the console stream or IURLProvider adapter.

SocketListenMultiConnectorProcess.getStreamsProxy() returns null. Tomcat provides a streams proxy. The proxy streams the content that goes into the console. I was going to use it as a generic method to into and get the urls. Since the web server could be on an odd port I thought it might be nifty to provide that into the GWT Dev View.

https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/c75fa7ab422a716a07a8763572afae5a1e57175b/third_party/com.google.cloud.tools.eclipse.jdt.launching/src/com/google/cloud/tools/eclipse/jdt/internal/launching/SocketListenMultiConnectorProcess.java#L265

**Comment by branflake2267** [comment]
Instead of providing the streams proxy, providing a IURLProvider adapter would be golden. 

```
 private String getServerUrl(IServer server, IModule rootMod) {
    IURLProvider urlProvider = (IURLProvider) server.loadAdapter(IURLProvider.class, null);
    if (urlProvider == null) {
      return null;
    }
    URL url = urlProvider.getModuleRootURL(rootMod);
    if (url == null) {
      return null;
    }
    return url.toString();
  }
```

Like for tomcat it turns out like this for the GWT Eclipse Plugin. This way the web url can be double clicked on quickly and activate super dev mode. 

![screen shot 2016-10-30 at 5 19 47 pm](https://cloud.githubusercontent.com/assets/1326504/19841242/9fa2b0a2-9ec5-11e6-88c0-121bf078437f.png)

**Comment by briandealwis** [comment]
That `SocketListenMultiConnectorProcess` is an internal class used for communicating debug information via JDI.  The `IURLProvider` would be implemented by `LocalAppEngineServerBehaviour`.  I'll close this as we were tracking the same issue in #768.

**Comment by briandealwis** [comment]
Take that back: let's use this for `IURLProvider`.

**Comment by branflake2267** [comment]
This is how it looks so far. Preview of running a GWT app. A Url will work out nicely. 
https://plus.google.com/+BrandonDonnelson/posts/MVbCcNg18zA?sfc=true

**Comment by elharo** [comment]
@briandealwis What's the status of this? Still open, still important?

**Comment by briandealwis** [comment]
Still open, still important.
