### ISSUE TITLE
Prevent entering relative path as project location in new project Maven wizard

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#929]
Currently, if a relative path is entered as a project location, the path eventually becomes relative to the work directory of Eclipse (i.e., relative to the directory from which Eclipse is launched). This results in creating directories relative to the Eclipse work directory.

This applies to ~~both non-Maven and Maven project wizards~~ the Maven wizard.

**Comment by elharo** [comment]
I believe this already works like this in standard:

![image](https://cloud.githubusercontent.com/assets/1005544/19928072/41905860-a0d3-11e6-9120-d26b3ff38cb1.png)

Maven, however, doesn't seem to make this check and puts it in a really weird place:

[INFO] project created from Archetype in dir: /Applications/Eclipse Mars.app/Contents/MacOS/f/g/g/gh

**Comment by elharo** [comment]
I wonder if this is an m2e or Eclipse bug? What's the difference between the standard and maven wizards' location fields?

**Comment by elharo** [comment]
Looks like the standard wizard uses a

ProjectContentsLocationArea instead of just a TextField for the location. 

This is an internal class. Maybe if we extended WizardNewProjectCreationPage instead of WizardPage as well?
