### ISSUE TITLE
Objectify javadoc not displayed

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#932]
Objectify Javadoc is hosted on javadoc.io, which is served by CloudFlare. The default settings on CloudFlare seem to disallow user agents from JDKs: https://github.com/nodejs/node-v0.x-archive/issues/25912
I've sent an email to the contacts on javadoc.io to see if they can modify the settings.
The problem is that we cannot override the user agent used to got the javadoc pages (maybe globally for the JVM running our plugin, but that's probably not something we should do), and there doesn't seem to be another publicly hosted Objectify javadoc site.

Alternatively once #921 is implemented we won't depend on javadoc.io.

**Comment by briandealwis** [comment]
#921 is the right way to go, methinks.  We can document the Javadoc resolving issue, with the workaround to modify the `eclipse.ini` and add `-Dhttp.agent=xxx`.

**Comment by branflake2267** [comment]
Just an idea. If you can't reach their javadoc, you could build it yourself, for use internally. I do this with third party dependencies, and display it on some of our sites. 

This is what I do. 
1. add pom.xml to build process
2. run it with mvn clean install -Dgwt.version=2.8.0 to change the version I need
3. It builds into the target directory, then I can distribute it to the location I need. 

https://gist.github.com/branflake2267/7f3a3bfcbaef71c752fe75129c34661d - pom.xml to build. I do this with several of the GWT dependencies. They just need to be on Maven central to Javadoc, or installed.

**Comment by akerekes** [comment]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=506935

**Comment by elharo** [comment]
seems to have been fixed.
