### ISSUE TITLE
appengine-web.xml files different between Maven and native Hello World projects

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#944]
Particularly, the native project has `<sessions-enabled>false</sessions-enabled>`, while the Maven project doesn't. Are they intended?

Maven:
```xml
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">
    <threadsafe>true</threadsafe>
    <system-properties>
        <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
    </system-properties>
</appengine-web-app>
```

Native:
```xml
<?xml version="1.0" encoding="utf-8"?>
<appengine-web-app xmlns="http://appengine.google.com/ns/1.0">

  <threadsafe>true</threadsafe>
  <sessions-enabled>false</sessions-enabled>

</appengine-web-app>
```

**Comment by elharo** [comment]
Sessions have negative performance impact and are contrary to the design of HTTP. They shouldn't be turned on by default (and hello world certainly doesn't need them.)

http://stackoverflow.com/questions/14699705/gae-http-session-why-disable-it

That said, the default value of this property is false so we could probably just remove it from our appengine-web.xml.
