### ISSUE TITLE
Checkbox in server creation UI for auto-correcting local run admin port

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#946]
The default admin port is 8000. When the port is in use, we let dev_appserver to pick an arbitrary port. [We could consider adding a checkbox UI to turn on or off this port auto-correction](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/pull/938#discussion_r86576839).

This should be wired through the server attribute `ADMIN_PORT_BOUND_FAILOVER_ATTRIBUTE_NAME` defined and used in `LocalAppEngineServerBehavior`.

**Comment by elharo** [comment]
Let's not further clutter our UI. This seems unlikely to be much used.
