### ISSUE TITLE
Server definition editors do not restore on restart

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#950]
Steps to repeat:

  1. Double click on an App Engine Standard server in the _Servers_ view to bring up a server definition editor.
  2. _File > Restart_
  3. See the server definition editor be replaced with an empty editor

<img width="687" alt="screen shot 2016-11-04 at 11 28 00 pm" src="https://cloud.githubusercontent.com/assets/202851/20027285/6a66203e-a2e6-11e6-82d1-255920538271.PNG">

**Comment by chanseokoh** [comment]
Interesting. I cannot reproduce, whether I do _File_ > _Restart_ or I close and open Eclipse again manually.

**Comment by briandealwis** [comment]
I'll dig into it.  I'm seeing this in a debug launch so it may be spurious.

**Comment by briandealwis** [comment]
Unable to reproduce, and I can't recall seeing this for ages.  Closing and will reopen if I see it again.

**Comment by briandealwis** [comment]
My mistake: these are web browser tabs, not server definition tabs.

**Comment by briandealwis** [comment]
Had a moment to dig into this.  We do not open our [web browsers with `IWorkbenchBrowserSupport#PERSISTENT`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.ui/src/com/google/cloud/tools/eclipse/ui/util/WorkbenchUtil.java#L102), which makes sense since the servers are stopped too.  The lack of this setting configures the web browser editor so as to be not persisted.  Eclipse's normally persists the workbench state on shutdown, and it first closes all non-persisted editors before persisting the workbench state.  But Eclipse also has a workbench autosave and since the autosave can't close open editors, they do get saved to the backup.  Normally this isn't a problem as the autosaved state is overwritten when the user exits normally.  But I frequently just terminate the debugging targets, and so the autosave backup is used on restart.
