### ISSUE TITLE
Ensure Servlet and JSP jars resolve to the same versions

### ISSUE THREAD

**Issue by akerekes** [GoogleCloudPlatform/google-cloud-eclipse#953]
When a project is associated with a runtime, in our case the GAE Standard runtime, which determines which version of servlet and jsp APIs are supported, and added to the classpath. We must ensure that if in the future the supported versions change, the projects associated with the current runtime type won't see a different version of APIs unless the user explicitly updates the runtime association.

I.e.: currently we read the supported versions from the libraries extension point. If a newer version will be supported, we need to ensure that it either results in a new runtime or runtime version, or the classpath provider knows which version to resolve for which project.

**Comment by briandealwis** [comment]
Maybe we should define the `servlet-api` and `jsp-api` library extensions with specific versions (i.e., `servlet-api-2.5`, `jsp-api-2.1`) and `ServletClasspathProvider` should reference those specific libraries.

**Comment by briandealwis** [comment]
This was done as part of #1855.
