### ISSUE TITLE
Library attach button bug in new project wizards

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/google-cloud-eclipse#954]
Steps to reproduce:

1. Open the wizard.
2. Click on _App Engine API_. (Becomes checked.)
3. Click on _App Engine API_. (Now unchecked.)
4. Click on _App Engine Endpoints_.

Observe that _App Engine API_ is unchecked.

![selection_001](https://cloud.githubusercontent.com/assets/10523105/20063543/92059a48-a4d5-11e6-9a34-2f87fd1b960c.png)

**Comment by elharo** [comment]
This does not appear to be fixed.

**Comment by elharo** [comment]
Looking over this code, I'm struck that it is very complex and over-engineered to solve what should be a simple problem. What if we rip out the data binding and just hard code the solution to the problem at hand?

**Comment by chanseokoh** [comment]
#955 (currently open and to be merged soon, I believe) fixes this.
