### ISSUE TITLE
A non-existent directory is an error but missing cloud SDK is only a warning

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#973]
On the preferences page.

Should both of these be blocking errors?

![image](https://cloud.githubusercontent.com/assets/1005544/20316904/e0abdc72-ab31-11e6-88ff-3ec20b1bb418.png)

![image](https://cloud.githubusercontent.com/assets/1005544/20316924/f8406902-ab31-11e6-9647-cacc71a68a9e.png)

**Comment by briandealwis** [comment]
I made it a warning in case there's some change in the Google Cloud SDK that `appengine-plugins-core`'s validation fails (e.g., some file is no longer being shipped, or has moved).  It may not be a blocking error.
