### ISSUE TITLE
default version for maven wizard

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#974]
As in Eclipse standard new maven project wizard, offer 0.0.1-SNAPSHOT as initial version.

![image](https://cloud.githubusercontent.com/assets/1005544/20319527/7855ea9a-ab3c-11e6-854d-f7346e9ead91.png)

(or maybe 0.1.0-SNAPSHOT? Consult Maven docs to see which is recommended.

**Comment by briandealwis** [comment]
We already set [`0.1.0-SNAPSHOT`](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.newproject.maven/src/com/google/cloud/tools/eclipse/appengine/newproject/maven/MavenAppEngineStandardWizardPage.java#L58)?

![screen shot 2016-11-15 at 2 14 46 pm](https://cloud.githubusercontent.com/assets/202851/20319912/ec0afc86-ab3d-11e6-90ae-c560be79f455.PNG)

**Comment by elharo** [comment]
Wonder if we did that after the build @ynr used in his user study.
