### ISSUE TITLE
Run As > App Engine Local Server

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#976]
In context menu, for an application with the app engine facet, should we have Run As > App Engine Local Server (exact wording to be determined) that can be used instead of Run As > Run On Server.

seems superfluous. It would be exactly the same as Run As > Run On Server
The issue here may be that WTP UI is confusing and not well understood.

**Comment by chanseokoh** [comment]
This may or may not be a duplicate of #225.
