### ISSUE TITLE
Create index.html for release p2 repository

### ISSUE THREAD

**Issue by briandealwis** [GoogleCloudPlatform/google-cloud-eclipse#989]
A p2 repository can host `.html` files too, so we should provide an `index.html` file on `https://dl.google.com/eclipse/google-cloud-eclipse/` that either does a meta-redirect (e.g., to our [installation page](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/wiki/Installation-and-setup)) or provides instructions on how to install in Eclipse.

For an example, see the [Eclipse Platform 4.6 p2 update repository](http://download.eclipse.org/eclipse/updates/4.6/).

These files should be put in `gcp-repo` in `src/main/resources`, and automatically copied in by the `tycho-p2-repository-plugin`.

**Comment by elharo** [comment]
closed by #990
