### ISSUE TITLE
support HTML only projects

### ISSUE THREAD

**Issue by elharo** [GoogleCloudPlatform/google-cloud-eclipse#999]
Tried to use this for a personal site this weekend and

Description | Resource | Path | Location | Type
--- | --- | --- | --- | ---
Project 'xom-website' is missing required source folder: 'src/main/java' | xom-website | Build path | Build Path | Problem

**Comment by briandealwis** [comment]
Our _AppEngine Standard_ facet pre-reqs [Servlet 2.5 and Java 1.7](https://github.com/GoogleCloudPlatform/google-cloud-eclipse/blob/master/plugins/com.google.cloud.tools.eclipse.appengine.facets/plugin.xml#L12).  We could move these into an _App Engine Standard for Java_ facet instead.  That would make sense thinking longer-term abour adding support for Python and Go.

**Comment by elharo** [comment]
@nbashirbello What do you think about splitting up the facets like Brian suggests?

**Comment by elharo** [comment]
WTP has a "Static Web Module" facet. Does that help us at all?

**Comment by briandealwis** [comment]
Yes, that's exactly what we should be using for this case.

**Comment by chanseokoh** [comment]
This issue is about running HTML only projects on devappserver, right? In that case, I think it's not possible. devappserver refuses to run if it has neither `WEB-INF` nor `app.yaml`:

`google.appengine.tools.devappserver2.errors.AppConfigNotFoundError: "/usr/local/google/home/chanseok/runtime-gcloud-eclipse/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/static-web" is a directory but does not contain app.yaml or app.yml or a WEB-INF subdirectory`

**Comment by elharo** [comment]
More about deployment. I think what we need to do is make deploy to app engine standard work when a project has the "Static Web Module" facet, preferably even if it doesn't have an appengine-web.xml. We should be able to autogenerate an appengine-web.xml that works for a static site.

**Comment by nbashirbello** [comment]
If we want the App Engine feature to support other languages except for Java, I think it makes sense to have multiple facets, if the Java projects would have a slightly different experiences that non-java projects. 

It feels this might be outside our teams scope.

**Comment by diegomarquezp** [comment]
Closing as not planned.
